// Generated by shadow-server-app typegen from ../shadow-app.local.json.
// Do not edit by hand. Update the JSON manifest and regenerate this file.
import type { ShadowServerAppManifest } from '@shadowob/sdk'

export const shadowServerAppManifest = {
  schemaVersion: 'shadow.app/1',
  appKey: 'shadow-space',
  name: 'Space',
  description:
    'A personal portfolio Server App for creator profiles, collected works, cover images, tags, responses, remakes, saved works, editions, restoration, and CDN-backed viewing.',
  version: '1.0.0',
  iconUrl: 'http://localhost:4217/assets/icon.svg',
  iframe: {
    entry: 'http://localhost:4217/shadow/server',
    allowedOrigins: ['http://localhost:4217'],
  },
  api: {
    baseUrl: 'http://localhost:4217',
    auth: {
      type: 'oauth2-bearer',
    },
  },
  access: {
    defaultPermissions: ['space.profile:read', 'space.artworks:read'],
    defaultApprovalMode: 'none',
  },
  commands: [
    {
      name: 'profile.get',
      title: 'Get Space profile',
      description: 'Read the portfolio home profile, custom CSS, introduction, and creator tags.',
      path: '/api/shadow/commands/profile.get',
      permission: 'space.profile:read',
      action: 'read',
      dataClass: 'public',
    },
    {
      name: 'profile.update',
      title: 'Update Space profile',
      description: 'Update profile copy, creator tags, and custom homepage CSS.',
      path: '/api/shadow/commands/profile.update',
      permission: 'space.profile:manage',
      action: 'manage',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['patch'],
        properties: {
          patch: {
            type: 'object',
            properties: {
              displayName: {
                type: 'string',
                maxLength: 120,
              },
              handle: {
                type: 'string',
                maxLength: 80,
              },
              headline: {
                type: 'string',
                maxLength: 180,
              },
              bio: {
                type: 'string',
                maxLength: 1200,
              },
              location: {
                type: 'string',
                maxLength: 120,
              },
              website: {
                type: 'string',
                maxLength: 240,
              },
              coverUrl: {
                type: 'string',
                maxLength: 500,
              },
              tags: {
                type: 'array',
                maxItems: 12,
                items: {
                  type: 'string',
                  minLength: 1,
                  maxLength: 40,
                },
              },
              customCss: {
                type: 'string',
                maxLength: 8000,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.list',
      title: 'List artworks',
      description:
        'Search and list works by query, tag, visibility, appreciation, notes, and edition details.',
      path: '/api/shadow/commands/artworks.list',
      permission: 'space.artworks:read',
      action: 'read',
      dataClass: 'public',
      inputSchema: {
        type: 'object',
        properties: {
          query: {
            type: 'string',
            maxLength: 120,
          },
          tag: {
            type: 'string',
            maxLength: 60,
          },
          visibility: {
            enum: ['all', 'public', 'private'],
          },
          limit: {
            type: 'integer',
            minimum: 1,
            maximum: 100,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.get',
      title: 'Open work',
      description:
        'Read one work with notes, interactions, editions, storage details, and viewing URLs.',
      path: '/api/shadow/commands/artworks.get',
      permission: 'space.artworks:read',
      action: 'read',
      dataClass: 'public',
      inputSchema: {
        type: 'object',
        required: ['artworkId'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.update',
      title: 'Update work details',
      description: 'Update title, description, tags, and public or private visibility.',
      path: '/api/shadow/commands/artworks.update',
      permission: 'space.artworks:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['artworkId'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
          title: {
            type: 'string',
            maxLength: 160,
          },
          description: {
            type: 'string',
            maxLength: 1200,
          },
          tags: {
            type: 'array',
            maxItems: 12,
            items: {
              type: 'string',
              minLength: 1,
              maxLength: 40,
            },
          },
          visibility: {
            enum: ['public', 'private'],
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.upload',
      title: 'Publish work',
      description:
        'Publish a finished work package, store it as an edition in the CDN, and make it viewable.',
      help: {
        summary: 'Create a new work or add a new edition from a local package.',
        usage:
          'shadowob app call shadow-space artworks.upload --server "<server>" --file ./work-package --json-input \'{"title":"My piece","tags":["portfolio"],"visibility":"public"}\' --json',
        details:
          'Packages should include a clear entry piece. Space chooses the shortest valid entry when there are multiple candidates.',
      },
      path: '/api/shadow/commands/artworks.upload',
      permission: 'space.artworks:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      input: 'multipart',
      binary: {
        supported: true,
        field: 'file',
        maxBytes: 26214400,
        contentTypes: ['text/html', 'application/zip', 'application/x-zip-compressed'],
      },
      inputSchema: {
        type: 'object',
        required: ['title', 'upload'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 160,
          },
          description: {
            type: 'string',
            maxLength: 1200,
          },
          tags: {
            type: 'array',
            maxItems: 12,
            items: {
              type: 'string',
              minLength: 1,
              maxLength: 40,
            },
          },
          visibility: {
            enum: ['public', 'private'],
          },
          versionTitle: {
            type: 'string',
            maxLength: 160,
          },
          notes: {
            type: 'string',
            maxLength: 1000,
          },
          upload: {
            type: 'object',
            required: ['filename', 'contentType', 'size', 'dataBase64'],
            properties: {
              field: {
                type: 'string',
                maxLength: 80,
              },
              filename: {
                type: 'string',
                minLength: 1,
                maxLength: 240,
              },
              contentType: {
                type: 'string',
                minLength: 1,
                maxLength: 160,
              },
              size: {
                type: 'integer',
                minimum: 1,
                maximum: 26214400,
              },
              dataBase64: {
                type: 'string',
                minLength: 1,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.comment',
      title: 'Add note to work',
      description: 'Add a note to one work.',
      path: '/api/shadow/commands/artworks.comment',
      permission: 'space.comments:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['artworkId', 'body'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
          body: {
            type: 'string',
            minLength: 1,
            maxLength: 1200,
          },
          context: {
            type: 'object',
            description:
              'Structured page state for selection notes, including box geometry, frame, version, and screenshot data.',
            additionalProperties: true,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'covers.upload',
      title: 'Update cover',
      description: 'Attach a cover image to the profile or one work.',
      help: {
        summary: 'Attach a visual cover to the Space profile or a work card.',
        usage:
          'shadowob app call shadow-space covers.upload --server "<server>" --file ./cover.png --json-input \'{"targetType":"artwork","artworkId":"art_123"}\' --json',
        details:
          'Use targetType=profile for the portfolio cover. Use targetType=artwork with artworkId for a work cover.',
      },
      path: '/api/shadow/commands/covers.upload',
      permission: 'space.artworks:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      input: 'multipart',
      binary: {
        supported: true,
        field: 'file',
        maxBytes: 10485760,
        contentTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/gif', 'image/svg+xml'],
      },
      inputSchema: {
        type: 'object',
        required: ['targetType', 'upload'],
        properties: {
          targetType: {
            enum: ['profile', 'artwork'],
          },
          artworkId: {
            type: 'string',
            minLength: 1,
          },
          upload: {
            type: 'object',
            required: ['filename', 'contentType', 'size', 'dataBase64'],
            properties: {
              field: {
                type: 'string',
                maxLength: 80,
              },
              filename: {
                type: 'string',
                minLength: 1,
                maxLength: 240,
              },
              contentType: {
                type: 'string',
                minLength: 1,
                maxLength: 160,
              },
              size: {
                type: 'integer',
                minimum: 1,
                maximum: 10485760,
              },
              dataBase64: {
                type: 'string',
                minLength: 1,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.like',
      title: 'Appreciate work',
      description: 'Toggle an appreciation interaction for one work.',
      path: '/api/shadow/commands/artworks.like',
      permission: 'space.interactions:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['artworkId'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.favorite',
      title: 'Collect work',
      description: 'Toggle a saved work and update the collection shelf.',
      path: '/api/shadow/commands/artworks.favorite',
      permission: 'space.favorites:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['artworkId'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.remix',
      title: 'Make a response',
      description:
        'Create a private response copy so the caller can make something in the same spirit.',
      path: '/api/shadow/commands/artworks.remix',
      permission: 'space.artworks:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['artworkId'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'versions.rollback',
      title: 'Restore edition',
      description: 'Create a restored edition from a previous edition and make it current.',
      path: '/api/shadow/commands/versions.rollback',
      permission: 'space.versions:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['artworkId', 'versionId'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
          versionId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'favorites.list',
      title: 'List collection',
      description: 'List the personal collection shelf with saved works.',
      path: '/api/shadow/commands/favorites.list',
      permission: 'space.favorites:read',
      action: 'read',
      dataClass: 'server-private',
    },
    {
      name: 'tags.list',
      title: 'List tags',
      description: 'List tag chips with counts.',
      path: '/api/shadow/commands/tags.list',
      permission: 'space.artworks:read',
      action: 'read',
      dataClass: 'public',
    },
  ],
  skills: [
    {
      name: 'shadow-space-portfolio-ops',
      description:
        'Use when a Buddy needs to inspect a Space portfolio, publish work, add notes, make responses, collect works, or restore an edition.',
      commandHints: [
        'shadow-space profile.get',
        'shadow-space artworks.list',
        'shadow-space artworks.get',
        'shadow-space artworks.upload',
        'shadow-space covers.upload',
        'shadow-space artworks.comment',
        'shadow-space artworks.remix',
        'shadow-space versions.rollback',
      ],
    },
  ],
  events: ['space.updated'],
  binary: {
    supported: true,
  },
} as const satisfies ShadowServerAppManifest

export type ShadowServerAppManifestDefinition = typeof shadowServerAppManifest
