// Generated by shadow-space-app typegen from ../space-app.local.json.
// Do not edit by hand. Update the JSON manifest and regenerate this file.
import type { ShadowSpaceAppManifest } from '@shadowob/sdk'

export const shadowSpaceAppManifest = {
  schemaVersion: 'shadow.space-app/1',
  appKey: 'space',
  name: 'Space',
  description:
    'A personal portfolio app for creator profiles, collected works, cover images, tags, responses, remakes, saved works, editions, restoration, and CDN-backed viewing.',
  version: '1.0.0',
  iconUrl: 'http://localhost:4217/assets/icon.svg',
  marketplace: {
    tagline: 'A creator space for profiles, works, covers, responses, and remakes.',
    summary:
      'Space gives creators a server-native portfolio with profile pages, uploaded works, cover images, tags, responses, remakes, saved works, editions, restoration, and CDN-backed viewing. It is designed for communities that make and discuss creative work together.',
    categories: ['Creation', 'Community', 'Portfolio'],
    supportedLanguages: ['English', '中文'],
    coverImageUrl: 'http://localhost:4217/assets/cover.png',
    gallery: [
      {
        url: 'http://localhost:4217/assets/cover.png',
        type: 'image',
        alt: 'Space cover',
      },
    ],
    links: [
      {
        label: 'Home',
        url: 'http://localhost:4217/shadow/server',
        type: 'website',
      },
    ],
    publisher: {
      name: 'Shadow',
    },
  },
  iframe: {
    entry: 'http://localhost:4217/shadow/server',
    allowedOrigins: ['http://localhost:4217'],
  },
  api: {
    baseUrl: 'http://localhost:4217',
    auth: {
      type: 'oauth2-bearer',
    },
  },
  access: {
    defaultPermissions: ['space.profile:read', 'space.artworks:read'],
    defaultApprovalMode: 'none',
  },
  commands: [
    {
      name: 'profile.get',
      title: 'Get Space profile',
      description: 'Read the portfolio home profile, custom CSS, introduction, and creator tags.',
      ingress: {
        path: '/.shadow/commands/profile.get',
        auth: 'shadow-command-jwt',
      },
      permission: 'space.profile:read',
      action: 'read',
      dataClass: 'public',
    },
    {
      name: 'profile.update',
      title: 'Update Space profile',
      description: 'Update profile copy, creator tags, and custom homepage CSS.',
      ingress: {
        path: '/.shadow/commands/profile.update',
        auth: 'shadow-command-jwt',
      },
      permission: 'space.profile:manage',
      action: 'manage',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['patch'],
        properties: {
          patch: {
            type: 'object',
            properties: {
              displayName: {
                type: 'string',
                maxLength: 120,
              },
              handle: {
                type: 'string',
                maxLength: 80,
              },
              headline: {
                type: 'string',
                maxLength: 180,
              },
              bio: {
                type: 'string',
                maxLength: 1200,
              },
              location: {
                type: 'string',
                maxLength: 120,
              },
              website: {
                type: 'string',
                maxLength: 240,
              },
              coverUrl: {
                type: 'string',
                maxLength: 500,
              },
              tags: {
                type: 'array',
                maxItems: 12,
                items: {
                  type: 'string',
                  minLength: 1,
                  maxLength: 40,
                },
              },
              customCss: {
                type: 'string',
                maxLength: 8000,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.list',
      title: 'List artworks',
      description:
        'Search and list works by query, tag, visibility, appreciation, notes, and edition details.',
      ingress: {
        path: '/.shadow/commands/artworks.list',
        auth: 'shadow-command-jwt',
      },
      permission: 'space.artworks:read',
      action: 'read',
      dataClass: 'public',
      inputSchema: {
        type: 'object',
        properties: {
          query: {
            type: 'string',
            maxLength: 120,
          },
          tag: {
            type: 'string',
            maxLength: 60,
          },
          visibility: {
            enum: ['all', 'public', 'private'],
          },
          limit: {
            type: 'integer',
            minimum: 1,
            maximum: 100,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.get',
      title: 'Open work',
      description:
        'Read one work with notes, interactions, editions, storage details, and viewing URLs.',
      ingress: {
        path: '/.shadow/commands/artworks.get',
        auth: 'shadow-command-jwt',
      },
      permission: 'space.artworks:read',
      action: 'read',
      dataClass: 'public',
      inputSchema: {
        type: 'object',
        required: ['artworkId'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.update',
      title: 'Update work details',
      description: 'Update title, description, tags, and public or private visibility.',
      ingress: {
        path: '/.shadow/commands/artworks.update',
        auth: 'shadow-command-jwt',
      },
      permission: 'space.artworks:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['artworkId'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
          title: {
            type: 'string',
            maxLength: 160,
          },
          description: {
            type: 'string',
            maxLength: 1200,
          },
          tags: {
            type: 'array',
            maxItems: 12,
            items: {
              type: 'string',
              minLength: 1,
              maxLength: 40,
            },
          },
          visibility: {
            enum: ['public', 'private'],
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.upload',
      title: 'Publish work',
      description:
        'Publish a finished work package, store it as an edition in the CDN, and make it viewable.',
      help: {
        summary: 'Create a new work or add a new edition from a local package.',
        usage:
          'shadowob space-app call space artworks.upload --server "<server>" --file ./work-package --json-input \'{"title":"My piece","tags":["portfolio"],"visibility":"public"}\' --json',
        details:
          'Packages should include a clear entry piece. Space chooses the shortest valid entry when there are multiple candidates.',
      },
      ingress: {
        path: '/.shadow/commands/artworks.upload',
        auth: 'shadow-command-jwt',
      },
      permission: 'space.artworks:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      input: 'multipart',
      binary: {
        supported: true,
        field: 'file',
        maxBytes: 26214400,
        contentTypes: ['text/html', 'application/zip', 'application/x-zip-compressed'],
      },
      inputSchema: {
        type: 'object',
        required: ['title', 'upload'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 160,
          },
          description: {
            type: 'string',
            maxLength: 1200,
          },
          tags: {
            type: 'array',
            maxItems: 12,
            items: {
              type: 'string',
              minLength: 1,
              maxLength: 40,
            },
          },
          visibility: {
            enum: ['public', 'private'],
          },
          versionTitle: {
            type: 'string',
            maxLength: 160,
          },
          notes: {
            type: 'string',
            maxLength: 1000,
          },
          upload: {
            type: 'object',
            required: ['filename', 'contentType', 'size', 'dataBase64'],
            properties: {
              field: {
                type: 'string',
                maxLength: 80,
              },
              filename: {
                type: 'string',
                minLength: 1,
                maxLength: 240,
              },
              contentType: {
                type: 'string',
                minLength: 1,
                maxLength: 160,
              },
              size: {
                type: 'integer',
                minimum: 1,
                maximum: 26214400,
              },
              dataBase64: {
                type: 'string',
                minLength: 1,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.comment',
      title: 'Add note to work',
      description: 'Add a note to one work.',
      ingress: {
        path: '/.shadow/commands/artworks.comment',
        auth: 'shadow-command-jwt',
      },
      permission: 'space.comments:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['artworkId', 'body'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
          body: {
            type: 'string',
            minLength: 1,
            maxLength: 1200,
          },
          context: {
            type: 'object',
            description:
              'Structured page state for selection notes, including box geometry, frame, version, and screenshot data.',
            additionalProperties: true,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'covers.upload',
      title: 'Update cover',
      description: 'Attach a cover image to the profile or one work.',
      help: {
        summary: 'Attach a visual cover to the Space profile or a work card.',
        usage:
          'shadowob space-app call space covers.upload --server "<server>" --file ./cover.png --json-input \'{"targetType":"artwork","artworkId":"art_123"}\' --json',
        details:
          'Use targetType=profile for the portfolio cover. Use targetType=artwork with artworkId for a work cover.',
      },
      ingress: {
        path: '/.shadow/commands/covers.upload',
        auth: 'shadow-command-jwt',
      },
      permission: 'space.artworks:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      input: 'multipart',
      binary: {
        supported: true,
        field: 'file',
        maxBytes: 10485760,
        contentTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/gif', 'image/svg+xml'],
      },
      inputSchema: {
        type: 'object',
        required: ['targetType', 'upload'],
        properties: {
          targetType: {
            enum: ['profile', 'artwork'],
          },
          artworkId: {
            type: 'string',
            minLength: 1,
          },
          upload: {
            type: 'object',
            required: ['filename', 'contentType', 'size', 'dataBase64'],
            properties: {
              field: {
                type: 'string',
                maxLength: 80,
              },
              filename: {
                type: 'string',
                minLength: 1,
                maxLength: 240,
              },
              contentType: {
                type: 'string',
                minLength: 1,
                maxLength: 160,
              },
              size: {
                type: 'integer',
                minimum: 1,
                maximum: 10485760,
              },
              dataBase64: {
                type: 'string',
                minLength: 1,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.like',
      title: 'Appreciate work',
      description: 'Toggle an appreciation interaction for one work.',
      ingress: {
        path: '/.shadow/commands/artworks.like',
        auth: 'shadow-command-jwt',
      },
      permission: 'space.interactions:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['artworkId'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.favorite',
      title: 'Collect work',
      description: 'Toggle a saved work and update the collection shelf.',
      ingress: {
        path: '/.shadow/commands/artworks.favorite',
        auth: 'shadow-command-jwt',
      },
      permission: 'space.favorites:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['artworkId'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'artworks.remix',
      title: 'Make a response',
      description:
        'Create a private response copy so the caller can make something in the same spirit.',
      ingress: {
        path: '/.shadow/commands/artworks.remix',
        auth: 'shadow-command-jwt',
      },
      permission: 'space.artworks:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['artworkId'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'versions.rollback',
      title: 'Restore edition',
      description: 'Create a restored edition from a previous edition and make it current.',
      ingress: {
        path: '/.shadow/commands/versions.rollback',
        auth: 'shadow-command-jwt',
      },
      permission: 'space.versions:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['artworkId', 'versionId'],
        properties: {
          artworkId: {
            type: 'string',
            minLength: 1,
          },
          versionId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'favorites.list',
      title: 'List collection',
      description: 'List the personal collection shelf with saved works.',
      ingress: {
        path: '/.shadow/commands/favorites.list',
        auth: 'shadow-command-jwt',
      },
      permission: 'space.favorites:read',
      action: 'read',
      dataClass: 'server-private',
    },
    {
      name: 'tags.list',
      title: 'List tags',
      description: 'List tag chips with counts.',
      ingress: {
        path: '/.shadow/commands/tags.list',
        auth: 'shadow-command-jwt',
      },
      permission: 'space.artworks:read',
      action: 'read',
      dataClass: 'public',
    },
  ],
  skills: [
    {
      name: 'space-portfolio-ops',
      description:
        'Use when a Buddy needs to inspect a Space portfolio, publish work, add notes, make responses, collect works, or restore an edition.',
      commandHints: [
        'space profile.get',
        'space artworks.list',
        'space artworks.get',
        'space artworks.upload',
        'space covers.upload',
        'space artworks.comment',
        'space artworks.remix',
        'space versions.rollback',
      ],
    },
  ],
  events: ['space.updated'],
  binary: {
    supported: true,
  },
  i18n: {
    'zh-CN': {
      name: '空间',
      description:
        '创作者作品集应用，支持个人主页、作品、封面、标签、回应、改作、收藏、版本恢复和 CDN 浏览。',
      marketplace: {
        tagline: '面向创作者的主页、作品、封面、回应和改作空间。',
        summary:
          '空间为创作者提供服务器原生作品集，包括个人主页、上传作品、封面图、标签、回应、改作、收藏作品、版本恢复和 CDN 浏览。它适合一起创作和讨论作品的社区。',
        categories: ['创作', '社区', '作品集'],
        gallery: [
          {
            alt: '空间封面',
          },
        ],
        links: [
          {
            label: '主页',
          },
        ],
      },
    },
  },
} as const satisfies ShadowSpaceAppManifest

export type ShadowSpaceAppManifestDefinition = typeof shadowSpaceAppManifest
