name: shadow-integrations-dev

services:
  trainer:
    command: pnpm dev:hot:install
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
      TRAINER_VITE_PORT: ${TRAINER_VITE_PORT:-5173}
      TRAINER_VITE_DEV_SERVER_URL: ${TRAINER_VITE_DEV_SERVER_URL:-http://localhost:5173}
    ports:
      - ${TRAINER_VITE_PORT:-5173}:${TRAINER_VITE_PORT:-5173}
    volumes:
      - ${TRAINER_DEV_APP_DIR:-./trainer}:/repo/integrations/trainer
      - trainer-node-modules:/repo/node_modules
      - trainer-space-app-node-modules:/repo/integrations/trainer/node_modules

volumes:
  trainer-node-modules:
  trainer-space-app-node-modules:
