import { randomUUID } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { basename, extname, join } from 'node:path'
import type { CardMeta } from '@shadowob/flash-types'
import type {
  FlashActorRef,
  FlashArena,
  FlashBoard,
  FlashBoardSnapshot,
  FlashCard,
  FlashCardKind,
  FlashCardPriority,
  FlashCommandEvent,
  FlashCommandName,
  FlashMutationResult,
  FlashPatchEvent,
  FlashSelection,
  FlashUploadedAsset,
  FlashUploadInput,
  FlashViewport,
} from '@shadowob/flash-types/server-app'
import {
  type ArenasActivateInput,
  type ArenasCreateInput,
  type AssetsUploadInput,
  type BoardEventsInput,
  type BoardGetInput,
  type BoardViewportUpdateInput,
  type CardsCommandInput,
  type CardsCreateInput,
  type CardsDeleteInput,
  type CardsGetInput,
  type CardsUpdateInput,
  type RoomsAttachInput,
  type SelectionGetInput,
  type SelectionUpdateInput,
} from '@shadowob/flash-types/server-app'
import type { ShadowServerAppActorRef, ShadowServerAppCommandContext } from '@shadowob/sdk'
import {
  FlashArenaDao,
  FlashBoardDao,
  FlashCardDao,
  FlashCommandEventDao,
  FlashSelectionDao,
} from '../dao/flash.dao.js'
import type {
  flashArenas,
  flashBoards,
  flashCards,
  flashCommandEvents,
  flashSelections,
} from '../db/schema.js'
import type { FlashRealtimeService } from './realtime.service.js'

type BoardRow = typeof flashBoards.$inferSelect
type CardRow = typeof flashCards.$inferSelect
type ArenaRow = typeof flashArenas.$inferSelect
type EventRow = typeof flashCommandEvents.$inferSelect
type SelectionRow = typeof flashSelections.$inferSelect

interface CommandDispatch {
  result: unknown
  patches: FlashPatchEvent[]
}

export interface FlashCommandScope {
  context: ShadowServerAppCommandContext
  actor: ShadowServerAppActorRef
}

function nowMs(date: Date) {
  return date.getTime()
}

function id(prefix: string) {
  return `${prefix}_${randomUUID()}`
}

function uploadDir() {
  return process.env.FLASH_UPLOAD_DIR ?? join(process.cwd(), 'data', 'uploads')
}

function uploadPublicPath(filename: string) {
  return `/uploads/${filename}`
}

function safeUploadExtension(filename: string, contentType: string) {
  const ext = extname(filename).toLowerCase()
  if (/^\.[a-z0-9]{1,12}$/u.test(ext)) return ext
  if (contentType === 'image/png') return '.png'
  if (contentType === 'image/jpeg') return '.jpg'
  if (contentType === 'image/webp') return '.webp'
  if (contentType === 'image/gif') return '.gif'
  return '.bin'
}

function asError(status: number, message: string) {
  return Object.assign(new Error(message), { status })
}

function asNumber(value: unknown, fallback: number) {
  return typeof value === 'number' && Number.isFinite(value) ? value : fallback
}

function asString(value: unknown, fallback: string) {
  return typeof value === 'string' && value.trim() ? value.trim() : fallback
}

function actorRef(scope: FlashCommandScope): FlashActorRef {
  return {
    ...scope.actor,
    profile: scope.context.actor.profile ?? null,
  }
}

function actorResourceOwner(scope: FlashCommandScope) {
  return scope.context.actor.ownerId ?? scope.context.actor.userId ?? scope.actor.userId ?? 'local'
}

function selectionActorId(scope: FlashCommandScope) {
  return scope.actor.id
}

function boardOwnerTitle(scope: FlashCommandScope) {
  const actor = scope.context.actor
  if (actor.kind === 'agent' && actor.ownerId && actor.ownerId !== actor.userId) {
    return "Owner's Flash Board"
  }
  return `${actorRef(scope).displayName}'s Flash Board`
}

function mapBoard(row: BoardRow): FlashBoard {
  return {
    id: row.id,
    serverId: row.serverId,
    ownerUserId: row.ownerUserId,
    title: row.title,
    viewport: row.viewport ?? null,
    createdAt: nowMs(row.createdAt),
    updatedAt: nowMs(row.updatedAt),
  }
}

function mapCard(row: CardRow): FlashCard {
  return {
    id: row.id,
    kind: row.kind,
    title: row.title,
    summary: row.summary ?? undefined,
    content: row.content ?? undefined,
    thumbnail: row.thumbnail ?? undefined,
    sourceId: row.sourceId,
    linkedCardIds: row.linkedCardIds ?? [],
    meta: (row.meta ?? {}) as CardMeta,
    tags: row.tags ?? [],
    priority: row.priority,
    autoGenerated: row.autoGenerated,
    rating: row.rating,
    filePath: row.filePath ?? undefined,
    fileMime: row.fileMime ?? undefined,
    deckIds: row.deckIds ?? [],
    createdAt: nowMs(row.createdAt),
    updatedAt: nowMs(row.updatedAt),
    layout: {
      x: row.x,
      y: row.y,
      angle: row.angle,
      flipped: row.flipped,
      hidden: row.hidden,
      locked: row.locked,
    },
    createdBy: row.createdBy ?? null,
  }
}

function mapArena(row: ArenaRow): FlashArena {
  return {
    id: row.id,
    boardId: row.boardId,
    kind: row.kind,
    label: row.label,
    x: row.x,
    y: row.y,
    radius: row.radius,
    color: row.color,
    cardIds: row.cardIds ?? [],
    script: row.script,
    createdAt: nowMs(row.createdAt),
    updatedAt: nowMs(row.updatedAt),
  }
}

function mapEvent(row: EventRow): FlashCommandEvent {
  return {
    id: row.id,
    seq: row.seq,
    boardId: row.boardId,
    cardId: row.cardId,
    commandName: row.commandName,
    command: row.command,
    result: row.result,
    patches: row.patches ?? [],
    actor: row.actor ?? null,
    createdAt: nowMs(row.createdAt),
  }
}

function mapSelection(row: SelectionRow): FlashSelection {
  return {
    boardId: row.boardId,
    actorId: row.actorId,
    actor: row.actor ?? null,
    selectedCardIds: row.selectedCardIds ?? [],
    anchorCardId: row.anchorCardId ?? null,
    revision: row.revision,
    updatedAt: nowMs(row.updatedAt),
  }
}

function nearby(cards: CardRow[], target: CardRow, radius: number) {
  return cards
    .filter((card) => card.id !== target.id)
    .map((card) => ({
      id: card.id,
      title: card.title,
      distance: Math.hypot(card.x - target.x, card.y - target.y),
    }))
    .filter((item) => item.distance <= radius)
    .sort((a, b) => a.distance - b.distance)
}

function dispatch(result: unknown, patches: FlashPatchEvent[] = []): CommandDispatch {
  return { result, patches }
}

function updatedCardPatch(card: CardRow | null): FlashPatchEvent[] {
  return card ? [{ type: 'card.updated', card: mapCard(card) }] : []
}

function commandInputForEvent(input: unknown) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) return input
  const { upload: _upload, ...rest } = input as Record<string, unknown>
  return rest
}

export class FlashService {
  constructor(
    private readonly deps: {
      boards: FlashBoardDao
      cards: FlashCardDao
      arenas: FlashArenaDao
      events: FlashCommandEventDao
      selections: FlashSelectionDao
      realtime: FlashRealtimeService
    },
  ) {}

  async getBoard(input: BoardGetInput, scope: FlashCommandScope) {
    const board = await this.resolveBoard(input.boardId, scope)
    return { snapshot: await this.snapshot(board, scope) }
  }

  async listBoardEvents(input: BoardEventsInput, scope: FlashCommandScope) {
    const board = await this.resolveBoard(input.boardId, scope)
    const rows = await this.deps.events.listAfter(board.id, input.after ?? 0, input.limit ?? 200)
    const events = rows.map(mapEvent)
    return { events, cursor: this.cursorFromEvents(events, input.after ?? 0) }
  }

  private async storeUpload(upload: FlashUploadInput): Promise<FlashUploadedAsset> {
    if (!upload.contentType.startsWith('image/')) throw asError(415, 'unsupported_upload_type')
    const bytes = Buffer.from(upload.dataBase64, 'base64')
    if (bytes.byteLength !== upload.size) throw asError(400, 'upload_size_mismatch')
    const filename = `${id('asset')}${safeUploadExtension(upload.filename, upload.contentType)}`
    await mkdir(uploadDir(), { recursive: true })
    await writeFile(join(uploadDir(), filename), bytes)
    return {
      url: uploadPublicPath(filename),
      path: uploadPublicPath(filename),
      filename: basename(upload.filename),
      contentType: upload.contentType,
      size: bytes.byteLength,
    }
  }

  private async applyUploadToCardInput<T extends CardsCreateInput | CardsUpdateInput>(
    input: T,
  ): Promise<T & { storedAsset?: FlashUploadedAsset }> {
    if (!input.upload) return input
    const asset = await this.storeUpload(input.upload)
    const meta = {
      ...(input.meta ?? {}),
      image: {
        ...((input.meta?.image as Record<string, unknown> | undefined) ?? {}),
        src: asset.url,
      },
      upload: {
        filename: asset.filename,
        contentType: asset.contentType,
        size: asset.size,
      },
    }
    return {
      ...input,
      kind: input.kind ?? 'image',
      thumbnail: input.thumbnail ?? asset.url,
      filePath: input.filePath ?? asset.path,
      fileMime: input.fileMime ?? asset.contentType,
      meta,
      storedAsset: asset,
    }
  }

  async updateBoardViewport(input: BoardViewportUpdateInput, scope: FlashCommandScope) {
    const board = await this.resolveBoard(input.boardId, scope)
    const viewport: FlashViewport = {
      offsetX: input.viewport.offsetX,
      offsetY: input.viewport.offsetY,
      zoom: input.viewport.zoom,
      updatedAt: Date.now(),
    }
    await this.deps.boards.updateViewport(board.id, viewport)
    return this.recordMutation(board, scope, 'boards.viewport.update', null, input, { viewport }, [
      { type: 'board.viewport.updated', viewport },
    ])
  }

  async getCard(input: CardsGetInput, scope: FlashCommandScope) {
    const board = await this.resolveBoard(input.boardId, scope)
    const card = await this.deps.cards.findById(board.id, input.cardId)
    if (!card) throw asError(404, 'card_not_found')
    return { card: mapCard(card), snapshot: await this.snapshot(board, scope) }
  }

  async createCard(input: CardsCreateInput, scope: FlashCommandScope) {
    const board = await this.resolveBoard(input.boardId, scope)
    const normalized = await this.applyUploadToCardInput(input)
    const card = await this.createCardRow(board, scope, {
      title: normalized.title,
      kind: (normalized.kind ?? 'inspiration') as FlashCardKind,
      summary: normalized.summary,
      content: normalized.content,
      tags: normalized.tags ?? [],
      x: normalized.x ?? 260,
      y: normalized.y ?? 240,
      angle: normalized.angle ?? 0,
      thumbnail: normalized.thumbnail,
      sourceId: normalized.sourceId ?? null,
      linkedCardIds: normalized.linkedCardIds ?? [],
      meta: normalized.meta,
      priority: normalized.priority ?? 'medium',
      autoGenerated: normalized.autoGenerated ?? false,
      rating: normalized.rating ?? 0,
      filePath: normalized.filePath,
      fileMime: normalized.fileMime,
      deckIds: normalized.deckIds ?? [],
      flipped: normalized.flipped ?? false,
      hidden: normalized.hidden ?? false,
      locked: normalized.locked ?? false,
    })
    const mapped = mapCard(card)
    return this.recordMutation(
      board,
      scope,
      'cards.create',
      card.id,
      commandInputForEvent(input),
      { card: mapped, asset: normalized.storedAsset ?? null },
      [{ type: 'card.created', card: mapped }],
    )
  }

  async updateCard(input: CardsUpdateInput, scope: FlashCommandScope) {
    const board = await this.resolveBoard(input.boardId, scope)
    const normalized = await this.applyUploadToCardInput(input)
    const card = await this.deps.cards.update(board.id, input.cardId, {
      title: normalized.title,
      kind: normalized.kind,
      summary: normalized.summary,
      content: normalized.content,
      thumbnail: normalized.thumbnail,
      sourceId: normalized.sourceId,
      linkedCardIds: normalized.linkedCardIds,
      meta: normalized.meta,
      tags: normalized.tags,
      priority: normalized.priority,
      autoGenerated: normalized.autoGenerated,
      rating: normalized.rating,
      filePath: normalized.filePath,
      fileMime: normalized.fileMime,
      deckIds: normalized.deckIds,
      x: normalized.x,
      y: normalized.y,
      angle: normalized.angle,
      flipped: normalized.flipped,
      hidden: normalized.hidden,
      locked: normalized.locked,
    })
    if (!card) throw asError(404, 'card_not_found')
    const mapped = mapCard(card)
    return this.recordMutation(
      board,
      scope,
      'cards.update',
      card.id,
      commandInputForEvent(input),
      { card: mapped, asset: normalized.storedAsset ?? null },
      [{ type: 'card.updated', card: mapped }],
    )
  }

  async deleteCard(input: CardsDeleteInput, scope: FlashCommandScope) {
    const board = await this.resolveBoard(input.boardId, scope)
    const card = await this.deps.cards.delete(board.id, input.cardId)
    if (!card) throw asError(404, 'card_not_found')
    const mapped = mapCard(card)
    return this.recordMutation(board, scope, 'cards.delete', card.id, input, { deleted: mapped }, [
      { type: 'card.deleted', cardId: card.id },
    ])
  }

  async uploadAsset(input: AssetsUploadInput, scope: FlashCommandScope) {
    const board = await this.resolveBoard(input.boardId, scope)
    const asset = await this.storeUpload(input.upload)
    return this.recordMutation(
      board,
      scope,
      'assets.upload',
      null,
      { upload: { filename: input.upload.filename, contentType: input.upload.contentType } },
      { asset },
      [],
    )
  }

  async getSelection(input: SelectionGetInput, scope: FlashCommandScope) {
    const board = await this.resolveBoard(input.boardId, scope)
    const rows = input.actorId
      ? [await this.deps.selections.findByActor(board.id, input.actorId)].filter(Boolean)
      : await this.deps.selections.listByBoard(board.id)
    return { selections: rows.map((row) => mapSelection(row!)) }
  }

  async updateSelection(input: SelectionUpdateInput, scope: FlashCommandScope) {
    const board = await this.resolveBoard(input.boardId, scope)
    const existingCardIds = new Set(
      (await this.deps.cards.listByBoard(board.id)).map((card) => card.id),
    )
    const selectedCardIds = input.selectedCardIds.filter((cardId) => existingCardIds.has(cardId))
    const selection = await this.deps.selections.upsert({
      boardId: board.id,
      actorId: selectionActorId(scope),
      actor: actorRef(scope),
      selectedCardIds,
      anchorCardId:
        input.anchorCardId && selectedCardIds.includes(input.anchorCardId)
          ? input.anchorCardId
          : null,
      revision: input.revision ?? Date.now(),
    })
    const mapped = mapSelection(selection)
    return this.recordMutation(
      board,
      scope,
      'selection.update',
      mapped.anchorCardId,
      input,
      { selection: mapped },
      [{ type: 'selection.updated', selection: mapped }],
    )
  }

  async attachRoom(input: RoomsAttachInput, scope: FlashCommandScope) {
    const board = await this.resolveBoard(input.boardId, scope)
    const cards = await this.deps.cards.listByBoard(board.id)
    const card = cards.find((item) => item.id === input.cardId)
    if (!card) throw asError(404, 'card_not_found')
    const near = nearby(cards, card, input.radius ?? 360)
    return {
      attached: {
        actor: actorRef(scope),
        card: mapCard(card),
        nearby: near,
        commandHints: [
          {
            command: 'cards.command',
            input: {
              command: { name: 'scan', cardId: card.id, params: { radius: input.radius ?? 360 } },
            },
          },
          {
            command: 'cards.command',
            input: {
              command: {
                name: 'arena',
                cardId: '__arena__',
                params: { kind: 'magic-circle', x: card.x, y: card.y },
              },
            },
          },
        ],
      },
      snapshot: await this.snapshot(board, scope),
    }
  }

  async createArena(input: ArenasCreateInput, scope: FlashCommandScope) {
    const board = await this.resolveBoard(input.boardId, scope)
    const arena = await this.deps.arenas.create({
      id: id('arena'),
      boardId: board.id,
      kind: input.kind ?? 'magic-circle',
      label: input.label ?? (input.kind === 'grid' ? 'Grid Arena' : 'Magic Circle'),
      x: input.x ?? 520,
      y: input.y ?? 360,
      radius: input.radius ?? 280,
      color: input.color ?? '#7c3aed',
      cardIds: [],
    })
    const mapped = mapArena(arena)
    return this.recordMutation(board, scope, 'arenas.create', null, input, { arena: mapped }, [
      { type: 'arena.created', arena: mapped },
    ])
  }

  async activateArena(input: ArenasActivateInput, scope: FlashCommandScope) {
    const board = await this.resolveBoard(input.boardId, scope)
    const result = await this.activateArenaById(board, input.arenaId)
    return this.recordMutation(board, scope, 'arenas.activate', null, input, result, [
      { type: 'arena.updated', arena: result.arena },
      { type: 'cards.updated', cards: result.affected },
    ])
  }

  async executeCommand(input: CardsCommandInput, scope: FlashCommandScope) {
    const board = await this.resolveBoard(input.boardId, scope)
    const dispatched = await this.dispatchPersistentCommand(board, input.command, scope)
    return this.recordMutation(
      board,
      scope,
      input.command.name,
      input.command.cardId || null,
      input.command,
      dispatched.result,
      dispatched.patches,
    )
  }

  private async createCardRow(
    board: BoardRow,
    scope: FlashCommandScope,
    input: {
      title: string
      kind: FlashCardKind
      summary?: string
      content?: string
      tags?: string[]
      x: number
      y: number
      angle?: number
      thumbnail?: string
      sourceId?: string | null
      linkedCardIds?: string[]
      meta?: Record<string, unknown>
      priority?: FlashCardPriority
      autoGenerated: boolean
      rating?: number
      filePath?: string
      fileMime?: string
      deckIds?: string[]
      flipped?: boolean
      hidden?: boolean
      locked?: boolean
    },
  ) {
    return this.deps.cards.create({
      id: id('card'),
      boardId: board.id,
      kind: input.kind,
      title: input.title,
      summary: input.summary,
      content: input.content,
      thumbnail: input.thumbnail,
      sourceId: input.sourceId ?? null,
      linkedCardIds: input.linkedCardIds ?? [],
      meta: input.meta ?? { body: input.content ?? input.summary ?? '' },
      tags: input.tags ?? [],
      priority: input.priority ?? 'medium',
      autoGenerated: input.autoGenerated,
      rating: input.rating ?? 0,
      filePath: input.filePath,
      fileMime: input.fileMime,
      deckIds: input.deckIds ?? [],
      x: input.x,
      y: input.y,
      angle: input.angle ?? 0,
      flipped: input.flipped,
      hidden: input.hidden,
      locked: input.locked,
      createdBy: actorRef(scope),
    })
  }

  private async resolveBoard(boardId: string | undefined, scope: FlashCommandScope) {
    const ownerUserId = actorResourceOwner(scope)
    let board = boardId ? await this.deps.boards.findById(boardId) : null
    if (board && board.serverId === scope.context.serverId && board.ownerUserId === ownerUserId) {
      return board
    }
    if (board) throw asError(403, 'board_not_accessible')

    if (!board) {
      board = await this.deps.boards.findByOwner(scope.context.serverId, ownerUserId)
    }
    if (!board) {
      board = await this.deps.boards.create({
        id: id('board'),
        serverId: scope.context.serverId,
        ownerUserId,
        title: boardOwnerTitle(scope),
      })
    }
    return board
  }

  private async snapshot(board: BoardRow, scope: FlashCommandScope): Promise<FlashBoardSnapshot> {
    const [cards, arenas, selections, events] = await Promise.all([
      this.deps.cards.listByBoard(board.id),
      this.deps.arenas.listByBoard(board.id),
      this.deps.selections.listByBoard(board.id),
      this.deps.events.listByBoard(board.id),
    ])
    const mappedEvents = events.map(mapEvent)
    return {
      actor: actorRef(scope),
      board: mapBoard(board),
      cards: cards.map(mapCard),
      arenas: arenas.map(mapArena),
      selections: selections.map(mapSelection),
      events: mappedEvents,
      cursor: this.cursorFromEvents(mappedEvents, 0),
    }
  }

  private cursorFromEvents(events: Array<{ seq: number }>, fallback: number) {
    return events.reduce((cursor, event) => Math.max(cursor, event.seq), fallback)
  }

  private async recordMutation(
    board: BoardRow,
    scope: FlashCommandScope,
    commandName: string,
    cardId: string | null,
    command: unknown,
    result: unknown,
    patches: FlashPatchEvent[],
  ): Promise<FlashMutationResult> {
    const row = await this.deps.events.create({
      id: id('evt'),
      boardId: board.id,
      cardId,
      commandName,
      command,
      result,
      patches,
      actor: actorRef(scope),
    })
    const event = mapEvent(row)
    await this.deps.boards.touch(board.id)
    await this.deps.realtime.publish({
      type: 'flash.events.appended',
      boardId: board.id,
      at: Date.now(),
      payload: {
        events: [event],
        cursor: event.seq,
      },
    })
    for (const patch of patches) {
      if (patch.type !== 'selection.updated') continue
      await this.deps.realtime.publish({
        type: 'flash.selection.updated',
        boardId: board.id,
        at: Date.now(),
        payload: patch.selection,
      })
    }
    return {
      result,
      events: [event],
      cursor: event.seq,
    }
  }

  private async dispatchPersistentCommand(
    board: BoardRow,
    command: CardsCommandInput['command'],
    scope: FlashCommandScope,
  ): Promise<CommandDispatch> {
    const cards = await this.deps.cards.listByBoard(board.id)
    const params = command.params ?? {}
    const target = cards.find((card) => card.id === command.cardId)

    if (command.name === 'help') {
      return dispatch({
        success: true,
        data: {
          commands: [
            '/add title=Idea kind=image',
            '/scan <card> radius=360',
            '/arena magic-circle x=520 y=360',
            '/move-to <card> <arenaId>',
            '/activate <arenaId>',
            'shadowob app call shadow-flash cards.create --file ./image.png',
            'shadowob app call shadow-flash selection.get',
          ],
        },
      })
    }

    if (command.name === 'add') {
      const card = await this.deps.cards.create({
        id: id('card'),
        boardId: board.id,
        kind: asString(params.kind, 'inspiration') as FlashCardKind,
        title: asString(params.title, 'New card'),
        summary: typeof params.summary === 'string' ? params.summary : undefined,
        content: typeof params.content === 'string' ? params.content : undefined,
        sourceId: null,
        linkedCardIds: [],
        meta: { body: typeof params.content === 'string' ? params.content : '' },
        tags: [],
        priority: 'medium',
        autoGenerated: false,
        rating: 0,
        deckIds: [],
        x: asNumber(params.x, 260),
        y: asNumber(params.y, 240),
        angle: 0,
        createdBy: actorRef(scope),
      })
      const mapped = mapCard(card)
      return dispatch({ success: true, data: { card: mapped } }, [
        { type: 'card.created', card: mapped },
      ])
    }

    if (command.name === 'arena') {
      const arena = await this.deps.arenas.create({
        id: id('arena'),
        boardId: board.id,
        kind: asString(params.kind, 'magic-circle') as FlashArena['kind'],
        label: asString(params.label, 'Magic Circle'),
        x: asNumber(params.x, 520),
        y: asNumber(params.y, 360),
        radius: asNumber(params.radius, 280),
        color: asString(params.color, '#7c3aed'),
        cardIds: [],
      })
      const mapped = mapArena(arena)
      return dispatch({ success: true, data: { arena: mapped, arenaId: arena.id } }, [
        { type: 'arena.created', arena: mapped },
      ])
    }

    if (command.name === 'activate') {
      const arenaId = asString(params.arenaId, command.cardId)
      const data = await this.activateArenaById(board, arenaId)
      return dispatch({ success: true, data }, [
        { type: 'arena.updated', arena: data.arena },
        { type: 'cards.updated', cards: data.affected },
      ])
    }

    if (command.name === 'stack') {
      const ids = Array.isArray(params.cardIds)
        ? params.cardIds.filter((item): item is string => typeof item === 'string')
        : cards.slice(0, 8).map((card) => card.id)
      const first = cards.find((card) => ids.includes(card.id)) ?? cards[0]
      if (!first) return { success: false, error: 'card_not_found' }
      const dx = asNumber(params.dx, 18)
      const dy = asNumber(params.dy, 8)
      const changed = await this.deps.cards.updateLayouts(
        board.id,
        ids.map((item, index) => ({
          id: item,
          x: first.x + index * dx,
          y: first.y + index * dy,
          angle: first.angle + index * 0.015,
        })),
      )
      return dispatch({ success: true, data: { cardIds: ids } }, [
        { type: 'cards.updated', cards: changed.map(mapCard) },
      ])
    }

    if (!target) return dispatch({ success: false, error: 'card_not_found' })

    if (command.name === 'move') {
      const x =
        params.x === undefined ? target.x + asNumber(params.dx, 0) : asNumber(params.x, target.x)
      const y =
        params.y === undefined ? target.y + asNumber(params.dy, 0) : asNumber(params.y, target.y)
      const card = await this.deps.cards.update(board.id, target.id, { x, y })
      return dispatch(
        { success: true, data: { card: card ? mapCard(card) : null } },
        updatedCardPatch(card),
      )
    }

    if (command.name === 'rotate') {
      const angle =
        params.angle === undefined
          ? target.angle + asNumber(params.delta, 15) * (Math.PI / 180)
          : asNumber(params.angle, target.angle)
      const card = await this.deps.cards.update(board.id, target.id, { angle })
      return dispatch(
        { success: true, data: { card: card ? mapCard(card) : null } },
        updatedCardPatch(card),
      )
    }

    if (command.name === 'flip') {
      const face = typeof params.face === 'string' ? params.face : 'toggle'
      const flipped = face === 'back' ? true : face === 'front' ? false : !target.flipped
      const card = await this.deps.cards.update(board.id, target.id, { flipped })
      return dispatch(
        { success: true, data: { card: card ? mapCard(card) : null } },
        updatedCardPatch(card),
      )
    }

    if (command.name === 'trash') {
      const deleted = await this.deps.cards.delete(board.id, target.id)
      return dispatch({ success: true, data: { deletedCardId: deleted?.id ?? target.id } }, [
        { type: 'card.deleted', cardId: deleted?.id ?? target.id },
      ])
    }

    if (command.name === 'link') {
      const targetId = asString(params.targetId, '')
      const exists = cards.some((card) => card.id === targetId)
      if (!exists) return dispatch({ success: false, error: 'target_card_not_found' })
      const linked = target.linkedCardIds.includes(targetId)
        ? target.linkedCardIds.filter((item) => item !== targetId)
        : [...target.linkedCardIds, targetId]
      const card = await this.deps.cards.update(board.id, target.id, { linkedCardIds: linked })
      return dispatch(
        { success: true, data: { card: card ? mapCard(card) : null } },
        updatedCardPatch(card),
      )
    }

    if (command.name === 'toggle') {
      const hidden = typeof params.visible === 'boolean' ? !params.visible : !target.hidden
      const card = await this.deps.cards.update(board.id, target.id, { hidden })
      return dispatch(
        { success: true, data: { card: card ? mapCard(card) : null } },
        updatedCardPatch(card),
      )
    }

    if (command.name === 'lock') {
      const locked = typeof params.locked === 'boolean' ? params.locked : !target.locked
      const card = await this.deps.cards.update(board.id, target.id, { locked })
      return dispatch(
        { success: true, data: { card: card ? mapCard(card) : null } },
        updatedCardPatch(card),
      )
    }

    if (command.name === 'scan') {
      return dispatch({
        success: true,
        data: { nearby: nearby(cards, target, asNumber(params.radius, 360)) },
      })
    }

    if (command.name === 'move-to') {
      const arenaId = asString(params.arenaId, '')
      const arena = await this.deps.arenas.findById(board.id, arenaId)
      if (!arena) return dispatch({ success: false, error: 'arena_not_found' })
      const cardIds = arena.cardIds.includes(target.id)
        ? arena.cardIds
        : [...arena.cardIds, target.id]
      const nextArena = await this.deps.arenas.updateCards(board.id, arena.id, cardIds)
      const card = await this.deps.cards.update(board.id, target.id, {
        x: arena.x + (cardIds.length % 3) * 28,
        y: arena.y + Math.floor(cardIds.length / 3) * 24,
      })
      const patches: FlashPatchEvent[] = []
      if (nextArena) patches.push({ type: 'arena.updated', arena: mapArena(nextArena) })
      patches.push(...updatedCardPatch(card))
      return dispatch(
        { success: true, data: { arenaId: arena.id, card: card ? mapCard(card) : null } },
        patches,
      )
    }

    return dispatch({
      success: true,
      data: {
        persisted: false,
        message: `${command.name} is a client-side visual command and was recorded.`,
      },
    })
  }

  private async activateArenaById(board: BoardRow, arenaId: string) {
    const arena = await this.deps.arenas.findById(board.id, arenaId)
    if (!arena) throw asError(404, 'arena_not_found')
    const allCards = await this.deps.cards.listByBoard(board.id)
    const activeIds =
      arena.cardIds.length > 0
        ? arena.cardIds
        : allCards
            .filter((card) => Math.hypot(card.x - arena.x, card.y - arena.y) <= arena.radius)
            .slice(0, 12)
            .map((card) => card.id)
    if (activeIds.length === 0) return { arenaId: arena.id, arena: mapArena(arena), affected: [] }

    const updates =
      arena.kind === 'grid'
        ? activeIds.map((cardId, index) => {
            const cols = Math.max(1, Math.ceil(Math.sqrt(activeIds.length)))
            return {
              id: cardId,
              x: arena.x - ((cols - 1) * 180) / 2 + (index % cols) * 180,
              y: arena.y - 90 + Math.floor(index / cols) * 150,
              angle: 0,
            }
          })
        : activeIds.map((cardId, index) => {
            const theta = (Math.PI * 2 * index) / activeIds.length - Math.PI / 2
            return {
              id: cardId,
              x: arena.x + Math.cos(theta) * arena.radius * 0.74,
              y: arena.y + Math.sin(theta) * arena.radius * 0.74,
              angle: theta + Math.PI / 2,
            }
          })
    const changed = await this.deps.cards.updateLayouts(board.id, updates)
    const updatedArena = await this.deps.arenas.updateCards(board.id, arena.id, activeIds)
    return {
      arenaId: arena.id,
      arena: mapArena(updatedArena ?? arena),
      affected: changed.map(mapCard),
    }
  }
}
