// Client

export type { MessageAgentChainMetadata } from '@shadowob/shared'
// Constants & room helpers
export {
  buildMessageAgentChainMetadata,
  buildMessageCopilotContextMetadata,
  isMessageAgentChainMetadata,
  isMessageCopilotContext,
  MESSAGE_AGENT_CHAIN_METADATA_KEY,
  MESSAGE_COPILOT_CONTEXT_METADATA_KEY,
} from '@shadowob/shared'
export {
  createShadowServerAppBrowserClient,
  createShadowServerAppClient,
  createShadowServerAppRuntimeClient,
  SHADOW_BRIDGE_CAPABILITIES,
  ShadowBridge,
  type ShadowBridgeAuthorizeOAuthInput,
  type ShadowBridgeAuthorizeOAuthResult,
  type ShadowBridgeCapability,
  type ShadowBridgeEnsureBuddyGrantInput,
  type ShadowBridgeLaunchContext,
  type ShadowBridgeLaunchUpdateHandler,
  type ShadowBridgeLaunchUpdateInput,
  type ShadowBridgeListBuddyInboxesInput,
  type ShadowBridgeOpenBuddyCreatorInput,
  type ShadowBridgeOpenCopilotInput,
  type ShadowBridgeOptions,
  type ShadowBridgeRefreshLaunchInput,
  type ShadowBridgeRouteNavigateEvent,
  type ShadowBridgeRouteNavigateHandler,
  type ShadowBridgeShareAppInput,
  type ShadowBridgeShareAppResult,
  ShadowServerAppBrowserClient,
  type ShadowServerAppBrowserClientOptions,
  type ShadowServerAppEnsureBuddyTaskGrantInput,
  type ShadowServerAppFetchWithLaunchOptions,
  type ShadowServerAppLaunchHeadersOptions,
  type ShadowServerAppListBuddyInboxesOptions,
  type ShadowServerAppRuntimeClientOptions,
} from './bridge'
export { ShadowClient } from './client'
export type { ClientEvent, ServerEvent } from './constants'
export { CLIENT_EVENTS, channelRoom, SERVER_EVENTS, threadRoom, userRoom } from './constants'
export type {
  BuddyInboxPlatformPermission,
  JsonSchemaToType,
  ShadowServerAppActorRef,
  ShadowServerAppBridgeAuthorizeOAuthRequest,
  ShadowServerAppBridgeCapabilitiesRequest,
  ShadowServerAppBridgeFailureResponse,
  ShadowServerAppBridgeOpenCopilotRequest,
  ShadowServerAppBridgeRequest,
  ShadowServerAppBridgeResponse,
  ShadowServerAppBridgeResponseType,
  ShadowServerAppBridgeRouteChangedEvent,
  ShadowServerAppBridgeRouteNavigateAck,
  ShadowServerAppBridgeRouteNavigateRequest,
  ShadowServerAppBridgeShareAppRequest,
  ShadowServerAppBridgeSuccessResponse,
  ShadowServerAppChannelMessageDelivery,
  ShadowServerAppChannelMessageDeliveryError,
  ShadowServerAppChannelMessageOutbox,
  ShadowServerAppCollaborationEvent,
  ShadowServerAppCollaborationMutation,
  ShadowServerAppCollaborationResource,
  ShadowServerAppCommandContext,
  ShadowServerAppCommandEnvelope,
  ShadowServerAppCommandEventType,
  ShadowServerAppCommandFailureResponse,
  ShadowServerAppCommandHandler,
  ShadowServerAppCommandHandlerContext,
  ShadowServerAppCommandHandlers,
  ShadowServerAppCommandInput,
  ShadowServerAppCommandName,
  ShadowServerAppCommandParseError,
  ShadowServerAppCommandParseResult,
  ShadowServerAppCommandParseSuccess,
  ShadowServerAppCommandRequestInput,
  ShadowServerAppCommandResponse,
  ShadowServerAppCommandSuccessResponse,
  ShadowServerAppExecutionFailure,
  ShadowServerAppExecutionResult,
  ShadowServerAppExecutionSuccess,
  ShadowServerAppFetch,
  ShadowServerAppHostAppRef,
  ShadowServerAppHostInboxTaskRequestInput,
  ShadowServerAppIdentitySnapshot,
  ShadowServerAppIdentitySubjectKind,
  ShadowServerAppInboxDelivery,
  ShadowServerAppInboxDeliveryError,
  ShadowServerAppInboxDeliveryFromMessageInput,
  ShadowServerAppInboxTarget,
  ShadowServerAppInboxTaskOutbox,
  ShadowServerAppInboxTaskPriority,
  ShadowServerAppInboxTaskResource,
  ShadowServerAppIntrospectionInput,
  ShadowServerAppLaunchCommandContextOptions,
  ShadowServerAppLaunchFetchOptions,
  ShadowServerAppLaunchIntrospection,
  ShadowServerAppLaunchOutboxDeliveryOptions,
  ShadowServerAppLaunchTokenHint,
  ShadowServerAppManifestOptions,
  ShadowServerAppOutboxPayload,
  ShadowServerAppResolvedInboxTaskRequest,
  ShadowServerAppResultShadow,
  ShadowServerAppResultWithShadow,
  ShadowServerAppRuntimeOptions,
  ShadowServerAppValidationIssue,
} from './server-app'
// App helpers
export {
  BUDDY_INBOX_DELIVERY_PERMISSION,
  buildShadowServerAppInboxDelivery,
  buildShadowServerAppInboxTaskRequest,
  createShadowServerAppCollaborationCursor,
  createShadowServerAppCollaborationEvent,
  createShadowServerAppCollaborationResource,
  createShadowServerAppManifest,
  createShadowServerAppRuntime,
  decodeShadowServerAppLaunchTokenHint,
  defineShadowServerApp,
  deliverShadowServerAppLaunchOutbox,
  extractShadowServerAppBearerToken,
  fetchShadowServerAppLaunchInboxes,
  getShadowServerAppChannelMessageDeliveries,
  getShadowServerAppChannelMessageErrors,
  getShadowServerAppTaskCardId,
  hasShadowServerAppPendingOutbox,
  introspectShadowServerAppLaunchToken,
  introspectShadowServerAppToken,
  normalizeShadowServerAppBaseCursor,
  normalizeShadowServerAppClientMutationId,
  normalizeShadowServerAppCommandInput,
  parseShadowServerAppCommandRequest,
  readShadowServerAppCommandResponse,
  resolveShadowServerAppLaunchCommandContext,
  SHADOW_SERVER_APP_COMMAND_COMPLETED_EVENT,
  SHADOW_SERVER_APP_COMMAND_EVENTS,
  SHADOW_SERVER_APP_COMMAND_FAILED_EVENT,
  SHADOW_SERVER_APP_PROTOCOL,
  ShadowServerAppCommandError,
  ShadowServerAppHttpError,
  ShadowServerAppOutbox,
  ShadowServerAppRuntime,
  shadowServerAppActorAvatarUrl,
  shadowServerAppActorDisplayName,
  shadowServerAppActorRef,
  shadowServerAppDisplayIdentity,
  shadowServerAppError,
  shadowServerAppIdentityKey,
  shadowServerAppIdentitySnapshot,
  shadowServerAppInboxTaskEndpoint,
  validateShadowServerAppJsonSchema,
} from './server-app'
export type { ShadowSocketOptions } from './socket'
// Socket
export { ShadowSocket } from './socket'
// Types
export type {
  ChannelCreatedPayload,
  ChannelMemberAddedPayload,
  ChannelMemberRemovedPayload,
  ClientEventMap,
  MemberJoinPayload,
  MemberLeavePayload,
  MessageDeletedPayload,
  PolicyChangedPayload,
  PresenceActivityPayload,
  PresenceChangePayload,
  ReactionPayload,
  ServerEventMap,
  ServerJoinedPayload,
  ShadowAddAgentsToServerResult,
  ShadowAgentUsageSnapshotInput,
  ShadowAttachment,
  ShadowBuddyInboxAdmissionMode,
  ShadowBuddyInboxAdmissionPendingActionResult,
  ShadowBuddyInboxAdmissionPendingDelivery,
  ShadowBuddyInboxAdmissionPendingResult,
  ShadowBuddyInboxAdmissionPolicy,
  ShadowBuddyInboxAdmissionPolicyResult,
  ShadowBuddyInboxAdmissionRule,
  ShadowBuddyInboxAdmissionSubjectKind,
  ShadowBuddyInboxSummary,
  ShadowCartItem,
  ShadowCategory,
  ShadowChannel,
  ShadowChannelAccess,
  ShadowChannelBootstrap,
  ShadowChannelJoinRequestResult,
  ShadowChannelJoinRequestStatus,
  ShadowChannelLastMessagePreview,
  ShadowChannelPolicy,
  ShadowChannelSlashCommand,
  ShadowCloudDeployment,
  ShadowCloudDeploymentBackup,
  ShadowCloudDeploymentDestroyResponse,
  ShadowCloudDeploymentRuntimeResponse,
  ShadowCloudDeploymentStatus,
  ShadowCloudProviderCatalog,
  ShadowCloudProviderEnvVar,
  ShadowCloudProviderModel,
  ShadowCloudProviderProfile,
  ShadowCloudTemplate,
  ShadowCommerceCheckoutPreview,
  ShadowCommerceProductCard,
  ShadowCommerceProductContext,
  ShadowCommerceProductPickerGroup,
  ShadowCommerceProductPickerResponse,
  ShadowCommunityAsset,
  ShadowCommunityAssetDefinition,
  ShadowCommunityAssetGrant,
  ShadowConnectorBootstrapResult,
  ShadowConnectorComputer,
  ShadowConnectorRuntimeInfo,
  ShadowContract,
  ShadowCreateCloudDeploymentInput,
  ShadowCreateCloudTemplateInput,
  ShadowDesktopReleaseDownload,
  ShadowDesktopReleaseInfo,
  ShadowDiyCloudRun,
  ShadowDiyCloudRunEvent,
  ShadowDiyCloudRunStatus,
  ShadowEnsureBuddyInboxResult,
  ShadowFriendship,
  ShadowInboxTaskInput,
  ShadowInteractiveActionInput,
  ShadowInteractiveActionResult,
  ShadowInteractiveBlock,
  ShadowInteractiveResponse,
  ShadowInteractiveState,
  ShadowInteractiveSubmissionPending,
  ShadowInviteCode,
  ShadowListing,
  ShadowMarketplaceCategoriesResponse,
  ShadowMarketplaceCategory,
  ShadowMarketplaceProduct,
  ShadowMarketplaceProductsResponse,
  ShadowMediaVariant,
  ShadowMember,
  ShadowMentionSuggestion,
  ShadowMentionSuggestionTrigger,
  ShadowMessage,
  ShadowMessageCard,
  ShadowMessageCardSource,
  ShadowMessageCopilotContext,
  ShadowMessageMention,
  ShadowMessageMetadata,
  ShadowModelProxyBilling,
  ShadowModelProxyChatCompletionRequest,
  ShadowModelProxyChatCompletionResponse,
  ShadowModelProxyModel,
  ShadowModelProxyModelsResponse,
  ShadowNotification,
  ShadowNotificationPreferences,
  ShadowOAuthApp,
  ShadowOAuthCommerceEntitlementAccess,
  ShadowOAuthCommerceEntitlementRedeemInput,
  ShadowOAuthCommerceEntitlementRedeemResult,
  ShadowOAuthCommerceEntitlementRedemption,
  ShadowOAuthCommerceEntitlementSummary,
  ShadowOAuthConsent,
  ShadowOAuthToken,
  ShadowOrder,
  ShadowPaidFileCard,
  ShadowPaidFileOpenResult,
  ShadowProduct,
  ShadowProductEntitlementConfig,
  ShadowProductMedia,
  ShadowProductSku,
  ShadowRemoteChannel,
  ShadowRemoteConfig,
  ShadowRemoteServer,
  ShadowReview,
  ShadowServer,
  ShadowServerAccess,
  ShadowServerAppActorProfile,
  ShadowServerAppApprovalMode,
  ShadowServerAppCatalogEntry,
  ShadowServerAppCommand,
  ShadowServerAppCommandApproval,
  ShadowServerAppCommandConsent,
  ShadowServerAppDiscovery,
  ShadowServerAppIntegration,
  ShadowServerAppLaunchContext,
  ShadowServerAppManifest,
  ShadowServerAppMobileConfig,
  ShadowServerAppMobileNavigationCapsule,
  ShadowServerAppMobileNavigationConfig,
  ShadowServerAppMobileNavigationMode,
  ShadowServerAppRealtimeSpec,
  ShadowServerAppSkillDocument,
  ShadowServerAppSummary,
  ShadowServerAppTokenIntrospection,
  ShadowServerJoinRequestResult,
  ShadowServerJoinRequestStatus,
  ShadowSettlementLine,
  ShadowShop,
  ShadowSlashCommand,
  ShadowTask,
  ShadowThread,
  ShadowTransaction,
  ShadowUsageProviderSnapshot,
  ShadowUser,
  ShadowVoiceCredentials,
  ShadowVoiceJoinResult,
  ShadowVoiceLeaveResult,
  ShadowVoiceParticipant,
  ShadowVoicePolicy,
  ShadowVoiceState,
  ShadowWallet,
  TypingPayload,
  VoiceParticipantPayload,
  VoicePolicyUpdatedPayload,
} from './types'
export type { ShadowVoiceConsumerOptions } from './voice'
export { ShadowVoiceConsumer } from './voice'
