// Client

export type {
  MessageAgentChainMetadata,
  ShadowWidgetCatalogEntry,
  ShadowWidgetCategory,
  ShadowWidgetDataRequest,
  ShadowWidgetDataResponse,
  ShadowWidgetDefinition,
  ShadowWidgetOption,
  ShadowWidgetSelectOption,
  ShadowWidgetSize,
  ShadowWidgetSurface,
  ShadowWidgetTone,
  ShadowWidgetValue,
  ShadowWidgetViewNode,
} from '@shadowob/shared'
// Constants & room helpers
export {
  buildMessageAgentChainMetadata,
  buildMessageCopilotContextMetadata,
  isMessageAgentChainMetadata,
  isMessageCopilotContext,
  MESSAGE_AGENT_CHAIN_METADATA_KEY,
  MESSAGE_COPILOT_CONTEXT_METADATA_KEY,
} from '@shadowob/shared'
export {
  createShadowSpaceAppBrowserClient,
  createShadowSpaceAppClient,
  defineShadowSpaceAppAuthorizeElement,
  SHADOW_BRIDGE_CAPABILITIES,
  ShadowBridge,
  type ShadowBridgeAuthorizeOAuthInput,
  type ShadowBridgeAuthorizeOAuthResult,
  type ShadowBridgeCapability,
  type ShadowBridgeLaunchContext,
  type ShadowBridgeLaunchUpdateHandler,
  type ShadowBridgeLaunchUpdateInput,
  type ShadowBridgeOpenBuddyCreatorInput,
  type ShadowBridgeOpenCopilotInput,
  type ShadowBridgeOptions,
  type ShadowBridgeRefreshLaunchInput,
  type ShadowBridgeRouteNavigateEvent,
  type ShadowBridgeRouteNavigateHandler,
  type ShadowBridgeShareSpaceAppInput,
  type ShadowBridgeShareSpaceAppResult,
  type ShadowSpaceAppAuthorizeElementData,
  type ShadowSpaceAppAuthorizeOAuthOptions,
  ShadowSpaceAppBrowserClient,
  type ShadowSpaceAppBrowserClientOptions,
  type ShadowSpaceAppEnsureBuddyTaskGrantInput,
  type ShadowSpaceAppFetchWithSessionOptions,
  type ShadowSpaceAppListBuddyInboxesOptions,
  shadowSpaceAppMountedPath,
  shadowSpaceAppMountedPathPrefix,
} from './bridge'
export { ShadowClient } from './client'
export type { ClientEvent, ServerEvent } from './constants'
export { CLIENT_EVENTS, channelRoom, SERVER_EVENTS, threadRoom, userRoom } from './constants'
export type { ShadowSocketOptions } from './socket'
// Socket
export { ShadowSocket } from './socket'
export type {
  BuddyInboxPlatformPermission,
  JsonSchemaToType,
  ShadowSpaceAppActorRef,
  ShadowSpaceAppBridgeAuthorizeOAuthRequest,
  ShadowSpaceAppBridgeCapabilitiesRequest,
  ShadowSpaceAppBridgeFailureResponse,
  ShadowSpaceAppBridgeOpenCopilotRequest,
  ShadowSpaceAppBridgeRequest,
  ShadowSpaceAppBridgeResponse,
  ShadowSpaceAppBridgeResponseType,
  ShadowSpaceAppBridgeRouteChangedEvent,
  ShadowSpaceAppBridgeRouteNavigateAck,
  ShadowSpaceAppBridgeRouteNavigateRequest,
  ShadowSpaceAppBridgeShareRequest,
  ShadowSpaceAppBridgeSuccessResponse,
  ShadowSpaceAppChannelMessageDelivery,
  ShadowSpaceAppChannelMessageDeliveryError,
  ShadowSpaceAppChannelMessageOutbox,
  ShadowSpaceAppCollaborationEvent,
  ShadowSpaceAppCollaborationMutation,
  ShadowSpaceAppCollaborationResource,
  ShadowSpaceAppCommandContext,
  ShadowSpaceAppCommandEnvelope,
  ShadowSpaceAppCommandEventType,
  ShadowSpaceAppCommandFailureResponse,
  ShadowSpaceAppCommandHandler,
  ShadowSpaceAppCommandHandlerContext,
  ShadowSpaceAppCommandHandlers,
  ShadowSpaceAppCommandInput,
  ShadowSpaceAppCommandName,
  ShadowSpaceAppCommandParseError,
  ShadowSpaceAppCommandParseResult,
  ShadowSpaceAppCommandParseSuccess,
  ShadowSpaceAppCommandRequestInput,
  ShadowSpaceAppCommandResponse,
  ShadowSpaceAppCommandSuccessResponse,
  ShadowSpaceAppEnvironment,
  ShadowSpaceAppExecutionFailure,
  ShadowSpaceAppExecutionResult,
  ShadowSpaceAppExecutionSuccess,
  ShadowSpaceAppFetch,
  ShadowSpaceAppHostInboxTaskRequestInput,
  ShadowSpaceAppHostRef,
  ShadowSpaceAppIdentitySnapshot,
  ShadowSpaceAppIdentitySubjectKind,
  ShadowSpaceAppInboxDelivery,
  ShadowSpaceAppInboxDeliveryError,
  ShadowSpaceAppInboxDeliveryFromMessageInput,
  ShadowSpaceAppInboxTarget,
  ShadowSpaceAppInboxTaskOutbox,
  ShadowSpaceAppInboxTaskPriority,
  ShadowSpaceAppInboxTaskResource,
  ShadowSpaceAppIntrospectionInput,
  ShadowSpaceAppLaunchChannel,
  ShadowSpaceAppLaunchCommandContextOptions,
  ShadowSpaceAppLaunchCommandContextResolution,
  ShadowSpaceAppLaunchCreatePollInput,
  ShadowSpaceAppLaunchCreatePollResult,
  ShadowSpaceAppLaunchEnsureBuddyTaskGrantInput,
  ShadowSpaceAppLaunchEnsureBuddyTaskGrantResult,
  ShadowSpaceAppLaunchEnsureChannelInput,
  ShadowSpaceAppLaunchEnsureChannelResult,
  ShadowSpaceAppLaunchFetchOptions,
  ShadowSpaceAppLaunchIntrospection,
  ShadowSpaceAppLaunchMember,
  ShadowSpaceAppLaunchOutboxDeliveryOptions,
  ShadowSpaceAppLaunchTokenHint,
  ShadowSpaceAppManifestOptions,
  ShadowSpaceAppNotificationPublishInput,
  ShadowSpaceAppNotificationPublishOptions,
  ShadowSpaceAppOutboxPayload,
  ShadowSpaceAppResolvedInboxTaskRequest,
  ShadowSpaceAppResultShadow,
  ShadowSpaceAppResultWithShadow,
  ShadowSpaceAppRuntimeOptions,
  ShadowSpaceAppValidationIssue,
} from './space-app'
// App helpers
export {
  BUDDY_INBOX_DELIVERY_PERMISSION,
  buildShadowSpaceAppInboxDelivery,
  buildShadowSpaceAppInboxTaskRequest,
  createShadowSpaceAppCollaborationCursor,
  createShadowSpaceAppCollaborationEvent,
  createShadowSpaceAppCollaborationResource,
  createShadowSpaceAppLaunchPoll,
  createShadowSpaceAppManifest,
  createShadowSpaceAppRuntime,
  decodeShadowSpaceAppLaunchTokenHint,
  defineShadowSpaceApp,
  deliverShadowSpaceAppLaunchOutbox,
  ensureShadowSpaceAppLaunchBuddyTaskGrant,
  ensureShadowSpaceAppLaunchChannel,
  extractShadowSpaceAppBearerToken,
  fetchShadowSpaceAppLaunchChannels,
  fetchShadowSpaceAppLaunchInboxes,
  fetchShadowSpaceAppLaunchMembers,
  fetchShadowSpaceAppLaunchMessage,
  getShadowSpaceAppChannelMessageDeliveries,
  getShadowSpaceAppChannelMessageErrors,
  getShadowSpaceAppInboxDeliveries,
  getShadowSpaceAppInboxErrors,
  getShadowSpaceAppTaskCardId,
  hasShadowSpaceAppPendingOutbox,
  introspectShadowSpaceAppLaunchToken,
  introspectShadowSpaceAppToken,
  isShadowSpaceAppSignedMediaUrl,
  normalizeShadowSpaceAppAvatarUrl,
  normalizeShadowSpaceAppBaseCursor,
  normalizeShadowSpaceAppClientMutationId,
  normalizeShadowSpaceAppCommandInput,
  parseShadowSpaceAppCommandRequest,
  publishShadowSpaceAppNotification,
  readShadowSpaceAppCommandResponse,
  resolveShadowSpaceAppLaunchCommandContext,
  resolveShadowSpaceAppLaunchCommandContextResolution,
  SHADOW_SPACE_APP_COMMAND_COMPLETED_EVENT,
  SHADOW_SPACE_APP_COMMAND_EVENTS,
  SHADOW_SPACE_APP_COMMAND_FAILED_EVENT,
  SHADOW_SPACE_APP_PROTOCOL,
  SHADOW_SPACE_APP_PUBLIC_AVATAR_CACHE_CONTROL,
  ShadowSpaceAppCommandError,
  ShadowSpaceAppHttpError,
  ShadowSpaceAppOutbox,
  ShadowSpaceAppRuntime,
  shadowSpaceAppActorAvatarUrl,
  shadowSpaceAppActorDisplayName,
  shadowSpaceAppActorRef,
  shadowSpaceAppApiBaseUrl,
  shadowSpaceAppAvatarRedirectUrl,
  shadowSpaceAppDisplayIdentity,
  shadowSpaceAppError,
  shadowSpaceAppIdentityKey,
  shadowSpaceAppIdentitySnapshot,
  shadowSpaceAppInboxTaskEndpoint,
  shadowSpaceAppLaunchIntrospectionError,
  shadowSpaceAppPublicBaseUrl,
  shadowSpaceAppPublicUrl,
  validateShadowSpaceAppJsonSchema,
} from './space-app'
// Types
export type {
  ChannelCreatedPayload,
  ChannelMemberAddedPayload,
  ChannelMemberRemovedPayload,
  ClientEventMap,
  MemberJoinPayload,
  MemberLeavePayload,
  MessageDeletedPayload,
  PolicyChangedPayload,
  PresenceActivityPayload,
  PresenceChangePayload,
  ReactionPayload,
  ServerEventMap,
  ServerJoinedPayload,
  ShadowAddAgentsToServerResult,
  ShadowAgentComputerPlacement,
  ShadowAgentUsageSnapshotInput,
  ShadowAttachment,
  ShadowBuddyInboxAdmissionMode,
  ShadowBuddyInboxAdmissionPendingActionResult,
  ShadowBuddyInboxAdmissionPendingDelivery,
  ShadowBuddyInboxAdmissionPendingResult,
  ShadowBuddyInboxAdmissionPolicy,
  ShadowBuddyInboxAdmissionPolicyResult,
  ShadowBuddyInboxAdmissionRule,
  ShadowBuddyInboxAdmissionSubjectKind,
  ShadowBuddyInboxSummary,
  ShadowCartItem,
  ShadowCategory,
  ShadowChannel,
  ShadowChannelAccess,
  ShadowChannelBootstrap,
  ShadowChannelJoinRequestResult,
  ShadowChannelJoinRequestStatus,
  ShadowChannelLastMessagePreview,
  ShadowChannelPolicy,
  ShadowChannelSlashCommand,
  ShadowCloudComputer,
  ShadowCloudComputerApp,
  ShadowCloudComputerAppsResponse,
  ShadowCloudComputerBackupsResponse,
  ShadowCloudComputerBrowserCapture,
  ShadowCloudComputerBrowserPage,
  ShadowCloudComputerBrowserSession,
  ShadowCloudComputerBuddiesResponse,
  ShadowCloudComputerBuddy,
  ShadowCloudComputerBuddyActionResponse,
  ShadowCloudComputerBuddyCreateResponse,
  ShadowCloudComputerBuddyRemoveResponse,
  ShadowCloudComputerConfigurationQuote,
  ShadowCloudComputerConnector,
  ShadowCloudComputerConnectorMutationResponse,
  ShadowCloudComputerConnectorOAuthFlowResponse,
  ShadowCloudComputerConnectorOAuthStartResponse,
  ShadowCloudComputerConnectorOptionField,
  ShadowCloudComputerConnectorsResponse,
  ShadowCloudComputerDesktopSession,
  ShadowCloudComputerFilesUnavailable,
  ShadowCloudComputerLifecycleResponse,
  ShadowCloudComputerRepairResponse,
  ShadowCloudComputerResourceProfile,
  ShadowCloudComputerRuntime,
  ShadowCloudComputerRuntimeRebuildResponse,
  ShadowCloudComputerRuntimeRepairResponse,
  ShadowCloudComputerShellColor,
  ShadowCloudComputerWorkspaceMount,
  ShadowCloudDeployment,
  ShadowCloudDeploymentBackup,
  ShadowCloudDeploymentDestroyResponse,
  ShadowCloudDeploymentRuntimeResponse,
  ShadowCloudDeploymentStatus,
  ShadowCloudProviderCatalog,
  ShadowCloudProviderEnvVar,
  ShadowCloudProviderModel,
  ShadowCloudProviderProfile,
  ShadowCloudTemplate,
  ShadowCommerceCheckoutPreview,
  ShadowCommerceProductCard,
  ShadowCommerceProductContext,
  ShadowCommerceProductPickerGroup,
  ShadowCommerceProductPickerResponse,
  ShadowCommunityAsset,
  ShadowCommunityAssetDefinition,
  ShadowCommunityAssetGrant,
  ShadowComputer,
  ShadowComputerBuddy,
  ShadowComputerCapabilities,
  ShadowComputerDevice,
  ShadowComputerDeviceClass,
  ShadowComputerKind,
  ShadowComputerRuntime,
  ShadowComputerStatus,
  ShadowConfigureCloudComputerConnectorInput,
  ShadowConnectorBootstrapResult,
  ShadowConnectorComputer,
  ShadowConnectorRuntimeInfo,
  ShadowContract,
  ShadowCreateCloudComputerBackupInput,
  ShadowCreateCloudComputerBuddyInput,
  ShadowCreateCloudComputerInput,
  ShadowCreateCloudComputerWorkspaceMountInput,
  ShadowCreateCloudDeploymentInput,
  ShadowCreateCloudTemplateInput,
  ShadowDesktopReleaseDownload,
  ShadowDesktopReleaseInfo,
  ShadowDiyCloudRun,
  ShadowDiyCloudRunEvent,
  ShadowDiyCloudRunStatus,
  ShadowEnsureBuddyInboxResult,
  ShadowFriendship,
  ShadowInboxTaskInput,
  ShadowInteractiveActionInput,
  ShadowInteractiveActionResult,
  ShadowInteractiveBlock,
  ShadowInteractiveResponse,
  ShadowInteractiveState,
  ShadowInteractiveSubmissionPending,
  ShadowInviteCode,
  ShadowListing,
  ShadowMarketplaceCategoriesResponse,
  ShadowMarketplaceCategory,
  ShadowMarketplaceProduct,
  ShadowMarketplaceProductsResponse,
  ShadowMediaVariant,
  ShadowMember,
  ShadowMentionSuggestion,
  ShadowMentionSuggestionTrigger,
  ShadowMessage,
  ShadowMessageCard,
  ShadowMessageCardSource,
  ShadowMessageCopilotContext,
  ShadowMessageMention,
  ShadowMessageMetadata,
  ShadowModelProxyBilling,
  ShadowModelProxyChatCompletionRequest,
  ShadowModelProxyChatCompletionResponse,
  ShadowModelProxyModel,
  ShadowModelProxyModelsResponse,
  ShadowNotification,
  ShadowNotificationPreferences,
  ShadowOAuthApp,
  ShadowOAuthCommerceEntitlementAccess,
  ShadowOAuthCommerceEntitlementRedeemInput,
  ShadowOAuthCommerceEntitlementRedeemResult,
  ShadowOAuthCommerceEntitlementRedemption,
  ShadowOAuthCommerceEntitlementSummary,
  ShadowOAuthConsent,
  ShadowOAuthToken,
  ShadowOrder,
  ShadowPaidFileCard,
  ShadowPaidFileOpenResult,
  ShadowProduct,
  ShadowProductEntitlementConfig,
  ShadowProductMedia,
  ShadowProductSku,
  ShadowRemoteChannel,
  ShadowRemoteConfig,
  ShadowRemoteServer,
  ShadowRestoreCloudComputerInput,
  ShadowReview,
  ShadowServer,
  ShadowServerAccess,
  ShadowServerDesktopChatInputWidget,
  ShadowServerDesktopChatInputWidgetMode,
  ShadowServerDesktopLayout,
  ShadowServerDesktopLayoutBuiltinAppItem,
  ShadowServerDesktopLayoutItem,
  ShadowServerDesktopLayoutSpaceAppItem,
  ShadowServerDesktopLayoutWorkspaceItem,
  ShadowServerDesktopPhotoWidget,
  ShadowServerDesktopPhotoWidgetSourceType,
  ShadowServerDesktopRemoteWidget,
  ShadowServerDesktopStickyNoteWidget,
  ShadowServerDesktopTypewriterWidget,
  ShadowServerDesktopTypewriterWidgetFontFamily,
  ShadowServerDesktopTypewriterWidgetTextShadow,
  ShadowServerDesktopVideoWidget,
  ShadowServerDesktopVideoWidgetProvider,
  ShadowServerDesktopWebEmbedWidget,
  ShadowServerDesktopWebEmbedWidgetSourceType,
  ShadowServerDesktopWidget,
  ShadowServerJoinRequestResult,
  ShadowServerJoinRequestStatus,
  ShadowServerWallpaperType,
  ShadowSettlementLine,
  ShadowShop,
  ShadowSlashCommand,
  ShadowSpaceAppActorProfile,
  ShadowSpaceAppApprovalMode,
  ShadowSpaceAppCatalogEntry,
  ShadowSpaceAppCommand,
  ShadowSpaceAppCommandApproval,
  ShadowSpaceAppCommandConsent,
  ShadowSpaceAppDiscovery,
  ShadowSpaceAppInstallation,
  ShadowSpaceAppLaunchContext,
  ShadowSpaceAppManifest,
  ShadowSpaceAppMobileConfig,
  ShadowSpaceAppMobileNavigationCapsule,
  ShadowSpaceAppMobileNavigationConfig,
  ShadowSpaceAppMobileNavigationMode,
  ShadowSpaceAppNotificationChannel,
  ShadowSpaceAppNotificationPreference,
  ShadowSpaceAppNotificationTopic,
  ShadowSpaceAppRealtimeSpec,
  ShadowSpaceAppSkillDocument,
  ShadowSpaceAppSummary,
  ShadowSpaceAppTokenIntrospection,
  ShadowTask,
  ShadowThread,
  ShadowTransaction,
  ShadowUpdateCloudComputerInput,
  ShadowUsageProviderSnapshot,
  ShadowUser,
  ShadowVoiceCredentials,
  ShadowVoiceJoinResult,
  ShadowVoiceLeaveResult,
  ShadowVoiceParticipant,
  ShadowVoicePolicy,
  ShadowVoiceState,
  ShadowWallet,
  TypingPayload,
  VoiceParticipantPayload,
  VoicePolicyUpdatedPayload,
} from './types'
export type { ShadowVoiceConsumerOptions } from './voice'
export { ShadowVoiceConsumer } from './voice'
