// ══════════════════════════════════════════════════════════════
// Component — Style (AoS, bitECS tag + object store)
// ══════════════════════════════════════════════════════════════

import type { CardKind } from '../../types'

export interface StyleData {
  readonly accentColor: string
  readonly kindLabel: string
  readonly pip: string
  readonly rank: string
}

/** bitECS tag object */
export const CStyle = {}

/** AoS data store indexed by EID */
export const styleStore: Array<StyleData | undefined> = []

export const KIND_COLORS: Record<CardKind, string> = {
  quote: '#f472b6',
  summary: '#60a5fa',
  argument: '#fb923c',
  data: '#22d3ee',
  table: '#2dd4bf',
  image: '#a855f7',
  code: '#a3e635',
  chart: '#fbbf24',
  idea: '#facc15',
  text: '#a1a1aa',
  audio: '#34d399',
  video: '#fb7185',
  keypoint: '#818cf8',
  definition: '#8b5cf6',
  example: '#38bdf8',
  reference: '#9ca3af',
  inspiration: '#d946ef',
  timeline: '#f97316',
  comparison: '#06b6d4',
  process: '#10b981',
  gif: '#f59e0b',
  qrcode: '#1d4ed8',
  person: '#ec4899',
  terminal: '#22c55e',
  lottie: '#8b5cf6',
  webpage: '#0ea5e9',
  countdown: '#ef4444',
  threed: '#06b6d4',
  link: '#0ea5e9',
  file: '#94a3b8',
  math: '#a78bfa',
  todo: '#4ade80',
  position: '#f87171',
  timestamp: '#fbbf24',
  color: '#f472b6',
  event: '#60a5fa',
  voice: '#2dd4bf',
  comment: '#fb923c',
  story: '#818cf8',
  social: '#d946ef',
}

export const KIND_LABELS: Record<CardKind, string> = {
  quote: 'Quote',
  summary: 'Summary',
  argument: 'Argument',
  data: 'Data',
  table: 'Table',
  image: 'Image',
  code: 'Code',
  chart: 'Chart',
  idea: 'Idea',
  text: 'Text',
  audio: 'Audio',
  video: 'Video',
  keypoint: 'Key Point',
  definition: 'Definition',
  example: 'Example',
  reference: 'Reference',
  inspiration: 'Inspiration',
  timeline: 'Timeline',
  comparison: 'Comparison',
  process: 'Process',
  gif: 'GIF',
  qrcode: 'QR Code',
  person: 'Person',
  terminal: 'Terminal',
  lottie: 'Lottie',
  webpage: 'Webpage',
  countdown: 'Countdown',
  threed: '3D',
  link: 'Link',
  file: 'File',
  math: 'Formula',
  todo: 'Todo',
  position: 'Position',
  timestamp: 'Timestamp',
  color: 'Color',
  event: 'Event',
  voice: 'Voice',
  comment: 'Comment',
  story: 'Story',
  social: 'Social',
}

export const KIND_PIPS: Record<CardKind, string> = {
  quote: '♦',
  summary: '♣',
  argument: '♠',
  data: '◆',
  table: '▦',
  image: '✧',
  code: '<>',
  chart: '▲',
  idea: '★',
  text: '¶',
  audio: '♪',
  video: '▶',
  keypoint: '✦',
  definition: '♔',
  example: '✎',
  reference: '⊕',
  inspiration: '✺',
  timeline: '⏳',
  comparison: '⚖',
  process: '⟳',
  gif: '□■',
  qrcode: '⯀',
  person: '●',
  terminal: '$',
  lottie: '⬡',
  webpage: '⌘',
  countdown: '⧗',
  threed: '◈',
  link: '↪',
  file: '📄',
  math: 'Σ',
  todo: '☑',
  position: '📍',
  timestamp: '🕐',
  color: '🎨',
  event: '📅',
  voice: '🎙',
  comment: '💬',
  story: '📖',
  social: '🔗',
}

export const KIND_RANKS: Record<CardKind, string> = {
  quote: 'Q',
  summary: 'K',
  argument: 'A',
  data: '10',
  table: '9',
  image: 'J',
  code: '7',
  chart: '8',
  idea: 'A',
  text: '6',
  audio: '5',
  video: 'J',
  keypoint: 'K',
  definition: 'Q',
  example: '4',
  reference: '3',
  inspiration: '★',
  timeline: 'T',
  comparison: 'V',
  process: 'P',
  gif: 'G',
  qrcode: 'QR',
  person: '♚',
  terminal: '>',
  lottie: 'L',
  webpage: 'W',
  countdown: '⌛',
  threed: '3',
  link: '↪',
  file: 'F',
  math: 'Σ',
  todo: '☑',
  position: 'P',
  timestamp: 'T',
  color: 'C',
  event: 'E',
  voice: 'V',
  comment: 'N',
  story: 'S',
  social: '✦',
}

/** Factory: resolve StyleData from a CardKind */
export function resolveStyle(kind: CardKind): StyleData {
  return {
    accentColor: KIND_COLORS[kind] || '#a1a1aa',
    kindLabel: KIND_LABELS[kind] || 'Card',
    pip: KIND_PIPS[kind] || '•',
    rank: KIND_RANKS[kind] || '?',
  }
}
