import { Hono } from 'hono'
import { bodyLimit } from 'hono/body-limit'
import { cors } from 'hono/cors'
import type { AppContainer } from './container'
import { createAdminHandler } from './handlers/admin.handler'
import { createAgentDashboardHandler } from './handlers/agent-dashboard.handler'
import { createAgentHandler } from './handlers/agent.handler'
import { createAppHandler } from './handlers/app.handler'
import { createAuthHandler } from './handlers/auth.handler'
import { createChannelHandler } from './handlers/channel.handler'
import { createDmHandler } from './handlers/dm.handler'
import { createFriendshipHandler } from './handlers/friendship.handler'
import { createInviteHandler } from './handlers/invite.handler'
import { createMediaHandler } from './handlers/media.handler'
import { createMessageHandler } from './handlers/message.handler'
import { createNotificationHandler } from './handlers/notification.handler'
import { createOAuthHandler } from './handlers/oauth.handler'
import { createPortfolioHandler } from './handlers/portfolio.handler'
import { createProfileCommentHandler } from './handlers/profile-comment.handler'
import { createRentalHandler } from './handlers/rental.handler'
import { createSearchHandler } from './handlers/search.handler'
import { createServerHandler } from './handlers/server.handler'
import { createShopHandler } from './handlers/shop.handler'
import { createTaskCenterHandler } from './handlers/task-center.handler'
import voiceEnhanceHandler from './handlers/voice-enhance.handler'
import { createWorkspaceHandler } from './handlers/workspace.handler'
import { logger } from './lib/logger'
import { loggerMiddleware } from './middleware/logger.middleware'