// ═══════════════════════════════════════════════════════════════
// @shadowob/flash-types — Server-side Record Types (DAO layer)
// ═══════════════════════════════════════════════════════════════

export interface MaterialRecord {
  id: string
  name: string
  type: string
  mimeType: string
  size: number
  path: string
  content?: string
  status: string
  cardIds: string[]
  uploadedAt: number
  projectId?: string
}

export interface CardRecord {
  id: string
  kind: string
  title: string
  summary?: string
  content?: string
  sourceId: string | null
  linkedCardIds: string[]
  meta: Record<string, unknown>
  tags: string[]
  priority: string
  autoGenerated: boolean
  rating: number
  deckIds: string[]
  filePath?: string
  fileMime?: string
  createdAt: number
  updatedAt: number
  projectId?: string
}

export interface DeckRecord {
  id: string
  title: string
  description: string
  outline: OutlineItemRecord[]
  theme: ThemeRefRecord | null
  autoCreatedReason?: string
  createdAt: number
  updatedAt: number
  projectId?: string
}

export interface OutlineItemRecord {
  id: string
  slideIndex: number
  title: string
  type: string
  keyPoints: string[]
  materialRefs: string[]
  cardRefs: string[]
  notes: string
}

export interface ThemeRefRecord {
  name?: string
  appearance?: string
  colorScheme?: Record<string, string>
  fontScheme?: Record<string, string>
}

export interface SkillRecord {
  id: string
  name: string
  emoji: string
  category: string
  description: string
  builtin: boolean
  status: string
  version: string
  skillPath?: string
  source?: string
}

export interface ThemeFolder {
  id: string
  name: string
  path?: string
  componentCount?: number
  promptCount?: number
  _resolvedPath?: string
  _themeDescription?: string
  _keywords?: string
  _score?: number
  components?: ThemeComponent[]
  promptContent?: string
}

export interface ThemeComponent {
  id: string
  name: string
  notes: string
  jsxCode: string
}
