import { nowIso } from '../lib/time.js'
import type { TravelState } from '../types.js'

export const travelSchemaVersion = 8

export const travelCollections = [
  'trips',
  'members',
  'guests',
  'invites',
  'recruitments',
  'joinApplications',
  'travelIntents',
  'days',
  'places',
  'assignments',
  'reservations',
  'expenses',
  'settlementRecords',
  'packingBags',
  'packingItems',
  'packingTemplates',
  'categoryAssignees',
  'todos',
  'tags',
  'categories',
  'tripSettings',
  'providerSettings',
  'providerCache',
  'routeSegments',
  'tripPhotoRefs',
  'syncMutations',
  'attachments',
  'shareLinks',
  'discussionRefs',
  'decisionRefs',
  'importJobs',
  'automationTasks',
  'appAccounts',
  'identityLinks',
  'appSessions',
  'tripBuddyBindings',
  'buddyPlanDrafts',
  'communityShareRefs',
  'backups',
  'notifications',
  'clientStates',
  'emergencyReports',
  'auditLogs',
] as const

export function emptyTravelState(): TravelState {
  return {
    schemaVersion: travelSchemaVersion,
    updatedAt: nowIso(),
    trips: [],
    members: [],
    guests: [],
    invites: [],
    recruitments: [],
    joinApplications: [],
    travelIntents: [],
    days: [],
    places: [],
    assignments: [],
    reservations: [],
    expenses: [],
    settlementRecords: [],
    packingBags: [],
    packingItems: [],
    packingTemplates: [],
    categoryAssignees: [],
    todos: [],
    tags: [],
    categories: [],
    tripSettings: [],
    providerSettings: [],
    providerCache: [],
    routeSegments: [],
    tripPhotoRefs: [],
    syncMutations: [],
    attachments: [],
    shareLinks: [],
    discussionRefs: [],
    decisionRefs: [],
    importJobs: [],
    automationTasks: [],
    appAccounts: [],
    identityLinks: [],
    appSessions: [],
    tripBuddyBindings: [],
    buddyPlanDrafts: [],
    communityShareRefs: [],
    backups: [],
    notifications: [],
    clientStates: [],
    emergencyReports: [],
    auditLogs: [],
  }
}

export function normalizeTravelState(input: Partial<TravelState> | null | undefined): TravelState {
  const empty = emptyTravelState()
  return {
    ...empty,
    ...input,
    schemaVersion: travelSchemaVersion,
    updatedAt: input?.updatedAt ?? empty.updatedAt,
    trips: input?.trips ?? [],
    members: input?.members ?? [],
    guests: input?.guests ?? [],
    invites: input?.invites ?? [],
    recruitments: input?.recruitments ?? [],
    joinApplications: input?.joinApplications ?? [],
    travelIntents: input?.travelIntents ?? [],
    days: input?.days ?? [],
    places: (input?.places ?? []).map((place) => ({
      ...place,
      photoRefs: place.photoRefs ?? [],
    })),
    assignments: (input?.assignments ?? []).map((assignment) => ({
      ...assignment,
      participantMemberIds: assignment.participantMemberIds ?? [],
    })),
    reservations: (input?.reservations ?? []).map((reservation) => ({
      ...reservation,
      status: reservation.status ?? 'confirmed',
      sequence: reservation.sequence ?? 0,
      participantMemberIds: reservation.participantMemberIds ?? [],
      passengerNames: reservation.passengerNames ?? [],
      attachmentIds: reservation.attachmentIds ?? [],
    })),
    expenses: (input?.expenses ?? []).map((expense) => ({
      ...expense,
      paidMemberIds: expense.paidMemberIds ?? [],
      sequence: expense.sequence ?? 0,
    })),
    settlementRecords: (input?.settlementRecords ?? []).map((record) => ({
      ...record,
      paidTransferIds: record.paidTransferIds ?? [],
    })),
    packingBags: (input?.packingBags ?? []).map((bag) => ({
      ...bag,
      memberIds: bag.memberIds ?? [],
    })),
    packingItems: (input?.packingItems ?? []).map((item) => ({
      ...item,
      contributorMemberIds: item.contributorMemberIds ?? [],
      sequence: item.sequence ?? 0,
    })),
    packingTemplates: (input?.packingTemplates ?? []).map((template) => ({
      ...template,
      destinationTags: template.destinationTags ?? [],
      items: template.items ?? [],
    })),
    categoryAssignees: input?.categoryAssignees ?? [],
    todos: input?.todos ?? [],
    tags: input?.tags ?? [],
    categories: input?.categories ?? [],
    tripSettings: input?.tripSettings ?? [],
    providerSettings: input?.providerSettings ?? [],
    providerCache: input?.providerCache ?? [],
    routeSegments: input?.routeSegments ?? [],
    tripPhotoRefs: input?.tripPhotoRefs ?? [],
    syncMutations: input?.syncMutations ?? [],
    attachments: input?.attachments ?? [],
    shareLinks: input?.shareLinks ?? [],
    discussionRefs: input?.discussionRefs ?? [],
    decisionRefs: input?.decisionRefs ?? [],
    importJobs: input?.importJobs ?? [],
    automationTasks: input?.automationTasks ?? [],
    appAccounts: input?.appAccounts ?? [],
    identityLinks: input?.identityLinks ?? [],
    appSessions: input?.appSessions ?? [],
    tripBuddyBindings: input?.tripBuddyBindings ?? [],
    buddyPlanDrafts: input?.buddyPlanDrafts ?? [],
    communityShareRefs: input?.communityShareRefs ?? [],
    backups: input?.backups ?? [],
    notifications: input?.notifications ?? [],
    clientStates: input?.clientStates ?? [],
    emergencyReports: input?.emergencyReports ?? [],
    auditLogs: input?.auditLogs ?? [],
  }
}
