// ══════════════════════════════════════════════════════════════
// ECS Resource — Texture Cache
//
// Owns the card-texture Map (canvas instances keyed by card.id)
// and the cheap hash used for cache invalidation.
//
// Responsibilities:
//   - CardTextureInfo type
//   - cardHash()  — derive a stable number from visible card fields
//   - CRUD helpers over the singleton cache Map
// ══════════════════════════════════════════════════════════════

import type { Card } from '@shadowob/flash-types'

// ─────────────────────────────────────
// Types
// ─────────────────────────────────────

export interface CardTextureInfo {
  canvas: HTMLCanvasElement | OffscreenCanvas
  needsUpdate: boolean
  cardVersion: number
  /** LOD scale used when baking this texture (1 | 2 | 4 | 6). */
  lodScale: number
  /** Approximate RGBA byte size of the baked face. */
  byteSize: number
  /** Last asset-pipeline frame that used this CPU-side face texture. */
  lastTouchedFrame: number
  /** Wall-clock timestamp used as a tie-breaker for LRU eviction. */
  lastUsedAt: number
  /** Face renderer backend that produced this texture. */
  backend: 'canvas2d' | 'offscreen-canvas' | 'canvaskit' | 'external'
}

export interface TextureCacheStats {
  entries: number
  totalBytes: number
}

// ─────────────────────────────────────
// Resource: singleton cache
// ─────────────────────────────────────

const _cache = new Map<string, CardTextureInfo>()

// ─────────────────────────────────────
// Hash (invalidation key)
// ─────────────────────────────────────

/** Fast, deterministic hash derived from all visible card fields. */
export function cardHash(card: Card): number {
  let h = 0
  const meta = (card.meta || {}) as Record<string, unknown>
  let metaSnap = ''
  try {
    metaSnap = JSON.stringify(meta).slice(0, 300)
  } catch {
    metaSnap = ''
  }
  const s = `${card.title}|${card.content?.slice(0, 80)}|${card.kind}|${card.rating}|${card.isStreaming ? 1 : 0}|${card.linkedCardIds.length}|${card.autoGenerated ? 1 : 0}|${card.summary || ''}|${metaSnap}`
  for (let i = 0; i < s.length; i++) {
    h = ((h << 5) - h + s.charCodeAt(i)) | 0
  }
  return h
}

// ─────────────────────────────────────
// Cache CRUD
// ─────────────────────────────────────

export function getCachedTexture(id: string): CardTextureInfo | undefined {
  return _cache.get(id)
}

export function setCachedTexture(id: string, info: CardTextureInfo): void {
  _cache.set(id, info)
}

export function removeCachedTexture(id: string): void {
  _cache.delete(id)
}

export function clearAllTextures(): void {
  _cache.clear()
}

export function getTextureCacheStats(): TextureCacheStats {
  let totalBytes = 0
  for (const info of _cache.values()) totalBytes += info.byteSize
  return { entries: _cache.size, totalBytes }
}

export function trimTextureCache(activeIds: Set<string>, maxBytes: number): string[] {
  let totalBytes = 0
  for (const info of _cache.values()) totalBytes += info.byteSize
  if (totalBytes <= maxBytes) return []

  const candidates = [..._cache.entries()]
    .filter(([id]) => !activeIds.has(id))
    .sort(([, a], [, b]) => a.lastTouchedFrame - b.lastTouchedFrame || a.lastUsedAt - b.lastUsedAt)

  const evicted: string[] = []
  for (const [id, info] of candidates) {
    if (totalBytes <= maxBytes) break
    _cache.delete(id)
    totalBytes -= info.byteSize
    evicted.push(id)
  }
  return evicted
}
