// Generated by shadow-server-app typegen from ../shadow-app.local.json.
// Do not edit by hand. Update the JSON manifest and regenerate this file.
import type { ShadowServerAppManifest } from '@shadowob/sdk'

export const shadowServerAppManifest = {
  schemaVersion: 'shadow.app/1',
  appKey: 'shadow-cat',
  name: 'StarPet Inn',
  description:
    'A playable virtual pet Server App with StarPet care, training, minigames, adventure maps, furniture upgrades, evolution, and leaderboard.',
  version: '1.1.0',
  iconUrl: 'http://localhost:4215/assets/icon.svg',
  iframe: {
    entry: 'http://localhost:4215/shadow/server',
    allowedOrigins: ['http://localhost:4215'],
  },
  api: {
    baseUrl: 'http://localhost:4215',
    auth: {
      type: 'oauth2-bearer',
    },
  },
  access: {
    defaultPermissions: ['cat.cats:read'],
    defaultApprovalMode: 'none',
  },
  commands: [
    {
      name: 'cats.assets.list',
      title: 'List pet assets',
      description: 'List generated transparent pet assets.',
      path: '/api/shadow/commands/cats.assets.list',
      permission: 'cat.assets:read',
      action: 'read',
      dataClass: 'server-private',
    },
    {
      name: 'cats.adopt',
      title: 'Adopt StarPet',
      description: 'Create a persistent StarPet for the actor.',
      path: '/api/shadow/commands/cats.adopt',
      permission: 'cat.cats:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        properties: {
          name: {
            type: 'string',
            maxLength: 40,
          },
          assetId: {
            type: 'string',
            maxLength: 40,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.list',
      title: 'List StarPets',
      description: 'List current StarPets after applying time-based attribute decay.',
      path: '/api/shadow/commands/cats.list',
      permission: 'cat.cats:read',
      action: 'read',
      dataClass: 'server-private',
    },
    {
      name: 'cats.get',
      title: 'Read StarPet',
      description: 'Read one StarPet with asset and recent game logs.',
      path: '/api/shadow/commands/cats.get',
      permission: 'cat.cats:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['catId'],
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.feed',
      title: 'Feed StarPet',
      description: 'Spend coins to feed a StarPet and reduce hunger.',
      path: '/api/shadow/commands/cats.feed',
      permission: 'cat.care:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['catId'],
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.pet',
      title: 'Pet StarPet',
      description: 'Pet a StarPet to raise mood and bond.',
      path: '/api/shadow/commands/cats.pet',
      permission: 'cat.care:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['catId'],
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.play',
      title: 'Play with StarPet',
      description: 'Play with a StarPet and gain bond and experience.',
      path: '/api/shadow/commands/cats.play',
      permission: 'cat.care:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['catId'],
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.clean',
      title: 'Clean StarPet',
      description: 'Spend coins to clean a StarPet and improve health.',
      path: '/api/shadow/commands/cats.clean',
      permission: 'cat.care:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['catId'],
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.rest',
      title: 'Rest StarPet',
      description: 'Let a StarPet rest and recover energy.',
      path: '/api/shadow/commands/cats.rest',
      permission: 'cat.care:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['catId'],
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.train',
      title: 'Train StarPet',
      description: 'Spend coins and energy to train a route and gain stats, bond, and experience.',
      path: '/api/shadow/commands/cats.train',
      permission: 'cat.care:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['catId', 'route'],
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
          route: {
            type: 'string',
            enum: ['str', 'agi', 'int', 'cha', 'luk', 'balanced'],
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.minigame',
      title: 'Play StarPet minigame',
      description: 'Spend energy to play a short minigame and gain ranked rewards.',
      path: '/api/shadow/commands/cats.minigame',
      permission: 'cat.care:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['catId'],
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.adventure',
      title: 'Send StarPet adventure',
      description:
        'Spend energy to run an adventure map with stat-based success and rare route core drops.',
      path: '/api/shadow/commands/cats.adventure',
      permission: 'cat.care:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['catId', 'mapId'],
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
          mapId: {
            type: 'integer',
            minimum: 1,
            maximum: 5,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.furniture.upgrade',
      title: 'Upgrade StarPet furniture',
      description: 'Spend coins to upgrade inn furniture and improve future adventure stability.',
      path: '/api/shadow/commands/cats.furniture.upgrade',
      permission: 'cat.care:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['catId'],
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.leaderboard',
      title: 'StarPet leaderboard',
      description:
        'Rank StarPets by care, growth, route stats, economy, furniture, and evolution score.',
      path: '/api/shadow/commands/cats.leaderboard',
      permission: 'cat.cats:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          limit: {
            type: 'integer',
            minimum: 1,
            maximum: 100,
          },
        },
        additionalProperties: false,
      },
    },
  ],
  skills: [
    {
      name: 'starpet-ops',
      description:
        'Use when a Buddy needs to adopt StarPets, inspect pet state, care for pets, train routes, run minigames or adventures, upgrade furniture, or read the leaderboard.',
      commandHints: [
        'shadow-cat cats.assets.list',
        'shadow-cat cats.adopt',
        'shadow-cat cats.list',
        'shadow-cat cats.get',
        'shadow-cat cats.feed',
        'shadow-cat cats.pet',
        'shadow-cat cats.train',
        'shadow-cat cats.minigame',
        'shadow-cat cats.adventure',
        'shadow-cat cats.furniture.upgrade',
        'shadow-cat cats.leaderboard',
      ],
    },
  ],
  events: ['cat.updated'],
} as const satisfies ShadowServerAppManifest

export type ShadowServerAppManifestDefinition = typeof shadowServerAppManifest
