// Generated by shadow-server-app typegen from ../shadow-app.local.json.
// Do not edit by hand. Update the JSON manifest and regenerate this file.
import type { ShadowServerAppManifest } from '@shadowob/sdk'

export const shadowServerAppManifest = {
  schemaVersion: 'shadow.app/1',
  appKey: 'shadow-cat',
  name: 'Cloud Cat',
  description:
    'A virtual pet Server App with generated cat assets, persistent cat state, care mechanics, automation, and leaderboard.',
  version: '1.0.0',
  iconUrl: 'http://localhost:4215/assets/icon.svg',
  iframe: {
    entry: 'http://localhost:4215/shadow/server',
    allowedOrigins: ['http://localhost:4215'],
  },
  api: {
    baseUrl: 'http://localhost:4215',
    auth: {
      type: 'oauth2-bearer',
    },
  },
  access: {
    defaultPermissions: ['cat.cats:read'],
    defaultApprovalMode: 'none',
  },
  commands: [
    {
      name: 'cats.assets.list',
      title: 'List cat assets',
      description: 'List the ten generated transparent cat assets.',
      path: '/api/shadow/commands/cats.assets.list',
      permission: 'cat.assets:read',
      action: 'read',
      dataClass: 'server-private',
    },
    {
      name: 'cats.adopt',
      title: 'Adopt cat',
      description: 'Create a persistent pet cat for the actor.',
      path: '/api/shadow/commands/cats.adopt',
      permission: 'cat.cats:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        properties: {
          name: {
            type: 'string',
            maxLength: 40,
          },
          assetId: {
            type: 'string',
            maxLength: 40,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.list',
      title: 'List cats',
      description: 'List current cats after applying time-based attribute decay.',
      path: '/api/shadow/commands/cats.list',
      permission: 'cat.cats:read',
      action: 'read',
      dataClass: 'server-private',
    },
    {
      name: 'cats.get',
      title: 'Read cat',
      description: 'Read one cat with asset and recent care logs.',
      path: '/api/shadow/commands/cats.get',
      permission: 'cat.cats:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['catId'],
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.feed',
      title: 'Feed cat',
      description: 'Feed a cat and update hunger, health, and mood.',
      path: '/api/shadow/commands/cats.feed',
      permission: 'cat.care:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['catId'],
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.play',
      title: 'Play with cat',
      description: 'Play with a cat and update happiness, energy, hunger, health, and mood.',
      path: '/api/shadow/commands/cats.play',
      permission: 'cat.care:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['catId'],
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.clean',
      title: 'Clean cat',
      description: 'Clean a cat and update cleanliness, happiness, health, and mood.',
      path: '/api/shadow/commands/cats.clean',
      permission: 'cat.care:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['catId'],
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.rest',
      title: 'Rest cat',
      description: 'Let a cat rest and recover energy.',
      path: '/api/shadow/commands/cats.rest',
      permission: 'cat.care:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['catId'],
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.auto_feed',
      title: 'Auto feed cats',
      description: 'Let a Buddy automatically feed one hungry cat or all hungry cats.',
      path: '/api/shadow/commands/cats.auto_feed',
      permission: 'cat.automation:write',
      action: 'manage',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        properties: {
          catId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cats.leaderboard',
      title: 'Cat leaderboard',
      description: 'Rank cats by current care score.',
      path: '/api/shadow/commands/cats.leaderboard',
      permission: 'cat.cats:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          limit: {
            type: 'integer',
            minimum: 1,
            maximum: 100,
          },
        },
        additionalProperties: false,
      },
    },
  ],
  skills: [
    {
      name: 'shadow-cat-ops',
      description:
        'Use when a Buddy needs to adopt cats, inspect pet state, care for cats, run auto feeding, or read the cat leaderboard.',
      commandHints: [
        'shadow-cat cats.assets.list',
        'shadow-cat cats.adopt',
        'shadow-cat cats.list',
        'shadow-cat cats.get',
        'shadow-cat cats.feed',
        'shadow-cat cats.auto_feed',
        'shadow-cat cats.leaderboard',
      ],
    },
  ],
  events: ['cat.updated'],
} as const satisfies ShadowServerAppManifest

export type ShadowServerAppManifestDefinition = typeof shadowServerAppManifest
