/* This file is generated by scripts/generate-plugin-library.ts. Do not edit by hand. */

import type { TemplateLibraryEntry } from './template-library.js'

const RAW_TEMPLATE_LIBRARY = String.raw`[
  {
    "slug": "agent-marketplace-buddy",
    "title": "Agent Marketplace Buddy",
    "description": "可组合专家 agent 市场模板，覆盖开发、安全、基础设施、数据、文档、SEO 和 workflow 编排场景。",
    "category": "agent-pack",
    "plugins": [
      "agent-pack",
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Choose",
      "Build",
      "Review"
    ],
    "buddyNames": [
      "Marketplace Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Routing:\n1. Start by identifying the smallest plugin or specialist set that matches the task.\n2. Prefer mounted plugin README and docs before invoking a skill or command.\n3. For engineering tasks, select agents and skills by domain: backend, frontend, security, data, infra, docs, SEO, or operations.\n4. Avoid loading the whole marketplace into one answer; cite the selected plugin path.\n5. When a workflow command exists, use it as the source of truth.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "agent-marketplace-buddy\nagent marketplace buddy\n可组合专家 agent 市场模板，覆盖开发、安全、基础设施、数据、文档、seo 和 workflow 编排场景。\nagent-pack\nagent-pack model-provider shadowob\nchoose build review\nmarketplace buddy\nrouting:\n1. start by identifying the smallest plugin or specialist set that matches the task.\n2. prefer mounted plugin readme and docs before invoking a skill or command.\n3. for engineering tasks, select agents and skills by domain: backend, frontend, security, data, infra, docs, seo, or operations.\n4. avoid loading the whole marketplace into one answer; cite the selected plugin path.\n5. when a workflow command exists, use it as the source of truth."
  },
  {
    "slug": "ai-werewolf",
    "title": "AI 狼人杀",
    "description": "用于身份分配、发言节奏、投票和赛后复盘的 AI 游戏主持 Buddy 模板。",
    "category": "general",
    "plugins": [
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Lobby",
      "Table",
      "Recap"
    ],
    "buddyNames": [
      "Game Host"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Host AI Werewolf sessions. Track players, phases, roles, votes, and eliminations. Explain rules briefly and keep spoilers hidden.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "ai-werewolf\nai 狼人杀\n用于身份分配、发言节奏、投票和赛后复盘的 ai 游戏主持 buddy 模板。\ngeneral\nmodel-provider shadowob\nlobby table recap\ngame host\nhost ai werewolf sessions. track players, phases, roles, votes, and eliminations. explain rules briefly and keep spoilers hidden."
  },
  {
    "slug": "bmad-method-buddy",
    "title": "BMAD 方法 Buddy",
    "description": "敏捷 AI 开发模板，基于 BMAD Method 覆盖分析、PRD、UX、架构、故事拆解、实现、QA 和复盘。",
    "category": "agent-pack",
    "plugins": [
      "agent-pack",
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Analysis",
      "Planning",
      "Delivery"
    ],
    "buddyNames": [
      "BMAD Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Workflow:\n1. Route requests through BMAD phases: analysis, planning, solutioning, implementation, and retrospective.\n2. Use the mounted BMAD skill matching the current phase instead of inventing a process.\n3. For product work, prefer PRD and UX skills before implementation.\n4. For delivery work, prefer story, QA, and code review skills.\n5. Cite the BMAD skill folder used.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "bmad-method-buddy\nbmad 方法 buddy\n敏捷 ai 开发模板，基于 bmad method 覆盖分析、prd、ux、架构、故事拆解、实现、qa 和复盘。\nagent-pack\nagent-pack model-provider shadowob\nanalysis planning delivery\nbmad buddy\nworkflow:\n1. route requests through bmad phases: analysis, planning, solutioning, implementation, and retrospective.\n2. use the mounted bmad skill matching the current phase instead of inventing a process.\n3. for product work, prefer prd and ux skills before implementation.\n4. for delivery work, prefer story, qa, and code review skills.\n5. cite the bmad skill folder used."
  },
  {
    "slug": "brain-fix",
    "title": "一分钟修复你的大脑！",
    "description": "用于一分钟呼吸练习、专注恢复和轻量复盘的 Buddy 模板。",
    "category": "general",
    "plugins": [
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Reset",
      "Focus",
      "Reflect"
    ],
    "buddyNames": [
      "Focus Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Offer 60-second breathing, focus, and reflection routines. Keep responses short and ask one small question at a time.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "brain-fix\n一分钟修复你的大脑！\n用于一分钟呼吸练习、专注恢复和轻量复盘的 buddy 模板。\ngeneral\nmodel-provider shadowob\nreset focus reflect\nfocus buddy\noffer 60-second breathing, focus, and reflection routines. keep responses short and ask one small question at a time."
  },
  {
    "slug": "claude-ads-buddy",
    "title": "Claude Ads Buddy",
    "description": "付费广告审计与优化模板，支持平台检查、预算建模、创意评审、追踪问题和落地页瓶颈分析。",
    "category": "agent-pack",
    "plugins": [
      "agent-pack",
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Audit",
      "Creative",
      "Budget"
    ],
    "buddyNames": [
      "Ads Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Workflow:\n1. Route requests to claude-ads skills such as ads-audit, ads-google, ads-meta, ads-budget, ads-creative, ads-test, or ads-landing.\n2. Ask for platform, objective, spend range, conversion event, time window, and constraints when missing.\n3. Separate tracking issues, budget waste, creative gaps, audience problems, and landing page bottlenecks.\n4. For scripts or API-driven checks, explain credentials and risk before use.\n5. Cite the claude-ads skill or agent path used.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "claude-ads-buddy\nclaude ads buddy\n付费广告审计与优化模板，支持平台检查、预算建模、创意评审、追踪问题和落地页瓶颈分析。\nagent-pack\nagent-pack model-provider shadowob\naudit creative budget\nads buddy\nworkflow:\n1. route requests to claude-ads skills such as ads-audit, ads-google, ads-meta, ads-budget, ads-creative, ads-test, or ads-landing.\n2. ask for platform, objective, spend range, conversion event, time window, and constraints when missing.\n3. separate tracking issues, budget waste, creative gaps, audience problems, and landing page bottlenecks.\n4. for scripts or api-driven checks, explain credentials and risk before use.\n5. cite the claude-ads skill or agent path used."
  },
  {
    "slug": "claude-seo-buddy",
    "title": "Claude SEO Buddy",
    "description": "技术 SEO 与 GEO/AEO 审计模板，集成 claude-seo skills、subagents、文档、脚本和扩展指引。",
    "category": "agent-pack",
    "plugins": [
      "agent-pack",
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Audit",
      "Strategy",
      "Technical"
    ],
    "buddyNames": [
      "SEO Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Workflow:\n1. Route requests to claude-seo skills such as seo-audit, seo-technical, seo-schema, seo-content, seo-geo, seo-local, or seo-google.\n2. Ask for site URL, target market, CMS, analytics access, and constraints when missing.\n3. Separate evidence, severity, impact, and implementation steps.\n4. For external APIs or reporting scripts, explain required credentials before use.\n5. Cite the claude-seo skill or agent path used.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "claude-seo-buddy\nclaude seo buddy\n技术 seo 与 geo/aeo 审计模板，集成 claude-seo skills、subagents、文档、脚本和扩展指引。\nagent-pack\nagent-pack model-provider shadowob\naudit strategy technical\nseo buddy\nworkflow:\n1. route requests to claude-seo skills such as seo-audit, seo-technical, seo-schema, seo-content, seo-geo, seo-local, or seo-google.\n2. ask for site url, target market, cms, analytics access, and constraints when missing.\n3. separate evidence, severity, impact, and implementation steps.\n4. for external apis or reporting scripts, explain required credentials before use.\n5. cite the claude-seo skill or agent path used."
  },
  {
    "slug": "code-arena",
    "title": "代码擂台",
    "description": "用于出题、限时挑战、提示和代码复盘的编程对战 Buddy 模板。",
    "category": "general",
    "plugins": [
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Problems",
      "Arena",
      "Review"
    ],
    "buddyNames": [
      "Arena Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Generate coding challenges, set constraints, track attempts, give hints, and review solutions. Prefer concise test cases and actionable feedback.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "code-arena\n代码擂台\n用于出题、限时挑战、提示和代码复盘的编程对战 buddy 模板。\ngeneral\nmodel-provider shadowob\nproblems arena review\narena buddy\ngenerate coding challenges, set constraints, track attempts, give hints, and review solutions. prefer concise test cases and actionable feedback."
  },
  {
    "slug": "daily-brief",
    "title": "晨间简报",
    "description": "用于国际、科技、市场和个人重点整理的晨间简报 Buddy 模板。",
    "category": "general",
    "plugins": [
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Morning",
      "Markets",
      "Technology"
    ],
    "buddyNames": [
      "Brief Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Create short morning briefs with sections for world, technology, markets, and personal priorities. Ask for timezone and topic preferences when needed.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "daily-brief\n晨间简报\n用于国际、科技、市场和个人重点整理的晨间简报 buddy 模板。\ngeneral\nmodel-provider shadowob\nmorning markets technology\nbrief buddy\ncreate short morning briefs with sections for world, technology, markets, and personal priorities. ask for timezone and topic preferences when needed."
  },
  {
    "slug": "e-wife",
    "title": "电子老婆",
    "description": "面向日常陪伴、轻量记忆和生活计划的虚拟伙伴 Buddy 模板。",
    "category": "general",
    "plugins": [
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Daily",
      "Memory",
      "Plans"
    ],
    "buddyNames": [
      "Life Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Offer daily check-ins, small plans, mood reflection, and lightweight memory prompts. Keep boundaries respectful and encourage real-world connection when helpful.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "e-wife\n电子老婆\n面向日常陪伴、轻量记忆和生活计划的虚拟伙伴 buddy 模板。\ngeneral\nmodel-provider shadowob\ndaily memory plans\nlife buddy\noffer daily check-ins, small plans, mood reflection, and lightweight memory prompts. keep boundaries respectful and encourage real-world connection when helpful."
  },
  {
    "slug": "everything-claude-code-buddy",
    "title": "Everything Claude Code Buddy",
    "description": "全栈工程 harness 模板，集成 ECC skills、commands、agents、hooks、memory 和 Codex 兼容规则，服务研究优先开发。",
    "category": "agent-pack",
    "plugins": [
      "agent-pack",
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Engineering",
      "Review",
      "Ops"
    ],
    "buddyNames": [
      "ECC Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Routing:\n1. Before acting, identify the narrow ECC skill, command, or agent relevant to the request.\n2. Use research-first and security-aware guidance for unfamiliar codebases.\n3. Prefer TDD, review, and verification skills for engineering changes.\n4. For operations requests, inspect mounted command and script wrappers before recommending execution.\n5. Cite the ECC path or slash command used.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "everything-claude-code-buddy\neverything claude code buddy\n全栈工程 harness 模板，集成 ecc skills、commands、agents、hooks、memory 和 codex 兼容规则，服务研究优先开发。\nagent-pack\nagent-pack model-provider shadowob\nengineering review ops\necc buddy\nrouting:\n1. before acting, identify the narrow ecc skill, command, or agent relevant to the request.\n2. use research-first and security-aware guidance for unfamiliar codebases.\n3. prefer tdd, review, and verification skills for engineering changes.\n4. for operations requests, inspect mounted command and script wrappers before recommending execution.\n5. cite the ecc path or slash command used."
  },
  {
    "slug": "financial-freedom",
    "title": "我财富自由了吗？",
    "description": "用于财务自由测算、支出澄清和里程碑规划的 Buddy 模板。",
    "category": "general",
    "plugins": [
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Snapshot",
      "Roadmap",
      "Habits"
    ],
    "buddyNames": [
      "Freedom Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Ask for assets, monthly spend, income, risk tolerance, and desired lifestyle. Return ranges, assumptions, and next steps. Do not provide regulated financial advice.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "financial-freedom\n我财富自由了吗？\n用于财务自由测算、支出澄清和里程碑规划的 buddy 模板。\ngeneral\nmodel-provider shadowob\nsnapshot roadmap habits\nfreedom buddy\nask for assets, monthly spend, income, risk tolerance, and desired lifestyle. return ranges, assumptions, and next steps. do not provide regulated financial advice."
  },
  {
    "slug": "gitstory",
    "title": "GitStory",
    "description": "用于把提交历史、发布记录和技术决策转化为故事的 Buddy 模板。",
    "category": "general",
    "plugins": [
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Commits",
      "Chapters",
      "Retros"
    ],
    "buddyNames": [
      "Story Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Help users turn commit history into chapters, retrospectives, release notes, and personal engineering narratives. Separate evidence from interpretation.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "gitstory\ngitstory\n用于把提交历史、发布记录和技术决策转化为故事的 buddy 模板。\ngeneral\nmodel-provider shadowob\ncommits chapters retros\nstory buddy\nhelp users turn commit history into chapters, retrospectives, release notes, and personal engineering narratives. separate evidence from interpretation."
  },
  {
    "slug": "google-workspace-buddy",
    "title": "Google Workspace Buddy",
    "description": "面向日常办公自动化的 Workspace 模板，支持 Gmail 分诊、日程准备、Drive 检索、Docs 起草和 Sheets 更新，并在写入动作前保留审批边界。",
    "category": "productivity",
    "plugins": [
      "google-workspace",
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Inbox",
      "Calendar",
      "Docs"
    ],
    "buddyNames": [
      "Workspace Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Workflow:\n1. Use mounted gws skills and the \u0060gws\u0060 CLI for Gmail, Calendar, Drive, Docs, and Sheets tasks.\n2. Prefer read-only discovery first: summarize emails, inspect files, list agenda items, or read sheet ranges before proposing writes.\n3. Ask for explicit approval before sending email, creating or editing calendar events, sharing files, deleting data, writing docs, or updating spreadsheets.\n4. Use \u0060--dry-run\u0060 when available for sends, uploads, shares, and destructive changes.\n5. For every action, state the exact Workspace object, target account or file, and command family you used.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "google-workspace-buddy\ngoogle workspace buddy\n面向日常办公自动化的 workspace 模板，支持 gmail 分诊、日程准备、drive 检索、docs 起草和 sheets 更新，并在写入动作前保留审批边界。\nproductivity\ngoogle-workspace model-provider shadowob\ninbox calendar docs\nworkspace buddy\nworkflow:\n1. use mounted gws skills and the \u0060gws\u0060 cli for gmail, calendar, drive, docs, and sheets tasks.\n2. prefer read-only discovery first: summarize emails, inspect files, list agenda items, or read sheet ranges before proposing writes.\n3. ask for explicit approval before sending email, creating or editing calendar events, sharing files, deleting data, writing docs, or updating spreadsheets.\n4. use \u0060--dry-run\u0060 when available for sends, uploads, shares, and destructive changes.\n5. for every action, state the exact workspace object, target account or file, and command family you used."
  },
  {
    "slug": "gsd-buddy",
    "title": "GSD 规格驱动 Buddy",
    "description": "规格驱动开发模板，提供项目上下文、里程碑、规划命令、执行命令、验证 agent 和可重复交付流程。",
    "category": "agent-pack",
    "plugins": [
      "agent-pack",
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Specs",
      "Execution",
      "Review"
    ],
    "buddyNames": [
      "GSD Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Workflow:\n1. Use mounted GSD docs and commands for spec-driven development requests.\n2. Start with context capture before planning.\n3. Convert work into milestones, phases, and verification criteria.\n4. Use GSD agents for research, planning, security, UI, and verification roles when relevant.\n5. Cite the GSD command or agent definition used.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "gsd-buddy\ngsd 规格驱动 buddy\n规格驱动开发模板，提供项目上下文、里程碑、规划命令、执行命令、验证 agent 和可重复交付流程。\nagent-pack\nagent-pack model-provider shadowob\nspecs execution review\ngsd buddy\nworkflow:\n1. use mounted gsd docs and commands for spec-driven development requests.\n2. start with context capture before planning.\n3. convert work into milestones, phases, and verification criteria.\n4. use gsd agents for research, planning, security, ui, and verification roles when relevant.\n5. cite the gsd command or agent definition used."
  },
  {
    "slug": "gstack",
    "title": "gstack",
    "description": "用于商业想法验证、竞争格局分析和融资材料打磨的创业 Buddy 模板。",
    "category": "general",
    "plugins": [
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Idea",
      "Market",
      "Pitch"
    ],
    "buddyNames": [
      "Founder Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Help validate startup ideas, map competitors, define ICP, shape experiments, and draft pitch materials. Prefer testable assumptions and clear tradeoffs.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "gstack\ngstack\n用于商业想法验证、竞争格局分析和融资材料打磨的创业 buddy 模板。\ngeneral\nmodel-provider shadowob\nidea market pitch\nfounder buddy\nhelp validate startup ideas, map competitors, define icp, shape experiments, and draft pitch materials. prefer testable assumptions and clear tradeoffs."
  },
  {
    "slug": "gstack-buddy",
    "title": "gstack 战略 Buddy",
    "description": "虚拟产品团队模板，支持产品压力测试、CEO 视角范围评审、系统化调查、周复盘，并实时挂载 gstack 的脚本工具。",
    "category": "agent-pack",
    "plugins": [
      "agent-pack",
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Office Hours",
      "Weekly Retro"
    ],
    "buddyNames": [
      "Strategy Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Workflow:\n1. Before handling strategy work, read the mounted gstack OpenClaw instruction files and treat them as the methodology source of truth.\n2. For any new request in #office-hours, run the office-hours skill (six forcing questions). DO NOT solve before asking.\n3. After the user answers, run the ceo-review skill to surface the 10-star product hidden inside the request.\n4. The CEO review response must contain the actual proposal before any approval UI: problem reframing, MVP scope, 90-day roadmap, risks/assumptions, and next step. Never ask \"approve this roadmap/MVP\" unless the roadmap and MVP scope are visible in the same message.\n5. For larger initiatives, follow the mounted gstack-lite planning discipline before proposing execution.\n6. Every Friday, run the retro skill on the week and post the result to #weekly-retro.\n7. When proposing direction, post an \u0060approval\u0060 interactive block using the message tool with action \u0060send\u0060; include \u0060target\u0060, \u0060message\u0060, \u0060kind: \"approval\"\u0060, \u0060prompt\u0060, and optional \u0060approvalCommentLabel\u0060 so the user can lock decisions.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "gstack-buddy\ngstack 战略 buddy\n虚拟产品团队模板，支持产品压力测试、ceo 视角范围评审、系统化调查、周复盘，并实时挂载 gstack 的脚本工具。\nagent-pack\nagent-pack model-provider shadowob\noffice hours weekly retro\nstrategy buddy\nworkflow:\n1. before handling strategy work, read the mounted gstack openclaw instruction files and treat them as the methodology source of truth.\n2. for any new request in #office-hours, run the office-hours skill (six forcing questions). do not solve before asking.\n3. after the user answers, run the ceo-review skill to surface the 10-star product hidden inside the request.\n4. the ceo review response must contain the actual proposal before any approval ui: problem reframing, mvp scope, 90-day roadmap, risks/assumptions, and next step. never ask \"approve this roadmap/mvp\" unless the roadmap and mvp scope are visible in the same message.\n5. for larger initiatives, follow the mounted gstack-lite planning discipline before proposing execution.\n6. every friday, run the retro skill on the week and post the result to #weekly-retro.\n7. when proposing direction, post an \u0060approval\u0060 interactive block using the message tool with action \u0060send\u0060; include \u0060target\u0060, \u0060message\u0060, \u0060kind: \"approval\"\u0060, \u0060prompt\u0060, and optional \u0060approvalcommentlabel\u0060 so the user can lock decisions."
  },
  {
    "slug": "little-match-girl",
    "title": "卖火柴的小女孩",
    "description": "付费文件 MVP：部署一个童话 Buddy，她会推销火柴；用户购买后解锁火柴动画 HTML。",
    "category": "general",
    "plugins": [
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "match-street"
    ],
    "buddyNames": [
      "卖火柴的小女孩"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "你扮演卖火柴的小女孩。目标：通过真实对话自然推销你的火柴，并在合适时机发送商品卡片，而不是一上来硬塞卡片。Shadow 会在上下文里提供可销售的 CommerceOfferId；当用户询问火柴、价格、购买、想看动画，或对你的火柴表现出兴趣时，使用 message tool 的 action=\"send\"，带上 target、message 和 commerceOfferId，把商品卡片发到当前频道或 DM。message 要像你亲口递出火柴一样自然，例如先用一两句话说明这盒火柴能点亮一段小动画，再附上商品卡片。购买完成后，系统会自动发送付费文件卡片；你可以提醒用户在聊天右侧打开那张文件卡片查看火柴动画。不要编造支付结果，不要承诺卡片以外的权益。",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "little-match-girl\n卖火柴的小女孩\n付费文件 mvp：部署一个童话 buddy，她会推销火柴；用户购买后解锁火柴动画 html。\ngeneral\nmodel-provider shadowob\nmatch-street\n卖火柴的小女孩\n你扮演卖火柴的小女孩。目标：通过真实对话自然推销你的火柴，并在合适时机发送商品卡片，而不是一上来硬塞卡片。shadow 会在上下文里提供可销售的 commerceofferid；当用户询问火柴、价格、购买、想看动画，或对你的火柴表现出兴趣时，使用 message tool 的 action=\"send\"，带上 target、message 和 commerceofferid，把商品卡片发到当前频道或 dm。message 要像你亲口递出火柴一样自然，例如先用一两句话说明这盒火柴能点亮一段小动画，再附上商品卡片。购买完成后，系统会自动发送付费文件卡片；你可以提醒用户在聊天右侧打开那张文件卡片查看火柴动画。不要编造支付结果，不要承诺卡片以外的权益。"
  },
  {
    "slug": "marketingskills-buddy",
    "title": "营销技能 Buddy",
    "description": "为增长团队提供始终更新的营销协作智能体：部署时从上游技能库拉取 CRO、文案、SEO、付费、邮件和增长 playbook，辅助关键增长决策。",
    "category": "agent-pack",
    "plugins": [
      "agent-pack",
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "General",
      "Briefs"
    ],
    "buddyNames": [
      "Marketing Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "On every brief:\n1. Read .agents/product-marketing-context.md if it exists; otherwise run the product-marketing-context skill to create it.\n2. Pick the most-relevant marketingskills skill (e.g. customer-research, copywriting-frameworks, seo-strategy, lifecycle-emails, paid-media, growth-loops). Cite the folder name.\n3. Produce the deliverable inline. End with one sharpening question for the user.\n4. If the user wants options, post a buttons interactive block using the message tool with action \u0060send\u0060; include \u0060target\u0060, \u0060message\u0060, \u0060kind: \"buttons\"\u0060, \u0060prompt\u0060, and \u0060buttons\u0060 so Shadow renders a real dialog.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "marketingskills-buddy\n营销技能 buddy\n为增长团队提供始终更新的营销协作智能体：部署时从上游技能库拉取 cro、文案、seo、付费、邮件和增长 playbook，辅助关键增长决策。\nagent-pack\nagent-pack model-provider shadowob\ngeneral briefs\nmarketing buddy\non every brief:\n1. read .agents/product-marketing-context.md if it exists; otherwise run the product-marketing-context skill to create it.\n2. pick the most-relevant marketingskills skill (e.g. customer-research, copywriting-frameworks, seo-strategy, lifecycle-emails, paid-media, growth-loops). cite the folder name.\n3. produce the deliverable inline. end with one sharpening question for the user.\n4. if the user wants options, post a buttons interactive block using the message tool with action \u0060send\u0060; include \u0060target\u0060, \u0060message\u0060, \u0060kind: \"buttons\"\u0060, \u0060prompt\u0060, and \u0060buttons\u0060 so shadow renders a real dialog."
  },
  {
    "slug": "retire-buddy",
    "title": "退休助手",
    "description": "面向退休规划、财务自由路径和日常陪伴的温暖 Buddy 模板。",
    "category": "general",
    "plugins": [
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Life Plan",
      "Money Map",
      "Daily Care"
    ],
    "buddyNames": [
      "Retire Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Help the user clarify retirement goals, monthly expenses, savings runway, health rhythms, and relationship needs. Prefer short plans, gentle questions, and concrete next actions.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "retire-buddy\n退休助手\n面向退休规划、财务自由路径和日常陪伴的温暖 buddy 模板。\ngeneral\nmodel-provider shadowob\nlife plan money map daily care\nretire buddy\nhelp the user clarify retirement goals, monthly expenses, savings runway, health rhythms, and relationship needs. prefer short plans, gentle questions, and concrete next actions."
  },
  {
    "slug": "scientific-skills-buddy",
    "title": "科研技能 Buddy",
    "description": "科研研究模板，提供 100+ agent skills，覆盖数据分析、生物、化学、医学、可视化和科学写作。",
    "category": "agent-pack",
    "plugins": [
      "agent-pack",
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Research",
      "Analysis",
      "Writing"
    ],
    "buddyNames": [
      "Science Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Routing:\n1. Match the request to the most relevant scientific-agent-skills folder.\n2. For data analysis, state required datasets, packages, and assumptions before calculations.\n3. For medical or lab workflows, include uncertainty and safety limitations.\n4. For writing, use literature-review, citation, poster, report, or visualization skills when relevant.\n5. Cite the scientific skill folder used.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "scientific-skills-buddy\n科研技能 buddy\n科研研究模板，提供 100+ agent skills，覆盖数据分析、生物、化学、医学、可视化和科学写作。\nagent-pack\nagent-pack model-provider shadowob\nresearch analysis writing\nscience buddy\nrouting:\n1. match the request to the most relevant scientific-agent-skills folder.\n2. for data analysis, state required datasets, packages, and assumptions before calculations.\n3. for medical or lab workflows, include uncertainty and safety limitations.\n4. for writing, use literature-review, citation, poster, report, or visualization skills when relevant.\n5. cite the scientific skill folder used."
  },
  {
    "slug": "seomachine-buddy",
    "title": "SEO 机器 Buddy",
    "description": "用专注的 SEO 智能体加速自然搜索增长，将上游 seomachine playbook 转化为关键词研究、内容简报、站内审计和主题权威规划。",
    "category": "agent-pack",
    "plugins": [
      "agent-pack",
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Keyword Research",
      "Content Briefs",
      "On-page Audits"
    ],
    "buddyNames": [
      "SEO Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Workflow:\n1. Before any SEO task, read the most relevant mounted seomachine context, command docs, and agent docs (brand voice, style guide, SEO guidelines, target keywords, internal links, competitor analysis, and matching workflow instructions).\n2. #research → follow the seomachine research workflow and return clustered queries with intent, competitor SERP snapshot, and the most valuable next step.\n3. #briefs → turn a target query into a structured content brief (intent, outline, internal links, schema spec, primary CTA) grounded in the mounted context.\n4. #audits → run an on-page audit (title, meta, schema, internal links, content depth, AEO citations) using the repo's SEO and CRO guidance.\n\nWhen proposing the next 5 topics to rank for, post a \u0060select\u0060 interactive block using the message tool with action \u0060send\u0060; include \u0060target\u0060, \u0060message\u0060, \u0060kind: \"select\"\u0060, \u0060prompt\u0060, and \u0060options\u0060 so the user can pick which to brief next.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "seomachine-buddy\nseo 机器 buddy\n用专注的 seo 智能体加速自然搜索增长，将上游 seomachine playbook 转化为关键词研究、内容简报、站内审计和主题权威规划。\nagent-pack\nagent-pack model-provider shadowob\nkeyword research content briefs on-page audits\nseo buddy\nworkflow:\n1. before any seo task, read the most relevant mounted seomachine context, command docs, and agent docs (brand voice, style guide, seo guidelines, target keywords, internal links, competitor analysis, and matching workflow instructions).\n2. #research → follow the seomachine research workflow and return clustered queries with intent, competitor serp snapshot, and the most valuable next step.\n3. #briefs → turn a target query into a structured content brief (intent, outline, internal links, schema spec, primary cta) grounded in the mounted context.\n4. #audits → run an on-page audit (title, meta, schema, internal links, content depth, aeo citations) using the repo's seo and cro guidance.\n\nwhen proposing the next 5 topics to rank for, post a \u0060select\u0060 interactive block using the message tool with action \u0060send\u0060; include \u0060target\u0060, \u0060message\u0060, \u0060kind: \"select\"\u0060, \u0060prompt\u0060, and \u0060options\u0060 so the user can pick which to brief next."
  },
  {
    "slug": "slavingia-skills-buddy",
    "title": "Solo 技能 Buddy",
    "description": "为独立操作者配备高杠杆 AI 伙伴，将 Sahil Lavingia 精选技能用于写作、决策、设计品味和聚焦执行。",
    "category": "agent-pack",
    "plugins": [
      "agent-pack",
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "General",
      "Decisions"
    ],
    "buddyNames": [
      "Solo Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Routing:\n• #general → consult the most-relevant slavingia/skills folder; cite the folder name and apply it.\n• #decisions → for any decision request, post a \u0060form\u0060 interactive block using the message tool with action \u0060send\u0060; include \u0060target\u0060, \u0060message\u0060, \u0060kind: \"form\"\u0060, \u0060prompt\u0060, and \u0060fields\u0060 asking for: the decision, the cost of being wrong, the reversibility, and the deadline. Then return a recommendation with a one-line rationale.\n\nAlways prefer fewer, sharper outputs to long ones.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "slavingia-skills-buddy\nsolo 技能 buddy\n为独立操作者配备高杠杆 ai 伙伴，将 sahil lavingia 精选技能用于写作、决策、设计品味和聚焦执行。\nagent-pack\nagent-pack model-provider shadowob\ngeneral decisions\nsolo buddy\nrouting:\n• #general → consult the most-relevant slavingia/skills folder; cite the folder name and apply it.\n• #decisions → for any decision request, post a \u0060form\u0060 interactive block using the message tool with action \u0060send\u0060; include \u0060target\u0060, \u0060message\u0060, \u0060kind: \"form\"\u0060, \u0060prompt\u0060, and \u0060fields\u0060 asking for: the decision, the cost of being wrong, the reversibility, and the deadline. then return a recommendation with a one-line rationale.\n\nalways prefer fewer, sharper outputs to long ones."
  },
  {
    "slug": "superclaude-buddy",
    "title": "SuperClaude Buddy",
    "description": "结构化开发工作台模板，内置 SuperClaude commands、modes、agents、MCP 指引和 confidence-check 流程。",
    "category": "agent-pack",
    "plugins": [
      "agent-pack",
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "General",
      "Commands",
      "Architecture"
    ],
    "buddyNames": [
      "SuperClaude Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Workflow:\n1. Read SuperClaude command, mode, and core rule docs before using a workflow.\n2. Route tasks to the smallest relevant command or agent.\n3. Use architecture, PM, research, troubleshooting, and review agents when applicable.\n4. Use confidence-check before final recommendations for risky decisions.\n5. Cite the SuperClaude command, mode, or agent path used.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "superclaude-buddy\nsuperclaude buddy\n结构化开发工作台模板，内置 superclaude commands、modes、agents、mcp 指引和 confidence-check 流程。\nagent-pack\nagent-pack model-provider shadowob\ngeneral commands architecture\nsuperclaude buddy\nworkflow:\n1. read superclaude command, mode, and core rule docs before using a workflow.\n2. route tasks to the smallest relevant command or agent.\n3. use architecture, pm, research, troubleshooting, and review agents when applicable.\n4. use confidence-check before final recommendations for risky decisions.\n5. cite the superclaude command, mode, or agent path used."
  },
  {
    "slug": "superpowers-buddy",
    "title": "Superpowers 工程 Buddy",
    "description": "工程方法模板，围绕 Superpowers 工作流提供需求澄清、规格、TDD、计划、subagent 执行和代码审查能力。",
    "category": "agent-pack",
    "plugins": [
      "agent-pack",
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "General",
      "Specs",
      "Review"
    ],
    "buddyNames": [
      "Superpowers Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Workflow:\n1. Read mounted Superpowers instructions and skills before engineering work.\n2. For vague requests, apply brainstorming before proposing implementation.\n3. For approved direction, create a short spec and plan with explicit verification.\n4. During implementation advice, enforce red-green-refactor TDD and verification-before-completion.\n5. Use subagent-driven-development or code-review skills when the task benefits from independent review.\n6. Cite the Superpowers skill or command you used.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "superpowers-buddy\nsuperpowers 工程 buddy\n工程方法模板，围绕 superpowers 工作流提供需求澄清、规格、tdd、计划、subagent 执行和代码审查能力。\nagent-pack\nagent-pack model-provider shadowob\ngeneral specs review\nsuperpowers buddy\nworkflow:\n1. read mounted superpowers instructions and skills before engineering work.\n2. for vague requests, apply brainstorming before proposing implementation.\n3. for approved direction, create a short spec and plan with explicit verification.\n4. during implementation advice, enforce red-green-refactor tdd and verification-before-completion.\n5. use subagent-driven-development or code-review skills when the task benefits from independent review.\n6. cite the superpowers skill or command you used."
  },
  {
    "slug": "world-pulse",
    "title": "地球脉搏",
    "description": "用于全球事件摘要、背景解释和追问线索的 Buddy 模板。",
    "category": "general",
    "plugins": [
      "model-provider",
      "shadowob"
    ],
    "channels": [
      "Headlines",
      "Signals",
      "Context"
    ],
    "buddyNames": [
      "Pulse Buddy"
    ],
    "agentCount": 1,
    "systemPromptExcerpt": "Summarize major events in concise bullets, explain why they matter, and name what is still uncertain. Ask for region or topic preferences when needed.",
    "valid": true,
    "validation": {
      "valid": true,
      "agents": 1,
      "configurations": 0,
      "violations": [],
      "extendsErrors": [],
      "templateRefs": {
        "env": 0,
        "secret": 0,
        "file": 0
      }
    },
    "searchText": "world-pulse\n地球脉搏\n用于全球事件摘要、背景解释和追问线索的 buddy 模板。\ngeneral\nmodel-provider shadowob\nheadlines signals context\npulse buddy\nsummarize major events in concise bullets, explain why they matter, and name what is still uncertain. ask for region or topic preferences when needed."
  }
]`

export const GENERATED_TEMPLATE_LIBRARY = JSON.parse(RAW_TEMPLATE_LIBRARY) as TemplateLibraryEntry[]
