import type {
  FlashActorRef,
  FlashCardKind,
  FlashCardPriority,
  FlashPatchEvent,
  FlashViewport,
} from '@shadowob/flash-types/space-app'
import { sql } from 'drizzle-orm'
import {
  bigint,
  bigserial,
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  real,
  text,
  timestamp,
  uniqueIndex,
} from 'drizzle-orm/pg-core'

export const flashBoards = pgTable(
  'flash_boards',
  {
    id: text('id').primaryKey(),
    serverId: text('server_id').notNull(),
    ownerUserId: text('owner_user_id').notNull(),
    title: text('title').notNull(),
    viewport: jsonb('viewport').$type<FlashViewport | null>(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    flashBoardsOwnerUnique: uniqueIndex('flash_boards_owner_unique').on(t.serverId, t.ownerUserId),
    flashBoardsServerIdx: index('flash_boards_server_idx').on(t.serverId),
  }),
)

export const flashCards = pgTable(
  'flash_cards',
  {
    id: text('id').primaryKey(),
    boardId: text('board_id')
      .notNull()
      .references(() => flashBoards.id, { onDelete: 'cascade' }),
    kind: text('kind').$type<FlashCardKind>().notNull(),
    title: text('title').notNull(),
    summary: text('summary'),
    content: text('content'),
    thumbnail: text('thumbnail'),
    sourceId: text('source_id'),
    linkedCardIds: jsonb('linked_card_ids').$type<string[]>().default([]).notNull(),
    meta: jsonb('meta').$type<Record<string, unknown>>().default({}).notNull(),
    tags: jsonb('tags').$type<string[]>().default([]).notNull(),
    priority: text('priority').$type<FlashCardPriority>().default('medium').notNull(),
    autoGenerated: boolean('auto_generated').default(false).notNull(),
    rating: integer('rating').default(0).notNull(),
    filePath: text('file_path'),
    fileMime: text('file_mime'),
    deckIds: jsonb('deck_ids').$type<string[]>().default([]).notNull(),
    x: real('x').default(240).notNull(),
    y: real('y').default(220).notNull(),
    angle: real('angle').default(0).notNull(),
    flipped: boolean('flipped').default(false).notNull(),
    hidden: boolean('hidden').default(false).notNull(),
    locked: boolean('locked').default(false).notNull(),
    revision: integer('revision').default(0).notNull(),
    createdBy: jsonb('created_by').$type<FlashActorRef | null>(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    flashCardsBoardIdx: index('flash_cards_board_idx').on(t.boardId),
    flashCardsUpdatedIdx: index('flash_cards_updated_idx').on(t.updatedAt),
  }),
)

export const flashArenas = pgTable(
  'flash_arenas',
  {
    id: text('id').primaryKey(),
    boardId: text('board_id')
      .notNull()
      .references(() => flashBoards.id, { onDelete: 'cascade' }),
    kind: text('kind').$type<'magic-circle' | 'grid' | 'custom'>().notNull(),
    label: text('label').notNull(),
    x: real('x').default(520).notNull(),
    y: real('y').default(360).notNull(),
    radius: real('radius').default(280).notNull(),
    color: text('color').default('#7c3aed').notNull(),
    cardIds: jsonb('card_ids').$type<string[]>().default([]).notNull(),
    script: text('script'),
    revision: integer('revision').default(0).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    flashArenasBoardIdx: index('flash_arenas_board_idx').on(t.boardId),
  }),
)

export const flashCommandEvents = pgTable(
  'flash_command_events',
  {
    id: text('id').primaryKey(),
    /** Global append sequence retained for diagnostics and old migrations. */
    seq: bigserial('seq', { mode: 'number' }).notNull(),
    /** Board-local authoritative cursor. Clients consume this value as FlashCommandEvent.seq. */
    boardSeq: bigint('board_seq', { mode: 'number' }).default(0).notNull(),
    boardId: text('board_id')
      .notNull()
      .references(() => flashBoards.id, { onDelete: 'cascade' }),
    cardId: text('card_id'),
    commandName: text('command_name').notNull(),
    command: jsonb('command').$type<unknown>(),
    result: jsonb('result').$type<unknown>(),
    patches: jsonb('patches').$type<FlashPatchEvent[]>().default([]).notNull(),
    clientMutationId: text('client_mutation_id'),
    baseCursor: bigint('base_cursor', { mode: 'number' }),
    causalLag: bigint('causal_lag', { mode: 'number' }).default(0).notNull(),
    actor: jsonb('actor').$type<FlashActorRef | null>(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    flashCommandEventsBoardIdx: index('flash_command_events_board_idx').on(t.boardId),
    flashCommandEventsGlobalSeqIdx: index('flash_command_events_global_seq_idx').on(t.seq),
    flashCommandEventsLegacyBoardSeqIdx: index('flash_command_events_legacy_board_seq_idx').on(
      t.boardId,
      t.seq,
    ),
    flashCommandEventsBoardSeqUnique: uniqueIndex('flash_command_events_board_seq_unique').on(
      t.boardId,
      t.boardSeq,
    ),
    flashCommandEventsMutationUnique: uniqueIndex('flash_command_events_mutation_unique')
      .on(t.boardId, t.clientMutationId)
      .where(sql`${t.clientMutationId} IS NOT NULL`),
  }),
)

export const flashBoardSnapshots = pgTable(
  'flash_board_snapshots',
  {
    id: text('id').primaryKey(),
    boardId: text('board_id')
      .notNull()
      .references(() => flashBoards.id, { onDelete: 'cascade' }),
    cursor: bigint('cursor', { mode: 'number' }).notNull(),
    schemaVersion: integer('schema_version').default(1).notNull(),
    snapshot: jsonb('snapshot').$type<unknown>().notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    flashBoardSnapshotsBoardCursorUnique: uniqueIndex(
      'flash_board_snapshots_board_cursor_unique',
    ).on(t.boardId, t.cursor),
    flashBoardSnapshotsBoardIdx: index('flash_board_snapshots_board_idx').on(t.boardId),
  }),
)

export const flashMutationReceipts = pgTable(
  'flash_mutation_receipts',
  {
    boardId: text('board_id')
      .notNull()
      .references(() => flashBoards.id, { onDelete: 'cascade' }),
    clientMutationId: text('client_mutation_id').notNull(),
    status: text('status').$type<'pending' | 'completed' | 'failed'>().default('pending').notNull(),
    eventId: text('event_id').references(() => flashCommandEvents.id, { onDelete: 'set null' }),
    result: jsonb('result').$type<unknown>(),
    error: text('error'),
    actor: jsonb('actor').$type<FlashActorRef | null>(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    flashMutationReceiptsUnique: uniqueIndex('flash_mutation_receipts_unique').on(
      t.boardId,
      t.clientMutationId,
    ),
    flashMutationReceiptsStatusIdx: index('flash_mutation_receipts_status_idx').on(
      t.boardId,
      t.status,
    ),
  }),
)

export const flashSelections = pgTable(
  'flash_selections',
  {
    boardId: text('board_id')
      .notNull()
      .references(() => flashBoards.id, { onDelete: 'cascade' }),
    actorId: text('actor_id').notNull(),
    actor: jsonb('actor').$type<FlashActorRef | null>(),
    selectedCardIds: jsonb('selected_card_ids').$type<string[]>().default([]).notNull(),
    anchorCardId: text('anchor_card_id'),
    revision: integer('revision').default(0).notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => ({
    flashSelectionsBoardActorUnique: uniqueIndex('flash_selections_board_actor_unique').on(
      t.boardId,
      t.actorId,
    ),
    flashSelectionsBoardIdx: index('flash_selections_board_idx').on(t.boardId),
  }),
)
