name: shadow-integrations-dev

services:
  resume:
    command: pnpm dev:hot:install
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
      RESUME_VITE_PORT: ${RESUME_VITE_PORT:-5174}
      RESUME_VITE_DEV_SERVER_URL: ${RESUME_VITE_DEV_SERVER_URL:-http://localhost:5174}
    ports:
      - ${RESUME_VITE_PORT:-5174}:${RESUME_VITE_PORT:-5174}
    volumes:
      - ${RESUME_DEV_APP_DIR:-./resume}:/repo/integrations/resume
      - resume-node-modules:/repo/node_modules
      - resume-app-node-modules:/repo/integrations/resume/node_modules

volumes:
  resume-node-modules:
  resume-app-node-modules:
