// Generated by shadow-server-app typegen from ../shadow-app.local.json.
// Do not edit by hand. Update the JSON manifest and regenerate this file.
import type { ShadowServerAppManifest } from '@shadowob/sdk'

export const shadowServerAppManifest = {
  schemaVersion: 'shadow.app/1',
  appKey: 'shadow-quiz',
  name: 'Shadow Quiz',
  description:
    'A quiz Server App for publishing answer-keyed quizzes, step-by-step submissions, and grader review by people or Buddies.',
  version: '1.0.0',
  iconUrl: 'http://localhost:4211/assets/icon.svg',
  iframe: {
    entry: 'http://localhost:4211/shadow/server',
    allowedOrigins: ['http://localhost:4211'],
  },
  api: {
    baseUrl: 'http://localhost:4211',
    auth: {
      type: 'oauth2-bearer',
    },
  },
  access: {
    defaultPermissions: ['quiz.quizzes:read'],
    defaultApprovalMode: 'none',
  },
  commands: [
    {
      name: 'quizzes.list',
      title: 'List quizzes',
      description: 'List published quizzes with submission counts.',
      path: '/api/shadow/commands/quizzes.list',
      permission: 'quiz.quizzes:read',
      action: 'read',
      dataClass: 'server-private',
    },
    {
      name: 'quizzes.get',
      title: 'Open quiz',
      description: 'Read one quiz with questions and submission summary.',
      path: '/api/shadow/commands/quizzes.get',
      permission: 'quiz.quizzes:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['quizId'],
        properties: {
          quizId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'quizzes.publish',
      title: 'Publish quiz',
      description:
        'Publish a quiz with single-choice, multiple-choice, fill-in, or short-answer questions and standard answers.',
      path: '/api/shadow/commands/quizzes.publish',
      permission: 'quiz.quizzes:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['title', 'questions'],
        properties: {
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 220,
          },
          description: {
            type: 'string',
            maxLength: 4000,
          },
          questions: {
            type: 'array',
            maxItems: 80,
            items: {
              type: 'object',
              required: ['type', 'prompt', 'answer'],
              properties: {
                id: {
                  type: 'string',
                  maxLength: 80,
                },
                type: {
                  enum: ['single', 'multiple', 'fill', 'short'],
                },
                prompt: {
                  type: 'string',
                  minLength: 1,
                  maxLength: 1200,
                },
                options: {
                  type: 'array',
                  maxItems: 12,
                  items: {
                    type: 'string',
                    minLength: 1,
                    maxLength: 240,
                  },
                },
                answer: {},
                points: {
                  type: 'number',
                },
                explanation: {
                  type: 'string',
                  maxLength: 2000,
                },
              },
              additionalProperties: false,
            },
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'submissions.submit',
      title: 'Submit quiz',
      description:
        'Submit answers for a quiz. The result enters pending review for a grader or Buddy.',
      path: '/api/shadow/commands/submissions.submit',
      permission: 'quiz.submissions:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['quizId', 'answers'],
        properties: {
          quizId: {
            type: 'string',
            minLength: 1,
          },
          answers: {
            type: 'object',
            additionalProperties: {},
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'submissions.list',
      title: 'List submissions',
      description: 'List pending or graded quiz submissions.',
      path: '/api/shadow/commands/submissions.list',
      permission: 'quiz.submissions:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          quizId: {
            type: 'string',
            minLength: 1,
          },
          status: {
            enum: ['pending_review', 'graded'],
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'submissions.grade',
      title: 'Grade submission',
      description: 'Grade a submitted quiz with score and feedback.',
      path: '/api/shadow/commands/submissions.grade',
      permission: 'quiz.submissions:grade',
      action: 'manage',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['submissionId', 'score'],
        properties: {
          submissionId: {
            type: 'string',
            minLength: 1,
          },
          score: {
            type: 'number',
          },
          feedback: {
            type: 'string',
            maxLength: 4000,
          },
        },
        additionalProperties: false,
      },
    },
  ],
  skills: [
    {
      name: 'shadow-quiz-ops',
      description:
        'Use when a Buddy needs to publish quizzes, submit answers, inspect pending submissions, or grade a quiz attempt.',
      commandHints: [
        'shadow-quiz quizzes.list',
        'shadow-quiz quizzes.get',
        'shadow-quiz quizzes.publish',
        'shadow-quiz submissions.submit',
        'shadow-quiz submissions.list',
        'shadow-quiz submissions.grade',
      ],
    },
  ],
  events: ['quiz.updated'],
} as const satisfies ShadowServerAppManifest

export type ShadowServerAppManifestDefinition = typeof shadowServerAppManifest
