// Generated by shadow-server-app typegen from ../shadow-app.local.json.
// Do not edit by hand. Update the JSON manifest and regenerate this file.
import type { ShadowServerAppManifest } from '@shadowob/sdk'

export const shadowServerAppManifest = {
  schemaVersion: 'shadow.app/1',
  appKey: 'shadow-trainer',
  name: 'Code Trainer',
  description:
    'A LeetCode-style Server App where learners submit code and Buddies fetch, execute, judge, and provide learning advice.',
  version: '1.0.0',
  iconUrl: 'http://localhost:4213/assets/icon.svg',
  iframe: {
    entry: 'http://localhost:4213/shadow/server',
    allowedOrigins: ['http://localhost:4213'],
  },
  api: {
    baseUrl: 'http://localhost:4213',
    auth: {
      type: 'oauth2-bearer',
    },
  },
  access: {
    defaultPermissions: ['trainer.challenges:read'],
    defaultApprovalMode: 'none',
  },
  commands: [
    {
      name: 'challenges.list',
      title: 'List challenges',
      description: 'Search programming challenges.',
      path: '/api/shadow/commands/challenges.list',
      permission: 'trainer.challenges:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          query: {
            type: 'string',
            maxLength: 120,
          },
          difficulty: {
            enum: ['easy', 'medium', 'hard'],
          },
          tag: {
            type: 'string',
            minLength: 1,
            maxLength: 40,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'challenges.get',
      title: 'Open challenge',
      description:
        'Read one challenge with examples, starter code, judge instructions, and related submissions.',
      path: '/api/shadow/commands/challenges.get',
      permission: 'trainer.challenges:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['challengeId'],
        properties: {
          challengeId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'challenges.upsert',
      title: 'Publish challenge',
      description: 'Create or update a persistent programming challenge for learners.',
      path: '/api/shadow/commands/challenges.upsert',
      permission: 'trainer.challenges:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['title', 'difficulty', 'prompt', 'starterCode', 'judgeInstructions'],
        properties: {
          id: {
            type: 'string',
            minLength: 1,
            maxLength: 80,
          },
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 160,
          },
          difficulty: {
            enum: ['easy', 'medium', 'hard'],
          },
          tags: {
            type: 'array',
            maxItems: 12,
            items: {
              type: 'string',
              minLength: 1,
              maxLength: 40,
            },
          },
          prompt: {
            type: 'string',
            minLength: 1,
            maxLength: 12000,
          },
          starterCode: {
            type: 'string',
            minLength: 1,
            maxLength: 40000,
          },
          examples: {
            type: 'array',
            maxItems: 20,
            items: {
              type: 'object',
              required: ['input', 'output'],
              properties: {
                input: {
                  type: 'string',
                  minLength: 1,
                  maxLength: 2000,
                },
                output: {
                  type: 'string',
                  minLength: 1,
                  maxLength: 2000,
                },
                explanation: {
                  type: 'string',
                  maxLength: 4000,
                },
              },
              additionalProperties: false,
            },
          },
          judgeInstructions: {
            type: 'string',
            minLength: 1,
            maxLength: 12000,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'sources.search',
      title: 'Search problem sources',
      description: 'Search supported public problem repositories for importable practice tasks.',
      path: '/api/shadow/commands/sources.search',
      permission: 'trainer.challenges:read',
      action: 'read',
      dataClass: 'public',
      inputSchema: {
        type: 'object',
        properties: {
          provider: {
            enum: ['leetcode', 'codeforces'],
          },
          query: {
            type: 'string',
            maxLength: 120,
          },
          limit: {
            type: 'integer',
            minimum: 1,
            maximum: 50,
          },
          offset: {
            type: 'integer',
            minimum: 0,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'sources.import',
      title: 'Import problem source',
      description:
        'Import a public problem statement and canonical test data into the persistent trainer problem set.',
      path: '/api/shadow/commands/sources.import',
      permission: 'trainer.challenges:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['sourceId'],
        properties: {
          provider: {
            enum: ['leetcode', 'codeforces'],
          },
          sourceId: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'submissions.create',
      title: 'Submit solution',
      description: 'Submit code for Buddy analysis and learning feedback.',
      path: '/api/shadow/commands/submissions.create',
      permission: 'trainer.submissions:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['challengeId', 'language', 'code', 'reviewer'],
        properties: {
          challengeId: {
            type: 'string',
            minLength: 1,
          },
          language: {
            type: 'string',
            minLength: 1,
            maxLength: 40,
          },
          code: {
            type: 'string',
            minLength: 1,
            maxLength: 40000,
          },
          reviewer: {
            type: 'object',
            properties: {
              agentId: {
                type: 'string',
                minLength: 1,
              },
              assigneeLabel: {
                type: 'string',
                minLength: 1,
                maxLength: 160,
              },
              displayName: {
                type: 'string',
                minLength: 1,
                maxLength: 160,
              },
              reviewFocus: {
                enum: ['standard', 'interview', 'debug', 'complexity'],
              },
              coachingFocuses: {
                type: 'array',
                maxItems: 8,
                items: {
                  enum: [
                    'reasoning',
                    'edge_cases',
                    'complexity',
                    'communication',
                    'follow_ups',
                    'debugging',
                  ],
                },
              },
              locale: {
                type: 'string',
                maxLength: 32,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'submissions.list',
      title: 'List submissions',
      description: 'List code submissions by challenge and status.',
      path: '/api/shadow/commands/submissions.list',
      permission: 'trainer.submissions:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          challengeId: {
            type: 'string',
            minLength: 1,
          },
          status: {
            enum: ['submitted', 'analyzed'],
          },
          limit: {
            type: 'integer',
            minimum: 1,
            maximum: 100,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'submissions.get',
      title: 'Read submission',
      description:
        'Read one code submission with its challenge instructions for execution and review.',
      path: '/api/shadow/commands/submissions.get',
      permission: 'trainer.submissions:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['submissionId'],
        properties: {
          submissionId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'submissions.pending',
      title: 'Fetch pending submissions',
      description: 'Fetch submitted code waiting for Buddy analysis.',
      path: '/api/shadow/commands/submissions.pending',
      permission: 'trainer.submissions:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          limit: {
            type: 'integer',
            minimum: 1,
            maximum: 100,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'submissions.analyze',
      title: 'Analyze submission',
      description:
        'Write Buddy analysis, score, explanation, and learning suggestions for submitted code.',
      path: '/api/shadow/commands/submissions.analyze',
      permission: 'trainer.submissions:analyze',
      action: 'manage',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['submissionId', 'outcome', 'score', 'summary', 'explanation'],
        properties: {
          submissionId: {
            type: 'string',
            minLength: 1,
          },
          outcome: {
            enum: ['accepted', 'needs_work', 'runtime_error', 'incomplete'],
          },
          score: {
            type: 'number',
            minimum: 0,
            maximum: 100,
          },
          summary: {
            type: 'string',
            minLength: 1,
            maxLength: 1200,
          },
          explanation: {
            type: 'string',
            minLength: 1,
            maxLength: 8000,
          },
          suggestions: {
            type: 'array',
            maxItems: 12,
            items: {
              type: 'string',
              minLength: 1,
              maxLength: 500,
            },
          },
          complexity: {
            type: 'string',
            maxLength: 1000,
          },
        },
        additionalProperties: false,
      },
    },
  ],
  skills: [
    {
      name: 'shadow-trainer-ops',
      description:
        'Use when a Buddy needs to fetch programming challenges, collect learner code, execute pending submissions, or write review feedback.',
      commandHints: [
        'shadow-trainer challenges.list',
        'shadow-trainer challenges.get',
        'shadow-trainer challenges.upsert',
        'shadow-trainer sources.search',
        'shadow-trainer sources.import',
        'shadow-trainer submissions.create',
        'shadow-trainer submissions.pending',
        'shadow-trainer submissions.get',
        'shadow-trainer submissions.analyze',
      ],
    },
  ],
  events: ['trainer.updated'],
} as const satisfies ShadowServerAppManifest

export type ShadowServerAppManifestDefinition = typeof shadowServerAppManifest
