// Generated by shadow-server-app typegen from ../shadow-app.local.json.
// Do not edit by hand. Update the JSON manifest and regenerate this file.
import type { ShadowServerAppManifest } from '@shadowob/sdk'

export const shadowServerAppManifest = {
  schemaVersion: 'shadow.app/1',
  appKey: 'shadow-trainer',
  name: 'Code Trainer',
  description:
    'A LeetCode-style Server App where learners submit code and Buddies fetch, execute, judge, and provide learning advice.',
  version: '1.0.0',
  iconUrl: 'http://localhost:4213/assets/icon.svg',
  iframe: {
    entry: 'http://localhost:4213/shadow/server',
    allowedOrigins: ['http://localhost:4213'],
  },
  api: {
    baseUrl: 'http://localhost:4213',
    auth: {
      type: 'oauth2-bearer',
    },
  },
  access: {
    defaultPermissions: ['trainer.challenges:read'],
    defaultApprovalMode: 'none',
  },
  commands: [
    {
      name: 'challenges.list',
      title: 'List challenges',
      description: 'Search programming challenges.',
      path: '/api/shadow/commands/challenges.list',
      permission: 'trainer.challenges:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          query: {
            type: 'string',
            maxLength: 120,
          },
          difficulty: {
            enum: ['easy', 'medium', 'hard'],
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'challenges.get',
      title: 'Open challenge',
      description:
        'Read one challenge with examples, starter code, judge instructions, and related submissions.',
      path: '/api/shadow/commands/challenges.get',
      permission: 'trainer.challenges:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['challengeId'],
        properties: {
          challengeId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'submissions.create',
      title: 'Submit solution',
      description: 'Submit code for external execution and review by a Buddy or human grader.',
      path: '/api/shadow/commands/submissions.create',
      permission: 'trainer.submissions:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['challengeId', 'language', 'code'],
        properties: {
          challengeId: {
            type: 'string',
            minLength: 1,
          },
          language: {
            type: 'string',
            minLength: 1,
            maxLength: 40,
          },
          code: {
            type: 'string',
            minLength: 1,
            maxLength: 40000,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'submissions.list',
      title: 'List submissions',
      description: 'List code submissions by challenge and status.',
      path: '/api/shadow/commands/submissions.list',
      permission: 'trainer.submissions:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          challengeId: {
            type: 'string',
            minLength: 1,
          },
          status: {
            enum: ['submitted', 'judged'],
          },
          limit: {
            type: 'integer',
            minimum: 1,
            maximum: 100,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'submissions.get',
      title: 'Read submission',
      description:
        'Read one code submission with its challenge instructions for execution and review.',
      path: '/api/shadow/commands/submissions.get',
      permission: 'trainer.submissions:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['submissionId'],
        properties: {
          submissionId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'submissions.pending',
      title: 'Fetch pending submissions',
      description: 'Fetch submitted code waiting for a Buddy or human grader.',
      path: '/api/shadow/commands/submissions.pending',
      permission: 'trainer.submissions:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          limit: {
            type: 'integer',
            minimum: 1,
            maximum: 100,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'submissions.judge',
      title: 'Judge submission',
      description:
        'Write a verdict, score, feedback, and learning suggestions after executing submitted code.',
      path: '/api/shadow/commands/submissions.judge',
      permission: 'trainer.submissions:grade',
      action: 'manage',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['submissionId', 'verdict', 'score', 'feedback'],
        properties: {
          submissionId: {
            type: 'string',
            minLength: 1,
          },
          verdict: {
            enum: ['accepted', 'wrong_answer', 'runtime_error', 'needs_review'],
          },
          score: {
            type: 'number',
            minimum: 0,
            maximum: 100,
          },
          feedback: {
            type: 'string',
            minLength: 1,
            maxLength: 8000,
          },
          suggestions: {
            type: 'array',
            maxItems: 12,
            items: {
              type: 'string',
              minLength: 1,
              maxLength: 500,
            },
          },
        },
        additionalProperties: false,
      },
    },
  ],
  skills: [
    {
      name: 'shadow-trainer-ops',
      description:
        'Use when a Buddy needs to fetch programming challenges, collect learner code, execute pending submissions, or write review feedback.',
      commandHints: [
        'shadow-trainer challenges.list',
        'shadow-trainer challenges.get',
        'shadow-trainer submissions.create',
        'shadow-trainer submissions.pending',
        'shadow-trainer submissions.get',
        'shadow-trainer submissions.judge',
      ],
    },
  ],
  events: ['trainer.updated'],
} as const satisfies ShadowServerAppManifest

export type ShadowServerAppManifestDefinition = typeof shadowServerAppManifest
