// ══════════════════════════════════════════════════════════════
// @shadowob/flash-cards/plugins — Built-in card kind plugins (individual exports)
//
// Import individual plugins for tree-shaking or custom composition:
//   import { dataSystem } from '@shadowob/flash-cards/plugins'
// ══════════════════════════════════════════════════════════════

export { argumentSystem } from './argumentSystem'
export { chartSystem } from './chartSystem'
export { codeSystem } from './codeSystem'
export { colorSystem } from './colorSystem'
export { commentSystem } from './commentSystem'
export { comparisonSystem } from './comparisonSystem'
export { countdownSystem } from './countdownSystem'
export { dataSystem } from './dataSystem'
export { definitionSystem } from './definitionSystem'
export { eventSystem } from './eventSystem'
export { exampleSystem } from './exampleSystem'
export { fileSystem } from './fileSystem'
export { gifSystem } from './gifSystem'
export { imageSystem } from './imageSystem'
export { inspirationSystem } from './inspirationSystem'
export { keypointSystem } from './keypointSystem'
export { linkSystem } from './linkSystem'
export { live2dSystem } from './live2dSystem'
export { lottieSystem } from './lottieSystem'
export { mathSystem } from './mathSystem'
export { personSystem } from './personSystem'
export { pokerSystem } from './pokerSystem'
export { positionSystem } from './positionSystem'
export { processSystem } from './processSystem'
export { qrcodeSystem } from './qrcodeSystem'
export { quoteSystem } from './quoteSystem'
export { referenceSystem } from './referenceSystem'
export { socialSystem } from './socialSystem'
export { storySystem } from './storySystem'
export { tableSystem } from './tableSystem'
export { tarotSystem } from './tarotSystem'
export { terminalSystem } from './terminalSystem'
export { threeSystem } from './threeSystem'
export { timelineSystem } from './timelineSystem'
export { timestampSystem } from './timestampSystem'
export { todoSystem } from './todoSystem'
export { voiceSystem } from './voiceSystem'
export { webpageSystem } from './webpageSystem'
