// Generated by shadow-server-app typegen from ../shadow-app.local.json.
// Do not edit by hand. Update the JSON manifest and regenerate this file.
import type { ShadowServerAppManifest } from '@shadowob/sdk'

export const shadowServerAppManifest = {
  schemaVersion: 'shadow.app/1',
  appKey: 'shadow-kanban',
  name: 'Shadow Kanban',
  description:
    'A Trello-style task board where people and Buddies coordinate cards, lists, assignees, and comments.',
  version: '1.0.0',
  iconUrl: 'http://localhost:4201/assets/icon.svg',
  iframe: {
    entry: 'http://localhost:4201/shadow/server',
    allowedOrigins: ['http://localhost:4201'],
  },
  api: {
    baseUrl: 'http://localhost:4201',
    auth: {
      type: 'oauth2-bearer',
    },
  },
  access: {
    defaultPermissions: ['kanban.boards:read'],
    defaultApprovalMode: 'none',
  },
  commands: [
    {
      name: 'boards.get',
      title: 'Open board',
      description: 'Read the current task board with columns, cards, assignees, and comments.',
      path: '/api/shadow/commands/boards.get',
      permission: 'kanban.boards:read',
      action: 'read',
      dataClass: 'server-private',
    },
    {
      name: 'cards.get',
      title: 'Open card detail',
      description: 'Read a single task card with assignees, description, and comments.',
      path: '/api/shadow/commands/cards.get',
      permission: 'kanban.boards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          cardId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.create',
      title: 'Create card',
      description:
        'Create a new task card in a board column. The calling actor is captured as creator and default assignee.',
      path: '/api/shadow/commands/cards.create',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['title'],
        properties: {
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 180,
          },
          columnId: {
            type: 'string',
            maxLength: 80,
          },
          description: {
            type: 'string',
            maxLength: 2000,
          },
          label: {
            type: 'string',
            maxLength: 40,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.create_and_dispatch',
      title: 'Create and dispatch card',
      description:
        'Create a Kanban card, assign it to a Buddy label, and emit a Shadow Inbox task card for that Buddy.',
      path: '/api/shadow/commands/cards.create_and_dispatch',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['title'],
        properties: {
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 180,
          },
          columnId: {
            type: 'string',
            maxLength: 80,
          },
          description: {
            type: 'string',
            maxLength: 2000,
          },
          label: {
            type: 'string',
            maxLength: 40,
          },
          assigneeLabel: {
            type: 'string',
            minLength: 1,
            maxLength: 80,
          },
          reason: {
            type: 'string',
            maxLength: 1000,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.move',
      title: 'Move card',
      description: 'Move a card to another column.',
      path: '/api/shadow/commands/cards.move',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId', 'columnId'],
        properties: {
          cardId: {
            type: 'string',
            minLength: 1,
          },
          columnId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.assign',
      title: 'Assign card',
      description:
        'Assign a person or Buddy to a task card. Omit assignee to assign the calling actor with profile and avatar.',
      path: '/api/shadow/commands/cards.assign',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          cardId: {
            type: 'string',
            minLength: 1,
          },
          assignee: {
            type: 'string',
            minLength: 1,
            maxLength: 80,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.comment',
      title: 'Comment on card',
      description:
        'Add a short update comment to a task card. A comment that mentions @Strategy Buddy emits an Inbox task card.',
      path: '/api/shadow/commands/cards.comment',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId', 'body'],
        properties: {
          cardId: {
            type: 'string',
            minLength: 1,
          },
          body: {
            type: 'string',
            minLength: 1,
            maxLength: 1000,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.dispatch',
      title: 'Dispatch card to Buddy',
      description:
        'Assign a Kanban card to a Buddy and emit a Shadow Inbox task card for the Buddy runtime.',
      path: '/api/shadow/commands/cards.dispatch',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          cardId: {
            type: 'string',
            minLength: 1,
          },
          assigneeLabel: {
            type: 'string',
            minLength: 1,
            maxLength: 80,
          },
          reason: {
            type: 'string',
            maxLength: 1000,
          },
        },
        additionalProperties: false,
      },
    },
  ],
  events: ['board.updated'],
} as const satisfies ShadowServerAppManifest

export type ShadowServerAppManifestDefinition = typeof shadowServerAppManifest
