// Generated by shadow-server-app typegen from ../shadow-app.local.json.
// Do not edit by hand. Update the JSON manifest and regenerate this file.
import type { ShadowServerAppManifest } from '@shadowob/sdk'

export const shadowServerAppManifest = {
  schemaVersion: 'shadow.app/1',
  appKey: 'kanban',
  name: 'Kanban',
  description:
    'A Trello-style Kanban workspace where teams and Buddies manage cards, lists, labels, dates, checklists, members, comments, and artifact references.',
  version: '1.0.0',
  iconUrl: 'http://localhost:4201/assets/icon.svg',
  marketplace: {
    tagline: 'A generic Kanban board for people and Buddies.',
    summary:
      'Kanban is a Trello-style task board for people and Buddies. Coordinators can create cards, organize them by list, add labels, dates, checklists, comments, and attach workspace artifacts without hardcoding a business domain.',
    categories: ['Collaboration', 'Productivity', 'Project Management'],
    supportedLanguages: ['English', '中文'],
    coverImageUrl: 'http://localhost:4201/assets/cover.png',
    gallery: [
      {
        url: 'http://localhost:4201/assets/cover.png',
        type: 'image',
        alt: 'Kanban cover',
      },
    ],
    links: [
      {
        label: 'Home',
        url: 'http://localhost:4201/shadow/server',
        type: 'website',
      },
    ],
    publisher: {
      name: 'Shadow',
    },
  },
  iframe: {
    entry: 'http://localhost:4201/shadow/server',
    allowedOrigins: ['http://localhost:4201'],
  },
  api: {
    baseUrl: 'http://host.lima.internal:4201',
    auth: {
      type: 'oauth2-bearer',
    },
  },
  access: {
    defaultPermissions: ['kanban.boards:read'],
    defaultApprovalMode: 'none',
  },
  commands: [
    {
      name: 'boards.get',
      title: 'Open board',
      description: 'Read the current task board with columns, cards, assignees, and comments.',
      path: '/api/shadow/commands/boards.get',
      permission: 'kanban.boards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'boards.list',
      title: 'List boards',
      description: 'List Kanban boards in the current Shadow server project.',
      path: '/api/shadow/commands/boards.list',
      permission: 'kanban.boards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'boards.create',
      title: 'Create board',
      description: 'Create a Kanban board inside the current Shadow server project.',
      path: '/api/shadow/commands/boards.create',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['title'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description:
              'Optional Kanban board id within the project. Generated from title when omitted.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'boards.update',
      title: 'Rename board',
      description: 'Rename a Kanban board in the current Shadow server project.',
      path: '/api/shadow/commands/boards.update',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['title'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Kanban board id within the project. Defaults to the current board.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'boards.delete',
      title: 'Delete board',
      description:
        'Delete a Kanban board in the current Shadow server project and return the next board.',
      path: '/api/shadow/commands/boards.delete',
      permission: 'kanban.cards:write',
      action: 'delete',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Kanban board id within the project. Defaults to the current board.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'columns.create',
      title: 'Create list',
      description: 'Create a board column/list in the current Kanban board.',
      path: '/api/shadow/commands/columns.create',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['title'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          columnId: {
            description: 'Optional stable column id. Generated from title when omitted.',
            type: 'string',
            minLength: 1,
            maxLength: 80,
          },
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 80,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'columns.delete',
      title: 'Delete list',
      description: 'Delete a board column/list and its cards from the current Kanban board.',
      path: '/api/shadow/commands/columns.delete',
      permission: 'kanban.cards:write',
      action: 'delete',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['columnId'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          columnId: {
            description: 'Column/list id to delete.',
            type: 'string',
            minLength: 1,
            maxLength: 80,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.get',
      title: 'Open card detail',
      description: 'Read a single task card with assignees, description, and comments.',
      path: '/api/shadow/commands/cards.get',
      permission: 'kanban.boards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.create',
      title: 'Create card',
      description:
        'Create a new Trello-style card in a board list. The calling actor is captured as creator and default member.',
      path: '/api/shadow/commands/cards.create',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['title'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 180,
          },
          columnId: {
            type: 'string',
            maxLength: 80,
          },
          column: {
            type: 'string',
            maxLength: 80,
          },
          description: {
            type: 'string',
            maxLength: 2000,
          },
          prompt: {
            type: 'string',
            maxLength: 4000,
          },
          label: {
            type: 'string',
            maxLength: 40,
          },
          labels: {
            type: 'array',
            maxItems: 8,
            items: {
              type: 'string',
              minLength: 1,
              maxLength: 40,
            },
          },
          labelIds: {
            type: 'array',
            maxItems: 8,
            items: {
              type: 'string',
              minLength: 1,
              maxLength: 80,
            },
          },
          startDate: {
            type: 'string',
            maxLength: 80,
          },
          dueDate: {
            type: 'string',
            maxLength: 80,
          },
          dueComplete: {
            type: 'boolean',
          },
          checklists: {
            type: 'array',
            maxItems: 10,
          },
          assignee: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.delete',
      title: 'Delete card',
      description: 'Delete a task card and clear related links and artifact references.',
      path: '/api/shadow/commands/cards.delete',
      permission: 'kanban.cards:write',
      action: 'delete',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.update',
      title: 'Update card',
      description:
        'Update card fields such as title, description, labels, dates, checklists, members, or list.',
      path: '/api/shadow/commands/cards.update',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 180,
          },
          columnId: {
            type: 'string',
            maxLength: 80,
          },
          column: {
            type: 'string',
            maxLength: 80,
          },
          description: {
            type: 'string',
            maxLength: 2000,
          },
          prompt: {
            type: 'string',
            maxLength: 4000,
          },
          labels: {
            type: 'array',
            maxItems: 8,
            items: {
              type: 'string',
              minLength: 1,
              maxLength: 40,
            },
          },
          labelIds: {
            type: 'array',
            maxItems: 8,
            items: {
              type: 'string',
              minLength: 1,
              maxLength: 80,
            },
          },
          startDate: {
            type: 'string',
            maxLength: 80,
          },
          dueDate: {
            type: 'string',
            maxLength: 80,
          },
          dueComplete: {
            type: 'boolean',
          },
          checklists: {
            type: 'array',
            maxItems: 10,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.move',
      title: 'Move card',
      description: 'Move a card to another column.',
      path: '/api/shadow/commands/cards.move',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId', 'columnId'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
          columnId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.assign',
      title: 'Assign card',
      description:
        'Assign a person or Buddy to a task card. Omit assignee to assign the calling actor with profile and avatar.',
      path: '/api/shadow/commands/cards.assign',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
          assignee: {
            type: 'string',
            minLength: 1,
            maxLength: 80,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.dispatch',
      title: 'Dispatch card to Buddy Inbox',
      description:
        'Assign a generic task card to a Buddy and enqueue the card context as a Buddy Inbox task. Domain execution remains with the target Buddy.',
      path: '/api/shadow/commands/cards.dispatch',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId', 'agentId'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
          agentId: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          agentUserId: {
            type: 'string',
            maxLength: 120,
          },
          assigneeLabel: {
            type: 'string',
            maxLength: 120,
          },
          assigneeAvatarUrl: {
            type: 'string',
            maxLength: 1000,
          },
          title: {
            type: 'string',
            maxLength: 180,
          },
          body: {
            type: 'string',
            maxLength: 8000,
          },
          priority: {
            enum: ['low', 'normal', 'medium', 'high'],
          },
          tags: {
            type: 'array',
            maxItems: 12,
            items: {
              oneOf: [
                {
                  type: 'string',
                  minLength: 1,
                  maxLength: 48,
                },
                {
                  type: 'object',
                  required: ['label'],
                  properties: {
                    id: {
                      type: 'string',
                      maxLength: 80,
                    },
                    label: {
                      type: 'string',
                      minLength: 1,
                      maxLength: 48,
                    },
                    color: {
                      type: 'string',
                      maxLength: 40,
                    },
                  },
                  additionalProperties: false,
                },
              ],
            },
          },
          idempotencyKey: {
            type: 'string',
            maxLength: 240,
          },
          requirements: {
            oneOf: [
              {
                type: 'object',
              },
              {
                type: 'null',
              },
            ],
          },
          outputContract: {
            oneOf: [
              {
                type: 'object',
              },
              {
                type: 'null',
              },
            ],
          },
          privacy: {
            oneOf: [
              {
                type: 'object',
              },
              {
                type: 'null',
              },
            ],
          },
          data: {
            oneOf: [
              {
                type: 'object',
              },
              {
                type: 'null',
              },
            ],
          },
          kanbanCardRef: {
            description:
              'Optional external task-card reference kept by callers; Kanban uses cardId as source of truth.',
            oneOf: [
              {
                type: 'object',
              },
              {
                type: 'string',
              },
              {
                type: 'null',
              },
            ],
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.comment',
      title: 'Comment on card',
      description: 'Add an update comment to a task card.',
      path: '/api/shadow/commands/cards.comment',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId', 'body'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
          body: {
            type: 'string',
            minLength: 1,
            maxLength: 4000,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.comments.delete',
      title: 'Delete card comment',
      description: 'Delete one comment from a task card and remove its matching activity entry.',
      path: '/api/shadow/commands/cards.comments.delete',
      permission: 'kanban.cards:write',
      action: 'delete',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId', 'commentId'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
          commentId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.complete',
      title: 'Complete card',
      description:
        'Atomically mark a card complete after Kanban validates dependencies and required workspace artifact contracts, then append an optional completion summary.',
      path: '/api/shadow/commands/cards.complete',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
          summary: {
            type: 'string',
            maxLength: 4000,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.link',
      title: 'Link cards',
      description:
        'Create a typed relationship between two cards, such as dependency, parent-child, duplicate, or related.',
      path: '/api/shadow/commands/cards.link',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['sourceCardId', 'targetCardId'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          sourceCardId: {
            type: 'string',
            minLength: 1,
          },
          targetCardId: {
            type: 'string',
            minLength: 1,
          },
          kind: {
            type: 'string',
            maxLength: 80,
          },
          label: {
            type: 'string',
            maxLength: 120,
          },
          metadata: {
            type: 'object',
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.rerun',
      title: 'Rerun card',
      description: 'Reopen a card and optionally override the prompt kept on that card.',
      path: '/api/shadow/commands/cards.rerun',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
          prompt: {
            type: 'string',
            maxLength: 4000,
          },
          reason: {
            type: 'string',
            maxLength: 1000,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.artifacts.add',
      title: 'Add card artifacts',
      description: 'Attach workspace artifact references to a card.',
      path: '/api/shadow/commands/cards.artifacts.add',
      permission: 'kanban.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId', 'artifacts'],
        properties: {
          projectId: {
            description:
              'Optional Kanban project id within the current Shadow server. Defaults to default.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          boardId: {
            description: 'Optional Kanban board id within the project. Defaults to kanban.',
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
          kind: {
            type: 'string',
            maxLength: 120,
          },
          title: {
            type: 'string',
            maxLength: 180,
          },
          name: {
            type: 'string',
            maxLength: 180,
          },
          url: {
            type: 'string',
            maxLength: 1000,
          },
          path: {
            type: 'string',
            maxLength: 1000,
          },
          mimeType: {
            type: 'string',
            maxLength: 120,
          },
          sizeBytes: {
            type: 'number',
          },
          summary: {
            type: 'string',
            maxLength: 1000,
          },
          description: {
            type: 'string',
            maxLength: 1000,
          },
          metadata: {
            type: 'object',
          },
          artifacts: {
            type: 'array',
            minItems: 1,
            maxItems: 12,
            items: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                  maxLength: 240,
                },
                workspaceFileId: {
                  type: 'string',
                  maxLength: 240,
                },
                workspaceNodeId: {
                  type: 'string',
                  maxLength: 240,
                },
                kind: {
                  type: 'string',
                  maxLength: 120,
                },
                title: {
                  type: 'string',
                  maxLength: 180,
                },
                name: {
                  type: 'string',
                  maxLength: 180,
                },
                url: {
                  type: 'string',
                  maxLength: 1000,
                },
                path: {
                  type: 'string',
                  maxLength: 1000,
                },
                mimeType: {
                  type: 'string',
                  maxLength: 120,
                },
                sizeBytes: {
                  type: 'number',
                },
                summary: {
                  type: 'string',
                  maxLength: 1000,
                },
                description: {
                  type: 'string',
                  maxLength: 1000,
                },
                metadata: {
                  type: 'object',
                },
              },
              additionalProperties: false,
            },
          },
        },
        additionalProperties: false,
      },
    },
  ],
  events: ['board.updated'],
  i18n: {
    'zh-CN': {
      name: '看板',
      description:
        '通用任务看板，用于成员和 Buddy 管理列表、卡片、标签、日期、清单、链接和 artifact 引用。',
      marketplace: {
        tagline: '面向成员和 Buddy 协作的通用看板。',
        summary:
          '看板提供 Trello 风格的任务卡片、列表位置、标签、日期、清单、artifact 引用和协作记录。协调者可以创建卡片、分配给成员或 Buddy，并保持流程可追踪，而不固化具体业务场景。',
        categories: ['协作', '效率', '项目管理'],
        gallery: [
          {
            alt: '看板封面',
          },
        ],
        links: [
          {
            label: '主页',
          },
        ],
      },
    },
  },
} as const satisfies ShadowServerAppManifest

export type ShadowServerAppManifestDefinition = typeof shadowServerAppManifest
