// ═══════════════════════════════════════════════════════════════
// Curate Handler — Materials → Cards
//
// Core principle: file write is the source of truth!
// AI writes cards to file via OpenClaw write tool →
// server detects file via file-watcher → immediately pushes to frontend
//
// v8: AI writes to /data/projects/{pid}/ai-output/curate-{ts}.json
// ═══════════════════════════════════════════════════════════════

import { writeFile } from 'node:fs/promises'
import type { ServerResponse } from 'node:http'
import { ensureProjectDirs, projectAiOutput, projectLogs } from '../../config.js'
import { watchForJsonArray } from '../../lib/file-watcher.js'
import { buildCardContext, buildMaterialContext } from '../../lib/helpers.js'
import { callOpenClawStream } from '../../lib/openclaw.js'
import { createNodeSSEWriter, finishSSE } from '../../lib/sse.js'
import { cardService } from '../../service/card.service.js'

/**
 * Per-kind field list — these fields are placed at the card top level in SKILL.md v4
 * and need to be moved into meta for frontend consumption.
 */
const KIND_FIELDS: Record<string, string[]> = {
  data: ['metrics', 'period', 'benchmark', 'highlight', 'visualHint'],
  chart: [
    'chartType',
    'categories',
    'series',
    'unit',
    'xAxisLabel',
    'yAxisLabel',
    'dataSource',
    'insight',
  ],
  table: ['columns', 'rows', 'sortBy', 'sortDirection', 'highlightRow', 'caption'],
  quote: ['text', 'author', 'role', 'source', 'language', 'emphasis'],
  argument: ['claim', 'evidence', 'counterpoint', 'strength', 'logicType'],
  keypoint: ['points', 'context', 'layout'],
  definition: [
    'term',
    'abbreviation',
    'fullName',
    'definition',
    'category',
    'relatedTerms',
    'example',
    'formula',
  ],
  example: ['subject', 'scenario', 'challenge', 'approach', 'results', 'takeaway', 'industry'],
  code: ['language', 'code', 'filename', 'highlight', 'description'],
  image: ['description', 'filePath', 'altText', 'dimensions', 'contentType', 'labels'],
  timeline: ['events', 'span', 'direction'],
  comparison: ['subjects', 'dimensions', 'conclusion', 'visualHint'],
  process: ['steps', 'isLinear', 'visualHint'],
  reference: ['refTitle', 'authors', 'publishDate', 'url', 'refType', 'credibility', 'citedIn'],
  summary: ['body'],
  idea: ['body'],
}

/** Fill in required card fields with defaults + move AI top-level structured fields into meta */
function enrichCards(cards: Record<string, unknown>[]): Record<string, unknown>[] {
  return cards.map((c) => {
    const kind = (c.kind as string) || 'text'
    const fields = KIND_FIELDS[kind] || []

    // Collect this kind's structured fields into meta
    const existingMeta = (c.meta as Record<string, unknown>) || {}
    const structuredMeta: Record<string, unknown> = { ...existingMeta }
    for (const field of fields) {
      if (c[field] !== undefined && structuredMeta[field] === undefined) {
        structuredMeta[field] = c[field]
      }
    }

    // Generate content fallback (if AI did not provide content)
    let content = c.content as string | undefined
    if (!content) {
      content = generateContentFallback(kind, c, structuredMeta)
    }

    return {
      ...c,
      content,
      meta: structuredMeta,
      autoGenerated: true,
      rating: (c.rating as number) || 0,
      deckIds: (c.deckIds as string[]) || [],
      linkedCardIds: (c.linkedCardIds as string[]) || [],
      tags: (c.tags as string[]) || [],
      priority: (c.priority as string) || 'medium',
      createdAt: Date.now(),
      updatedAt: Date.now(),
    }
  })
}

/** Generate plain-text content fallback from structured data — for full-text search and LLM context */
function generateContentFallback(
  kind: string,
  c: Record<string, unknown>,
  meta: Record<string, unknown>,
): string {
  switch (kind) {
    case 'data': {
      const metrics = (meta.metrics || c.metrics) as
        | { key: string; value: string | number; unit?: string }[]
        | undefined
      return (
        metrics?.map((m) => `${m.key}: ${m.value}${m.unit || ''}`).join('; ') ||
        (c.summary as string) ||
        ''
      )
    }
    case 'quote':
      return ((meta.text || c.text) as string) || ''
    case 'argument':
      return ((meta.claim || c.claim) as string) || ''
    case 'summary':
    case 'idea':
    case 'inspiration':
      return ((meta.body || c.body) as string) || ''
    case 'definition':
      return `${((meta.term || c.term) as string) || ''}: ${((meta.definition || c.definition) as string) || ''}`
    case 'example':
      return ((meta.takeaway || c.takeaway || meta.scenario || c.scenario) as string) || ''
    case 'keypoint': {
      const points = (meta.points || c.points) as { label: string; detail?: string }[] | undefined
      return points?.map((p) => `${p.label}: ${p.detail || ''}`).join('; ') || ''
    }
    case 'chart':
      return ((meta.insight || c.insight) as string) || (c.summary as string) || ''
    case 'code':
      return ((meta.description || c.description || meta.code || c.code) as string) || ''
    default:
      return (c.summary as string) || ''
  }
}

/** Push card data to frontend */
function pushCardsToClient(
  cards: Record<string, unknown>[],
  writer: ReturnType<typeof createNodeSSEWriter>,
  pid: string,
  materials: Array<{ id: string }>,
) {
  const enriched = enrichCards(cards)
  writer.write(`data: ${JSON.stringify({ type: 'cards', data: JSON.stringify(enriched) })}\n\n`)
  cardService.saveBulk(enriched, pid)
  for (const mat of materials) {
    writer.write(
      `data: ${JSON.stringify({ type: 'material_curated', data: JSON.stringify({ materialId: mat.id }) })}\n\n`,
    )
  }
  console.log(`[Curate] ✅ Pushed ${enriched.length} cards to frontend`)
}

export async function handleCurate(
  body: Record<string, unknown>,
  res: ServerResponse,
): Promise<void> {
  const { projectId, materials, existingCards, decks: deckList } = body

  console.log(
    `[Curate] ▶ handleCurate called: projectId=${projectId}, materials=${(materials as [])?.length || 0}, existingCards=${(existingCards as [])?.length || 0}`,
  )

  const writer = createNodeSSEWriter(res)
  const sessionKey = `sf-curate-${projectId}`
  const pid = (projectId as string) || 'default'

  ensureProjectDirs(pid)

  const materialContext = await buildMaterialContext((materials as []) || [], pid)
  const cardContext = buildCardContext((existingCards as []) || [])
  const materialIds = ((materials as Array<{ id: string; name: string; type: string }>) || [])
    .map((m) => `${m.id}: ${m.name} (${m.type})`)
    .join('\n')

  const deckContext = (deckList as Array<{ id: string; title: string; description?: string }>)
    ?.length
    ? `\n\n## Current Decks\n${(
        deckList as Array<{ id: string; title: string; description?: string }>
      )
        .map((d) => `- [${d.id}] ${d.title}: ${d.description || 'No description'}`)
        .join('\n')}`
    : ''

  // v8: AI outputs to project ai-output directory
  const cardFilePath = projectAiOutput(pid, `curate-${Date.now()}.json`)

  const matList = (materials as Array<{ id: string }>) || []

  // ── Prompt: explicitly instruct AI to write file using write tool ──
  const messages = [
    {
      role: 'user',
      content: `[skill: curate]\n\nPlease analyze the following materials and extract knowledge cards following the curate skill rules.\n\n**You must use the write tool to write the card JSON array to file: \`${cardFilePath}\`**\n\n## Material Content\n\n${materialContext}\n\n## Material ID Mapping\n\n${materialIds}\n${cardContext}${deckContext}`,
    },
  ]

  // ── Start in parallel: LLM stream + file watcher ──
  let cardsPushed = false

  // File watcher: triggers immediately when AI writes the file
  const fileWatchPromise = watchForJsonArray<Record<string, unknown>>(
    cardFilePath,
    (item: unknown) => {
      const obj = item as Record<string, unknown>
      return typeof obj === 'object' && obj !== null && 'kind' in obj && 'title' in obj
    },
    {
      debounceMs: 300,
      timeoutMs: 300_000, // 5-minute timeout (aligned with LLM timeout)
      pollIntervalMs: 2000,
      minFileSize: 10,
    },
  )
    .then((result) => {
      if (!cardsPushed && result.data.length > 0) {
        cardsPushed = true
        console.log(
          `[Curate] 📂 File watcher triggered (${result.source}), detected ${result.data.length} cards after ${result.elapsedMs}ms`,
        )
        pushCardsToClient(result.data, writer, pid, matList)
      }
    })
    .catch((err) => {
      // File watcher failure is non-fatal (LLM stream may have already ended and handled it)
      if (!cardsPushed) {
        console.warn(
          `[Curate] File watcher failed to capture:`,
          err instanceof Error ? err.message : err,
        )
      }
    })

  // LLM stream: simultaneously stream thinking events to frontend
  console.log(`[Curate] 🔗 Calling OpenClaw stream: sessionKey=${sessionKey}`)
  const fullContent = await callOpenClawStream(messages, sessionKey, writer)
  console.log(`[Curate] 📝 OpenClaw stream done. fullContent length: ${fullContent?.length || 0}`)

  // ── Fallback check after LLM stream ends ──
  if (!cardsPushed && fullContent) {
    // Wait up to 3 seconds for file watcher
    await Promise.race([fileWatchPromise, new Promise((resolve) => setTimeout(resolve, 3000))])
  }

  // ── Fallback: parse JSON array from AI response (AI may not have used write tool) ──
  if (!cardsPushed && fullContent) {
    console.log(
      `[Curate] ⚠️ File watcher did not capture cards, attempting to parse from AI response...`,
    )
    try {
      // Try matching ```json ... ``` code block
      const jsonMatch = fullContent.match(/```(?:json)?\s*([\s\S]*?)```/)
      const jsonStr = jsonMatch ? jsonMatch[1].trim() : fullContent.trim()
      // Try to find JSON array
      const arrayMatch = jsonStr.match(/\[[\s\S]*\]/)
      if (arrayMatch) {
        const parsed = JSON.parse(arrayMatch[0])
        if (Array.isArray(parsed) && parsed.length > 0 && parsed[0].kind && parsed[0].title) {
          cardsPushed = true
          console.log(`[Curate] ✅ Fallback parse succeeded: ${parsed.length} cards`)
          pushCardsToClient(parsed, writer, pid, matList)
          // Also write parsed result to file for records
          await writeFile(cardFilePath, JSON.stringify(parsed, null, 2), 'utf-8')
        }
      }
    } catch (parseErr) {
      console.warn(
        `[Curate] Fallback parse failed:`,
        parseErr instanceof Error ? parseErr.message : parseErr,
      )
    }
  }

  // If neither file watcher nor stream parsing pushed cards, report error
  if (!cardsPushed) {
    console.error(
      `[Curate] ❌ AI did not write valid card file. fullContent length: ${fullContent?.length || 0}`,
    )
    writer.write(
      `data: ${JSON.stringify({
        type: 'error',
        data: 'AI failed to extract cards. Please retry.',
      })}\n\n`,
    )
  }

  // Save raw response log
  if (fullContent) {
    await writeFile(
      projectLogs(pid, 'curate-response.md'),
      `<!-- pushed: ${cardsPushed}, file: ${cardFilePath} -->\n\n${fullContent}`,
      'utf-8',
    )
  }

  finishSSE(writer, res)
}
