// ═══════════════════════════════════════════════════════════════
// Inspire Handler — AI generates inspiration cards
//
// Core principle: file write is the source of truth!
// AI writes inspiration cards to file via OpenClaw write tool →
// server detects file via file-watcher → immediately pushes to frontend
//
// v8: AI writes to /data/projects/{pid}/ai-output/inspire-{ts}.json
// ═══════════════════════════════════════════════════════════════

import type { ServerResponse } from 'node:http'
import { ensureProjectDirs, projectAiOutput } from '../../config.js'
import { watchForJsonArray } from '../../lib/file-watcher.js'
import { buildCardContext, buildMaterialContext } from '../../lib/helpers.js'
import { callOpenClawStream } from '../../lib/openclaw.js'
import { createNodeSSEWriter, finishSSE } from '../../lib/sse.js'
import { cardService } from '../../service/card.service.js'

/** Fill in required inspiration card fields + move top-level structured fields into meta */
function enrichInspireCards(cards: Record<string, unknown>[]): Record<string, unknown>[] {
  // inspire skill may output kinds: inspiration/idea/summary etc.
  const INSPIRE_FIELDS: Record<string, string[]> = {
    inspiration: ['body', 'ideaType', 'impact', 'difficulty'],
    idea: ['body'],
    summary: ['body'],
    argument: ['claim', 'evidence', 'counterpoint', 'strength', 'logicType'],
    data: ['metrics', 'period', 'benchmark', 'highlight', 'visualHint'],
    keypoint: ['points', 'context', 'layout'],
  }

  return cards.map((c) => {
    const kind = (c.kind as string) || 'inspiration'
    const fields = INSPIRE_FIELDS[kind] || INSPIRE_FIELDS['inspiration'] || []

    const existingMeta = (c.meta as Record<string, unknown>) || {}
    const structuredMeta: Record<string, unknown> = { ...existingMeta }
    for (const field of fields) {
      if (c[field] !== undefined && structuredMeta[field] === undefined) {
        structuredMeta[field] = c[field]
      }
    }

    return {
      ...c,
      kind,
      autoGenerated: true,
      rating: (c.rating as number) || 3,
      deckIds: (c.deckIds as string[]) || [],
      linkedCardIds: (c.linkedCardIds as string[]) || [],
      tags: (c.tags as string[]) || [],
      priority: (c.priority as string) || 'medium',
      meta: structuredMeta,
      sourceId: (c.sourceId as string) || null,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    }
  })
}

export async function handleInspire(
  body: Record<string, unknown>,
  res: ServerResponse,
): Promise<void> {
  const { projectId, materials, cards, outline, todos } = body

  const writer = createNodeSSEWriter(res)
  const pid = (projectId as string) || 'default'
  const sessionKey = `sf-inspire-${pid}`

  ensureProjectDirs(pid)

  const materialContext = await buildMaterialContext((materials as []) || [], pid)
  const cardContext = buildCardContext((cards as []) || [])

  const outlineContext =
    ((outline as Array<{ title: string; type: string; keyPoints?: string[] }>) || []).length > 0
      ? `\n\n## Current Outline\n${(
          (outline as Array<{ title: string; type: string; keyPoints?: string[] }>) || []
        )
          .map(
            (o, i) =>
              `- Slide ${i + 1}: ${o.title} [${o.type}] — ${(o.keyPoints || []).join(', ')}`,
          )
          .join('\n')}`
      : ''

  const todoContext =
    ((todos as Array<{ done: boolean; text: string }>) || []).length > 0
      ? `\n\n## Current Requirements\n${((todos as Array<{ done: boolean; text: string }>) || [])
          .map((t) => `- [${t.done ? '✅' : '⬜'}] ${t.text}`)
          .join('\n')}`
      : ''

  // v8: AI outputs to project ai-output directory
  const cardFilePath = projectAiOutput(pid, `inspire-${Date.now()}.json`)

  // ── Prompt: explicitly instruct AI to write file using write tool ──
  const messages = [
    {
      role: 'user',
      content: `[skill: inspire]\n\nPlease provide inspiration suggestions following the inspire skill rules.\n\n**You must use the write tool to write the inspiration card array to file: \`${cardFilePath}\`**\n\n## Current Materials\n${materialContext || 'No materials'}\n${cardContext || 'No cards'}${outlineContext}${todoContext}`,
    },
  ]

  // ── Start in parallel: LLM stream + file watcher ──
  let cardsPushed = false

  // File watcher
  const fileWatchPromise = watchForJsonArray<Record<string, unknown>>(
    cardFilePath,
    (item: unknown) => {
      const obj = item as Record<string, unknown>
      return typeof obj === 'object' && obj !== null && 'title' in obj
    },
    {
      debounceMs: 300,
      timeoutMs: 300_000,
      pollIntervalMs: 2000,
      minFileSize: 10,
    },
  )
    .then((result) => {
      if (!cardsPushed && result.data.length > 0) {
        cardsPushed = true
        const enriched = enrichInspireCards(result.data)
        console.log(
          `[Inspire] 📂 File watcher triggered (${result.source}), detected ${enriched.length} inspiration cards after ${result.elapsedMs}ms`,
        )
        writer.write(
          `data: ${JSON.stringify({ type: 'cards', data: JSON.stringify(enriched) })}\n\n`,
        )
        cardService.saveBulk(enriched, pid)
      }
    })
    .catch((err) => {
      if (!cardsPushed) {
        console.warn(
          `[Inspire] File watcher failed to capture:`,
          err instanceof Error ? err.message : err,
        )
      }
    })

  // LLM stream
  const fullContent = await callOpenClawStream(messages, sessionKey, writer)

  // ── Fallback check after LLM stream ends ──
  if (!cardsPushed && fullContent) {
    await Promise.race([fileWatchPromise, new Promise((resolve) => setTimeout(resolve, 3000))])
  }

  if (!cardsPushed) {
    console.error(
      `[Inspire] ❌ AI did not write valid inspiration card file. fullContent length: ${fullContent?.length || 0}`,
    )
    writer.write(
      `data: ${JSON.stringify({
        type: 'error',
        data: 'AI failed to write inspiration cards to the specified file. Please retry.',
      })}\n\n`,
    )
  }

  finishSSE(writer, res)
}
