import { mkdir, stat, writeFile } from 'node:fs/promises'
import { createRequire } from 'node:module'
import { dirname, relative, resolve } from 'node:path'

export interface GenerateSpaceAppScaffoldOptions {
  appKey: string
  directory?: string
  name?: string
  description?: string
  port?: number
  force?: boolean
}

export interface GenerateSpaceAppScaffoldResult {
  directory: string
  files: string[]
}

interface ScaffoldContext {
  appKey: string
  appName: string
  description: string
  port: number
  updatedAt: string
  envPrefix: string
  permissionPrefix: string
}

const APP_KEY_PATTERN = /^[a-z][a-z0-9-]{1,62}[a-z0-9]$/
const require = createRequire(import.meta.url)

function shadowSdkPackageSpec() {
  try {
    const pkg = require('../../package.json') as { version?: string }
    return pkg.version ? `^${pkg.version}` : 'latest'
  } catch {
    return 'latest'
  }
}

function titleCaseAppKey(appKey: string) {
  return appKey
    .split('-')
    .filter(Boolean)
    .map((part) => `${part.slice(0, 1).toUpperCase()}${part.slice(1)}`)
    .join(' ')
}

function envPrefix(appKey: string) {
  return appKey.replace(/[^a-zA-Z0-9]+/g, '_').toUpperCase()
}

function assertAppKey(appKey: string) {
  if (!APP_KEY_PATTERN.test(appKey)) {
    throw new Error(
      'Space App key must be 3-64 lowercase letters, numbers, and hyphens; start with a letter and end with a letter or number.',
    )
  }
}

function manifest(context: ScaffoldContext) {
  const baseUrl = `http://localhost:${context.port}`
  return {
    schemaVersion: 'shadow.space-app/1',
    appKey: context.appKey,
    name: context.appName,
    description: context.description,
    version: '0.1.0',
    updatedAt: context.updatedAt,
    iconUrl: `${baseUrl}/assets/icon.svg`,
    iframe: {
      entry: `${baseUrl}/shadow/server`,
      allowedOrigins: [baseUrl],
    },
    api: {
      baseUrl,
      auth: {
        type: 'oauth2-bearer',
      },
    },
    access: {
      defaultPermissions: [`${context.permissionPrefix}.status:read`],
      defaultApprovalMode: 'none',
    },
    commands: [
      {
        name: 'status.get',
        title: 'Get status',
        description: 'Return a minimal status payload for validating the app runtime.',
        ingress: {
          path: '/.shadow/commands/status.get',
          auth: 'shadow-command-jwt',
        },
        permission: `${context.permissionPrefix}.status:read`,
        action: 'read',
        dataClass: 'server-private',
        inputSchema: {
          type: 'object',
          properties: {},
          additionalProperties: false,
        },
      },
    ],
    skills: [
      {
        name: 'Runtime validation',
        description:
          'Use the status.get command to verify that the app is installed, reachable, and authorized before adding domain-specific commands.',
        commandHints: ['status.get'],
      },
    ],
  }
}

function packageJson(context: ScaffoldContext) {
  return `${JSON.stringify(
    {
      name: `shadow-space-app-${context.appKey}`,
      version: '0.1.0',
      private: true,
      type: 'module',
      scripts: {
        typegen: 'shadow-space-app typegen space-app.local.json src/space-app.generated.ts',
        dev: 'pnpm build && node --watch dist/server.js',
        build: 'pnpm typegen && tsc',
        check: 'pnpm build',
        start: 'node dist/server.js',
        'start:background':
          "sh -c 'nohup node dist/server.js > .space-app.log 2>&1 & echo $! > .space-app.pid && cat .space-app.pid'",
      },
      dependencies: {
        '@hono/node-server': '^1.19.11',
        '@shadowob/sdk': shadowSdkPackageSpec(),
        dotenv: '^17.4.2',
        hono: '^4.12.25',
      },
      devDependencies: {
        '@types/node': '^22.15.21',
        typescript: '^5.9.3',
      },
    },
    null,
    2,
  )}\n`
}

function tsconfigJson() {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        module: 'NodeNext',
        moduleResolution: 'NodeNext',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        outDir: 'dist',
        rootDir: 'src',
      },
      include: ['src/**/*.ts'],
    },
    null,
    2,
  )}\n`
}

function pnpmWorkspaceYaml() {
  return `packages: []\n`
}

function generatedManifestModule(context: ScaffoldContext) {
  return `// Generated by shadow-space-app typegen from ../space-app.local.json.
// Do not edit by hand. Update the JSON manifest and regenerate this file.
import type { ShadowSpaceAppManifest } from '@shadowob/sdk'

export const shadowSpaceAppManifest = ${JSON.stringify(manifest(context), null, 2)} as const satisfies ShadowSpaceAppManifest

export type ShadowSpaceAppManifestDefinition = typeof shadowSpaceAppManifest
`
}

function manifestModule(context: ScaffoldContext) {
  return `import { defineShadowSpaceApp } from '@shadowob/sdk'
import { shadowSpaceAppManifest } from './space-app.generated.js'

export const shadowSpaceApp = defineShadowSpaceApp(shadowSpaceAppManifest, {
  shadowBaseUrl: process.env.SHADOWOB_SERVER_URL ?? 'http://localhost:3002',
})

export function manifest() {
  const port = Number(process.env.PORT ?? ${context.port})
  return shadowSpaceApp.manifest({
    port,
    publicBaseUrl: process.env.${context.envPrefix}_PUBLIC_BASE_URL ?? process.env.SHADOWOB_APP_PUBLIC_BASE_URL,
    apiBaseUrl: process.env.${context.envPrefix}_API_BASE_URL ?? process.env.SHADOWOB_APP_API_BASE_URL,
  })
}
`
}

function dataModule(context: ScaffoldContext) {
  return `import { resolve } from 'node:path'
import { createShadowSpaceAppJsonStore } from '@shadowob/sdk/space-app/node'

export interface AppState {
  schemaVersion: '${context.appKey}.state/1'
  createdAt: string
  updatedAt: string
}

function now() {
  return new Date().toISOString()
}

const store = createShadowSpaceAppJsonStore<AppState>({
  filePath: resolve(process.env.${context.envPrefix}_DATA_FILE ?? './data/app-state.json'),
  defaultValue: () => {
    const timestamp = now()
    return {
      schemaVersion: '${context.appKey}.state/1',
      createdAt: timestamp,
      updatedAt: timestamp,
    }
  },
})

export function readState() {
  return store.read()
}

export function touchState() {
  return store.update((state) => {
    state.updatedAt = now()
  })
}
`
}

function commandsModule() {
  return `import { shadowSpaceAppActorRef } from '@shadowob/sdk/space-app'
import { touchState } from './data.js'
import { shadowSpaceApp } from './manifest.js'

export const commands = shadowSpaceApp.defineCommands({
  'status.get': async (_input, { context }) => {
    const state = touchState()
    return {
      ok: true,
      appKey: context.appKey,
      serverId: context.serverId,
      actor: shadowSpaceAppActorRef(context),
      state,
    }
  },
})
`
}

function uiModule(context: ScaffoldContext) {
  return `export function renderAppPage() {
  return \`<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${context.appName}</title>
    <style>
      :root {
        color-scheme: light dark;
        font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      }
      body {
        margin: 0;
        min-height: 100vh;
        display: grid;
        place-items: center;
        background: Canvas;
        color: CanvasText;
      }
      main {
        width: min(720px, calc(100vw - 32px));
        border: 1px solid color-mix(in srgb, CanvasText 14%, transparent);
        border-radius: 8px;
        padding: 24px;
      }
      code {
        font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
      }
    </style>
  </head>
  <body>
    <main>
      <h1>${context.appName}</h1>
      <p>The app shell is running. Replace this page with the app experience and keep Shadow protocol routes stable.</p>
      <p><code>status.get</code> is available for installation and authorization checks.</p>
    </main>
  </body>
</html>\`
}
`
}

function serverModule(context: ScaffoldContext) {
  return `import 'dotenv/config'
import { pathToFileURL } from 'node:url'
import { serve } from '@hono/node-server'
import { Hono } from 'hono'
import {
  fetchShadowSpaceAppLaunchInboxes,
  type ShadowSpaceAppCommandName,
} from '@shadowob/sdk'
import { createShadowSpaceAppSessionManager } from '@shadowob/sdk/space-app/node'
import { commands } from './commands.js'
import { readState } from './data.js'
import { manifest, shadowSpaceApp } from './manifest.js'
import { shadowSpaceAppManifest } from './space-app.generated.js'
import { renderAppPage } from './ui.js'

type SpaceAppCommandName = ShadowSpaceAppCommandName<typeof shadowSpaceAppManifest>

export const app = new Hono()
const port = Number(process.env.PORT ?? ${context.port})
const commandNames = new Set<string>(shadowSpaceAppManifest.commands.map((command) => command.name))

function commandName(value: string): SpaceAppCommandName | null {
  return commandNames.has(value) ? (value as SpaceAppCommandName) : null
}

function shadowApiBaseUrl() {
  return (process.env.SHADOWOB_SERVER_URL ?? 'http://localhost:3002').replace(/\\/$/, '')
}

const appSessions = createShadowSpaceAppSessionManager({
  appKey: shadowSpaceAppManifest.appKey,
  shadowApiBaseUrl: shadowApiBaseUrl(),
})

function iconSvg() {
  return \`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96">
  <rect width="96" height="96" rx="22" fill="#0f766e"/>
  <path d="M25 31h46v34H25z" fill="#fff"/>
  <path d="M34 42h28M34 54h18" stroke="#0f766e" stroke-width="6" stroke-linecap="round"/>
</svg>\`
}

function healthPayload() {
  return { ok: true, appKey: ${JSON.stringify(context.appKey)} }
}

app.get('/health', (c) => c.json(healthPayload()))
app.get('/healthz', (c) => c.json(healthPayload()))
app.get('/.well-known/space-app.json', (c) => c.json(manifest()))
app.get('/assets/icon.svg', (c) => c.body(iconSvg(), 200, { 'Content-Type': 'image/svg+xml' }))
app.get('/shadow/server', (c) => c.html(renderAppPage()))
app.get('/api/state', (c) => c.json(readState()))

app.post('/api/shadow/session', async (c) => {
  const result = await appSessions.exchange({
    authorizationHeader: c.req.header('authorization'),
    cookieHeader: c.req.header('cookie'),
    requestUrl: c.req.url,
  })
  if (result.ok) c.header('Set-Cookie', result.setCookie)
  return c.json(result.body, result.status)
})

app.get('/api/shadow/events', async (c) => {
  const response = await appSessions.eventStream({
    cookieHeader: c.req.header('cookie'),
    lastEventId: c.req.header('last-event-id'),
  })
  return response ?? c.json({ ok: false, error: 'session_required' }, 401)
})

app.get('/api/inboxes', async (c) => {
  const session = await appSessions.authorizedSession({
    cookieHeader: c.req.header('cookie'),
    requireCsrf: false,
  })
  if (!session) return c.json({ ok: false, error: 'session_required' }, 401)
  try {
    return c.json(
      await fetchShadowSpaceAppLaunchInboxes({
        launchToken: session.launchToken,
        shadowApiBaseUrl: shadowApiBaseUrl(),
      }),
    )
  } catch (error) {
    return c.json({ ok: false, error: error instanceof Error ? error.message : 'inbox_lookup_failed' }, 502)
  }
})

app.post('/api/commands/:commandName', async (c) => {
  const name = commandName(c.req.param('commandName'))
  if (!name) return c.json({ ok: false, error: 'command_not_found' }, 404)
  let body: { input?: unknown }
  try {
    body = (await c.req.json()) as { input?: unknown }
  } catch {
    return c.json({ ok: false, error: 'invalid_json' }, 400)
  }
  const resolution = await appSessions.commandContext({
    cookieHeader: c.req.header('cookie'),
    csrfToken: c.req.header('X-Shadow-Space-App-CSRF'),
    commandName: name,
    manifest: shadowSpaceAppManifest,
  })
  if (!resolution.context) return c.json({ ok: false, error: resolution.error }, 401)
  const context = resolution.context
  const result = await shadowSpaceApp.executeLocal(name, body.input ?? {}, context, commands)
  return c.json(result.body, result.status as 200)
})

app.post('/.shadow/commands/:commandName', async (c) => {
  const name = commandName(c.req.param('commandName'))
  if (!name) return c.json({ ok: false, error: 'command_not_found' }, 404)
  const result = await shadowSpaceApp.executeCommand(
    name,
    {
      authorizationHeader: c.req.header('authorization'),
      requestBody: await c.req.text(),
    },
    commands,
  )
  return c.json(result.body, result.status as 200)
})

export function startStandalone() {
  serve({ fetch: app.fetch, port })
  console.log(\`${context.appName} listening on http://localhost:\${port}\`)
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  startStandalone()
}
`
}

function dockerfile() {
  return `FROM node:22-bookworm-slim AS deps
WORKDIR /app
COPY package.json pnpm-lock.yaml* ./
RUN corepack enable && pnpm install --prod=false --frozen-lockfile=false

FROM deps AS build
COPY . .
RUN pnpm build && pnpm prune --prod

FROM node:22-bookworm-slim
WORKDIR /app
ENV NODE_ENV=production
RUN mkdir -p /app /app/data && chown -R node:node /app
COPY --from=build --chown=node:node /app/package.json ./
COPY --from=build --chown=node:node /app/node_modules ./node_modules
COPY --from=build --chown=node:node /app/dist ./dist
COPY --from=build --chown=node:node /app/space-app.local.json ./space-app.local.json
USER node
CMD ["node", "dist/server.js"]
`
}

function envExample(context: ScaffoldContext) {
  return `PORT=${context.port}
SHADOWOB_SERVER_URL=http://localhost:3002
${context.envPrefix}_PUBLIC_BASE_URL=http://localhost:${context.port}
${context.envPrefix}_API_BASE_URL=http://localhost:${context.port}
${context.envPrefix}_DATA_FILE=./data/app-state.json
`
}

function readme(context: ScaffoldContext) {
  return `# ${context.appName}

Space App scaffold generated for \`${context.appKey}\`.

## Structure

- \`space-app.local.json\`: source manifest for local development.
- \`src/space-app.generated.ts\`: typed manifest module generated from the JSON manifest.
- \`src/manifest.ts\`: manifest rewriting and public URL configuration.
- \`src/commands.ts\`: command handlers. Add domain commands here.
- \`src/data.ts\`: Space App-owned JSON state store.
- \`src/server.ts\`: HTTP routes for health, manifest, iframe, state, and command execution.
- \`src/ui.ts\`: minimal iframe shell. Replace it with the real Space App UI.

## Develop

\`\`\`bash
pnpm install
cp .env.example .env
pnpm dev
\`\`\`

The scaffold includes a minimal \`pnpm-workspace.yaml\` so it installs as an
independent project even when generated inside another monorepo.


After changing \`space-app.local.json\`, regenerate types:

\`\`\`bash
pnpm typegen
\`\`\`

Validate the manifest through Shadow:

\`\`\`bash
shadowob space-app preview --server <server> --manifest-file space-app.local.json --json
\`\`\`

## Build

\`\`\`bash
pnpm build
pnpm start
\`\`\`

For Cloud runtime publish tasks, keep the service running without blocking the task shell:

\`\`\`bash
PORT=${context.port} pnpm start:background
curl -fsS http://127.0.0.1:${context.port}/health
\`\`\`

Before publishing, replace the scaffold description, add real commands, declare state paths, and choose a backup policy.
`
}

function scaffoldFiles(context: ScaffoldContext): Record<string, string> {
  return {
    'README.md': readme(context),
    'package.json': packageJson(context),
    'pnpm-workspace.yaml': pnpmWorkspaceYaml(),
    'tsconfig.json': tsconfigJson(),
    'space-app.local.json': `${JSON.stringify(manifest(context), null, 2)}\n`,
    '.env.example': envExample(context),
    Dockerfile: dockerfile(),
    'src/space-app.generated.ts': generatedManifestModule(context),
    'src/manifest.ts': manifestModule(context),
    'src/commands.ts': commandsModule(),
    'src/data.ts': dataModule(context),
    'src/ui.ts': uiModule(context),
    'src/server.ts': serverModule(context),
  }
}

async function pathExists(path: string) {
  try {
    await stat(path)
    return true
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return false
    throw error
  }
}

export async function generateSpaceAppScaffold(
  options: GenerateSpaceAppScaffoldOptions,
): Promise<GenerateSpaceAppScaffoldResult> {
  const appKey = options.appKey.trim()
  assertAppKey(appKey)

  const port = options.port ?? 4201
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error('--port must be an integer between 1 and 65535')
  }

  const directory = resolve(options.directory ?? appKey)
  const context: ScaffoldContext = {
    appKey,
    appName: options.name?.trim() || titleCaseAppKey(appKey),
    description:
      options.description?.trim() ||
      'A Space App scaffold. Replace this description before publishing.',
    port,
    updatedAt: new Date().toISOString(),
    envPrefix: envPrefix(appKey),
    permissionPrefix: appKey,
  }
  const files = scaffoldFiles(context)
  const conflicts = []
  for (const relativePath of Object.keys(files)) {
    const target = resolve(directory, relativePath)
    if (await pathExists(target)) conflicts.push(relativePath)
  }
  if (conflicts.length > 0 && !options.force) {
    throw new Error(
      `Refusing to overwrite existing scaffold file(s): ${conflicts.join(', ')}. Pass --force to overwrite.`,
    )
  }

  await mkdir(directory, { recursive: true })
  for (const [relativePath, content] of Object.entries(files)) {
    const target = resolve(directory, relativePath)
    await mkdir(dirname(target), { recursive: true })
    await writeFile(target, content.endsWith('\n') ? content : `${content}\n`)
  }

  return {
    directory,
    files: Object.keys(files).map((file) => relative(process.cwd(), resolve(directory, file))),
  }
}
