/**
 * GitAgent K8s Adapter — generates K8s-specific artifacts from gitagent config.
 *
 * Contains:
 * - buildGitCloneCommand — init container command for git repo cloning
 * - generateGitAgentDockerfile — multi-stage Dockerfile for baking gitagent files
 *
 * Used by the infra layer (infra/index.ts, infra/agent-deployment.ts) and
 * build commands (interfaces/cli/build.command.ts).
 */

/**
 * Standard gitagent files to copy from a cloned repo.
 */
const STANDARD_GITAGENT_FILES = [
  'SOUL.md',
  'RULES.md',
  'AGENTS.md',
  'INSTRUCTIONS.md',
  'agent.yaml',
  'scheduler.yml',
  'scheduler.yaml',
  'skills',
  'tools',
  'hooks',
  'skillflows',
  'memory',
  'knowledge',
  'compliance',
]

/**
 * Generate the init container command for cloning a git repo.
 * Used by the K8s infra layer to add an init container to the agent Deployment.
 */
export function buildGitCloneCommand(opts: {
  url: string
  ref: string
  depth: number
  agentDir?: string
  mountPath: string
  include?: string[]
}): string[] {
  const { url, ref, depth, agentDir, mountPath, include } = opts

  // Build clone command
  const cloneTarget = '/tmp/agent-source'
  const cmds: string[] = []

  // Clone
  cmds.push(`git clone --depth ${depth} --branch "${ref}" "${url}" "${cloneTarget}"`)

  // Determine source directory
  const sourceDir = agentDir ? `${cloneTarget}/${agentDir}` : cloneTarget

  // Create mount path
  cmds.push(`mkdir -p "${mountPath}"`)

  if (include && include.length > 0) {
    // Copy only specified files/dirs
    for (const pattern of include) {
      cmds.push(`cp -r "${sourceDir}/${pattern}" "${mountPath}/" 2>/dev/null || true`)
    }
  } else {
    // Copy standard gitagent files
    for (const f of STANDARD_GITAGENT_FILES) {
      cmds.push(`cp -r "${sourceDir}/${f}" "${mountPath}/" 2>/dev/null || true`)
    }
  }

  return ['/bin/sh', '-c', cmds.join(' && ')]
}

/**
 * Generate a multi-stage Dockerfile for baking gitagent files into an image.
 * Used by the build-image strategy.
 */
export function generateGitAgentDockerfile(opts: {
  baseImage: string
  gitUrl: string
  gitRef: string
  agentDir?: string
  destPath: string
  include?: string[]
}): string {
  const { baseImage, gitUrl, gitRef, agentDir, destPath, include } = opts
  const sourceDir = agentDir ? `/source/${agentDir}` : '/source'

  const copyLines: string[] = []
  if (include && include.length > 0) {
    for (const f of include) {
      copyLines.push(`RUN cp -r ${sourceDir}/${f} ${destPath}/ 2>/dev/null || true`)
    }
  } else {
    for (const f of STANDARD_GITAGENT_FILES) {
      copyLines.push(`RUN cp -r ${sourceDir}/${f} ${destPath}/ 2>/dev/null || true`)
    }
  }

  return `# Auto-generated by shadowob-cloud — DO NOT EDIT
# Bakes gitagent files from ${gitUrl} into the agent image

# ── Stage 1: Clone agent source ──────────────────────────────────
FROM alpine/git AS gitagent-source
ARG GIT_TOKEN=""
RUN if [ -n "$GIT_TOKEN" ]; then \\
      git clone --depth 1 --branch "${gitRef}" "https://$GIT_TOKEN@${gitUrl.replace(/^https?:\/\//, '')}" /source; \\
    else \\
      git clone --depth 1 --branch "${gitRef}" "${gitUrl}" /source; \\
    fi

# ── Stage 2: Runtime image with agent files overlaid ─────────────
FROM ${baseImage}

RUN mkdir -p ${destPath}

# Copy standard gitagent files from source
${copyLines.join('\n')}

# Set agentDir env for OpenClaw
ENV OPENCLAW_AGENT_DIR=${destPath}
LABEL gitagent.url="${gitUrl}" gitagent.ref="${gitRef}"
`
}
