// Generated by shadow-server-app typegen from ../shadow-app.local.json.
// Do not edit by hand. Update the JSON manifest and regenerate this file.
import type { ShadowServerAppManifest } from '@shadowob/sdk'

export const shadowServerAppManifest = {
  schemaVersion: 'shadow.app/1',
  appKey: 'shadow-wheel',
  name: 'Animal Spin Wheel',
  description:
    'A weighted animal prize wheel Server App with three spins per round, scoring, persistent history, and participant leaderboard.',
  version: '1.0.0',
  iconUrl: 'http://localhost:4212/assets/icon.svg',
  iframe: {
    entry: 'http://localhost:4212/shadow/server',
    allowedOrigins: ['http://localhost:4212'],
  },
  api: {
    baseUrl: 'http://localhost:4212',
    auth: {
      type: 'oauth2-bearer',
    },
  },
  access: {
    defaultPermissions: ['wheel.prizes:read', 'wheel.scores:read'],
    defaultApprovalMode: 'none',
  },
  commands: [
    {
      name: 'wheel.prizes.list',
      title: 'List wheel prizes',
      description: 'List weighted animal prizes and score values.',
      path: '/api/shadow/commands/wheel.prizes.list',
      permission: 'wheel.prizes:read',
      action: 'read',
      dataClass: 'server-private',
    },
    {
      name: 'wheel.spin.start',
      title: 'Spin three times',
      description:
        'Create one persisted round with exactly three weighted animal spins for the actor or named participant.',
      path: '/api/shadow/commands/wheel.spin.start',
      permission: 'wheel.spins:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        properties: {
          participantName: {
            type: 'string',
            maxLength: 40,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'wheel.runs.list',
      title: 'List recent spin rounds',
      description: 'List recent persisted three-spin rounds.',
      path: '/api/shadow/commands/wheel.runs.list',
      permission: 'wheel.scores:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          limit: {
            type: 'integer',
            minimum: 1,
            maximum: 100,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'wheel.leaderboard',
      title: 'Read leaderboard',
      description: 'Aggregate participants by total score, best round, and number of rounds.',
      path: '/api/shadow/commands/wheel.leaderboard',
      permission: 'wheel.scores:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          limit: {
            type: 'integer',
            minimum: 1,
            maximum: 100,
          },
        },
        additionalProperties: false,
      },
    },
  ],
  skills: [
    {
      name: 'shadow-wheel-ops',
      description:
        'Use when a Buddy needs to inspect animal wheel prizes, start a three-spin round, or read the leaderboard.',
      commandHints: [
        'shadow-wheel wheel.prizes.list',
        'shadow-wheel wheel.spin.start',
        'shadow-wheel wheel.runs.list',
        'shadow-wheel wheel.leaderboard',
      ],
    },
  ],
  events: ['wheel.updated'],
} as const satisfies ShadowServerAppManifest

export type ShadowServerAppManifestDefinition = typeof shadowServerAppManifest
