export const spacing = {
  none: 0,
  px: 1,
  xxs: 2,
  xs: 4,
  tight: 6,
  sm: 8,
  md: 12,
  lg: 16,
  xl: 20,
  '2xl': 24,
  '3xl': 32,
  '4xl': 40,
  '5xl': 48,
  '6xl': 64,
} as const

export const radius = {
  none: 0,
  xs: 2,
  sm: 4,
  md: 8,
  lg: 12,
  '2lg': 16,
  xl: 20,
  '2xl': 24,
  '3xl': 32,
  '4xl': 40,
  full: 9999,
} as const

export const fontSize = {
  micro: 10,
  xs: 12,
  sm: 14,
  md: 16,
  lg: 18,
  xl: 22,
  '2xl': 28,
  '3xl': 34,
  '4xl': 40,
} as const

export const lineHeight = {
  micro: 14,
  xs: 17,
  sm: 20,
  md: 24,
  lg: 28,
  xl: 32,
  '2xl': 36,
  '3xl': 42,
  '4xl': 48,
} as const

export const letterSpacing = {
  none: 0,
} as const

export const border = {
  none: 0,
  hairline: 1,
  active: 2,
} as const

export const iconSize = {
  micro: 10,
  xs: 12,
  sm: 14,
  md: 16,
  lg: 18,
  xl: 20,
  '2xl': 22,
  '3xl': 24,
  '4xl': 28,
  '5xl': 32,
  '6xl': 40,
  hero: 64,
} as const

export const size = {
  dotXs: 4,
  dotSm: 6,
  dotMd: 8,
  dotLg: 12,
  dividerAccent: 3,
  badgeSm: 16,
  badgeMd: 18,
  badgeLg: 20,
  iconBubble: 34,
  iconTile: 38,
  checkbox: 22,
  iconButtonSm: 32,
  iconButtonMd: 36,
  iconButtonLg: 40,
  controlXs: 28,
  controlSm: 36,
  controlMd: 44,
  controlLg: 48,
  avatarXs: 24,
  avatarSm: 32,
  avatarMd: 40,
  avatarLg: 48,
  avatarXl: 64,
  listItemLg: 72,
  actionTileMin: 82,
  textareaMin: 80,
  textareaInputLg: 88,
  textareaLg: 110,
  navBar: 56,
  navSide: 112,
  tabBar: 58,
  contentMaxWidth: 420,
  authCardMaxWidth: 480,
  keyValueLabel: 112,
  sectionCompactIcon: 30,
  metricMinWidth: 130,
  pillMaxWidth: 120,
  chipMaxWidth: 180,
  compactChipMaxWidth: 160,
  commerceChipMaxWidth: 260,
  attachmentImageWidth: 250,
  commerceCardMaxWidth: 340,
  actionMinWidth: 190,
  dropdownMaxHeight: 240,
  panelStateMinHeight: 180,
  profileHeroMinHeight: 230,
  settingsRowMinHeight: 68,
  plusPanelIcon: 52,
  plusPanelIconLg: 60,
  thumbnailMd: 80,
  composerInputMaxHeight: 120,
  commentInputMaxHeight: 100,
  mediaPlaceholderMinHeight: 220,
  mediaViewportMaxHeight: 360,
  previewImageHeight: 300,
  illustrationLg: 88,
  tutorialMaxHeight: 280,
  floatingCallWidth: 324,
  emojiPanelMaxHeight: 320,
  callHandleWidth: 30,
  callHandleHeight: 42,
  audioBarBase: 9,
  audioBarRange: 20,
  voicePreviewWaveformMinWidth: 96,
  dialogMaxWidth: 360,
  chatWorkMaxWidth: 220,
  sheetHandleWidth: 36,
  sheetHandleHeight: 4,
} as const

export const palette = {
  foundation: '#050508',
  surface: '#12121A',
  cyan: '#00F3FF',
  cyanSoft: '#CCFFFF',
  cyanDark: '#0099AA',
  yellow: '#F8E71C',
  yellowDark: '#B3A100',
  emerald: '#00E676',
  emeraldDark: '#00A862',
  crimson: '#FF2A55',
  crimsonDark: '#DC2626',
  indigo: '#7C4DFF',
  warning: '#FF9100',
  white: '#FFFFFF',
  black: '#000000',
  blackOverlay: 'rgba(0, 0, 0, 0.52)',
  ink: '#0F172A',
  neutral50: '#F8FAFC',
  neutral100: '#F1F5F9',
  neutral200: '#E2E8F0',
  neutral300: '#CBD5E1',
  neutral400: '#94A3B8',
  neutral500: '#64748B',
  neutral600: '#475569',
  neutral700: '#334155',
  neutral800: '#1B1E28',
  neutral900: '#0F172A',
  slate: '#64748B',
  lineLight: '#D8E2EA',
  lineDark: '#2A2E39',
  cyanSurface: '#BCEFF6',
  accentSurface: '#FFFBEA',
  successSurface: '#E8FFF3',
  warningSurface: '#FFF7E0',
  dangerSurface: '#FFE8ED',
  mutedSurface: '#E8EEF3',
  googleBlue: '#4285F4',
  googleGreen: '#34A853',
  googleYellow: '#FBBC05',
  googleRed: '#EA4335',
} as const

export const lightColors = {
  mode: 'light',
  background: '#F5F8FA',
  surface: palette.white,
  surfaceHover: '#EAFBFD',
  border: palette.lineLight,
  text: palette.ink,
  textSecondary: palette.neutral700,
  textMuted: palette.slate,
  primary: palette.cyan,
  primaryLight: palette.cyan,
  primaryDark: palette.cyanDark,
  accent: palette.yellow,
  accentStrong: palette.yellowDark,
  error: palette.crimsonDark,
  success: palette.emeraldDark,
  warning: palette.warning,
  info: palette.indigo,
  onPrimary: palette.foundation,
  onAccent: palette.foundation,
  onDanger: palette.white,
  card: palette.white,
  cardBorder: '#DDE6ED',
  inputBackground: '#F1F5F9',
  tonePrimarySurface: palette.cyanSurface,
  toneAccentSurface: palette.accentSurface,
  toneSuccessSurface: palette.successSurface,
  toneWarningSurface: palette.warningSurface,
  toneDangerSurface: palette.dangerSurface,
  toneMutedSurface: palette.mutedSurface,
  serverSidebar: palette.white,
  channelSidebar: '#F1F5F9',
  chatBackground: '#F5F8FA',
  messageHover: '#EAFBFD',
  overlay: palette.blackOverlay,
  shadowSoft: '#CBD5E1',
  shadowStrong: '#94A3B8',
  statusOnline: palette.emeraldDark,
  statusIdle: palette.warning,
  statusDnd: palette.crimsonDark,
  statusOffline: '#94A3B8',
  shrimpCoin: '#F43F5E',
}

export const darkColors = {
  mode: 'dark',
  background: palette.foundation,
  surface: palette.surface,
  surfaceHover: '#1A2A2D',
  border: palette.lineDark,
  text: palette.neutral50,
  textSecondary: '#A1A1AA',
  textMuted: palette.neutral400,
  primary: palette.cyan,
  primaryLight: palette.cyanSoft,
  primaryDark: palette.cyanDark,
  accent: palette.yellow,
  accentStrong: palette.yellowDark,
  error: palette.crimson,
  success: palette.emerald,
  warning: palette.warning,
  info: palette.indigo,
  onPrimary: palette.foundation,
  onAccent: palette.foundation,
  onDanger: palette.white,
  card: palette.surface,
  cardBorder: palette.lineDark,
  inputBackground: '#1B1E28',
  tonePrimarySurface: '#12313A',
  toneAccentSurface: '#34320D',
  toneSuccessSurface: '#123326',
  toneWarningSurface: '#332614',
  toneDangerSurface: '#3B1824',
  toneMutedSurface: '#1B1E28',
  serverSidebar: palette.foundation,
  channelSidebar: palette.surface,
  chatBackground: palette.foundation,
  messageHover: '#1A2A2D',
  overlay: palette.blackOverlay,
  shadowSoft: palette.black,
  shadowStrong: palette.black,
  statusOnline: palette.emerald,
  statusIdle: palette.warning,
  statusDnd: palette.crimson,
  statusOffline: '#94A3B8',
  shrimpCoin: '#FB7185',
}

export type ColorTokens = typeof darkColors | typeof lightColors
