// Generated by shadow-server-app typegen from ../shadow-app.local.json.
// Do not edit by hand. Update the JSON manifest and regenerate this file.
import type { ShadowServerAppManifest } from '@shadowob/sdk'

export const shadowServerAppManifest = {
  schemaVersion: 'shadow.app/1',
  appKey: 'shadow-flash',
  name: 'Flash',
  description:
    'Persistent multi-card canvas with realtime rooms, server-side command execution, file-backed image cards, and Buddy-assisted board operations.',
  version: '1.1.0',
  updatedAt: '2026-05-21T00:00:00.000Z',
  iconUrl: 'http://localhost:4216/assets/icon.svg',
  iframe: {
    entry: 'http://localhost:4216/shadow/server',
    allowedOrigins: ['http://localhost:4216'],
  },
  api: {
    baseUrl: 'http://localhost:4216',
    auth: {
      type: 'oauth2-bearer',
    },
  },
  access: {
    defaultPermissions: ['flash.boards:read', 'flash.boards:write', 'flash.cards:read'],
    defaultApprovalMode: 'none',
  },
  help: {
    overview:
      'Flash is a server-backed canvas for many card kinds, including image, quote, summary, argument, data, table, code, chart, timeline, comparison, process, math, todo, link, file, poker, tarot, Live2D, Three.js, and inspiration cards. Start from the command list, then request per-command help only when the input schema or examples are needed.',
    usage:
      "Use shadowob app call shadow-flash <command> --server <server> --channel-id <channel> --json-input '<input-json>' --json. Use --help on a specific command for detailed schema and examples.",
    commandIndex:
      'Use boards.get for snapshots, cards.create/cards.update for typed cards, assets.upload or cards.create --file for local images, selection.get for the current stored selection, and shadowob app events shadow-flash for realtime updates.',
  },
  commands: [
    {
      name: 'boards.get',
      title: 'Open board',
      description:
        'Open the caller-owned Flash board with cards, arenas, recent command events, and actor identity.',
      path: '/api/shadow/commands/boards.get',
      permission: 'flash.boards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'boards.events',
      title: 'Read board events',
      description:
        'Read ordered Flash board events after a cursor so clients can catch up without refetching the full board.',
      path: '/api/shadow/commands/boards.events',
      permission: 'flash.boards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          after: {
            type: 'integer',
            minimum: 0,
          },
          limit: {
            type: 'integer',
            minimum: 1,
            maximum: 200,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'boards.viewport.update',
      title: 'Save viewport',
      description: 'Persist the caller-owned Flash board viewport so reopen restores pan and zoom.',
      path: '/api/shadow/commands/boards.viewport.update',
      permission: 'flash.boards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'none',
      inputSchema: {
        type: 'object',
        required: ['viewport'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          viewport: {
            type: 'object',
            required: ['offsetX', 'offsetY', 'zoom'],
            properties: {
              offsetX: {
                type: 'number',
              },
              offsetY: {
                type: 'number',
              },
              zoom: {
                type: 'number',
                minimum: 0.1,
                maximum: 4,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.get',
      title: 'Open card',
      description: 'Read a single card from the caller-owned board.',
      path: '/api/shadow/commands/cards.get',
      permission: 'flash.cards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.create',
      title: 'Create card',
      description: 'Create any supported Flash card kind on the caller-owned board.',
      help: {
        summary:
          'Create text, image, code, chart, timeline, poker, tarot, Live2D, Three.js, inspiration, and other Flash card kinds.',
        usage:
          'shadowob app call shadow-flash cards.create --server "<server>" --channel-id "<channel>" --json-input \'{"kind":"image","title":"Sketch"}\' --file ./sketch.png --json',
        details:
          'The kind field selects the renderer. Image cards can be created in one command by passing --file; the app uploads the image, stores a file-backed URL, and links it to the created card. For non-image cards, put kind-specific structured data in meta.',
        examples: [
          {
            title: 'Create an image card from a local file',
            command:
              'shadowob app call shadow-flash cards.create --server "<server>" --channel-id "<channel>" --json-input \'{"kind":"image","title":"Moodboard"}\' --file ./moodboard.png --json',
          },
          {
            title: 'Create a chart card',
            input: {
              kind: 'chart',
              title: 'Weekly usage',
              meta: {
                chartType: 'bar',
                labels: ['Mon', 'Tue'],
                series: [
                  {
                    name: 'Runs',
                    data: [12, 18],
                  },
                ],
              },
            },
          },
        ],
      },
      path: '/api/shadow/commands/cards.create',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      input: 'multipart',
      binary: {
        supported: true,
        field: 'file',
        maxBytes: 10485760,
        contentTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/gif'],
      },
      inputSchema: {
        type: 'object',
        required: ['title'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 160,
          },
          kind: {
            enum: [
              'quote',
              'summary',
              'argument',
              'data',
              'table',
              'image',
              'code',
              'chart',
              'idea',
              'text',
              'audio',
              'video',
              'keypoint',
              'definition',
              'example',
              'reference',
              'inspiration',
              'timeline',
              'comparison',
              'process',
              'gif',
              'qrcode',
              'person',
              'terminal',
              'lottie',
              'webpage',
              'countdown',
              'threed',
              'live2d',
              'link',
              'file',
              'math',
              'todo',
              'position',
              'timestamp',
              'color',
              'event',
              'voice',
              'comment',
              'story',
              'social',
              'poker',
              'tarot',
              'flash',
            ],
          },
          summary: {
            type: 'string',
            maxLength: 1000,
          },
          content: {
            type: 'string',
            maxLength: 12000,
          },
          thumbnail: {
            type: 'string',
            maxLength: 2000,
          },
          sourceId: {
            type: ['string', 'null'],
            maxLength: 200,
          },
          linkedCardIds: {
            type: 'array',
            maxItems: 80,
            items: {
              type: 'string',
              maxLength: 120,
            },
          },
          meta: {
            type: 'object',
          },
          tags: {
            type: 'array',
            maxItems: 12,
            items: {
              type: 'string',
              maxLength: 40,
            },
          },
          priority: {
            enum: ['high', 'medium', 'low'],
          },
          autoGenerated: {
            type: 'boolean',
          },
          rating: {
            type: 'integer',
            minimum: 0,
            maximum: 5,
          },
          filePath: {
            type: 'string',
            maxLength: 2000,
          },
          fileMime: {
            type: 'string',
            maxLength: 120,
          },
          deckIds: {
            type: 'array',
            maxItems: 80,
            items: {
              type: 'string',
              maxLength: 120,
            },
          },
          x: {
            type: 'number',
          },
          y: {
            type: 'number',
          },
          angle: {
            type: 'number',
          },
          flipped: {
            type: 'boolean',
          },
          hidden: {
            type: 'boolean',
          },
          locked: {
            type: 'boolean',
          },
          upload: {
            type: 'object',
            required: ['filename', 'contentType', 'size', 'dataBase64'],
            properties: {
              field: {
                type: 'string',
                maxLength: 80,
              },
              filename: {
                type: 'string',
                minLength: 1,
                maxLength: 240,
              },
              contentType: {
                type: 'string',
                minLength: 1,
                maxLength: 160,
              },
              size: {
                type: 'integer',
                minimum: 1,
                maximum: 10485760,
              },
              dataBase64: {
                type: 'string',
                minLength: 1,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.update',
      title: 'Update card',
      description: 'Update card kind, text, tags, layout, metadata, or attached file-backed image.',
      help: {
        summary:
          'Patch an existing card, including layout, metadata, renderer kind, and optional uploaded image.',
        usage:
          'shadowob app call shadow-flash cards.update --server "<server>" --json-input \'{"cardId":"<card>","x":320,"y":240}\' --json',
        details:
          'Layout fields are server-authoritative snapshots. Realtime physics clients should debounce layout writes, attach a monotonic clientRevision, and ignore lower-revision remote echoes while a newer local layout is pending.',
      },
      path: '/api/shadow/commands/cards.update',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      input: 'multipart',
      binary: {
        supported: true,
        field: 'file',
        maxBytes: 10485760,
        contentTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/gif'],
      },
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
          clientRevision: {
            type: 'integer',
            minimum: 0,
            description:
              'Client-local monotonic layout revision. Realtime clients use it to ignore stale card layout echoes.',
          },
          kind: {
            enum: [
              'quote',
              'summary',
              'argument',
              'data',
              'table',
              'image',
              'code',
              'chart',
              'idea',
              'text',
              'audio',
              'video',
              'keypoint',
              'definition',
              'example',
              'reference',
              'inspiration',
              'timeline',
              'comparison',
              'process',
              'gif',
              'qrcode',
              'person',
              'terminal',
              'lottie',
              'webpage',
              'countdown',
              'threed',
              'live2d',
              'link',
              'file',
              'math',
              'todo',
              'position',
              'timestamp',
              'color',
              'event',
              'voice',
              'comment',
              'story',
              'social',
              'poker',
              'tarot',
              'flash',
            ],
          },
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 160,
          },
          summary: {
            type: 'string',
            maxLength: 1000,
          },
          content: {
            type: 'string',
            maxLength: 12000,
          },
          thumbnail: {
            type: 'string',
            maxLength: 2000,
          },
          sourceId: {
            type: ['string', 'null'],
            maxLength: 200,
          },
          linkedCardIds: {
            type: 'array',
            maxItems: 80,
            items: {
              type: 'string',
              maxLength: 120,
            },
          },
          meta: {
            type: 'object',
          },
          tags: {
            type: 'array',
            maxItems: 12,
            items: {
              type: 'string',
              maxLength: 40,
            },
          },
          priority: {
            enum: ['high', 'medium', 'low'],
          },
          autoGenerated: {
            type: 'boolean',
          },
          rating: {
            type: 'integer',
            minimum: 0,
            maximum: 5,
          },
          filePath: {
            type: 'string',
            maxLength: 2000,
          },
          fileMime: {
            type: 'string',
            maxLength: 120,
          },
          deckIds: {
            type: 'array',
            maxItems: 80,
            items: {
              type: 'string',
              maxLength: 120,
            },
          },
          x: {
            type: 'number',
          },
          y: {
            type: 'number',
          },
          angle: {
            type: 'number',
          },
          flipped: {
            type: 'boolean',
          },
          hidden: {
            type: 'boolean',
          },
          locked: {
            type: 'boolean',
          },
          upload: {
            type: 'object',
            required: ['filename', 'contentType', 'size', 'dataBase64'],
            properties: {
              field: {
                type: 'string',
                maxLength: 80,
              },
              filename: {
                type: 'string',
                minLength: 1,
                maxLength: 240,
              },
              contentType: {
                type: 'string',
                minLength: 1,
                maxLength: 160,
              },
              size: {
                type: 'integer',
                minimum: 1,
                maximum: 10485760,
              },
              dataBase64: {
                type: 'string',
                minLength: 1,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.delete',
      title: 'Delete card',
      description: 'Delete a card from the caller-owned board.',
      path: '/api/shadow/commands/cards.delete',
      permission: 'flash.cards:delete',
      action: 'delete',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'assets.upload',
      title: 'Upload asset',
      description:
        'Upload a local binary image into Flash storage and return a file-backed asset URL.',
      help: {
        summary: 'Upload a local image for later use by image/file cards.',
        usage:
          'shadowob app call shadow-flash assets.upload --server "<server>" --file ./image.png --json-input \'{}\' --json',
        details:
          'Use cards.create with --file when the asset should immediately become a card. Use assets.upload when you only need the uploaded URL first.',
      },
      path: '/api/shadow/commands/assets.upload',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      input: 'multipart',
      binary: {
        supported: true,
        field: 'file',
        maxBytes: 10485760,
        contentTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/gif'],
      },
      inputSchema: {
        type: 'object',
        required: ['upload'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          upload: {
            type: 'object',
            required: ['filename', 'contentType', 'size', 'dataBase64'],
            properties: {
              field: {
                type: 'string',
                maxLength: 80,
              },
              filename: {
                type: 'string',
                minLength: 1,
                maxLength: 240,
              },
              contentType: {
                type: 'string',
                minLength: 1,
                maxLength: 160,
              },
              size: {
                type: 'integer',
                minimum: 1,
                maximum: 10485760,
              },
              dataBase64: {
                type: 'string',
                minLength: 1,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.command',
      title: 'Execute card command',
      description:
        'Execute a Flash command through the server dispatcher, persist the result, and broadcast the room update.',
      path: '/api/shadow/commands/cards.command',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['command'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          command: {
            type: 'object',
            required: ['name', 'cardId'],
            properties: {
              name: {
                enum: [
                  'move',
                  'flip',
                  'rotate',
                  'orbit',
                  'trash',
                  'link',
                  'toggle',
                  'highlight',
                  'focus',
                  'lock',
                  'play',
                  'pause',
                  'act',
                  'add',
                  'scan',
                  'arena',
                  'move-to',
                  'activate',
                  'help',
                  'stack',
                ],
              },
              cardId: {
                type: 'string',
              },
              params: {
                type: 'object',
              },
              timestamp: {
                type: 'number',
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'rooms.attach',
      title: 'Attach card view',
      description:
        'Attach a Buddy or user to one card perspective and return nearby cards plus command affordances.',
      path: '/api/shadow/commands/rooms.attach',
      permission: 'flash.cards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
          radius: {
            type: 'number',
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'arenas.create',
      title: 'Create arena',
      description: 'Create a magic-circle, grid, or custom arena on the board.',
      path: '/api/shadow/commands/arenas.create',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          kind: {
            enum: ['magic-circle', 'grid', 'custom'],
          },
          label: {
            type: 'string',
            maxLength: 120,
          },
          x: {
            type: 'number',
          },
          y: {
            type: 'number',
          },
          radius: {
            type: 'number',
          },
          color: {
            type: 'string',
            maxLength: 40,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'arenas.activate',
      title: 'Activate arena',
      description: 'Activate an arena and persist the resulting card arrangement.',
      path: '/api/shadow/commands/arenas.activate',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['arenaId'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          arenaId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'selection.get',
      title: 'Read selection',
      description: 'Read stored realtime selection state for the board or one actor.',
      help: {
        summary: 'Return current selected card ids so a Buddy can act on what the user selected.',
        usage:
          'shadowob app call shadow-flash selection.get --server "<server>" --channel-id "<channel>" --json-input \'{}\' --json',
      },
      path: '/api/shadow/commands/selection.get',
      permission: 'flash.cards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          actorId: {
            type: 'string',
            minLength: 1,
            maxLength: 160,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'selection.update',
      title: 'Publish selection',
      description: "Store and broadcast the caller's selected card ids.",
      help: {
        summary: 'Publish the current selection as durable realtime state.',
        usage:
          'shadowob app call shadow-flash selection.update --server "<server>" --json-input \'{"selectedCardIds":["<card>"]}\' --json',
        details:
          'The app stores selection by actor id. UI clients call this after click, marquee selection, select-all, and clear-selection operations; Buddies can read it with selection.get.',
      },
      path: '/api/shadow/commands/selection.update',
      permission: 'flash.boards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'none',
      inputSchema: {
        type: 'object',
        required: ['selectedCardIds'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          selectedCardIds: {
            type: 'array',
            maxItems: 80,
            items: {
              type: 'string',
              maxLength: 120,
            },
          },
          anchorCardId: {
            type: ['string', 'null'],
            maxLength: 120,
          },
          revision: {
            type: 'integer',
            minimum: 0,
          },
        },
        additionalProperties: false,
      },
    },
  ],
  skills: [
    {
      name: 'shadow-flash-card-workspace',
      description:
        "Use when a Buddy reads user-provided material, creates or edits any Flash card kind, uploads local images, reads the user's current selection, subscribes to board events, attaches to a card perspective, inspects nearby cards, or executes Flash board commands.",
      commandHints: [
        'shadow-flash boards.get',
        'shadow-flash selection.get',
        'shadow-flash cards.create',
        'shadow-flash cards.create --file ./image.png',
        'shadow-flash assets.upload --file ./image.png',
        'shadow-flash cards.update',
        'shadow-flash rooms.attach',
        'shadow-flash cards.command',
        'shadow-flash arenas.create',
        'shadow-flash arenas.activate',
        'shadowob app events shadow-flash',
      ],
    },
  ],
  events: [
    'flash.events.appended',
    'flash.board.updated',
    'flash.command.executed',
    'flash.selection.updated',
  ],
  realtime: {
    transports: ['sse', 'websocket'],
    subscribe: {
      events: ['flash.events.appended', 'flash.selection.updated', 'server_app.command.completed'],
      help: 'Use shadowob app events shadow-flash --server "<server>" --json for Shadow command lifecycle events. Browser clients subscribe directly to the Flash board event stream with the Shadow launch token; local dev uses the same board SSE endpoint.',
    },
    publish: {
      command: 'selection.update',
      events: ['flash.selection.updated'],
      help: 'Publish user intent and durable presence-like state through commands such as selection.update; command execution appends ordered board events that subscribers consume.',
    },
    stateSync: {
      model: 'frame-sync',
      authority: 'server',
      tickRate: 30,
      help: 'Treat card layout as server-authoritative frames with client-side prediction during drag. Clients publish final transforms after pointer release, subscribe to ordered board events, discard frames at or below the local cursor, and reconcile from the server cursor.',
    },
  },
  binary: {
    supported: true,
    maxBytes: 10485760,
    contentTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/gif'],
  },
} as const satisfies ShadowServerAppManifest

export type ShadowServerAppManifestDefinition = typeof shadowServerAppManifest
