// Generated by shadow-server-app typegen from ../shadow-app.local.json.
// Do not edit by hand. Update the JSON manifest and regenerate this file.
import type { ShadowServerAppManifest } from '@shadowob/sdk'

export const shadowServerAppManifest = {
  schemaVersion: 'shadow.app/1',
  appKey: 'shadow-flash',
  name: 'Flash',
  description:
    'Persistent multi-card canvas with realtime rooms, server-side command execution, file-backed image cards, and Buddy-assisted board operations.',
  version: '1.2.0',
  updatedAt: '2026-06-04T00:00:00.000Z',
  iconUrl: 'http://localhost:4216/assets/icon.svg',
  marketplace: {
    tagline: 'A visual card canvas for building, arranging, and sharing ideas with your server.',
    summary:
      'Flash gives a server a persistent creative canvas for cards, images, code, charts, timelines, poker, tarot, Live2D, Three.js scenes, and realtime board collaboration. People and Buddies can create cards, upload assets, publish board state, and keep visual work organized in one shared place.',
    categories: ['创作', '效率', '工具'],
    supportedLanguages: ['English', '中文'],
    coverImageUrl: 'http://localhost:4216/assets/cover.png',
    gallery: [
      {
        url: 'http://localhost:4216/assets/cover.png',
        type: 'image',
        alt: 'flash cover',
      },
    ],
    links: [
      {
        label: '主页',
        url: 'http://localhost:4216/shadow/server',
        type: 'website',
      },
    ],
    publisher: {
      name: 'Shadow',
    },
  },
  iframe: {
    entry: 'http://localhost:4216/shadow/server',
    allowedOrigins: ['http://localhost:4216'],
  },
  api: {
    baseUrl: 'http://localhost:4216',
    auth: {
      type: 'oauth2-bearer',
    },
  },
  access: {
    defaultPermissions: ['flash.boards:read', 'flash.boards:write', 'flash.cards:read'],
    defaultApprovalMode: 'none',
  },
  help: {
    overview:
      'Flash is a server-backed semantic card canvas. For Buddy-generated boards or multi-card content, use cards.compose first so material is split by intent into typed cards with kind-specific metadata and renderers. Use cards.create only for one already-decided card.',
    usage:
      "Use shadowob app call shadow-flash <command> --server <server> --channel-id <channel> --json-input '<input-json>' --json. Use --help on a specific command for detailed schema and examples.",
    commandIndex:
      'Use cards.compose for any request that asks Buddy to create, split, summarize, test, brainstorm, or arrange multiple cards. Use cards.create/cards.update only for a single already-decided typed card, boards.get for snapshots, boards.events for incremental sync, assets.upload or cards.create --file for local images, and selection.get for current selection.',
  },
  commands: [
    {
      name: 'boards.get',
      title: 'Open board',
      description:
        'Open the caller-owned Flash board with cards, arenas, recent command events, and actor identity.',
      path: '/api/shadow/commands/boards.get',
      permission: 'flash.boards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'boards.events',
      title: 'Read board events',
      description:
        'Read ordered Flash board events after a cursor so clients can catch up without refetching the full board.',
      path: '/api/shadow/commands/boards.events',
      permission: 'flash.boards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          after: {
            type: 'integer',
            minimum: 0,
          },
          limit: {
            type: 'integer',
            minimum: 1,
            maximum: 200,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'boards.viewport.update',
      title: 'Save viewport',
      description: 'Persist the caller-owned Flash board viewport so reopen restores pan and zoom.',
      path: '/api/shadow/commands/boards.viewport.update',
      permission: 'flash.boards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'none',
      inputSchema: {
        type: 'object',
        required: ['viewport'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          clientMutationId: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          baseCursor: {
            type: 'integer',
            minimum: 0,
          },
          viewport: {
            type: 'object',
            required: ['offsetX', 'offsetY', 'zoom'],
            properties: {
              offsetX: {
                type: 'number',
              },
              offsetY: {
                type: 'number',
              },
              zoom: {
                type: 'number',
                minimum: 0.1,
                maximum: 4,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.get',
      title: 'Open card',
      description: 'Read a single card from the caller-owned board.',
      path: '/api/shadow/commands/cards.get',
      permission: 'flash.cards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.compose',
      title: 'Compose semantic card board',
      description:
        'Split Buddy/user material by intent and create multiple typed Flash cards with kind-specific metadata, layout, and render behavior.',
      help: {
        summary:
          'Primary Buddy entry point for creating multiple cards. It prevents large-text card dumps by normalizing each draft into the renderer schema for its kind.',
        usage: `shadowob app call shadow-flash cards.compose --server "<server>" --json-input '{"intent":"card-showcase","title":"卡片测试","material":"每张卡只讲一个点，类型各不相同"}' --json`,
        details:
          'Use this command whenever the user asks to build a board, split notes, make a card test, brainstorm, summarize source material into cards, create a study deck, or generate several cards. Buddy should pass explicit drafts with kind/title/content whenever it understands the intended structure; otherwise pass material plus intent and preferredKinds. The server chooses or validates card kinds, fills structured meta such as todo.items, definition.term/definition, process.steps, argument.evidence, quote.text, timeline.events, rule.principles, and places cards in a grid. Do not put a whole brief into cards.create.content when more than one semantic card is intended.',
        examples: [
          {
            title: 'Create a card showcase with different renderers',
            input: {
              intent: 'card-showcase',
              title: '卡片测试',
              material: '每张卡只讲一个点，内容精简，类型名不相同。',
              maxCards: 11,
            },
          },
          {
            title: 'Normalize explicit Buddy drafts',
            input: {
              intent: 'study-deck',
              drafts: [
                {
                  kind: 'definition',
                  title: '能量 ≠ 激情',
                  content: '能量不是兴奋，而是一种稳定投入。',
                },
                {
                  kind: 'todo',
                  title: '检查你头上的钉子',
                  content: '- [ ] 识别卡点\n- [ ] 请求外部反馈',
                },
              ],
            },
          },
        ],
      },
      path: '/api/shadow/commands/cards.compose',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        properties: {
          boardId: { type: 'string', minLength: 1 },
          clientMutationId: { type: 'string', minLength: 1, maxLength: 120 },
          baseCursor: { type: 'integer', minimum: 0 },
          intent: {
            enum: [
              'auto',
              'card-showcase',
              'study-deck',
              'research-map',
              'project-plan',
              'argument-map',
              'story-world',
              'presentation',
              'ruleset',
              'brainstorm',
            ],
          },
          title: { type: 'string', minLength: 1, maxLength: 160 },
          material: { type: 'string', maxLength: 60000 },
          instructions: { type: 'string', maxLength: 4000 },
          preferredKinds: {
            type: 'array',
            maxItems: 24,
            items: {
              enum: [
                'quote',
                'summary',
                'argument',
                'data',
                'table',
                'image',
                'code',
                'chart',
                'idea',
                'text',
                'audio',
                'video',
                'keypoint',
                'definition',
                'example',
                'reference',
                'inspiration',
                'timeline',
                'comparison',
                'process',
                'gif',
                'qrcode',
                'person',
                'terminal',
                'lottie',
                'webpage',
                'countdown',
                'threed',
                'live2d',
                'link',
                'file',
                'math',
                'todo',
                'position',
                'timestamp',
                'color',
                'event',
                'voice',
                'comment',
                'story',
                'social',
                'poker',
                'tarot',
                'flash',
                'rule',
              ],
            },
          },
          maxCards: { type: 'integer', minimum: 1, maximum: 40 },
          placement: {
            type: 'object',
            properties: {
              x: { type: 'number' },
              y: { type: 'number' },
              columns: { type: 'integer', minimum: 1, maximum: 12 },
              gapX: { type: 'number', exclusiveMinimum: 0, maximum: 1000 },
              gapY: { type: 'number', exclusiveMinimum: 0, maximum: 1000 },
              angleJitter: { type: 'number', minimum: 0, maximum: 0.4 },
            },
            additionalProperties: false,
          },
          drafts: {
            type: 'array',
            maxItems: 40,
            items: {
              type: 'object',
              properties: {
                id: { type: 'string', minLength: 1, maxLength: 120 },
                title: { type: 'string', minLength: 1, maxLength: 160 },
                kind: {
                  enum: [
                    'quote',
                    'summary',
                    'argument',
                    'data',
                    'table',
                    'image',
                    'code',
                    'chart',
                    'idea',
                    'text',
                    'audio',
                    'video',
                    'keypoint',
                    'definition',
                    'example',
                    'reference',
                    'inspiration',
                    'timeline',
                    'comparison',
                    'process',
                    'gif',
                    'qrcode',
                    'person',
                    'terminal',
                    'lottie',
                    'webpage',
                    'countdown',
                    'threed',
                    'live2d',
                    'link',
                    'file',
                    'math',
                    'todo',
                    'position',
                    'timestamp',
                    'color',
                    'event',
                    'voice',
                    'comment',
                    'story',
                    'social',
                    'poker',
                    'tarot',
                    'flash',
                    'rule',
                  ],
                },
                summary: { type: 'string', maxLength: 1000 },
                content: { type: 'string', maxLength: 12000 },
                thumbnail: { type: 'string', maxLength: 2000 },
                sourceId: { type: ['string', 'null'], maxLength: 200 },
                linkedCardIds: {
                  type: 'array',
                  maxItems: 80,
                  items: { type: 'string', maxLength: 120 },
                },
                meta: { type: 'object' },
                tags: { type: 'array', maxItems: 12, items: { type: 'string', maxLength: 40 } },
                priority: { enum: ['high', 'medium', 'low'] },
                autoGenerated: { type: 'boolean' },
                rating: { type: 'integer', minimum: 0, maximum: 5 },
                filePath: { type: 'string', maxLength: 2000 },
                fileMime: { type: 'string', maxLength: 120 },
                deckIds: { type: 'array', maxItems: 80, items: { type: 'string', maxLength: 120 } },
              },
              additionalProperties: false,
            },
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.create',
      title: 'Create card',
      description: 'Create any supported Flash card kind on the caller-owned board.',
      help: {
        summary:
          'Create text, image, code, chart, timeline, poker, tarot, Live2D, Three.js, inspiration, and other Flash card kinds.',
        usage:
          'shadowob app call shadow-flash cards.create --server "<server>" --channel-id "<channel>" --json-input \'{"kind":"image","title":"Sketch"}\' --file ./sketch.png --json',
        details:
          'The kind field selects the renderer. For one card, the server normalizes content into kind-specific meta. For multiple cards or any Buddy-generated board, use cards.compose instead; do not put an entire brief into one cards.create content field. Image cards can be created in one command by passing --file.',
        examples: [
          {
            title: 'Create an image card from a local file',
            command:
              'shadowob app call shadow-flash cards.create --server "<server>" --channel-id "<channel>" --json-input \'{"kind":"image","title":"Moodboard"}\' --file ./moodboard.png --json',
          },
          {
            title: 'Create a chart card',
            input: {
              kind: 'chart',
              title: 'Weekly usage',
              meta: {
                chartType: 'bar',
                labels: ['Mon', 'Tue'],
                series: [
                  {
                    name: 'Runs',
                    data: [12, 18],
                  },
                ],
              },
            },
          },
        ],
      },
      path: '/api/shadow/commands/cards.create',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      input: 'multipart',
      binary: {
        supported: true,
        field: 'file',
        maxBytes: 10485760,
        contentTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/gif'],
      },
      inputSchema: {
        type: 'object',
        required: ['title'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          clientMutationId: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          baseCursor: {
            type: 'integer',
            minimum: 0,
          },
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 160,
          },
          kind: {
            enum: [
              'quote',
              'summary',
              'argument',
              'data',
              'table',
              'image',
              'code',
              'chart',
              'idea',
              'text',
              'audio',
              'video',
              'keypoint',
              'definition',
              'example',
              'reference',
              'inspiration',
              'timeline',
              'comparison',
              'process',
              'gif',
              'qrcode',
              'person',
              'terminal',
              'lottie',
              'webpage',
              'countdown',
              'threed',
              'live2d',
              'link',
              'file',
              'math',
              'todo',
              'position',
              'timestamp',
              'color',
              'event',
              'voice',
              'comment',
              'story',
              'social',
              'poker',
              'tarot',
              'flash',
              'rule',
            ],
          },
          summary: {
            type: 'string',
            maxLength: 1000,
          },
          content: {
            type: 'string',
            maxLength: 12000,
          },
          thumbnail: {
            type: 'string',
            maxLength: 2000,
          },
          sourceId: {
            type: ['string', 'null'],
            maxLength: 200,
          },
          linkedCardIds: {
            type: 'array',
            maxItems: 80,
            items: {
              type: 'string',
              maxLength: 120,
            },
          },
          meta: {
            type: 'object',
          },
          tags: {
            type: 'array',
            maxItems: 12,
            items: {
              type: 'string',
              maxLength: 40,
            },
          },
          priority: {
            enum: ['high', 'medium', 'low'],
          },
          autoGenerated: {
            type: 'boolean',
          },
          rating: {
            type: 'integer',
            minimum: 0,
            maximum: 5,
          },
          filePath: {
            type: 'string',
            maxLength: 2000,
          },
          fileMime: {
            type: 'string',
            maxLength: 120,
          },
          deckIds: {
            type: 'array',
            maxItems: 80,
            items: {
              type: 'string',
              maxLength: 120,
            },
          },
          x: {
            type: 'number',
          },
          y: {
            type: 'number',
          },
          angle: {
            type: 'number',
          },
          flipped: {
            type: 'boolean',
          },
          hidden: {
            type: 'boolean',
          },
          locked: {
            type: 'boolean',
          },
          upload: {
            type: 'object',
            required: ['filename', 'contentType', 'size', 'dataBase64'],
            properties: {
              field: {
                type: 'string',
                maxLength: 80,
              },
              filename: {
                type: 'string',
                minLength: 1,
                maxLength: 240,
              },
              contentType: {
                type: 'string',
                minLength: 1,
                maxLength: 160,
              },
              size: {
                type: 'integer',
                minimum: 1,
                maximum: 10485760,
              },
              dataBase64: {
                type: 'string',
                minLength: 1,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.update',
      title: 'Update card',
      description: 'Update card kind, text, tags, layout, metadata, or attached file-backed image.',
      help: {
        summary:
          'Patch an existing card, including layout, metadata, renderer kind, and optional uploaded image.',
        usage:
          'shadowob app call shadow-flash cards.update --server "<server>" --json-input \'{"cardId":"<card>","x":320,"y":240}\' --json',
        details:
          'Layout fields are server-authoritative snapshots. Realtime physics clients should debounce layout writes, send the last known card revision as clientRevision, and ignore stale remote layout echoes while a local layout is pending.',
      },
      path: '/api/shadow/commands/cards.update',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      input: 'multipart',
      binary: {
        supported: true,
        field: 'file',
        maxBytes: 10485760,
        contentTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/gif'],
      },
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          clientMutationId: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          baseCursor: {
            type: 'integer',
            minimum: 0,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
          clientRevision: {
            type: 'integer',
            minimum: 0,
            description:
              'Last known server card revision for optimistic layout/content updates. The server returns 409 on mismatch.',
          },
          kind: {
            enum: [
              'quote',
              'summary',
              'argument',
              'data',
              'table',
              'image',
              'code',
              'chart',
              'idea',
              'text',
              'audio',
              'video',
              'keypoint',
              'definition',
              'example',
              'reference',
              'inspiration',
              'timeline',
              'comparison',
              'process',
              'gif',
              'qrcode',
              'person',
              'terminal',
              'lottie',
              'webpage',
              'countdown',
              'threed',
              'live2d',
              'link',
              'file',
              'math',
              'todo',
              'position',
              'timestamp',
              'color',
              'event',
              'voice',
              'comment',
              'story',
              'social',
              'poker',
              'tarot',
              'flash',
              'rule',
            ],
          },
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 160,
          },
          summary: {
            type: 'string',
            maxLength: 1000,
          },
          content: {
            type: 'string',
            maxLength: 12000,
          },
          thumbnail: {
            type: 'string',
            maxLength: 2000,
          },
          sourceId: {
            type: ['string', 'null'],
            maxLength: 200,
          },
          linkedCardIds: {
            type: 'array',
            maxItems: 80,
            items: {
              type: 'string',
              maxLength: 120,
            },
          },
          meta: {
            type: 'object',
          },
          tags: {
            type: 'array',
            maxItems: 12,
            items: {
              type: 'string',
              maxLength: 40,
            },
          },
          priority: {
            enum: ['high', 'medium', 'low'],
          },
          autoGenerated: {
            type: 'boolean',
          },
          rating: {
            type: 'integer',
            minimum: 0,
            maximum: 5,
          },
          filePath: {
            type: 'string',
            maxLength: 2000,
          },
          fileMime: {
            type: 'string',
            maxLength: 120,
          },
          deckIds: {
            type: 'array',
            maxItems: 80,
            items: {
              type: 'string',
              maxLength: 120,
            },
          },
          x: {
            type: 'number',
          },
          y: {
            type: 'number',
          },
          angle: {
            type: 'number',
          },
          flipped: {
            type: 'boolean',
          },
          hidden: {
            type: 'boolean',
          },
          locked: {
            type: 'boolean',
          },
          upload: {
            type: 'object',
            required: ['filename', 'contentType', 'size', 'dataBase64'],
            properties: {
              field: {
                type: 'string',
                maxLength: 80,
              },
              filename: {
                type: 'string',
                minLength: 1,
                maxLength: 240,
              },
              contentType: {
                type: 'string',
                minLength: 1,
                maxLength: 160,
              },
              size: {
                type: 'integer',
                minimum: 1,
                maximum: 10485760,
              },
              dataBase64: {
                type: 'string',
                minLength: 1,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.layout.update',
      title: 'Commit card layout batch',
      description:
        'Atomically persist one or more final card transforms after local drag, stack, or scripted layout changes.',
      help: {
        summary:
          'Use this for drag-end and stack commits. Layout conflicts default to merge-layout so stale drag revisions do not throw user-visible 409 errors.',
        usage: `shadowob app call shadow-flash cards.layout.update --server "<server>" --json-input '{"updates":[{"cardId":"<card>","x":320,"y":240}]}' --json`,
        details:
          'The command writes all supplied transforms in one durable event. Use conflictPolicy=reject only for tools that require exact revision matching.',
      },
      path: '/api/shadow/commands/cards.layout.update',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['updates'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          clientMutationId: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          baseCursor: {
            type: 'integer',
            minimum: 0,
          },
          conflictPolicy: {
            enum: ['merge-layout', 'reject'],
          },
          updates: {
            type: 'array',
            minItems: 1,
            maxItems: 160,
            items: {
              type: 'object',
              required: ['cardId'],
              properties: {
                cardId: {
                  type: 'string',
                  minLength: 1,
                },
                clientRevision: {
                  type: 'integer',
                  minimum: 0,
                },
                x: {
                  type: 'number',
                },
                y: {
                  type: 'number',
                },
                angle: {
                  type: 'number',
                },
                flipped: {
                  type: 'boolean',
                },
                hidden: {
                  type: 'boolean',
                },
                locked: {
                  type: 'boolean',
                },
              },
              additionalProperties: false,
            },
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.delete',
      title: 'Delete card',
      description: 'Delete a card from the caller-owned board.',
      path: '/api/shadow/commands/cards.delete',
      permission: 'flash.cards:delete',
      action: 'delete',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          clientMutationId: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          baseCursor: {
            type: 'integer',
            minimum: 0,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'assets.upload',
      title: 'Upload asset',
      description:
        'Upload a local binary image into Flash storage and return a file-backed asset URL.',
      help: {
        summary: 'Upload a local image for later use by image/file cards.',
        usage:
          'shadowob app call shadow-flash assets.upload --server "<server>" --file ./image.png --json-input \'{}\' --json',
        details:
          'Use cards.create with --file when the asset should immediately become a card. Use assets.upload when you only need the uploaded URL first.',
      },
      path: '/api/shadow/commands/assets.upload',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      input: 'multipart',
      binary: {
        supported: true,
        field: 'file',
        maxBytes: 10485760,
        contentTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/gif'],
      },
      inputSchema: {
        type: 'object',
        required: ['upload'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          clientMutationId: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          baseCursor: {
            type: 'integer',
            minimum: 0,
          },
          upload: {
            type: 'object',
            required: ['filename', 'contentType', 'size', 'dataBase64'],
            properties: {
              field: {
                type: 'string',
                maxLength: 80,
              },
              filename: {
                type: 'string',
                minLength: 1,
                maxLength: 240,
              },
              contentType: {
                type: 'string',
                minLength: 1,
                maxLength: 160,
              },
              size: {
                type: 'integer',
                minimum: 1,
                maximum: 10485760,
              },
              dataBase64: {
                type: 'string',
                minLength: 1,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.command',
      title: 'Execute card command',
      description:
        'Execute a Flash command through the server dispatcher, persist the result, and broadcast the room update.',
      path: '/api/shadow/commands/cards.command',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['command'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          clientMutationId: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          baseCursor: {
            type: 'integer',
            minimum: 0,
          },
          command: {
            type: 'object',
            required: ['name', 'cardId'],
            properties: {
              name: {
                enum: [
                  'move',
                  'flip',
                  'rotate',
                  'orbit',
                  'trash',
                  'link',
                  'toggle',
                  'highlight',
                  'focus',
                  'lock',
                  'play',
                  'pause',
                  'act',
                  'add',
                  'scan',
                  'arena',
                  'move-to',
                  'activate',
                  'help',
                  'stack',
                ],
              },
              cardId: {
                type: 'string',
              },
              params: {
                type: 'object',
              },
              timestamp: {
                type: 'number',
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'rooms.attach',
      title: 'Attach card view',
      description:
        'Attach a Buddy or user to one card perspective and return nearby cards plus command affordances.',
      path: '/api/shadow/commands/rooms.attach',
      permission: 'flash.cards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
          radius: {
            type: 'number',
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'arenas.create',
      title: 'Create arena',
      description: 'Create a magic-circle, grid, or custom arena on the board.',
      path: '/api/shadow/commands/arenas.create',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          clientMutationId: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          baseCursor: {
            type: 'integer',
            minimum: 0,
          },
          kind: {
            enum: ['magic-circle', 'grid', 'custom'],
          },
          label: {
            type: 'string',
            maxLength: 120,
          },
          x: {
            type: 'number',
          },
          y: {
            type: 'number',
          },
          radius: {
            type: 'number',
          },
          color: {
            type: 'string',
            maxLength: 40,
          },
          script: {
            type: 'string',
            maxLength: 20000,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'arenas.activate',
      title: 'Activate arena',
      description: 'Activate an arena and persist the resulting card arrangement.',
      path: '/api/shadow/commands/arenas.activate',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['arenaId'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          clientMutationId: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          baseCursor: {
            type: 'integer',
            minimum: 0,
          },
          clientRevision: {
            type: 'integer',
            minimum: 0,
          },
          arenaId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'selection.get',
      title: 'Read selection',
      description: 'Read stored realtime selection state for the board or one actor.',
      help: {
        summary: 'Return current selected card ids so a Buddy can act on what the user selected.',
        usage:
          'shadowob app call shadow-flash selection.get --server "<server>" --channel-id "<channel>" --json-input \'{}\' --json',
      },
      path: '/api/shadow/commands/selection.get',
      permission: 'flash.cards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          actorId: {
            type: 'string',
            minLength: 1,
            maxLength: 160,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'selection.update',
      title: 'Publish selection',
      description: "Store and broadcast the caller's selected card ids.",
      help: {
        summary: 'Publish the current selection as durable realtime state.',
        usage:
          'shadowob app call shadow-flash selection.update --server "<server>" --json-input \'{"selectedCardIds":["<card>"]}\' --json',
        details:
          'The app stores selection by actor id. UI clients call this after click, marquee selection, select-all, and clear-selection operations; Buddies can read it with selection.get.',
      },
      path: '/api/shadow/commands/selection.update',
      permission: 'flash.boards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'none',
      inputSchema: {
        type: 'object',
        required: ['selectedCardIds'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          clientMutationId: {
            type: 'string',
            minLength: 1,
            maxLength: 120,
          },
          baseCursor: {
            type: 'integer',
            minimum: 0,
          },
          selectedCardIds: {
            type: 'array',
            maxItems: 80,
            items: {
              type: 'string',
              maxLength: 120,
            },
          },
          anchorCardId: {
            type: ['string', 'null'],
            maxLength: 120,
          },
          revision: {
            type: 'integer',
            minimum: 0,
          },
        },
        additionalProperties: false,
      },
    },
  ],
  skills: [
    {
      name: 'shadow-flash-card-workspace',
      description:
        "Use when a Buddy reads user-provided material, composes a semantic multi-card board, creates or edits any Flash card kind, uploads local images, reads the user's current selection, subscribes to board events, attaches to a card perspective, inspects nearby cards, or executes Flash board commands. For generated multi-card work, prefer cards.compose over repeated cards.create.",
      commandHints: [
        'shadow-flash boards.get',
        'shadow-flash selection.get',
        'shadow-flash cards.compose',
        'shadow-flash cards.create',
        'shadow-flash cards.create --file ./image.png',
        'shadow-flash assets.upload --file ./image.png',
        'shadow-flash cards.update',
        'shadow-flash rooms.attach',
        'shadow-flash cards.command',
        'shadow-flash arenas.create',
        'shadow-flash arenas.activate',
        'shadowob app events shadow-flash',
      ],
    },
  ],
  events: [
    'flash.events.appended',
    'flash.board.updated',
    'flash.command.executed',
    'flash.selection.updated',
  ],
  realtime: {
    transports: ['sse', 'websocket'],
    subscribe: {
      events: ['flash.events.appended', 'flash.selection.updated', 'server_app.command.completed'],
      help: 'Use shadowob app events shadow-flash --server "<server>" --json for Shadow command lifecycle events. Browser clients subscribe directly to the Flash board event stream with the Shadow launch token; local dev uses the same board SSE endpoint.',
    },
    publish: {
      command: 'selection.update',
      events: ['flash.selection.updated'],
      help: 'Publish user intent and durable presence-like state through commands such as selection.update; command execution appends ordered board events that subscribers consume.',
    },
    stateSync: {
      model: 'frame-sync',
      authority: 'server',
      tickRate: 30,
      help: 'Treat card layout as server-authoritative frames with client-side prediction during drag. Clients publish final transforms with clientMutationId, baseCursor, and entity revision; consume board-local ordered events; buffer gaps; then reconcile from the authoritative cursor.',
    },
  },
  binary: {
    supported: true,
    maxBytes: 10485760,
    contentTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/gif'],
  },
} as const satisfies ShadowServerAppManifest

export type ShadowServerAppManifestDefinition = typeof shadowServerAppManifest
