// Generated by shadow-server-app typegen from ../shadow-app.local.json.
// Do not edit by hand. Update the JSON manifest and regenerate this file.
import type { ShadowServerAppManifest } from '@shadowob/sdk'

export const shadowServerAppManifest = {
  schemaVersion: 'shadow.app/1',
  appKey: 'shadow-flash',
  name: 'Flash',
  description:
    'Persistent inspiration-card board with realtime rooms, server-side command execution, and Buddy-assisted card operations.',
  version: '1.0.0',
  iconUrl: 'http://localhost:4216/assets/icon.svg',
  iframe: {
    entry: 'http://localhost:4216/shadow/server',
    allowedOrigins: ['http://localhost:4216'],
  },
  api: {
    baseUrl: 'http://localhost:4216',
    auth: {
      type: 'oauth2-bearer',
    },
  },
  access: {
    defaultPermissions: ['flash.boards:read', 'flash.boards:write', 'flash.cards:read'],
    defaultApprovalMode: 'none',
  },
  commands: [
    {
      name: 'boards.get',
      title: 'Open board',
      description:
        'Open the caller-owned Flash board with cards, arenas, recent command events, and actor identity.',
      path: '/api/shadow/commands/boards.get',
      permission: 'flash.boards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'boards.events',
      title: 'Read board events',
      description:
        'Read ordered Flash board events after a cursor so clients can catch up without refetching the full board.',
      path: '/api/shadow/commands/boards.events',
      permission: 'flash.boards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          after: {
            type: 'integer',
            minimum: 0,
          },
          limit: {
            type: 'integer',
            minimum: 1,
            maximum: 200,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'boards.viewport.update',
      title: 'Save viewport',
      description: 'Persist the caller-owned Flash board viewport so reopen restores pan and zoom.',
      path: '/api/shadow/commands/boards.viewport.update',
      permission: 'flash.boards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'none',
      inputSchema: {
        type: 'object',
        required: ['viewport'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          viewport: {
            type: 'object',
            required: ['offsetX', 'offsetY', 'zoom'],
            properties: {
              offsetX: {
                type: 'number',
              },
              offsetY: {
                type: 'number',
              },
              zoom: {
                type: 'number',
                minimum: 0.1,
                maximum: 4,
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.get',
      title: 'Open card',
      description: 'Read a single card from the caller-owned board.',
      path: '/api/shadow/commands/cards.get',
      permission: 'flash.cards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.create',
      title: 'Create card',
      description: 'Create a card on the caller-owned board.',
      path: '/api/shadow/commands/cards.create',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['title'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 160,
          },
          kind: {
            type: 'string',
            maxLength: 40,
          },
          summary: {
            type: 'string',
            maxLength: 1000,
          },
          content: {
            type: 'string',
            maxLength: 12000,
          },
          thumbnail: {
            type: 'string',
            maxLength: 2000,
          },
          sourceId: {
            type: ['string', 'null'],
            maxLength: 200,
          },
          linkedCardIds: {
            type: 'array',
            maxItems: 80,
            items: {
              type: 'string',
              maxLength: 120,
            },
          },
          meta: {
            type: 'object',
          },
          tags: {
            type: 'array',
            maxItems: 12,
            items: {
              type: 'string',
              maxLength: 40,
            },
          },
          priority: {
            enum: ['high', 'medium', 'low'],
          },
          autoGenerated: {
            type: 'boolean',
          },
          rating: {
            type: 'integer',
            minimum: 0,
            maximum: 5,
          },
          filePath: {
            type: 'string',
            maxLength: 2000,
          },
          fileMime: {
            type: 'string',
            maxLength: 120,
          },
          deckIds: {
            type: 'array',
            maxItems: 80,
            items: {
              type: 'string',
              maxLength: 120,
            },
          },
          x: {
            type: 'number',
          },
          y: {
            type: 'number',
          },
          angle: {
            type: 'number',
          },
          flipped: {
            type: 'boolean',
          },
          hidden: {
            type: 'boolean',
          },
          locked: {
            type: 'boolean',
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.update',
      title: 'Update card',
      description: 'Update card text, tags, layout, or metadata.',
      path: '/api/shadow/commands/cards.update',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 160,
          },
          summary: {
            type: 'string',
            maxLength: 1000,
          },
          content: {
            type: 'string',
            maxLength: 12000,
          },
          thumbnail: {
            type: 'string',
            maxLength: 2000,
          },
          sourceId: {
            type: ['string', 'null'],
            maxLength: 200,
          },
          linkedCardIds: {
            type: 'array',
            maxItems: 80,
            items: {
              type: 'string',
              maxLength: 120,
            },
          },
          meta: {
            type: 'object',
          },
          tags: {
            type: 'array',
            maxItems: 12,
            items: {
              type: 'string',
              maxLength: 40,
            },
          },
          priority: {
            enum: ['high', 'medium', 'low'],
          },
          autoGenerated: {
            type: 'boolean',
          },
          rating: {
            type: 'integer',
            minimum: 0,
            maximum: 5,
          },
          filePath: {
            type: 'string',
            maxLength: 2000,
          },
          fileMime: {
            type: 'string',
            maxLength: 120,
          },
          deckIds: {
            type: 'array',
            maxItems: 80,
            items: {
              type: 'string',
              maxLength: 120,
            },
          },
          x: {
            type: 'number',
          },
          y: {
            type: 'number',
          },
          angle: {
            type: 'number',
          },
          flipped: {
            type: 'boolean',
          },
          hidden: {
            type: 'boolean',
          },
          locked: {
            type: 'boolean',
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.delete',
      title: 'Delete card',
      description: 'Delete a card from the caller-owned board.',
      path: '/api/shadow/commands/cards.delete',
      permission: 'flash.cards:delete',
      action: 'delete',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'cards.command',
      title: 'Execute card command',
      description:
        'Execute a Flash command through the server dispatcher, persist the result, and broadcast the room update.',
      path: '/api/shadow/commands/cards.command',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['command'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          command: {
            type: 'object',
            required: ['name', 'cardId'],
            properties: {
              name: {
                enum: [
                  'move',
                  'flip',
                  'rotate',
                  'orbit',
                  'trash',
                  'link',
                  'toggle',
                  'highlight',
                  'focus',
                  'lock',
                  'play',
                  'pause',
                  'act',
                  'add',
                  'scan',
                  'arena',
                  'move-to',
                  'activate',
                  'help',
                  'stack',
                ],
              },
              cardId: {
                type: 'string',
              },
              params: {
                type: 'object',
              },
              timestamp: {
                type: 'number',
              },
            },
            additionalProperties: false,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'rooms.attach',
      title: 'Attach card view',
      description:
        'Attach a Buddy or user to one card perspective and return nearby cards plus command affordances.',
      path: '/api/shadow/commands/rooms.attach',
      permission: 'flash.cards:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['cardId'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          cardId: {
            type: 'string',
            minLength: 1,
          },
          radius: {
            type: 'number',
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'arenas.create',
      title: 'Create arena',
      description: 'Create a magic-circle, grid, or custom arena on the board.',
      path: '/api/shadow/commands/arenas.create',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          kind: {
            enum: ['magic-circle', 'grid', 'custom'],
          },
          label: {
            type: 'string',
            maxLength: 120,
          },
          x: {
            type: 'number',
          },
          y: {
            type: 'number',
          },
          radius: {
            type: 'number',
          },
          color: {
            type: 'string',
            maxLength: 40,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'arenas.activate',
      title: 'Activate arena',
      description: 'Activate an arena and persist the resulting card arrangement.',
      path: '/api/shadow/commands/arenas.activate',
      permission: 'flash.cards:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['arenaId'],
        properties: {
          boardId: {
            type: 'string',
            minLength: 1,
          },
          arenaId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
  ],
  skills: [
    {
      name: 'shadow-flash-card-workspace',
      description:
        'Use when a Buddy reads user-provided material itself, creates inspiration cards, attaches to a card perspective, inspects nearby cards, or executes Flash board commands.',
      commandHints: [
        'shadow-flash boards.get',
        'shadow-flash cards.create',
        'shadow-flash cards.update',
        'shadow-flash rooms.attach',
        'shadow-flash cards.command',
        'shadow-flash arenas.create',
        'shadow-flash arenas.activate',
      ],
    },
  ],
  events: ['flash.board.updated', 'flash.command.executed'],
} as const satisfies ShadowServerAppManifest

export type ShadowServerAppManifestDefinition = typeof shadowServerAppManifest
