// Generated by shadow-server-app typegen from ../shadow-app.local.json.
// Do not edit by hand. Update the JSON manifest and regenerate this file.
import type { ShadowServerAppManifest } from '@shadowob/sdk'

export const shadowServerAppManifest = {
  schemaVersion: 'shadow.app/1',
  appKey: 'shadow-resume',
  name: 'Super Resume',
  description:
    'A resume App for CRUD, Buddy-guided profile collection, resume generation, and CSS style updates.',
  version: '1.0.0',
  iconUrl: 'http://localhost:4214/assets/icon.svg',
  marketplace: {
    tagline: 'Build polished resumes with structured facts, generation, and style controls.',
    summary:
      'Super Resume helps people collect career facts, create resumes, update sections, delete stale drafts, and refine CSS styling with Buddy guidance. It keeps resume work structured enough for automation while still easy to edit by hand.',
    categories: ['效率', '创作', '工具'],
    supportedLanguages: ['English', '中文'],
    coverImageUrl: 'http://localhost:4214/assets/cover.png',
    gallery: [
      {
        url: 'http://localhost:4214/assets/cover.png',
        type: 'image',
        alt: 'resume cover',
      },
    ],
    links: [
      {
        label: '主页',
        url: 'http://localhost:4214/shadow/server',
        type: 'website',
      },
    ],
    publisher: {
      name: 'Shadow',
    },
  },
  iframe: {
    entry: 'http://localhost:4214/shadow/server',
    allowedOrigins: ['http://localhost:4214'],
  },
  api: {
    baseUrl: 'http://localhost:4214',
    auth: {
      type: 'oauth2-bearer',
    },
  },
  access: {
    defaultPermissions: ['resume.resumes:read'],
    defaultApprovalMode: 'none',
  },
  commands: [
    {
      name: 'resumes.list',
      title: 'List resumes',
      description: 'Search persisted resumes.',
      path: '/api/shadow/commands/resumes.list',
      permission: 'resume.resumes:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        properties: {
          query: {
            type: 'string',
            maxLength: 120,
          },
          limit: {
            type: 'integer',
            minimum: 1,
            maximum: 100,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'resumes.get',
      title: 'Read resume',
      description: 'Read one resume with profile, sections, and style CSS.',
      path: '/api/shadow/commands/resumes.get',
      permission: 'resume.resumes:read',
      action: 'read',
      dataClass: 'server-private',
      inputSchema: {
        type: 'object',
        required: ['resumeId'],
        properties: {
          resumeId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'resumes.create',
      title: 'Create resume',
      description: 'Create a resume from structured profile and section fields.',
      path: '/api/shadow/commands/resumes.create',
      permission: 'resume.resumes:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['title'],
        properties: {
          title: {
            type: 'string',
            minLength: 1,
            maxLength: 160,
          },
          profile: {
            type: 'object',
            additionalProperties: true,
          },
          sections: {
            type: 'object',
            additionalProperties: true,
          },
          styleCss: {
            type: 'string',
            maxLength: 8000,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'resumes.update',
      title: 'Update resume',
      description: 'Patch resume title, profile, or sections.',
      path: '/api/shadow/commands/resumes.update',
      permission: 'resume.resumes:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['resumeId', 'patch'],
        properties: {
          resumeId: {
            type: 'string',
            minLength: 1,
          },
          patch: {
            type: 'object',
            additionalProperties: true,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'resumes.delete',
      title: 'Delete resume',
      description: 'Delete a persisted resume.',
      path: '/api/shadow/commands/resumes.delete',
      permission: 'resume.resumes:delete',
      action: 'delete',
      dataClass: 'server-private',
      approvalMode: 'every_time',
      inputSchema: {
        type: 'object',
        required: ['resumeId'],
        properties: {
          resumeId: {
            type: 'string',
            minLength: 1,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'resumes.generate',
      title: 'Generate resume',
      description: 'Create a resume from Buddy-collected candidate notes.',
      path: '/api/shadow/commands/resumes.generate',
      permission: 'resume.resumes:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['profileText'],
        properties: {
          title: {
            type: 'string',
            maxLength: 160,
          },
          profileText: {
            type: 'string',
            minLength: 1,
            maxLength: 12000,
          },
          styleCss: {
            type: 'string',
            maxLength: 8000,
          },
        },
        additionalProperties: false,
      },
    },
    {
      name: 'resumes.style.update',
      title: 'Update resume CSS',
      description: 'Replace resume CSS declarations for visual styling.',
      path: '/api/shadow/commands/resumes.style.update',
      permission: 'resume.styles:write',
      action: 'write',
      dataClass: 'server-private',
      approvalMode: 'first_time',
      inputSchema: {
        type: 'object',
        required: ['resumeId', 'styleCss'],
        properties: {
          resumeId: {
            type: 'string',
            minLength: 1,
          },
          styleCss: {
            type: 'string',
            maxLength: 8000,
          },
        },
        additionalProperties: false,
      },
    },
  ],
  skills: [
    {
      name: 'shadow-resume-ops',
      description:
        'Use when a Buddy needs to collect resume facts, generate or update a resume, delete stale resumes, or adjust resume CSS.',
      commandHints: [
        'shadow-resume resumes.list',
        'shadow-resume resumes.get',
        'shadow-resume resumes.create',
        'shadow-resume resumes.update',
        'shadow-resume resumes.generate',
        'shadow-resume resumes.style.update',
      ],
    },
  ],
  events: ['resume.updated'],
} as const satisfies ShadowServerAppManifest

export type ShadowServerAppManifestDefinition = typeof shadowServerAppManifest
