/**
 * Comprehensive Model Provider Presets for OpenClaw
 *
 * Contains full metadata for all supported AI model providers including:
 * - Provider configuration (baseUrl, auth type, docs)
 * - Model definitions with context windows, max output tokens, capabilities
 * - Quick setup guides with step-by-step instructions
 * - Provider branding and categorization
 *
 * Data sourced from official provider documentation and OpenClaw integration guides.
 * Last updated: 2026-03-20
 *
 * @see https://docs.openclaw.ai/concepts/model-providers
 */

// ─── Types ───────────────────────────────────────────────────────────────────

export type ModelCapability =
  | 'chat'
  | 'completion'
  | 'vision'
  | 'function-calling'
  | 'json-mode'
  | 'streaming'
  | 'thinking'
  | 'code'
  | 'reasoning'
  | 'web-search'
  | 'file-upload'
  | 'image-generation'
  | 'audio'
  | 'video'
  | 'embedding'

export type ModelTier = 'flagship' | 'balanced' | 'fast' | 'economy' | 'specialized'

export type ProviderCategory = 'global' | 'china' | 'coding-plan' | 'local' | 'custom'

export interface ModelPreset {
  /** Model ID used in API calls */
  id: string
  /** Human-readable display name */
  name: string
  /** Context window size in tokens */
  contextWindow: number
  /** Maximum output tokens */
  maxTokens: number
  /** Supported capabilities */
  capabilities: ModelCapability[]
  /** Model tier / performance class */
  tier: ModelTier
  /** Short description */
  description: string
  /** Whether this model is recommended as default */
  recommended?: boolean
  /** Whether this model is deprecated */
  deprecated?: boolean
  /** Release / knowledge cutoff date */
  releasedAt?: string
  /** Pricing info: input cost per 1M tokens in USD */
  inputPricePer1M?: number
  /** Pricing info: output cost per 1M tokens in USD */
  outputPricePer1M?: number
  /** Pricing info: cached input cost per 1M tokens in USD */
  cachedInputPricePer1M?: number
}

export interface ProviderQuickGuide {
  /** Link to official docs */
  docsUrl: string
  /** Link to get API key */
  apiKeyUrl: string
  /** Step-by-step setup instructions */
  steps: string[]
  /** Additional tips */
  tips?: string[]
  /** Pricing page URL */
  pricingUrl?: string
  /** Coding plan / subscription URL */
  codingPlanUrl?: string
}

/** Valid API format identifiers */
export type ModelApiFormat =
  | 'openai-completions'
  | 'openai-responses'
  | 'openai-codex-responses'
  | 'anthropic-messages'
  | 'google-generative-ai'
  | 'github-copilot'
  | 'bedrock-converse-stream'
  | 'ollama'

/** Coding Plan metadata — fixed-rate subscription plans that aggregate models */
export interface CodingPlanInfo {
  /** Display name */
  name: string
  /** URL to the coding plan page */
  url: string
  /** Description of what the plan includes */
  description: string
  /** Whether this plan includes models from other providers (cross-provider aggregation) */
  crossProvider?: boolean
  /** Model IDs included in this coding plan */
  models: string[]
  /** Pricing description (e.g., "$50/月", "按量计费") */
  pricing?: string
  /** Provider ID alias for the coding plan (e.g., "volcengine-plan") */
  planProviderId?: string
  /** Separate base URL for the coding plan (if different from main provider) */
  baseUrl?: string
  /** API format for the coding plan (if different from main provider) */
  apiFormat?: ModelApiFormat
}

export interface ProviderPreset {
  /** Unique provider ID (used as key in openclaw.json) */
  id: string
  /** Display name */
  name: string
  /** Short description */
  description: string
  /** Provider category */
  category: ProviderCategory
  /** API base URL */
  baseUrl: string
  /** Authentication type */
  auth: 'api-key' | 'oauth' | 'token' | 'none'
  /** API key placeholder hint */
  apiKeyPlaceholder?: string
  /** All available models */
  models: ModelPreset[]
  /** Quick setup guide */
  guide: ProviderQuickGuide
  /** Coding plan info (if available) */
  codingPlan?: CodingPlanInfo
  /** Custom headers if needed */
  defaultHeaders?: Record<string, string>
  /** Whether provider supports OpenAI-compatible API */
  openaiCompatible: boolean
  /** Provider website URL */
  websiteUrl: string
  /** Provider color for branding */
  brandColor: string
  /** API format identifier for OpenClaw (e.g., 'openai-completions', 'anthropic-messages') */
  apiFormat: ModelApiFormat
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const CHAT_BASE: ModelCapability[] = ['chat', 'streaming']
const CHAT_TOOLS: ModelCapability[] = ['chat', 'streaming', 'function-calling', 'json-mode']
const CHAT_VISION: ModelCapability[] = [
  'chat',
  'streaming',
  'function-calling',
  'json-mode',
  'vision',
]
const THINKING: ModelCapability[] = [
  'chat',
  'streaming',
  'function-calling',
  'json-mode',
  'thinking',
  'reasoning',
]
const THINKING_VISION: ModelCapability[] = [
  'chat',
  'streaming',
  'function-calling',
  'json-mode',
  'vision',
  'thinking',
  'reasoning',
]
const CODE_REASON: ModelCapability[] = [
  'chat',
  'streaming',
  'function-calling',
  'json-mode',
  'code',
  'reasoning',
]
const FULL_MULTI: ModelCapability[] = [
  'chat',
  'streaming',
  'function-calling',
  'json-mode',
  'vision',
  'code',
]

// ─── OpenAI ──────────────────────────────────────────────────────────────────

const OPENAI_MODELS: ModelPreset[] = [
  // ── GPT-5.4 Series (2026) ──
  {
    id: 'gpt-5.4',
    name: 'GPT-5.4',
    contextWindow: 1047576,
    maxTokens: 32768,
    capabilities: [...FULL_MULTI, 'thinking', 'reasoning'],
    tier: 'flagship',
    description: '最新旗舰模型，代码与推理全面进化',
    recommended: true,
    releasedAt: '2026-01',
    inputPricePer1M: 2.5,
    outputPricePer1M: 10.0,
    cachedInputPricePer1M: 0.625,
  },
  {
    id: 'gpt-5.4-pro',
    name: 'GPT-5.4 Pro',
    contextWindow: 1047576,
    maxTokens: 32768,
    capabilities: [...FULL_MULTI, 'thinking', 'reasoning'],
    tier: 'flagship',
    description: '高级版本，优先处理 + 更强推理',
    releasedAt: '2026-01',
    inputPricePer1M: 5.0,
    outputPricePer1M: 20.0,
    cachedInputPricePer1M: 1.25,
  },
  // ── GPT-4.1 Series (2025) ──
  {
    id: 'gpt-4.1',
    name: 'GPT-4.1',
    contextWindow: 1047576,
    maxTokens: 32768,
    capabilities: FULL_MULTI,
    tier: 'flagship',
    description: '超长上下文 1M tokens',
    releasedAt: '2025-04',
    inputPricePer1M: 2.0,
    outputPricePer1M: 8.0,
    cachedInputPricePer1M: 0.5,
  },
  {
    id: 'gpt-4.1-mini',
    name: 'GPT-4.1 Mini',
    contextWindow: 1047576,
    maxTokens: 32768,
    capabilities: FULL_MULTI,
    tier: 'balanced',
    description: '高性价比，1M 上下文',
    recommended: true,
    releasedAt: '2025-04',
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.6,
    cachedInputPricePer1M: 0.1,
  },
  {
    id: 'gpt-4.1-nano',
    name: 'GPT-4.1 Nano',
    contextWindow: 1047576,
    maxTokens: 32768,
    capabilities: CHAT_VISION,
    tier: 'economy',
    description: '极致成本优化，适合轻量任务',
    releasedAt: '2025-04',
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    cachedInputPricePer1M: 0.025,
  },
  // ── GPT-4o Series ──
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    contextWindow: 128000,
    maxTokens: 16384,
    capabilities: FULL_MULTI,
    tier: 'flagship',
    description: '高性能多模态旗舰模型',
    releasedAt: '2024-05',
    inputPricePer1M: 2.5,
    outputPricePer1M: 10.0,
    cachedInputPricePer1M: 1.25,
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    contextWindow: 128000,
    maxTokens: 16384,
    capabilities: FULL_MULTI,
    tier: 'balanced',
    description: '性价比极高的小型模型',
    releasedAt: '2024-07',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    cachedInputPricePer1M: 0.075,
  },
  // ── O-Series (Reasoning) ──
  {
    id: 'o4-mini',
    name: 'o4-mini',
    contextWindow: 200000,
    maxTokens: 100000,
    capabilities: THINKING_VISION,
    tier: 'balanced',
    description: '高效推理模型，支持工具调用',
    recommended: true,
    releasedAt: '2025-04',
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    cachedInputPricePer1M: 0.275,
  },
  {
    id: 'o3',
    name: 'o3',
    contextWindow: 200000,
    maxTokens: 100000,
    capabilities: THINKING_VISION,
    tier: 'flagship',
    description: '最强推理模型，复杂问题解决',
    releasedAt: '2025-04',
    inputPricePer1M: 10.0,
    outputPricePer1M: 40.0,
    cachedInputPricePer1M: 2.5,
  },
  {
    id: 'o3-mini',
    name: 'o3-mini',
    contextWindow: 200000,
    maxTokens: 100000,
    capabilities: THINKING,
    tier: 'balanced',
    description: '推理模型，高性价比',
    releasedAt: '2025-01',
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    cachedInputPricePer1M: 0.55,
  },
  {
    id: 'o1',
    name: 'o1',
    contextWindow: 200000,
    maxTokens: 100000,
    capabilities: THINKING_VISION,
    tier: 'flagship',
    description: '第一代推理模型',
    releasedAt: '2024-12',
    inputPricePer1M: 15.0,
    outputPricePer1M: 60.0,
    cachedInputPricePer1M: 7.5,
  },
  {
    id: 'o1-mini',
    name: 'o1 Mini',
    contextWindow: 128000,
    maxTokens: 65536,
    capabilities: THINKING,
    tier: 'balanced',
    description: '轻量推理模型',
    releasedAt: '2024-09',
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    cachedInputPricePer1M: 0.55,
    deprecated: true,
  },
  // ── Legacy ──
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    contextWindow: 128000,
    maxTokens: 4096,
    capabilities: CHAT_VISION,
    tier: 'flagship',
    description: 'GPT-4 增强版 128K 上下文',
    releasedAt: '2024-04',
    inputPricePer1M: 10.0,
    outputPricePer1M: 30.0,
    deprecated: true,
  },
  {
    id: 'gpt-4',
    name: 'GPT-4',
    contextWindow: 8192,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'flagship',
    description: '经典 GPT-4 模型',
    releasedAt: '2023-03',
    inputPricePer1M: 30.0,
    outputPricePer1M: 60.0,
    deprecated: true,
  },
  {
    id: 'gpt-3.5-turbo',
    name: 'GPT-3.5 Turbo',
    contextWindow: 16385,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'economy',
    description: '经济实惠的通用模型',
    releasedAt: '2023-11',
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    deprecated: true,
  },
]

// ─── Anthropic ───────────────────────────────────────────────────────────────

const ANTHROPIC_MODELS: ModelPreset[] = [
  // ── Claude 4.6 Series (2026) ──
  {
    id: 'claude-opus-4-6',
    name: 'Claude Opus 4.6',
    contextWindow: 200000,
    maxTokens: 32000,
    capabilities: [...THINKING_VISION, 'code'],
    tier: 'flagship',
    description: '最新旗舰 Claude，极致推理与编程',
    recommended: true,
    releasedAt: '2026-02',
    inputPricePer1M: 15.0,
    outputPricePer1M: 75.0,
    cachedInputPricePer1M: 1.875,
  },
  {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    contextWindow: 200000,
    maxTokens: 16000,
    capabilities: [...THINKING_VISION, 'code'],
    tier: 'balanced',
    description: '最新平衡模型，速度与质量兼顾',
    recommended: true,
    releasedAt: '2026-02',
    inputPricePer1M: 3.0,
    outputPricePer1M: 15.0,
    cachedInputPricePer1M: 0.375,
  },
  // ── Claude 4 Series (2025) ──
  {
    id: 'claude-opus-4-20250514',
    name: 'Claude Opus 4',
    contextWindow: 200000,
    maxTokens: 32000,
    capabilities: [...THINKING_VISION, 'code'],
    tier: 'flagship',
    description: '上一代旗舰 Claude 模型',
    releasedAt: '2025-05',
    inputPricePer1M: 15.0,
    outputPricePer1M: 75.0,
    cachedInputPricePer1M: 1.875,
  },
  {
    id: 'claude-sonnet-4-20250514',
    name: 'Claude Sonnet 4',
    contextWindow: 200000,
    maxTokens: 16000,
    capabilities: [...THINKING_VISION, 'code'],
    tier: 'balanced',
    description: '上一代平衡模型',
    releasedAt: '2025-05',
    inputPricePer1M: 3.0,
    outputPricePer1M: 15.0,
    cachedInputPricePer1M: 0.375,
  },
  // ── Claude 3.5 Series ──
  {
    id: 'claude-3.5-sonnet-20241022',
    name: 'Claude 3.5 Sonnet',
    contextWindow: 200000,
    maxTokens: 8192,
    capabilities: CHAT_VISION,
    tier: 'balanced',
    description: '上一代优秀平衡模型',
    releasedAt: '2024-10',
    inputPricePer1M: 3.0,
    outputPricePer1M: 15.0,
    cachedInputPricePer1M: 0.375,
  },
  {
    id: 'claude-3.5-haiku-20241022',
    name: 'Claude 3.5 Haiku',
    contextWindow: 200000,
    maxTokens: 8192,
    capabilities: CHAT_TOOLS,
    tier: 'fast',
    description: '最快速的 Claude 模型',
    recommended: true,
    releasedAt: '2024-10',
    inputPricePer1M: 0.8,
    outputPricePer1M: 4.0,
    cachedInputPricePer1M: 0.08,
  },
  // ── Claude 3 Series ──
  {
    id: 'claude-3-opus-20240229',
    name: 'Claude 3 Opus',
    contextWindow: 200000,
    maxTokens: 4096,
    capabilities: CHAT_VISION,
    tier: 'flagship',
    description: '上一代旗舰模型',
    releasedAt: '2024-02',
    inputPricePer1M: 15.0,
    outputPricePer1M: 75.0,
    cachedInputPricePer1M: 1.875,
    deprecated: true,
  },
  {
    id: 'claude-3-haiku-20240307',
    name: 'Claude 3 Haiku',
    contextWindow: 200000,
    maxTokens: 4096,
    capabilities: CHAT_VISION,
    tier: 'economy',
    description: '最经济的 Claude 模型',
    releasedAt: '2024-03',
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.25,
    cachedInputPricePer1M: 0.03,
    deprecated: true,
  },
]

// ─── Google AI (Gemini) ──────────────────────────────────────────────────────

const GOOGLE_MODELS: ModelPreset[] = [
  // ── Gemini 3.x Series (2026) ──
  {
    id: 'gemini-3.1-pro-preview',
    name: 'Gemini 3.1 Pro Preview',
    contextWindow: 1048576,
    maxTokens: 65536,
    capabilities: [...THINKING_VISION, 'code', 'audio', 'video', 'web-search', 'image-generation'],
    tier: 'flagship',
    description: '最新旗舰，思考 + 多模态 + 图生成',
    recommended: true,
    releasedAt: '2026-02',
    inputPricePer1M: 1.25,
    outputPricePer1M: 10.0,
    cachedInputPricePer1M: 0.315,
  },
  {
    id: 'gemini-3-flash-preview',
    name: 'Gemini 3 Flash Preview',
    contextWindow: 1048576,
    maxTokens: 65536,
    capabilities: [...THINKING_VISION, 'code', 'audio', 'video', 'web-search'],
    tier: 'balanced',
    description: '最新高速思考模型',
    recommended: true,
    releasedAt: '2026-02',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    cachedInputPricePer1M: 0.0375,
  },
  // ── Gemini 2.5 Series ──
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    contextWindow: 1048576,
    maxTokens: 65536,
    capabilities: [...THINKING_VISION, 'code', 'audio', 'video'],
    tier: 'flagship',
    description: '多模态 + 思考能力，代码与推理',
    releasedAt: '2025-03',
    inputPricePer1M: 1.25,
    outputPricePer1M: 10.0,
    cachedInputPricePer1M: 0.315,
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    contextWindow: 1048576,
    maxTokens: 65536,
    capabilities: [...THINKING_VISION, 'code', 'audio', 'video'],
    tier: 'balanced',
    description: '高速思考模型，性价比出色',
    releasedAt: '2025-03',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    cachedInputPricePer1M: 0.0375,
  },
  // ── Gemini 2.0 Series ──
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    contextWindow: 1048576,
    maxTokens: 8192,
    capabilities: [...CHAT_VISION, 'code', 'audio'],
    tier: 'fast',
    description: '极速多模态模型',
    releasedAt: '2025-02',
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    cachedInputPricePer1M: 0.025,
  },
  {
    id: 'gemini-2.0-flash-lite',
    name: 'Gemini 2.0 Flash Lite',
    contextWindow: 1048576,
    maxTokens: 8192,
    capabilities: CHAT_VISION,
    tier: 'economy',
    description: '成本最低的 Gemini 模型',
    releasedAt: '2025-02',
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.3,
    cachedInputPricePer1M: 0.018,
  },
  // ── Gemini 1.5 Series ──
  {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    contextWindow: 2097152,
    maxTokens: 8192,
    capabilities: [...CHAT_VISION, 'audio', 'video'],
    tier: 'flagship',
    description: '2M 超长上下文多模态模型',
    releasedAt: '2024-09',
    inputPricePer1M: 1.25,
    outputPricePer1M: 5.0,
    cachedInputPricePer1M: 0.315,
  },
  {
    id: 'gemini-1.5-flash',
    name: 'Gemini 1.5 Flash',
    contextWindow: 1048576,
    maxTokens: 8192,
    capabilities: [...CHAT_VISION, 'audio', 'video'],
    tier: 'balanced',
    description: '1M 上下文快速模型',
    releasedAt: '2024-09',
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.3,
    cachedInputPricePer1M: 0.018,
  },
  {
    id: 'gemini-1.5-flash-8b',
    name: 'Gemini 1.5 Flash 8B',
    contextWindow: 1048576,
    maxTokens: 8192,
    capabilities: CHAT_VISION,
    tier: 'economy',
    description: '超轻量 8B 参数，超低成本',
    releasedAt: '2024-10',
    inputPricePer1M: 0.0375,
    outputPricePer1M: 0.15,
    cachedInputPricePer1M: 0.01,
  },
]

// ─── DeepSeek ────────────────────────────────────────────────────────────────

const DEEPSEEK_MODELS: ModelPreset[] = [
  {
    id: 'deepseek-chat',
    name: 'DeepSeek V3',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'balanced',
    description: '通用对话模型 V3，128K 上下文',
    recommended: true,
    releasedAt: '2025-03',
    inputPricePer1M: 0.27,
    outputPricePer1M: 1.1,
    cachedInputPricePer1M: 0.07,
  },
  {
    id: 'deepseek-reasoner',
    name: 'DeepSeek R1',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...THINKING, 'code'],
    tier: 'flagship',
    description: '深度推理模型 R1，复杂问题求解',
    recommended: true,
    releasedAt: '2025-01',
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
    cachedInputPricePer1M: 0.14,
  },
  {
    id: 'deepseek-coder',
    name: 'DeepSeek Coder',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'specialized',
    description: '专业编程模型（映射到 DeepSeek V3）',
    releasedAt: '2025-03',
    inputPricePer1M: 0.27,
    outputPricePer1M: 1.1,
    cachedInputPricePer1M: 0.07,
  },
]

// ─── Zhipu AI (智谱) ─────────────────────────────────────────────────────────

const ZHIPU_MODELS: ModelPreset[] = [
  // ── GLM-5 Series (2026) ──
  {
    id: 'glm-5',
    name: 'GLM-5',
    contextWindow: 128000,
    maxTokens: 8192,
    capabilities: [...FULL_MULTI, 'thinking', 'reasoning'],
    tier: 'flagship',
    description: '最新旗舰 GLM-5，前向兼容',
    recommended: true,
    releasedAt: '2026-01',
    inputPricePer1M: 50.0,
    outputPricePer1M: 50.0,
  },
  {
    id: 'glm-4.7',
    name: 'GLM-4.7',
    contextWindow: 128000,
    maxTokens: 8192,
    capabilities: [...FULL_MULTI, 'thinking', 'reasoning'],
    tier: 'flagship',
    description: 'GLM-4 系列最强版本',
    releasedAt: '2025-12',
    inputPricePer1M: 50.0,
    outputPricePer1M: 50.0,
  },
  {
    id: 'glm-4.6',
    name: 'GLM-4.6',
    contextWindow: 128000,
    maxTokens: 8192,
    capabilities: FULL_MULTI,
    tier: 'balanced',
    description: 'GLM-4 平衡版本',
    releasedAt: '2025-09',
    inputPricePer1M: 25.0,
    outputPricePer1M: 25.0,
  },
  {
    id: 'glm-4.5',
    name: 'GLM-4.5',
    contextWindow: 128000,
    maxTokens: 8192,
    capabilities: FULL_MULTI,
    tier: 'balanced',
    description: 'GLM-4 增强版本',
    releasedAt: '2025-06',
    inputPricePer1M: 25.0,
    outputPricePer1M: 25.0,
  },
  // ── GLM-4 Plus Series ──
  {
    id: 'glm-4-plus',
    name: 'GLM-4 Plus',
    contextWindow: 128000,
    maxTokens: 4096,
    capabilities: FULL_MULTI,
    tier: 'flagship',
    description: '旗舰版 GLM-4，最优效果',
    recommended: true,
    releasedAt: '2024-08',
    inputPricePer1M: 50.0,
    outputPricePer1M: 50.0,
  },
  {
    id: 'glm-4-0520',
    name: 'GLM-4 0520',
    contextWindow: 128000,
    maxTokens: 4096,
    capabilities: FULL_MULTI,
    tier: 'flagship',
    description: 'GLM-4 快照版本',
    releasedAt: '2024-05',
    inputPricePer1M: 100.0,
    outputPricePer1M: 100.0,
  },
  {
    id: 'glm-4',
    name: 'GLM-4',
    contextWindow: 128000,
    maxTokens: 4096,
    capabilities: CHAT_VISION,
    tier: 'balanced',
    description: '标准 GLM-4 模型',
    releasedAt: '2024-01',
    inputPricePer1M: 100.0,
    outputPricePer1M: 100.0,
  },
  {
    id: 'glm-4-air',
    name: 'GLM-4 Air',
    contextWindow: 128000,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'fast',
    description: '轻量快速版本',
    releasedAt: '2024-06',
    inputPricePer1M: 1.0,
    outputPricePer1M: 1.0,
  },
  {
    id: 'glm-4-airx',
    name: 'GLM-4 AirX',
    contextWindow: 8192,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'fast',
    description: 'AirX 极速推理',
    releasedAt: '2024-06',
    inputPricePer1M: 10.0,
    outputPricePer1M: 10.0,
  },
  {
    id: 'glm-4-flash',
    name: 'GLM-4 Flash',
    contextWindow: 128000,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'economy',
    description: '免费闪电模型',
    recommended: true,
    releasedAt: '2024-06',
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
  },
  {
    id: 'glm-4-flashx',
    name: 'GLM-4 FlashX',
    contextWindow: 128000,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'economy',
    description: 'FlashX 极速经济模型',
    releasedAt: '2024-09',
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
  },
  {
    id: 'glm-4-long',
    name: 'GLM-4 Long',
    contextWindow: 1048576,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'specialized',
    description: '1M 超长上下文模型',
    releasedAt: '2024-07',
    inputPricePer1M: 1.0,
    outputPricePer1M: 1.0,
  },
  // ── GLM-4V (Vision) ──
  {
    id: 'glm-4v',
    name: 'GLM-4V',
    contextWindow: 2048,
    maxTokens: 1024,
    capabilities: CHAT_VISION,
    tier: 'specialized',
    description: '多模态视觉模型',
    releasedAt: '2024-06',
    inputPricePer1M: 50.0,
    outputPricePer1M: 50.0,
  },
  {
    id: 'glm-4v-plus',
    name: 'GLM-4V Plus',
    contextWindow: 8192,
    maxTokens: 1024,
    capabilities: [...CHAT_VISION, 'video'],
    tier: 'specialized',
    description: '增强版视觉多模态',
    releasedAt: '2024-10',
    inputPricePer1M: 10.0,
    outputPricePer1M: 10.0,
  },
]

// ─── Moonshot (Kimi) ─────────────────────────────────────────────────────────

const MOONSHOT_MODELS: ModelPreset[] = [
  // ── K2.5 Series ──
  {
    id: 'kimi-k2.5',
    name: 'Kimi K2.5',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...FULL_MULTI, 'reasoning', 'web-search'],
    tier: 'flagship',
    description: '最新旗舰 K2.5 模型，多模态+思考',
    recommended: true,
    releasedAt: '2025-06',
    inputPricePer1M: 8.0,
    outputPricePer1M: 8.0,
  },
  // ── Moonshot V1 Series ──
  {
    id: 'moonshot-v1-128k',
    name: 'Moonshot V1 128K',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: '128K 长上下文模型',
    releasedAt: '2024-03',
    inputPricePer1M: 60.0,
    outputPricePer1M: 60.0,
  },
  {
    id: 'moonshot-v1-32k',
    name: 'Moonshot V1 32K',
    contextWindow: 32768,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: '32K 标准上下文模型',
    releasedAt: '2024-03',
    inputPricePer1M: 24.0,
    outputPricePer1M: 24.0,
  },
  {
    id: 'moonshot-v1-8k',
    name: 'Moonshot V1 8K',
    contextWindow: 8192,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'economy',
    description: '8K 经济模型',
    releasedAt: '2024-03',
    inputPricePer1M: 12.0,
    outputPricePer1M: 12.0,
  },
]

// ─── Bailian (阿里云百炼 / DashScope) ────────────────────────────────────────

const BAILIAN_MODELS: ModelPreset[] = [
  // ── Qwen 3.5 Series (2026) ──
  {
    id: 'qwen3.5-plus',
    name: 'Qwen 3.5 Plus',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: [...FULL_MULTI, 'reasoning'],
    tier: 'balanced',
    description: '最新 Qwen 3.5 系列平衡模型',
    recommended: true,
    releasedAt: '2026-02',
    inputPricePer1M: 0.8,
    outputPricePer1M: 2.0,
  },
  {
    id: 'qwen3.5-flash',
    name: 'Qwen 3.5 Flash',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: CHAT_VISION,
    tier: 'fast',
    description: '极速响应模型',
    releasedAt: '2026-02',
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.6,
  },
  // ── Qwen 3 Series ──
  {
    id: 'qwen3-max',
    name: 'Qwen3 Max',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: [...FULL_MULTI, 'thinking', 'reasoning'],
    tier: 'flagship',
    description: 'Qwen3 旗舰，支持思考模式',
    recommended: true,
    releasedAt: '2025-05',
    inputPricePer1M: 2.4,
    outputPricePer1M: 9.6,
    cachedInputPricePer1M: 0.6,
  },
  {
    id: 'qwen3-coder-plus',
    name: 'Qwen3 Coder Plus',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: [...CHAT_TOOLS, 'code', 'thinking', 'reasoning'],
    tier: 'specialized',
    description: 'Qwen3 专业编程模型',
    recommended: true,
    releasedAt: '2025-06',
    inputPricePer1M: 2.0,
    outputPricePer1M: 6.0,
  },
  // ── Qwen Classic Series ──
  {
    id: 'qwen-max',
    name: 'Qwen Max',
    contextWindow: 32768,
    maxTokens: 8192,
    capabilities: FULL_MULTI,
    tier: 'flagship',
    description: 'Qwen 旗舰模型',
    releasedAt: '2024-11',
    inputPricePer1M: 2.4,
    outputPricePer1M: 9.6,
    cachedInputPricePer1M: 0.6,
  },
  {
    id: 'qwen-plus',
    name: 'Qwen Plus',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: CHAT_VISION,
    tier: 'balanced',
    description: '性能与成本的最佳平衡',
    releasedAt: '2024-09',
    inputPricePer1M: 0.8,
    outputPricePer1M: 2.0,
    cachedInputPricePer1M: 0.2,
  },
  {
    id: 'qwen-turbo',
    name: 'Qwen Turbo',
    contextWindow: 1048576,
    maxTokens: 8192,
    capabilities: CHAT_TOOLS,
    tier: 'fast',
    description: '高速经济模型，1M 上下文',
    releasedAt: '2024-09',
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.6,
    cachedInputPricePer1M: 0.05,
  },
  {
    id: 'qwen-long',
    name: 'Qwen Long',
    contextWindow: 10000000,
    maxTokens: 6000,
    capabilities: ['chat', 'streaming', 'file-upload'],
    tier: 'specialized',
    description: '超长文档处理模型（10M tokens）',
    releasedAt: '2024-05',
    inputPricePer1M: 0.5,
    outputPricePer1M: 2.0,
  },
  // ── QwQ (Reasoning) ──
  {
    id: 'qwq-plus',
    name: 'QwQ Plus',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: THINKING,
    tier: 'balanced',
    description: 'Qwen 推理模型，深度思考',
    releasedAt: '2025-03',
    inputPricePer1M: 1.0,
    outputPricePer1M: 3.0,
    cachedInputPricePer1M: 0.2,
  },
  {
    id: 'qwq-max',
    name: 'QwQ Max',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: THINKING,
    tier: 'flagship',
    description: 'Qwen 旗舰推理模型',
    releasedAt: '2025-04',
    inputPricePer1M: 2.0,
    outputPricePer1M: 8.0,
    cachedInputPricePer1M: 0.5,
  },
  // ── Qwen VL (Vision-Language) ──
  {
    id: 'qwen-vl-max',
    name: 'Qwen VL Max',
    contextWindow: 32768,
    maxTokens: 4096,
    capabilities: [...CHAT_VISION, 'video'],
    tier: 'flagship',
    description: '视觉旗舰多模态',
    releasedAt: '2024-12',
    inputPricePer1M: 3.0,
    outputPricePer1M: 6.0,
  },
  {
    id: 'qwen-vl-plus',
    name: 'Qwen VL Plus',
    contextWindow: 32768,
    maxTokens: 4096,
    capabilities: CHAT_VISION,
    tier: 'balanced',
    description: '视觉平衡模型',
    releasedAt: '2024-08',
    inputPricePer1M: 1.5,
    outputPricePer1M: 3.0,
  },
  // ── 百炼聚合模型 (Cross-Provider via Coding Plan) ──
  {
    id: 'glm-5',
    name: 'GLM-5 (百炼)',
    contextWindow: 128000,
    maxTokens: 8192,
    capabilities: [...FULL_MULTI, 'thinking', 'reasoning'],
    tier: 'flagship',
    description: '智谱 GLM-5 via 百炼聚合',
    releasedAt: '2026-01',
  },
  {
    id: 'glm-4.7',
    name: 'GLM-4.7 (百炼)',
    contextWindow: 128000,
    maxTokens: 8192,
    capabilities: FULL_MULTI,
    tier: 'flagship',
    description: '智谱 GLM-4.7 via 百炼聚合',
    releasedAt: '2025-12',
  },
  {
    id: 'kimi-k2.5',
    name: 'Kimi K2.5 (百炼)',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...FULL_MULTI, 'reasoning', 'web-search'],
    tier: 'flagship',
    description: 'Moonshot Kimi K2.5 via 百炼聚合',
    releasedAt: '2025-06',
  },
  {
    id: 'MiniMax-M2.5',
    name: 'MiniMax M2.5 (百炼)',
    contextWindow: 200000,
    maxTokens: 8192,
    capabilities: FULL_MULTI,
    tier: 'balanced',
    description: 'MiniMax M2.5 via 百炼聚合',
    releasedAt: '2025-03',
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3 (百炼)',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'balanced',
    description: 'DeepSeek V3 via 百炼聚合',
    releasedAt: '2025-03',
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1 (百炼)',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...THINKING, 'code'],
    tier: 'flagship',
    description: 'DeepSeek R1 推理 via 百炼聚合',
    releasedAt: '2025-01',
  },
]

// ─── MiniMax ─────────────────────────────────────────────────────────────────

const MINIMAX_MODELS: ModelPreset[] = [
  {
    id: 'MiniMax-M2.7',
    name: 'MiniMax M2.7',
    contextWindow: 1048576,
    maxTokens: 65536,
    capabilities: [...FULL_MULTI, 'thinking', 'reasoning'],
    tier: 'flagship',
    description: '最新旗舰 MoE 模型，1M 上下文',
    recommended: true,
    releasedAt: '2025-06',
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
  },
  {
    id: 'MiniMax-M2.7-highspeed',
    name: 'MiniMax M2.7 高速',
    contextWindow: 1048576,
    maxTokens: 65536,
    capabilities: [...FULL_MULTI, 'thinking', 'reasoning'],
    tier: 'fast',
    description: 'M2.7 高速推理版本',
    releasedAt: '2025-06',
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.2,
  },
  {
    id: 'MiniMax-M2.5',
    name: 'MiniMax M2.5',
    contextWindow: 1048576,
    maxTokens: 32768,
    capabilities: FULL_MULTI,
    tier: 'balanced',
    description: '上一代旗舰 MoE 模型',
    releasedAt: '2025-03',
    inputPricePer1M: 0.8,
    outputPricePer1M: 3.2,
  },
  {
    id: 'MiniMax-M2.5-highspeed',
    name: 'MiniMax M2.5 高速',
    contextWindow: 1048576,
    maxTokens: 32768,
    capabilities: FULL_MULTI,
    tier: 'fast',
    description: 'M2.5 高速推理版本',
    releasedAt: '2025-03',
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.6,
  },
  {
    id: 'MiniMax-Text-01',
    name: 'MiniMax Text 01',
    contextWindow: 4096000,
    maxTokens: 262144,
    capabilities: CHAT_TOOLS,
    tier: 'specialized',
    description: '超长上下文文本模型（4M tokens）',
    releasedAt: '2025-01',
    inputPricePer1M: 1.0,
    outputPricePer1M: 4.0,
  },
  {
    id: 'MiniMax-VL-01',
    name: 'MiniMax VL-01',
    contextWindow: 200000,
    maxTokens: 8192,
    capabilities: [...CHAT_VISION, 'video'],
    tier: 'specialized',
    description: '视觉多模态模型，支持图文输入',
    releasedAt: '2025-06',
    inputPricePer1M: 0.3,
    outputPricePer1M: 1.2,
  },
]

// ─── Tencent Hunyuan (腾讯混元) ──────────────────────────────────────────────

const TENCENT_HUNYUAN_MODELS: ModelPreset[] = [
  {
    id: 'hunyuan-t1-latest',
    name: '混元 T1',
    contextWindow: 65536,
    maxTokens: 16384,
    capabilities: [...THINKING_VISION, 'code'],
    tier: 'flagship',
    description: '旗舰深度推理模型',
    recommended: true,
    releasedAt: '2025-04',
    inputPricePer1M: 10.0,
    outputPricePer1M: 30.0,
  },
  {
    id: 'hunyuan-turbos-latest',
    name: '混元 TurboS',
    contextWindow: 65536,
    maxTokens: 16384,
    capabilities: FULL_MULTI,
    tier: 'balanced',
    description: '全能对话模型，性价比极高',
    recommended: true,
    releasedAt: '2025-03',
    inputPricePer1M: 1.5,
    outputPricePer1M: 5.0,
  },
  {
    id: 'hunyuan-turbo-latest',
    name: '混元 Turbo',
    contextWindow: 32768,
    maxTokens: 4096,
    capabilities: CHAT_VISION,
    tier: 'balanced',
    description: '对话增强版',
    releasedAt: '2024-09',
    inputPricePer1M: 3.0,
    outputPricePer1M: 6.0,
  },
  {
    id: 'hunyuan-a13b',
    name: '混元 A13B',
    contextWindow: 32768,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'fast',
    description: '轻量快速模型，适合高频调用',
    releasedAt: '2025-06',
    inputPricePer1M: 0.6,
    outputPricePer1M: 1.0,
  },
  {
    id: 'hunyuan-lite',
    name: '混元 Lite',
    contextWindow: 32768,
    maxTokens: 4096,
    capabilities: CHAT_BASE,
    tier: 'economy',
    description: '免费基础模型',
    releasedAt: '2024-06',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
  },
  {
    id: 'hunyuan-vision',
    name: '混元 Vision',
    contextWindow: 8192,
    maxTokens: 4096,
    capabilities: [...CHAT_VISION, 'video'],
    tier: 'specialized',
    description: '专业多模态视觉理解',
    releasedAt: '2024-11',
    inputPricePer1M: 8.0,
    outputPricePer1M: 8.0,
  },
  {
    id: 'hunyuan-role-latest',
    name: '混元 Role',
    contextWindow: 32768,
    maxTokens: 4096,
    capabilities: CHAT_BASE,
    tier: 'specialized',
    description: '角色扮演专用模型',
    releasedAt: '2024-08',
    inputPricePer1M: 2.0,
    outputPricePer1M: 2.0,
  },
  {
    id: 'hunyuan-code-latest',
    name: '混元 Code',
    contextWindow: 65536,
    maxTokens: 16384,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'specialized',
    description: '专业代码生成与理解',
    releasedAt: '2024-12',
    inputPricePer1M: 2.0,
    outputPricePer1M: 6.0,
  },
]

// ─── Ollama (Local Models) ───────────────────────────────────────────────────

const OLLAMA_MODELS: ModelPreset[] = [
  // ── Llama 3.x Series ──
  {
    id: 'llama3.3',
    name: 'Llama 3.3 70B',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'flagship',
    description: '70B 参数，支持工具调用',
    recommended: true,
    releasedAt: '2024-12',
  },
  {
    id: 'llama3.2',
    name: 'Llama 3.2',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: CHAT_VISION,
    tier: 'balanced',
    description: '支持视觉 (11B/90B)',
    releasedAt: '2024-09',
  },
  {
    id: 'llama3.2:1b',
    name: 'Llama 3.2 1B',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: CHAT_BASE,
    tier: 'economy',
    description: '超轻量 1B 参数模型',
    releasedAt: '2024-09',
  },
  {
    id: 'llama3.2:3b',
    name: 'Llama 3.2 3B',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: CHAT_BASE,
    tier: 'economy',
    description: '轻量 3B 参数模型',
    releasedAt: '2024-09',
  },
  {
    id: 'llama3.1',
    name: 'Llama 3.1',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'balanced',
    description: '128K 上下文，工具调用 (8B/70B/405B)',
    releasedAt: '2024-07',
  },
  {
    id: 'llama3.1:70b',
    name: 'Llama 3.1 70B',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'flagship',
    description: '70B 高性能本地模型',
    releasedAt: '2024-07',
  },
  // ── Qwen Series ──
  {
    id: 'qwen3',
    name: 'Qwen 3',
    contextWindow: 40960,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'thinking', 'reasoning', 'code'],
    tier: 'flagship',
    description: 'Qwen3 支持混合思考模式 (0.6B-235B)',
    recommended: true,
    releasedAt: '2025-04',
  },
  {
    id: 'qwen2.5',
    name: 'Qwen 2.5',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'balanced',
    description: '128K 上下文 Qwen 2.5 (0.5B-72B)',
    releasedAt: '2024-09',
  },
  {
    id: 'qwen2.5-coder',
    name: 'Qwen 2.5 Coder',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'specialized',
    description: '专业编程模型 (1.5B-32B)',
    releasedAt: '2024-11',
  },
  // ── DeepSeek Series ──
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...THINKING, 'code'],
    tier: 'flagship',
    description: 'DeepSeek 推理模型 (1.5B-671B)',
    recommended: true,
    releasedAt: '2025-01',
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'balanced',
    description: 'DeepSeek V3 通用模型 (671B MoE)',
    releasedAt: '2025-03',
  },
  // ── Code Focused ──
  {
    id: 'codellama',
    name: 'Code Llama',
    contextWindow: 16384,
    maxTokens: 4096,
    capabilities: ['chat', 'streaming', 'code'],
    tier: 'specialized',
    description: 'Meta 代码专用模型 (7B/13B/34B)',
    releasedAt: '2024-01',
  },
  {
    id: 'starcoder2',
    name: 'StarCoder 2',
    contextWindow: 16384,
    maxTokens: 4096,
    capabilities: ['chat', 'streaming', 'code'],
    tier: 'specialized',
    description: 'BigCode 代码模型 (3B/7B/15B)',
    releasedAt: '2024-02',
  },
  // ── General Purpose ──
  {
    id: 'mistral',
    name: 'Mistral 7B',
    contextWindow: 32768,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'economy',
    description: '轻量高效的 7B 模型',
    releasedAt: '2023-09',
  },
  {
    id: 'mixtral',
    name: 'Mixtral 8x7B',
    contextWindow: 32768,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: 'MoE 混合专家模型',
    releasedAt: '2023-12',
  },
  {
    id: 'phi4',
    name: 'Phi-4',
    contextWindow: 16384,
    maxTokens: 4096,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'balanced',
    description: 'Microsoft 小型高效模型 14B',
    releasedAt: '2024-12',
  },
  {
    id: 'phi3',
    name: 'Phi-3',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'economy',
    description: 'Microsoft 超轻量模型 (3.8B)',
    releasedAt: '2024-04',
  },
  {
    id: 'gemma2',
    name: 'Gemma 2',
    contextWindow: 8192,
    maxTokens: 4096,
    capabilities: CHAT_BASE,
    tier: 'economy',
    description: 'Google 开源轻量模型 (2B/9B/27B)',
    releasedAt: '2024-06',
  },
  {
    id: 'command-r-plus',
    name: 'Command R+',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: [...CHAT_TOOLS, 'web-search'],
    tier: 'flagship',
    description: 'Cohere 旗舰检索增强模型 104B',
    releasedAt: '2024-04',
  },
  {
    id: 'command-r',
    name: 'Command R',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: [...CHAT_TOOLS, 'web-search'],
    tier: 'balanced',
    description: 'Cohere RAG 模型 35B',
    releasedAt: '2024-03',
  },
]

// ─── Volcengine / ByteDance (火山引擎 / 字节跳动) ────────────────────────────

const VOLCENGINE_MODELS: ModelPreset[] = [
  // ── Doubao Seed 1.8 Series (2025-2026) ──
  {
    id: 'doubao-seed-1-8-251228',
    name: '豆包 Seed 1.8',
    contextWindow: 262144,
    maxTokens: 16384,
    capabilities: [...FULL_MULTI, 'thinking', 'reasoning'],
    tier: 'flagship',
    description: '最新旗舰 Seed 1.8 模型',
    recommended: true,
    releasedAt: '2025-12',
    inputPricePer1M: 0.8,
    outputPricePer1M: 2.0,
  },
  {
    id: 'doubao-seed-code-preview-251028',
    name: '豆包 Seed Code Preview',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: [...CHAT_TOOLS, 'code', 'reasoning'],
    tier: 'specialized',
    description: '专业编程模型',
    recommended: true,
    releasedAt: '2025-10',
    inputPricePer1M: 0.8,
    outputPricePer1M: 2.0,
  },
  // ── 火山聚合模型 (Cross-Provider) ──
  {
    id: 'kimi-k2-5-260127',
    name: 'Kimi K2.5 (火山)',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...FULL_MULTI, 'reasoning'],
    tier: 'flagship',
    description: 'Kimi K2.5 via 火山引擎',
    releasedAt: '2026-01',
  },
  {
    id: 'glm-4-7-251222',
    name: 'GLM-4.7 (火山)',
    contextWindow: 128000,
    maxTokens: 8192,
    capabilities: FULL_MULTI,
    tier: 'flagship',
    description: '智谱 GLM-4.7 via 火山引擎',
    releasedAt: '2025-12',
  },
  {
    id: 'deepseek-v3-2-251201',
    name: 'DeepSeek V3.2 (火山)',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'balanced',
    description: 'DeepSeek V3.2 128K via 火山引擎',
    releasedAt: '2025-12',
  },
  // ── Doubao 1.5 Series ──
  {
    id: 'doubao-1.5-pro-256k',
    name: '豆包 1.5 Pro 256K',
    contextWindow: 262144,
    maxTokens: 16384,
    capabilities: FULL_MULTI,
    tier: 'flagship',
    description: '豆包旗舰版 256K 上下文',
    recommended: true,
    releasedAt: '2025-02',
    inputPricePer1M: 0.8,
    outputPricePer1M: 2.0,
  },
  {
    id: 'doubao-1.5-pro-32k',
    name: '豆包 1.5 Pro 32K',
    contextWindow: 32768,
    maxTokens: 16384,
    capabilities: FULL_MULTI,
    tier: 'balanced',
    description: '豆包 Pro 标准模型',
    releasedAt: '2025-02',
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.3,
  },
  {
    id: 'doubao-1.5-lite-32k',
    name: '豆包 1.5 Lite 32K',
    contextWindow: 32768,
    maxTokens: 16384,
    capabilities: CHAT_TOOLS,
    tier: 'economy',
    description: '豆包轻量版，超低成本',
    releasedAt: '2025-02',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.3,
  },
  {
    id: 'doubao-vision-pro-32k',
    name: '豆包 Vision Pro',
    contextWindow: 32768,
    maxTokens: 4096,
    capabilities: [...CHAT_VISION, 'video'],
    tier: 'specialized',
    description: '多模态视觉理解模型',
    releasedAt: '2024-12',
    inputPricePer1M: 3.0,
    outputPricePer1M: 6.0,
  },
  {
    id: 'doubao-thinking-pro-128k',
    name: '豆包 Thinking Pro',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: [...THINKING, 'code'],
    tier: 'flagship',
    description: '深度推理模型 128K 上下文',
    recommended: true,
    releasedAt: '2025-04',
    inputPricePer1M: 4.0,
    outputPricePer1M: 16.0,
  },
  {
    id: 'deepseek-v3-250324',
    name: 'DeepSeek V3 (火山)',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'balanced',
    description: '火山引擎托管 DeepSeek V3',
    releasedAt: '2025-03',
    inputPricePer1M: 0.27,
    outputPricePer1M: 1.1,
  },
  {
    id: 'deepseek-r1-250120',
    name: 'DeepSeek R1 (火山)',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...THINKING, 'code'],
    tier: 'flagship',
    description: '火山引擎托管 DeepSeek R1',
    releasedAt: '2025-01',
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
  },
]

// ─── SiliconFlow (硅流) ──────────────────────────────────────────────────────

const SILICONFLOW_MODELS: ModelPreset[] = [
  {
    id: 'deepseek-ai/DeepSeek-V3',
    name: 'DeepSeek V3',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'balanced',
    description: 'DeepSeek V3 671B MoE',
    recommended: true,
    releasedAt: '2025-03',
    inputPricePer1M: 0.27,
    outputPricePer1M: 1.1,
  },
  {
    id: 'deepseek-ai/DeepSeek-R1',
    name: 'DeepSeek R1',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...THINKING, 'code'],
    tier: 'flagship',
    description: 'DeepSeek R1 推理模型',
    recommended: true,
    releasedAt: '2025-01',
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
  },
  {
    id: 'Qwen/Qwen3-235B-A22B',
    name: 'Qwen3 235B',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: [...CHAT_TOOLS, 'thinking', 'reasoning', 'code'],
    tier: 'flagship',
    description: 'Qwen3 MoE 旗舰 235B',
    releasedAt: '2025-04',
    inputPricePer1M: 1.0,
    outputPricePer1M: 4.0,
  },
  {
    id: 'Qwen/Qwen3-30B-A3B',
    name: 'Qwen3 30B A3B',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: [...CHAT_TOOLS, 'thinking', 'reasoning', 'code'],
    tier: 'balanced',
    description: 'Qwen3 轻量 MoE 模型',
    releasedAt: '2025-04',
    inputPricePer1M: 0.35,
    outputPricePer1M: 1.4,
  },
  {
    id: 'Qwen/Qwen2.5-Coder-32B-Instruct',
    name: 'Qwen 2.5 Coder 32B',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'specialized',
    description: 'Qwen 编程模型 32B',
    releasedAt: '2024-11',
    inputPricePer1M: 0.6,
    outputPricePer1M: 0.6,
  },
  {
    id: 'Pro/google/gemma-2-9b-it',
    name: 'Gemma 2 9B',
    contextWindow: 8192,
    maxTokens: 4096,
    capabilities: CHAT_BASE,
    tier: 'economy',
    description: 'Google Gemma 2 轻量模型',
    releasedAt: '2024-06',
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
  },
  {
    id: 'meta-llama/Llama-3.3-70B-Instruct',
    name: 'Llama 3.3 70B',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'flagship',
    description: 'Meta Llama 3.3 旗舰',
    releasedAt: '2024-12',
    inputPricePer1M: 0.7,
    outputPricePer1M: 0.7,
  },
]

// ─── Mistral AI ──────────────────────────────────────────────────────────────

const MISTRAL_MODELS: ModelPreset[] = [
  {
    id: 'mistral-large-latest',
    name: 'Mistral Large',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: FULL_MULTI,
    tier: 'flagship',
    description: '旗舰模型，多模态/工具',
    recommended: true,
    releasedAt: '2025-03',
    inputPricePer1M: 2.0,
    outputPricePer1M: 6.0,
  },
  {
    id: 'mistral-medium-latest',
    name: 'Mistral Medium',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: '平衡模型',
    releasedAt: '2025-04',
    inputPricePer1M: 0.4,
    outputPricePer1M: 2.0,
  },
  {
    id: 'mistral-small-latest',
    name: 'Mistral Small',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: CHAT_VISION,
    tier: 'fast',
    description: '高效轻量模型',
    releasedAt: '2025-02',
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
  },
  {
    id: 'codestral-latest',
    name: 'Codestral',
    contextWindow: 262144,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'specialized',
    description: '专业代码模型 256K',
    recommended: true,
    releasedAt: '2025-05',
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.9,
  },
  {
    id: 'open-mistral-nemo',
    name: 'Mistral Nemo',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: CHAT_TOOLS,
    tier: 'economy',
    description: '12B 开源级模型',
    releasedAt: '2024-07',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.15,
  },
  {
    id: 'pixtral-large-latest',
    name: 'Pixtral Large',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...CHAT_VISION, 'code'],
    tier: 'flagship',
    description: '视觉旗舰模型 124B',
    releasedAt: '2024-11',
    inputPricePer1M: 2.0,
    outputPricePer1M: 6.0,
  },
]

// ─── xAI (Grok) ─────────────────────────────────────────────────────────────

const XAI_MODELS: ModelPreset[] = [
  {
    id: 'grok-3',
    name: 'Grok 3',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: FULL_MULTI,
    tier: 'flagship',
    description: '最强 Grok 模型',
    recommended: true,
    releasedAt: '2025-02',
    inputPricePer1M: 3.0,
    outputPricePer1M: 15.0,
  },
  {
    id: 'grok-3-fast',
    name: 'Grok 3 Fast',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: FULL_MULTI,
    tier: 'fast',
    description: 'Grok 3 高速版',
    releasedAt: '2025-02',
    inputPricePer1M: 5.0,
    outputPricePer1M: 25.0,
  },
  {
    id: 'grok-3-mini',
    name: 'Grok 3 Mini',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: THINKING,
    tier: 'balanced',
    description: '轻量推理模型',
    recommended: true,
    releasedAt: '2025-02',
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.5,
  },
  {
    id: 'grok-3-mini-fast',
    name: 'Grok 3 Mini Fast',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: THINKING,
    tier: 'fast',
    description: 'Mini 高速版',
    releasedAt: '2025-02',
    inputPricePer1M: 0.6,
    outputPricePer1M: 4.0,
  },
  {
    id: 'grok-2',
    name: 'Grok 2',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: CHAT_VISION,
    tier: 'balanced',
    description: '上一代 Grok 模型',
    releasedAt: '2024-08',
    inputPricePer1M: 2.0,
    outputPricePer1M: 10.0,
  },
]

// ─── Together.ai ─────────────────────────────────────────────────────────────

const TOGETHER_MODELS: ModelPreset[] = [
  {
    id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    name: 'Llama 3.3 70B Turbo',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'flagship',
    description: 'Meta 旗舰模型加速版',
    recommended: true,
    releasedAt: '2024-12',
    inputPricePer1M: 0.88,
    outputPricePer1M: 0.88,
  },
  {
    id: 'deepseek-ai/DeepSeek-R1',
    name: 'DeepSeek R1',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...THINKING, 'code'],
    tier: 'flagship',
    description: 'DeepSeek R1 推理模型',
    recommended: true,
    releasedAt: '2025-01',
    inputPricePer1M: 3.0,
    outputPricePer1M: 7.0,
  },
  {
    id: 'deepseek-ai/DeepSeek-V3',
    name: 'DeepSeek V3',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'balanced',
    description: '通用 V3 模型',
    releasedAt: '2025-03',
    inputPricePer1M: 0.9,
    outputPricePer1M: 0.9,
  },
  {
    id: 'Qwen/Qwen2.5-72B-Instruct-Turbo',
    name: 'Qwen 2.5 72B Turbo',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'flagship',
    description: 'Qwen 2.5 旗舰加速版',
    releasedAt: '2024-09',
    inputPricePer1M: 1.2,
    outputPricePer1M: 1.2,
  },
  {
    id: 'Qwen/Qwen2.5-Coder-32B-Instruct',
    name: 'Qwen 2.5 Coder 32B',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'specialized',
    description: 'Qwen 编程模型',
    releasedAt: '2024-11',
    inputPricePer1M: 0.9,
    outputPricePer1M: 0.9,
  },
  {
    id: 'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo',
    name: 'Llama 3.1 405B Turbo',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'flagship',
    description: '最大开源模型 405B 加速版',
    releasedAt: '2024-07',
    inputPricePer1M: 3.5,
    outputPricePer1M: 3.5,
  },
  {
    id: 'google/gemma-2-27b-it',
    name: 'Gemma 2 27B',
    contextWindow: 8192,
    maxTokens: 4096,
    capabilities: CHAT_BASE,
    tier: 'economy',
    description: 'Google Gemma2 中型',
    releasedAt: '2024-06',
    inputPricePer1M: 0.27,
    outputPricePer1M: 0.27,
  },
  {
    id: 'mistralai/Mixtral-8x22B-Instruct-v0.1',
    name: 'Mixtral 8x22B',
    contextWindow: 65536,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: 'Mistral MoE 模型 8x22B',
    releasedAt: '2024-04',
    inputPricePer1M: 0.9,
    outputPricePer1M: 0.9,
  },
]

// ─── OpenRouter ──────────────────────────────────────────────────────────────

const OPENROUTER_MODELS: ModelPreset[] = [
  {
    id: 'anthropic/claude-sonnet-4',
    name: 'Claude Sonnet 4',
    contextWindow: 200000,
    maxTokens: 16000,
    capabilities: [...THINKING_VISION, 'code'],
    tier: 'balanced',
    description: 'Anthropic 旗舰平衡',
    recommended: true,
    releasedAt: '2025-05',
    inputPricePer1M: 3.0,
    outputPricePer1M: 15.0,
  },
  {
    id: 'google/gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    contextWindow: 1048576,
    maxTokens: 65536,
    capabilities: [...THINKING_VISION, 'code'],
    tier: 'balanced',
    description: 'Google 高速思考',
    recommended: true,
    releasedAt: '2025-03',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
  },
  {
    id: 'openai/gpt-4.1',
    name: 'GPT-4.1',
    contextWindow: 1047576,
    maxTokens: 32768,
    capabilities: FULL_MULTI,
    tier: 'flagship',
    description: 'OpenAI 最新旗舰',
    releasedAt: '2025-04',
    inputPricePer1M: 2.0,
    outputPricePer1M: 8.0,
  },
  {
    id: 'openai/o4-mini',
    name: 'o4-mini',
    contextWindow: 200000,
    maxTokens: 100000,
    capabilities: THINKING_VISION,
    tier: 'balanced',
    description: 'OpenAI 高效推理',
    releasedAt: '2025-04',
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
  },
  {
    id: 'deepseek/deepseek-chat',
    name: 'DeepSeek V3',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'economy',
    description: 'DeepSeek V3 经济模型',
    releasedAt: '2025-03',
    inputPricePer1M: 0.27,
    outputPricePer1M: 1.1,
  },
  {
    id: 'deepseek/deepseek-r1',
    name: 'DeepSeek R1',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: [...THINKING, 'code'],
    tier: 'balanced',
    description: 'DeepSeek R1 推理',
    releasedAt: '2025-01',
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'balanced',
    description: 'Meta 开源旗舰 70B',
    releasedAt: '2024-12',
    inputPricePer1M: 0.39,
    outputPricePer1M: 0.39,
  },
  {
    id: 'x-ai/grok-3-mini',
    name: 'Grok 3 Mini',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: THINKING,
    tier: 'economy',
    description: 'xAI 轻量推理',
    releasedAt: '2025-02',
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.5,
  },
  {
    id: 'mistralai/mistral-large-latest',
    name: 'Mistral Large',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: FULL_MULTI,
    tier: 'flagship',
    description: 'Mistral 旗舰',
    releasedAt: '2025-02',
    inputPricePer1M: 2.0,
    outputPricePer1M: 6.0,
  },
]

// ─── Groq ────────────────────────────────────────────────────────────────────

const GROQ_MODELS: ModelPreset[] = [
  {
    id: 'llama-3.3-70b-versatile',
    name: 'Llama 3.3 70B',
    contextWindow: 131072,
    maxTokens: 32768,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'flagship',
    description: '70B 极速推理 (LPU)',
    recommended: true,
    releasedAt: '2024-12',
    inputPricePer1M: 0.59,
    outputPricePer1M: 0.79,
  },
  {
    id: 'llama-3.1-8b-instant',
    name: 'Llama 3.1 8B',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: CHAT_TOOLS,
    tier: 'economy',
    description: '8B 超低延迟',
    releasedAt: '2024-07',
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.08,
  },
  {
    id: 'deepseek-r1-distill-llama-70b',
    name: 'DeepSeek R1 Distill 70B',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: THINKING,
    tier: 'flagship',
    description: 'R1 蒸馏版极速推理',
    recommended: true,
    releasedAt: '2025-01',
    inputPricePer1M: 0.75,
    outputPricePer1M: 0.99,
  },
  {
    id: 'qwen-qwq-32b',
    name: 'QwQ 32B',
    contextWindow: 131072,
    maxTokens: 16384,
    capabilities: THINKING,
    tier: 'balanced',
    description: 'Qwen 推理模型极速版',
    releasedAt: '2025-03',
    inputPricePer1M: 0.29,
    outputPricePer1M: 0.39,
  },
  {
    id: 'gemma2-9b-it',
    name: 'Gemma 2 9B',
    contextWindow: 8192,
    maxTokens: 4096,
    capabilities: CHAT_BASE,
    tier: 'economy',
    description: 'Google 轻量模型超速',
    releasedAt: '2024-06',
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.2,
  },
  {
    id: 'mistral-saba-24b',
    name: 'Mistral Saba 24B',
    contextWindow: 32768,
    maxTokens: 8192,
    capabilities: CHAT_TOOLS,
    tier: 'economy',
    description: 'Mistral 轻量模型',
    releasedAt: '2025-02',
    inputPricePer1M: 0.29,
    outputPricePer1M: 0.39,
  },
]

// ─── AWS Bedrock ─────────────────────────────────────────────────────────────

const BEDROCK_MODELS: ModelPreset[] = [
  {
    id: 'anthropic.claude-sonnet-4-20250514-v1:0',
    name: 'Claude Sonnet 4',
    contextWindow: 200000,
    maxTokens: 16000,
    capabilities: [...THINKING_VISION, 'code'],
    tier: 'balanced',
    description: 'Anthropic 旗舰平衡模型',
    recommended: true,
    releasedAt: '2025-05',
    inputPricePer1M: 3.0,
    outputPricePer1M: 15.0,
  },
  {
    id: 'anthropic.claude-opus-4-20250514-v1:0',
    name: 'Claude Opus 4',
    contextWindow: 200000,
    maxTokens: 32000,
    capabilities: [...THINKING_VISION, 'code'],
    tier: 'flagship',
    description: 'Anthropic 旗舰模型',
    releasedAt: '2025-05',
    inputPricePer1M: 15.0,
    outputPricePer1M: 75.0,
  },
  {
    id: 'anthropic.claude-3-5-haiku-20241022-v1:0',
    name: 'Claude 3.5 Haiku',
    contextWindow: 200000,
    maxTokens: 8192,
    capabilities: CHAT_TOOLS,
    tier: 'fast',
    description: '最快的 Claude 模型',
    releasedAt: '2024-10',
    inputPricePer1M: 0.8,
    outputPricePer1M: 4.0,
  },
  {
    id: 'amazon.nova-pro-v1:0',
    name: 'Amazon Nova Pro',
    contextWindow: 300000,
    maxTokens: 5000,
    capabilities: [...CHAT_VISION, 'video'],
    tier: 'balanced',
    description: 'AWS Nova 多模态模型',
    releasedAt: '2024-12',
    inputPricePer1M: 0.8,
    outputPricePer1M: 3.2,
  },
  {
    id: 'amazon.nova-lite-v1:0',
    name: 'Amazon Nova Lite',
    contextWindow: 300000,
    maxTokens: 5000,
    capabilities: [...CHAT_VISION, 'video'],
    tier: 'economy',
    description: 'Nova 轻量版，超低成本',
    releasedAt: '2024-12',
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.24,
  },
  {
    id: 'amazon.nova-micro-v1:0',
    name: 'Amazon Nova Micro',
    contextWindow: 128000,
    maxTokens: 5000,
    capabilities: CHAT_BASE,
    tier: 'economy',
    description: 'Nova 纯文本极速模型',
    releasedAt: '2024-12',
    inputPricePer1M: 0.035,
    outputPricePer1M: 0.14,
  },
  {
    id: 'meta.llama3-3-70b-instruct-v1:0',
    name: 'Llama 3.3 70B',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: [...CHAT_TOOLS, 'code'],
    tier: 'flagship',
    description: 'Meta Llama 3.3 on Bedrock',
    releasedAt: '2024-12',
    inputPricePer1M: 0.72,
    outputPricePer1M: 0.72,
  },
  {
    id: 'mistral.mistral-large-2411-v1:0',
    name: 'Mistral Large',
    contextWindow: 131072,
    maxTokens: 8192,
    capabilities: FULL_MULTI,
    tier: 'flagship',
    description: 'Mistral 旗舰 on Bedrock',
    releasedAt: '2024-11',
    inputPricePer1M: 2.0,
    outputPricePer1M: 6.0,
  },
]

// ─── Cohere ──────────────────────────────────────────────────────────────────

const COHERE_MODELS: ModelPreset[] = [
  {
    id: 'command-a',
    name: 'Command A',
    contextWindow: 262144,
    maxTokens: 8192,
    capabilities: [...CHAT_TOOLS, 'web-search', 'code'],
    tier: 'flagship',
    description: '最新旗舰 Agentic 模型 256K',
    recommended: true,
    releasedAt: '2025-03',
    inputPricePer1M: 2.5,
    outputPricePer1M: 10.0,
  },
  {
    id: 'command-r-plus',
    name: 'Command R+',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: [...CHAT_TOOLS, 'web-search'],
    tier: 'balanced',
    description: '检索增强模型 104B',
    releasedAt: '2024-04',
    inputPricePer1M: 2.5,
    outputPricePer1M: 10.0,
  },
  {
    id: 'command-r',
    name: 'Command R',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: [...CHAT_TOOLS, 'web-search'],
    tier: 'economy',
    description: '轻量 RAG 模型 35B',
    releasedAt: '2024-03',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
  },
  {
    id: 'command-nightly',
    name: 'Command (Nightly)',
    contextWindow: 131072,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: 'Nightly 最新预览版',
    releasedAt: '2024-01',
    inputPricePer1M: 1.0,
    outputPricePer1M: 2.0,
  },
]

// ─── Coding Plan Model Presets ────────────────────────────────────────────────

const CODEX_MODELS: ModelPreset[] = [
  {
    id: 'gpt-5.4',
    name: 'GPT-5.4 (Codex)',
    contextWindow: 1047576,
    maxTokens: 32768,
    capabilities: [...FULL_MULTI, 'thinking', 'reasoning'],
    tier: 'flagship',
    description: '最新旗舰模型，通过 Codex 订阅使用',
    recommended: true,
    releasedAt: '2026-01',
  },
  {
    id: 'gpt-5.3-codex-spark',
    name: 'GPT-5.3 Codex Spark',
    contextWindow: 1047576,
    maxTokens: 32768,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: '轻量 Codex 模型，快速响应',
    releasedAt: '2026-01',
  },
]

const KIMI_CODING_MODELS: ModelPreset[] = [
  {
    id: 'k2p5',
    name: 'Kimi for Coding',
    contextWindow: 262144,
    maxTokens: 32768,
    capabilities: [...THINKING_VISION],
    tier: 'flagship',
    description: 'Kimi Coding 旗舰，支持推理与多模态',
    recommended: true,
    releasedAt: '2025-06',
  },
  {
    id: 'kimi-k2.5',
    name: 'Kimi K2.5',
    contextWindow: 262144,
    maxTokens: 32768,
    capabilities: [...THINKING_VISION],
    tier: 'flagship',
    description: 'Kimi K2.5 多模态推理',
    releasedAt: '2025-06',
  },
  {
    id: 'kimi-k2-thinking',
    name: 'Kimi K2 Thinking',
    contextWindow: 262144,
    maxTokens: 32768,
    capabilities: THINKING,
    tier: 'balanced',
    description: '深度推理模型',
    releasedAt: '2025-06',
  },
  {
    id: 'kimi-k2-thinking-turbo',
    name: 'Kimi K2 Thinking Turbo',
    contextWindow: 262144,
    maxTokens: 32768,
    capabilities: THINKING,
    tier: 'balanced',
    description: '快速推理模型',
    releasedAt: '2025-06',
  },
]

const MODELSTUDIO_MODELS: ModelPreset[] = [
  {
    id: 'qwen3.5-plus',
    name: 'Qwen 3.5 Plus',
    contextWindow: 1000000,
    maxTokens: 65536,
    capabilities: CHAT_VISION,
    tier: 'flagship',
    description: '百炼 Coding Plan 旗舰，1M 上下文',
    recommended: true,
    releasedAt: '2025-06',
  },
  {
    id: 'qwen3-coder-next',
    name: 'Qwen 3 Coder Next',
    contextWindow: 262144,
    maxTokens: 65536,
    capabilities: CHAT_TOOLS,
    tier: 'flagship',
    description: 'Qwen 编程专用模型',
    recommended: true,
    releasedAt: '2025-01',
  },
  {
    id: 'qwen3-coder-plus',
    name: 'Qwen 3 Coder Plus',
    contextWindow: 1000000,
    maxTokens: 65536,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: 'Qwen 编程模型 1M 上下文',
    releasedAt: '2025-01',
  },
  {
    id: 'qwen3-max-2026-01-23',
    name: 'Qwen 3 Max',
    contextWindow: 262144,
    maxTokens: 65536,
    capabilities: CHAT_TOOLS,
    tier: 'flagship',
    description: 'Qwen 3 旗舰',
    releasedAt: '2026-01',
  },
  {
    id: 'MiniMax-M2.5',
    name: 'MiniMax M2.5',
    contextWindow: 1000000,
    maxTokens: 65536,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: 'MiniMax M2.5（百炼聚合）',
    releasedAt: '2025-06',
  },
  {
    id: 'glm-5',
    name: 'GLM-5',
    contextWindow: 202752,
    maxTokens: 16384,
    capabilities: CHAT_TOOLS,
    tier: 'flagship',
    description: 'GLM-5（百炼聚合）',
    releasedAt: '2025-06',
  },
  {
    id: 'glm-4.7',
    name: 'GLM-4.7',
    contextWindow: 202752,
    maxTokens: 16384,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: 'GLM-4.7（百炼聚合）',
    releasedAt: '2025-03',
  },
  {
    id: 'kimi-k2.5',
    name: 'Kimi K2.5',
    contextWindow: 262144,
    maxTokens: 32768,
    capabilities: CHAT_VISION,
    tier: 'balanced',
    description: 'Kimi K2.5（百炼聚合）',
    releasedAt: '2025-06',
  },
]

const VOLCENGINE_PLAN_MODELS: ModelPreset[] = [
  {
    id: 'ark-code-latest',
    name: 'Ark Coding Plan',
    contextWindow: 256000,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'flagship',
    description: 'Ark 综合编程模型',
    recommended: true,
    releasedAt: '2025-06',
  },
  {
    id: 'doubao-seed-code',
    name: 'Doubao Seed Code',
    contextWindow: 256000,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: '豆包编程专用模型',
    releasedAt: '2025-06',
  },
  {
    id: 'doubao-seed-code-preview-251028',
    name: 'Doubao Seed Code Preview',
    contextWindow: 256000,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: '豆包编程预览版',
    releasedAt: '2025-10',
  },
  {
    id: 'kimi-k2.5',
    name: 'Kimi K2.5 Coding',
    contextWindow: 256000,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: 'Kimi K2.5（火山聚合）',
    releasedAt: '2025-06',
  },
  {
    id: 'kimi-k2-thinking',
    name: 'Kimi K2 Thinking',
    contextWindow: 256000,
    maxTokens: 4096,
    capabilities: THINKING,
    tier: 'balanced',
    description: 'Kimi K2 推理（火山聚合）',
    releasedAt: '2025-06',
  },
  {
    id: 'glm-4.7',
    name: 'GLM 4.7 Coding',
    contextWindow: 200000,
    maxTokens: 4096,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: 'GLM 4.7（火山聚合）',
    releasedAt: '2025-03',
  },
]

const ZAI_MODELS: ModelPreset[] = [
  {
    id: 'glm-5',
    name: 'GLM-5',
    contextWindow: 202752,
    maxTokens: 16384,
    capabilities: [...THINKING],
    tier: 'flagship',
    description: '智谱最新旗舰，深度推理',
    recommended: true,
    releasedAt: '2025-06',
  },
  {
    id: 'glm-5-turbo',
    name: 'GLM-5 Turbo',
    contextWindow: 202752,
    maxTokens: 16384,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: 'GLM-5 高速版',
    releasedAt: '2025-06',
  },
  {
    id: 'glm-4.7',
    name: 'GLM-4.7',
    contextWindow: 202752,
    maxTokens: 16384,
    capabilities: CHAT_TOOLS,
    tier: 'balanced',
    description: 'GLM-4.7 均衡模型',
    releasedAt: '2025-03',
  },
  {
    id: 'glm-4.7-flash',
    name: 'GLM-4.7 Flash',
    contextWindow: 202752,
    maxTokens: 16384,
    capabilities: CHAT_TOOLS,
    tier: 'economy',
    description: 'GLM-4.7 快速低成本',
    releasedAt: '2025-03',
  },
  {
    id: 'glm-4.7-flashx',
    name: 'GLM-4.7 FlashX',
    contextWindow: 202752,
    maxTokens: 16384,
    capabilities: CHAT_TOOLS,
    tier: 'economy',
    description: 'GLM-4.7 极速版',
    releasedAt: '2025-03',
  },
]

const MINIMAX_CODING_MODELS: ModelPreset[] = [
  {
    id: 'MiniMax-M2.7',
    name: 'MiniMax M2.7',
    contextWindow: 1000000,
    maxTokens: 65536,
    capabilities: [...THINKING],
    tier: 'flagship',
    description: 'MiniMax 最新旗舰，1M 上下文',
    recommended: true,
    releasedAt: '2025-06',
  },
  {
    id: 'MiniMax-M2.7-highspeed',
    name: 'MiniMax M2.7 Highspeed',
    contextWindow: 1000000,
    maxTokens: 65536,
    capabilities: [...THINKING],
    tier: 'balanced',
    description: '高速推理版',
    releasedAt: '2025-06',
  },
  {
    id: 'MiniMax-M2.5',
    name: 'MiniMax M2.5',
    contextWindow: 1000000,
    maxTokens: 65536,
    capabilities: [...THINKING],
    tier: 'balanced',
    description: 'MiniMax M2.5 推理',
    releasedAt: '2025-06',
  },
  {
    id: 'MiniMax-M2.5-highspeed',
    name: 'MiniMax M2.5 Highspeed',
    contextWindow: 1000000,
    maxTokens: 65536,
    capabilities: CHAT_TOOLS,
    tier: 'economy',
    description: '极速推理版',
    releasedAt: '2025-06',
  },
]

// ═════════════════════════════════════════════════════════════════════════════
// ─── Provider Presets Registry ───────────────────────────────────────────────
// ═════════════════════════════════════════════════════════════════════════════

export const PROVIDER_PRESETS: ProviderPreset[] = [
  // ── Global Providers ──
  {
    id: 'openai',
    name: 'OpenAI',
    description: 'GPT-5.4、GPT-4.1 与 O 系列推理模型',
    category: 'global',
    baseUrl: 'https://api.openai.com/v1',
    auth: 'api-key',
    apiKeyPlaceholder: 'sk-proj-...',
    models: OPENAI_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://platform.openai.com',
    brandColor: '#10A37F',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://docs.openclaw.ai/providers/openai',
      apiKeyUrl: 'https://platform.openai.com/api-keys',
      pricingUrl: 'https://openai.com/api/pricing/',
      codingPlanUrl: 'https://openai.com/codex/',
      steps: [
        '打开 OpenAI 平台 → API Keys 页面，创建一个新的 API Key。',
        '建议为 Shadow 创建独立的 Project，便于控费。',
        '将 API Key 粘贴在下方，点击保存即可。',
      ],
      tips: [
        '推荐使用 gpt-5.4 最新旗舰模型。',
        'gpt-4.1-mini 性价比极高，适合日常使用。',
        'o4-mini 适合需要深度推理的场景。',
        '设置 Usage Limits 可以避免意外高额账单。',
        'Codex 订阅用户可通过 OAuth 免 API Key 接入。',
      ],
    },
    codingPlan: {
      name: 'OpenAI Codex',
      url: 'https://openai.com/codex/',
      description: 'ChatGPT Plus/Pro 订阅即可使用 Codex，免 API Key',
      models: ['gpt-5.4', 'gpt-5.3-codex-spark'],
      pricing: '订阅制',
      planProviderId: 'openai-codex',
    },
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    description: 'Claude 4.6 旗舰与 Claude 4 系列模型',
    category: 'global',
    baseUrl: 'https://api.anthropic.com/v1',
    auth: 'api-key',
    apiKeyPlaceholder: 'sk-ant-...',
    models: ANTHROPIC_MODELS,
    openaiCompatible: false,
    websiteUrl: 'https://console.anthropic.com',
    brandColor: '#D97706',
    apiFormat: 'anthropic-messages',
    guide: {
      docsUrl: 'https://docs.openclaw.ai/providers/anthropic',
      apiKeyUrl: 'https://console.anthropic.com/settings/keys',
      pricingUrl: 'https://www.anthropic.com/pricing',
      codingPlanUrl: 'https://code.claude.com/docs/en/overview',
      steps: [
        '登录 Anthropic Console → Settings → API Keys，创建密钥。',
        '选择合适的模型：Sonnet 4 平衡最优，Opus 4 极致质量。',
        '粘贴 API Key 并保存即可。',
      ],
      tips: [
        'Claude Sonnet 4.6 是日常使用的最佳选择。',
        'Claude Opus 4.6 适合极致质量与复杂推理。',
        'Claude Code 订阅可通过 setup-token 接入。',
        'Claude 支持 200K 上下文，适合长文档处理。',
      ],
    },
  },
  {
    id: 'google',
    name: 'Google AI',
    description: 'Gemini 3.1/2.5 系列多模态 AI 模型',
    category: 'global',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    auth: 'api-key',
    apiKeyPlaceholder: 'AIza...',
    models: GOOGLE_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://aistudio.google.com',
    brandColor: '#4285F4',
    apiFormat: 'google-generative-ai',
    guide: {
      docsUrl: 'https://docs.openclaw.ai/concepts/model-providers',
      apiKeyUrl: 'https://aistudio.google.com/apikey',
      pricingUrl: 'https://ai.google.dev/pricing',
      steps: [
        '打开 Google AI Studio → 点击「Get API key」获取密钥。',
        '推荐 Gemini 3 Flash Preview 最新高速模型。',
        '粘贴 API Key 并保存。',
      ],
      tips: [
        'Gemini 3.1 Pro Preview 是最新旗舰，支持思考、图生成、网页搜索。',
        'Gemini 3 Flash Preview 性价比极高。',
        'Google AI 支持 1M tokens 上下文。',
        '免费额度慷慨，适合个人使用。',
      ],
    },
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'DeepSeek V3 对话与 R1 推理模型',
    category: 'global',
    baseUrl: 'https://api.deepseek.com/v1',
    auth: 'api-key',
    apiKeyPlaceholder: 'sk-...',
    models: DEEPSEEK_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://platform.deepseek.com',
    brandColor: '#4D6BFE',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://api-docs.deepseek.com/',
      apiKeyUrl: 'https://platform.deepseek.com/api_keys',
      pricingUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
      steps: [
        '登录 DeepSeek 开放平台 → API Keys 页面创建密钥。',
        '通用对话选 deepseek-chat，深度推理选 deepseek-reasoner。',
        '粘贴 API Key 并保存。',
      ],
      tips: [
        'DeepSeek 定价极其优惠，适合大量使用场景。',
        'DeepSeek R1 推理能力出众，适合数学/编程。',
        '支持 128K 上下文窗口。',
      ],
    },
  },
  {
    id: 'xai',
    name: 'xAI',
    description: 'Grok 3 系列模型（Elon Musk 的 AI）',
    category: 'global',
    baseUrl: 'https://api.x.ai/v1',
    auth: 'api-key',
    apiKeyPlaceholder: 'xai-...',
    models: XAI_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://console.x.ai',
    brandColor: '#000000',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://docs.x.ai/docs',
      apiKeyUrl: 'https://console.x.ai/team/default/api-keys',
      pricingUrl: 'https://docs.x.ai/docs/pricing',
      steps: [
        '登录 xAI Console → API Keys 创建密钥。',
        '推荐 Grok 3 Mini 作为日常使用模型。',
        '粘贴 API Key 并保存。',
      ],
      tips: [
        'Grok 3 Mini 推理性能出色，价格低廉。',
        '支持 128K 上下文窗口。',
        'xAI 提供每月免费额度。',
      ],
    },
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    description: 'Mistral Large 与 Codestral 代码模型',
    category: 'global',
    baseUrl: 'https://api.mistral.ai/v1',
    auth: 'api-key',
    apiKeyPlaceholder: 'M...',
    models: MISTRAL_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://console.mistral.ai',
    brandColor: '#FF7000',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://docs.mistral.ai/',
      apiKeyUrl: 'https://console.mistral.ai/api-keys/',
      pricingUrl: 'https://mistral.ai/products/la-plateforme#pricing',
      steps: [
        '登录 Mistral Console → API Keys 创建密钥。',
        '日常使用推荐 Mistral Small；编程推荐 Codestral。',
        '粘贴 API Key 并保存。',
      ],
      tips: [
        'Codestral 是顶级代码模型之一，256K 代码上下文。',
        'Mistral Small 是最具性价比的选择。',
        '所有模型都支持函数调用。',
      ],
    },
  },
  {
    id: 'cohere',
    name: 'Cohere',
    description: 'Command A 企业级 RAG 与 Agentic 模型',
    category: 'global',
    baseUrl: 'https://api.cohere.ai/compatibility/v1',
    auth: 'api-key',
    apiKeyPlaceholder: '...',
    models: COHERE_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://dashboard.cohere.com',
    brandColor: '#39594D',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://docs.cohere.com/',
      apiKeyUrl: 'https://dashboard.cohere.com/api-keys',
      pricingUrl: 'https://cohere.com/pricing',
      steps: [
        '登录 Cohere Dashboard → API Keys 创建密钥。',
        '推荐 Command A 处理复杂 Agent 任务。',
        '粘贴 API Key 并保存。',
      ],
      tips: [
        'Cohere 专注企业级 RAG 与检索增强。',
        'Command R 有免费试用 API（Rate Limited）。',
        '支持 256K 上下文 (Command A)。',
      ],
    },
  },

  // ── China Providers ──
  {
    id: 'zhipu',
    name: '智谱 AI',
    description: 'GLM-5/4 系列大语言模型',
    category: 'china',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    auth: 'api-key',
    apiKeyPlaceholder: '...',
    models: ZHIPU_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://open.bigmodel.cn',
    brandColor: '#1E6FFF',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://docs.openclaw.ai/providers/zai',
      apiKeyUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
      pricingUrl: 'https://open.bigmodel.cn/pricing',
      codingPlanUrl: 'https://docs.z.ai/devpack/tool/openclaw',
      steps: [
        '登录智谱开放平台 → 个人中心 → API Keys 创建密钥。',
        'GLM-4 Flash 免费，推荐先用它验证配置。',
        '粘贴 API Key 并保存。',
      ],
      tips: [
        'GLM-5 是最新旗舰模型，推荐优先使用。',
        'GLM-4 Flash 完全免费，适合开发测试。',
        'GLM-4 Long 支持 1M 上下文。',
        'Z.AI Coding Plan 提供 GLM-5/4.7/4.6/4.5 等模型。',
      ],
    },
    codingPlan: {
      name: 'GLM Coding Plan',
      url: 'https://docs.z.ai/devpack/tool/openclaw',
      description: '智谱 GLM 系列 Coding Plan，best-effort 调度',
      models: [
        'glm-5',
        'glm-4.7',
        'glm-4.6',
        'glm-4.5',
        'glm-4-plus',
        'glm-4-flash',
        'glm-4-long',
        'glm-4-flashx',
      ],
      pricing: '按量计费',
    },
  },
  {
    id: 'moonshot',
    name: 'Moonshot',
    description: 'Kimi K2.5 与 Moonshot V1 对话模型',
    category: 'china',
    baseUrl: 'https://api.moonshot.cn/v1',
    auth: 'api-key',
    apiKeyPlaceholder: 'sk-...',
    models: MOONSHOT_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://platform.moonshot.cn',
    brandColor: '#6C5CE7',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://docs.openclaw.ai/providers/moonshot',
      apiKeyUrl: 'https://platform.moonshot.cn/console/api-keys',
      pricingUrl: 'https://platform.moonshot.cn/docs/pricing',
      codingPlanUrl: 'https://platform.moonshot.ai/docs/guide/use-kimi-in-openclaw',
      steps: [
        '登录 Moonshot 控制台 → API Keys 创建密钥。',
        '推荐使用 Kimi K2.5 最新旗舰模型。',
        '粘贴 API Key 并保存。',
      ],
      tips: [
        'Kimi K2.5 是最新旗舰模型，支持多模态。',
        'Moonshot V1 按上下文长度计费，8K 最便宜。',
        '新用户注册即赠送免费额度。',
      ],
    },
    codingPlan: {
      name: 'Kimi Coding',
      url: 'https://platform.moonshot.ai/docs/guide/use-kimi-in-openclaw',
      description: 'Kimi K2.5/K2 系列 Coding 模型',
      models: [
        'kimi-k2.5',
        'kimi-k2-0905-preview',
        'kimi-k2-turbo-preview',
        'kimi-k2-thinking',
        'kimi-k2-thinking-turbo',
      ],
      pricing: '按量计费',
      planProviderId: 'kimi-coding',
    },
  },
  {
    id: 'bailian',
    name: '阿里云百炼',
    description: '通义千问 Qwen 3.5/3 + GLM / Kimi / MiniMax / DeepSeek 聚合',
    category: 'china',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    auth: 'api-key',
    apiKeyPlaceholder: 'sk-...',
    models: BAILIAN_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://bailian.console.aliyun.com',
    brandColor: '#FF6A00',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://docs.openclaw.ai/providers/modelstudio',
      apiKeyUrl: 'https://bailian.console.aliyun.com/#/api-key',
      pricingUrl: 'https://help.aliyun.com/zh/model-studio/billing-for-model-studio',
      codingPlanUrl: 'https://www.alibabacloud.com/help/zh/model-studio/openclaw-coding-plan',
      steps: [
        '登录阿里云百炼控制台 → API-KEY 管理创建密钥。',
        '推荐 Qwen3.5 Plus 或 Qwen3 Max 作为主力模型。',
        '粘贴 API Key 并保存。',
      ],
      tips: [
        'Qwen Turbo 支持 1M 上下文，超长文档处理首选。',
        'QwQ Plus 推理模型效果出众且定价亲民。',
        'Qwen3 Coder Plus 专为编程任务优化。',
        '百炼 Coding Plan 聚合 Qwen + GLM + Kimi + MiniMax + DeepSeek 多家模型。',
        '聚合模型可通过同一 API Key 直接调用，无需单独配置。',
      ],
    },
    codingPlan: {
      name: '百炼 Coding Plan',
      url: 'https://www.alibabacloud.com/help/zh/model-studio/openclaw-coding-plan',
      description: '百炼聚合方案，含 Qwen、GLM、Kimi、MiniMax 等多家模型',
      crossProvider: true,
      models: [
        'qwen-coder-plus-latest',
        'qwen-plus-latest',
        'qwq-plus-latest',
        'glm-5',
        'glm-4.7',
        'kimi-k2.5',
        'minimax-m2.5',
        'deepseek-v3',
        'deepseek-r1',
      ],
      pricing: '$50/月',
      planProviderId: 'modelstudio',
    },
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    description: 'MiniMax M2.7 旗舰多模态 MoE 模型',
    category: 'china',
    baseUrl: 'https://api.minimaxi.com/v1',
    auth: 'api-key',
    apiKeyPlaceholder: 'eyJ...',
    models: MINIMAX_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://platform.minimaxi.com',
    brandColor: '#FF4500',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://docs.openclaw.ai/providers/minimax',
      apiKeyUrl: 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
      pricingUrl: 'https://platform.minimaxi.com/docs/pricing',
      codingPlanUrl: 'https://platform.minimax.io/docs/coding-plan/openclaw',
      steps: [
        '登录 MiniMax 平台 → 用户中心 → 接口密钥创建密钥。',
        '推荐 MiniMax M2.7 旗舰模型。',
        '粘贴 API Key 并保存。',
      ],
      tips: [
        'M2.7 支持 1M 上下文，带思考能力。',
        'M2.7 Highspeed 推理速度更快，成本更低。',
        'Text-01 支持 4M 超长上下文。',
        'MiniMax Coding Plan 提供年费订阅 ($100-1500/年)。',
      ],
    },
    codingPlan: {
      name: 'MiniMax Coding Plan',
      url: 'https://platform.minimax.io/docs/coding-plan/openclaw',
      description: 'MiniMax M2.7/M2.5 Coding Plan 年费订阅',
      models: ['MiniMax-M2.7', 'MiniMax-M2.5', 'MiniMax-M2.5-T', 'MiniMax-Text-01'],
      pricing: '$100-1500/年',
    },
  },
  {
    id: 'tencent-hunyuan',
    name: '腾讯混元',
    description: '混元 T1 推理与 TurboS 全能模型',
    category: 'china',
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    auth: 'api-key',
    apiKeyPlaceholder: 'sk-...',
    models: TENCENT_HUNYUAN_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://hunyuan.tencent.com',
    brandColor: '#006EFF',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://www.tencentcloud.com/techpedia/142830',
      apiKeyUrl: 'https://console.cloud.tencent.com/hunyuan/api-key',
      pricingUrl: 'https://cloud.tencent.com/document/product/1729/97731',
      steps: [
        '登录腾讯云控制台 → 混元大模型 → API 密钥管理创建密钥。',
        '推荐 TurboS 作为通用模型，T1 用于深度推理。',
        '粘贴 API Key 并保存。',
      ],
      tips: [
        '混元 Lite 完全免费，适合开发调试。',
        '混元 T1 深度推理能力强劲。',
        '混元 Code 专为编程任务优化。',
      ],
    },
  },
  {
    id: 'volcengine',
    name: '火山引擎',
    description: '豆包 Seed 1.8 / 1.5 + Kimi + GLM + DeepSeek 聚合',
    category: 'china',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    auth: 'api-key',
    apiKeyPlaceholder: '...',
    models: VOLCENGINE_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://www.volcengine.com/product/doubao',
    brandColor: '#3370FF',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://docs.byteplus.com/en/docs/ModelArk/1925114',
      apiKeyUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
      pricingUrl: 'https://www.volcengine.com/pricing?product=doubao',
      codingPlanUrl: 'https://docs.byteplus.com/en/docs/modelark/2229107',
      steps: [
        '登录火山引擎控制台 → 模型广场 (ModelArk) → API Key 管理创建密钥。',
        '需要先在「在线推理」中创建接入点 (Endpoint) 对应模型。',
        '将 Endpoint ID 作为 model ID 使用，粘贴 API Key 并保存。',
      ],
      tips: [
        '火山引擎采用接入点 (Endpoint) 模式，需先创建接入点。',
        '豆包 Seed 1.8 是最新旗舰模型。',
        '支持 DeepSeek 系列模型托管。',
        'Coding Plan 聚合豆包、Kimi、GLM、DeepSeek 等多家模型。',
        '聚合模型可通过同一 API Key 直接调用。',
      ],
    },
    codingPlan: {
      name: '火山引擎 Coding Plan',
      url: 'https://docs.byteplus.com/en/docs/modelark/2229107',
      description: '火山引擎 ModelArk Coding Plan，聚合豆包 + Kimi + GLM + DeepSeek',
      crossProvider: true,
      models: [
        'ark-code-latest',
        'doubao-seed-code',
        'kimi-k2.5',
        'kimi-k2-thinking',
        'glm-4.7',
        'deepseek-v3.2',
        'doubao-seed-1-8-251228',
      ],
      pricing: '订阅制',
      planProviderId: 'volcengine-plan',
    },
  },

  // ── Aggregators / Cloud ──
  {
    id: 'openrouter',
    name: 'OpenRouter',
    description: '统一 API 接入所有主流 AI 模型',
    category: 'global',
    baseUrl: 'https://openrouter.ai/api/v1',
    auth: 'api-key',
    apiKeyPlaceholder: 'sk-or-...',
    models: OPENROUTER_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://openrouter.ai',
    brandColor: '#6366F1',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://openrouter.ai/docs',
      apiKeyUrl: 'https://openrouter.ai/settings/keys',
      pricingUrl: 'https://openrouter.ai/models',
      steps: [
        '登录 OpenRouter → Settings → Keys 创建 API Key。',
        '一个 Key 即可访问 200+ 模型（GPT、Claude、Gemini 等）。',
        '粘贴 API Key 并保存。',
      ],
      tips: [
        'OpenRouter 是最便捷的多模型接入方式，一个 Key 用所有模型。',
        '支持自动路由和 Fallback，提升可靠性。',
        '定价透明，按实际使用量计费。',
      ],
    },
  },
  {
    id: 'together',
    name: 'Together.ai',
    description: '高速开源模型推理平台',
    category: 'global',
    baseUrl: 'https://api.together.xyz/v1',
    auth: 'api-key',
    apiKeyPlaceholder: '...',
    models: TOGETHER_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://api.together.ai',
    brandColor: '#0057FF',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://docs.together.ai/',
      apiKeyUrl: 'https://api.together.ai/settings/api-keys',
      pricingUrl: 'https://www.together.ai/pricing',
      steps: [
        '登录 Together.ai → Settings → API Keys 创建密钥。',
        '推荐 Llama 3.3 70B Turbo 或 DeepSeek R1。',
        '粘贴 API Key 并保存。',
      ],
      tips: [
        '专注开源模型，推理速度极快。',
        '价格实惠，适合大量调用场景。',
        '支持 Llama、Qwen、DeepSeek 等主流开源模型。',
      ],
    },
  },
  {
    id: 'groq',
    name: 'Groq',
    description: 'LPU 芯片极速推理（超低延迟）',
    category: 'global',
    baseUrl: 'https://api.groq.com/openai/v1',
    auth: 'api-key',
    apiKeyPlaceholder: 'gsk_...',
    models: GROQ_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://console.groq.com',
    brandColor: '#F55036',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://console.groq.com/docs',
      apiKeyUrl: 'https://console.groq.com/keys',
      pricingUrl: 'https://groq.com/pricing/',
      steps: [
        '登录 Groq Console → API Keys 创建密钥。',
        '推荐 Llama 3.3 70B 或 DeepSeek R1 Distill。',
        '粘贴 API Key 并保存。',
      ],
      tips: [
        'Groq 使用自研 LPU 芯片，延迟极低（< 100ms TTFT）。',
        '免费额度充足，适合快速原型开发。',
        '最适合需要实时响应的场景。',
      ],
    },
  },
  {
    id: 'siliconflow',
    name: '硅基流动',
    description: '国内高速开源模型推理平台',
    category: 'china',
    baseUrl: 'https://api.siliconflow.cn/v1',
    auth: 'api-key',
    apiKeyPlaceholder: 'sk-...',
    models: SILICONFLOW_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://cloud.siliconflow.cn',
    brandColor: '#7C3AED',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://docs.siliconflow.cn/',
      apiKeyUrl: 'https://cloud.siliconflow.cn/account/ak',
      pricingUrl: 'https://siliconflow.cn/pricing',
      steps: [
        '登录硅基流动控制台 → 账户 → API 密钥创建密钥。',
        '推荐 DeepSeek V3 或 Qwen3 作为主力模型。',
        '粘贴 API Key 并保存。',
      ],
      tips: [
        '部分模型如 Gemma 2 有免费额度。',
        '国内访问速度极快。',
        '支持众多开源模型，API 兼容 OpenAI。',
      ],
    },
  },
  {
    id: 'bedrock',
    name: 'AWS Bedrock',
    description: 'AWS 托管的 Claude、Llama、Nova 模型',
    category: 'global',
    baseUrl: 'https://bedrock-runtime.{region}.amazonaws.com',
    auth: 'token',
    models: BEDROCK_MODELS,
    openaiCompatible: false,
    websiteUrl: 'https://aws.amazon.com/bedrock/',
    brandColor: '#FF9900',
    apiFormat: 'bedrock-converse-stream',
    guide: {
      docsUrl: 'https://docs.aws.amazon.com/bedrock/',
      apiKeyUrl: 'https://console.aws.amazon.com/iam/home#/security_credentials',
      pricingUrl: 'https://aws.amazon.com/bedrock/pricing/',
      steps: [
        '在 AWS Bedrock 控制台启用所需模型的访问权限。',
        '创建 IAM 用户或使用 AWS Access Key + Secret Key。',
        '在 OpenClaw 配置中设置 auth 为 aws-sdk 并填入凭证。',
      ],
      tips: [
        'Bedrock 按实际使用计费，无预付费。',
        '支持 Claude、Llama、Mistral、Amazon Nova 等模型。',
        '企业级安全合规首选。',
      ],
    },
  },

  // ── Coding Plan Providers ──
  {
    id: 'openai-codex',
    name: 'OpenAI Codex',
    description: 'ChatGPT Plus/Pro 订阅 Codex 编程助手（OAuth 免 API Key）',
    category: 'coding-plan',
    baseUrl: 'https://chatgpt.com/backend-api',
    auth: 'oauth',
    models: CODEX_MODELS,
    openaiCompatible: false,
    websiteUrl: 'https://openai.com/codex/',
    brandColor: '#10A37F',
    apiFormat: 'openai-codex-responses',
    guide: {
      docsUrl: 'https://docs.openclaw.ai/providers/openai',
      apiKeyUrl: 'https://openai.com/codex/',
      pricingUrl: 'https://openai.com/chatgpt/pricing/',
      steps: [
        '需要 ChatGPT Plus ($20/月) 或 Pro ($200/月) 订阅。',
        '运行 openclaw login 完成 OAuth 授权登录。',
        '授权完成后即可使用 Codex 模型。',
      ],
      tips: [
        'Codex 通过 OAuth 授权，无需 API Key。',
        'GPT-5.4 是 Codex 最强旗舰模型。',
        'GPT-5.3 Codex Spark 适合轻量快速任务。',
        '订阅用户可直接使用，无额外 API 费用。',
      ],
    },
  },
  {
    id: 'kimi-coding',
    name: 'Kimi Coding',
    description: 'Kimi K2.5/K2 系列 Coding 模型 (Anthropic 协议)',
    category: 'coding-plan',
    baseUrl: 'https://api.kimi.com/coding/',
    auth: 'api-key',
    apiKeyPlaceholder: 'sk-...',
    models: KIMI_CODING_MODELS,
    openaiCompatible: false,
    websiteUrl: 'https://platform.moonshot.ai',
    brandColor: '#6C5CE7',
    apiFormat: 'anthropic-messages',
    guide: {
      docsUrl: 'https://platform.moonshot.ai/docs/guide/use-kimi-in-openclaw',
      apiKeyUrl: 'https://platform.moonshot.cn/console/api-keys',
      pricingUrl: 'https://platform.moonshot.cn/docs/pricing',
      steps: [
        '登录 Moonshot 控制台 → API Keys 创建密钥。',
        '使用与 Moonshot 相同的 API Key（KIMI_API_KEY）。',
        '注意：Kimi Coding 使用 Anthropic 协议，与 Moonshot 不同。',
      ],
      tips: [
        'Kimi Coding 使用独立的 baseUrl (api.kimi.com/coding/)。',
        'API 格式为 anthropic-messages，非 openai-completions。',
        'k2p5 是旗舰模型，支持推理和多模态。',
        '与 Moonshot 共用 API Key 但协议不同，需单独配置。',
      ],
    },
  },
  {
    id: 'modelstudio',
    name: '百炼 Coding Plan',
    description: '阿里云百炼聚合 Qwen + GLM + Kimi + MiniMax 多家模型',
    category: 'coding-plan',
    baseUrl: 'https://coding.dashscope.aliyuncs.com/v1',
    auth: 'api-key',
    apiKeyPlaceholder: 'sk-sp-...',
    models: MODELSTUDIO_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://bailian.console.aliyun.com',
    brandColor: '#FF6A00',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://docs.openclaw.ai/providers/modelstudio',
      apiKeyUrl: 'https://bailian.console.aliyun.com/#/api-key',
      pricingUrl: 'https://help.aliyun.com/zh/model-studio/billing-for-model-studio',
      steps: [
        '登录阿里云百炼控制台 → 开通 Coding Plan 服务。',
        '创建 Coding Plan 专用 API Key（格式 sk-sp-xxxxx）。',
        '粘贴 API Key 并保存，即可使用聚合模型。',
      ],
      tips: [
        '百炼 Coding Plan 使用独立 baseUrl (coding.dashscope.aliyuncs.com)。',
        'API Key 格式为 sk-sp-xxxxx，与普通百炼 Key 不同。',
        '聚合 Qwen、GLM、Kimi、MiniMax 等多家模型，同一 Key 调用。',
        '定价 $50/月，包含所有聚合模型额度。',
      ],
    },
  },
  {
    id: 'volcengine-plan',
    name: '火山引擎 Coding Plan',
    description: '火山引擎 ModelArk 聚合豆包 + Kimi + GLM + DeepSeek',
    category: 'coding-plan',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/coding/v3',
    auth: 'api-key',
    apiKeyPlaceholder: '...',
    models: VOLCENGINE_PLAN_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://www.volcengine.com/product/doubao',
    brandColor: '#3370FF',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://docs.byteplus.com/en/docs/modelark/2229107',
      apiKeyUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
      pricingUrl: 'https://www.volcengine.com/pricing?product=doubao',
      steps: [
        '登录火山引擎控制台 → 开通 ModelArk Coding Plan。',
        '在 API Key 管理中创建密钥。',
        '粘贴 API Key 并保存，即可使用聚合模型。',
      ],
      tips: [
        'Coding Plan baseUrl 与普通火山引擎不同 (/api/coding/v3)。',
        '聚合豆包、Kimi、GLM、DeepSeek 等多家模型。',
        'ark-code-latest 是综合编程优选模型。',
        '订阅制计费，无需单独创建接入点。',
      ],
    },
  },
  {
    id: 'zai',
    name: 'Z.AI (智谱 Coding)',
    description: '智谱 GLM 系列 Coding Plan，best-effort 调度',
    category: 'coding-plan',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    auth: 'api-key',
    apiKeyPlaceholder: '...',
    models: ZAI_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://docs.z.ai',
    brandColor: '#1E6FFF',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://docs.z.ai/devpack/tool/openclaw',
      apiKeyUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
      pricingUrl: 'https://open.bigmodel.cn/pricing',
      steps: [
        '登录智谱开放平台 → API Keys 创建密钥。',
        '使用与智谱 AI 相同的 API Key。',
        '粘贴 API Key 并保存，通过 Z.AI Coding Plan 调度。',
      ],
      tips: [
        'Z.AI Coding Plan 采用 best-effort 调度策略。',
        'GLM-5 是旗舰推理模型，GLM-5 Turbo 为高速版。',
        '与智谱 AI 共用 API Key，但 provider ID 为 zai。',
        'GLM-4.7 Flash / FlashX 成本极低。',
      ],
    },
  },
  {
    id: 'minimax-coding',
    name: 'MiniMax Coding Plan',
    description: 'MiniMax M2.7/M2.5 Coding Plan (Anthropic 协议)',
    category: 'coding-plan',
    baseUrl: 'https://api.minimax.io/anthropic',
    auth: 'api-key',
    apiKeyPlaceholder: 'eyJ...',
    models: MINIMAX_CODING_MODELS,
    openaiCompatible: false,
    websiteUrl: 'https://platform.minimax.io',
    brandColor: '#FF4500',
    apiFormat: 'anthropic-messages',
    guide: {
      docsUrl: 'https://platform.minimax.io/docs/coding-plan/openclaw',
      apiKeyUrl: 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
      pricingUrl: 'https://platform.minimaxi.com/docs/pricing',
      steps: [
        '登录 MiniMax 平台 → 开通 Coding Plan 订阅。',
        '在用户中心创建接口密钥。',
        '粘贴 API Key 并保存。',
      ],
      tips: [
        'MiniMax Coding Plan 使用 Anthropic 协议 (api.minimax.io/anthropic)。',
        '与普通 MiniMax 的 baseUrl 和协议均不同，需单独配置。',
        'M2.7 支持 1M 上下文与深度推理。',
        '年费订阅制 ($100-1500/年)。',
      ],
    },
  },

  // ── Local ──
  {
    id: 'ollama',
    name: 'Ollama',
    description: '本地运行开源 AI 模型（免费无限制）',
    category: 'local',
    baseUrl: 'http://localhost:11434/v1',
    auth: 'none',
    models: OLLAMA_MODELS,
    openaiCompatible: true,
    websiteUrl: 'https://ollama.com',
    brandColor: '#FFFFFF',
    apiFormat: 'ollama',
    guide: {
      docsUrl: 'https://docs.ollama.com/integrations/openclaw',
      apiKeyUrl: 'https://ollama.com/download',
      steps: [
        '下载并安装 Ollama 客户端。',
        '在终端运行 `ollama pull qwen3` 拉取模型。',
        '无需 API Key，直接保存即可使用本地模型。',
      ],
      tips: [
        '推荐先试 qwen3 或 llama3.3，效果已接近商用模型。',
        'deepseek-r1 本地版推理能力强劲，需要较大显存。',
        '本地运行，数据完全不离开设备，隐私安全。',
        '可运行在 CPU 上，GPU 加速更快。',
      ],
    },
  },

  // ── Custom ──
  {
    id: 'custom',
    name: '自定义提供商',
    description: '任何 OpenAI 兼容的 API 端点',
    category: 'custom',
    baseUrl: '',
    auth: 'api-key',
    models: [],
    openaiCompatible: true,
    websiteUrl: '',
    brandColor: '#6B7280',
    apiFormat: 'openai-completions',
    guide: {
      docsUrl: 'https://docs.openclaw.ai/concepts/model-providers',
      apiKeyUrl: '',
      steps: [
        '输入 API 基础地址（必须兼容 OpenAI Chat Completions 格式）。',
        '如果需要认证，填入 API Key。',
        '手动添加可用的模型 ID。',
      ],
      tips: [
        '适用于私有部署的模型、API 网关、代理服务等。',
        '本地 vLLM / Text Generation Inference 也可以使用此方式接入。',
        '确保端点支持 /v1/chat/completions 接口。',
      ],
    },
  },
]

// ─── Utility Functions ───────────────────────────────────────────────────────

/** Get a provider preset by ID */
export function getProviderPreset(id: string): ProviderPreset | undefined {
  return PROVIDER_PRESETS.find((p) => p.id === id)
}

/** Get recommended models for a provider */
export function getRecommendedModels(providerId: string): ModelPreset[] {
  const preset = getProviderPreset(providerId)
  if (!preset) return []
  return preset.models.filter((m) => m.recommended)
}

/** Get non-deprecated models for a provider */
export function getActiveModels(providerId: string): ModelPreset[] {
  const preset = getProviderPreset(providerId)
  if (!preset) return []
  return preset.models.filter((m) => !m.deprecated)
}

/** Get model preset by id within a provider */
export function getModelPreset(providerId: string, modelId: string): ModelPreset | undefined {
  const preset = getProviderPreset(providerId)
  return preset?.models.find((m) => m.id === modelId)
}

/** Format context window for display (e.g. 128000 → "128K") */
export function formatContextWindow(tokens: number): string {
  if (tokens >= 1000000) {
    const m = tokens / 1000000
    return m === Math.floor(m) ? `${m}M` : `${m.toFixed(1)}M`
  }
  const k = tokens / 1000
  return k === Math.floor(k) ? `${k}K` : `${k.toFixed(1)}K`
}

/** Format price for display (e.g. 2.5 → "$2.50/M") */
export function formatPrice(pricePer1M: number | undefined): string {
  if (pricePer1M === undefined) return '—'
  if (pricePer1M === 0) return '免费'
  if (pricePer1M < 0.01) return `$${pricePer1M.toFixed(4)}`
  if (pricePer1M < 1) return `$${pricePer1M.toFixed(2)}`
  return `$${pricePer1M.toFixed(1)}`
}

/** Format max output tokens */
export function formatMaxTokens(tokens: number): string {
  if (tokens >= 1000) {
    const k = tokens / 1000
    return k === Math.floor(k) ? `${k}K` : `${k.toFixed(1)}K`
  }
  return String(tokens)
}

/** Get capability display label */
export const CAPABILITY_LABELS: Record<ModelCapability, string> = {
  chat: '对话',
  completion: '补全',
  vision: '视觉',
  'function-calling': '工具调用',
  'json-mode': 'JSON',
  streaming: '流式',
  thinking: '思考',
  code: '编程',
  reasoning: '推理',
  'web-search': '联网',
  'file-upload': '文件',
  'image-generation': '生图',
  audio: '语音',
  video: '视频',
  embedding: '向量',
}

/** Get tier display label and color */
export const TIER_INFO: Record<ModelTier, { label: string; color: string; bgColor: string }> = {
  flagship: { label: '旗舰', color: 'text-amber-400', bgColor: 'bg-amber-400/10' },
  balanced: { label: '平衡', color: 'text-blue-400', bgColor: 'bg-blue-400/10' },
  fast: { label: '高速', color: 'text-green-400', bgColor: 'bg-green-400/10' },
  economy: { label: '经济', color: 'text-gray-400', bgColor: 'bg-gray-400/10' },
  specialized: { label: '专项', color: 'text-purple-400', bgColor: 'bg-purple-400/10' },
}

/** Get provider presets grouped by category */
export function getPresetsByCategory(): Record<ProviderCategory, ProviderPreset[]> {
  const result: Record<ProviderCategory, ProviderPreset[]> = {
    global: [],
    china: [],
    'coding-plan': [],
    local: [],
    custom: [],
  }
  for (const p of PROVIDER_PRESETS) {
    result[p.category].push(p)
  }
  return result
}

/** Get category display label */
export const CATEGORY_LABELS: Record<ProviderCategory, string> = {
  global: '海外提供商',
  china: '国内提供商',
  'coding-plan': 'Coding Plan',
  local: '本地模型',
  custom: '自定义',
}
