// ══════════════════════════════════════════════════════════════
// ECS Resource — Texture Cache
//
// Owns the card-texture Map (canvas instances keyed by card.id)
// and the cheap hash used for cache invalidation.
//
// Responsibilities:
//   - CardTextureInfo type
//   - cardHash()  — derive a stable number from visible card fields
//   - CRUD helpers over the singleton cache Map
// ══════════════════════════════════════════════════════════════

import type { Card } from '../../types'

// ─────────────────────────────────────
// Types
// ─────────────────────────────────────

export interface CardTextureInfo {
  canvas: HTMLCanvasElement | OffscreenCanvas
  needsUpdate: boolean
  cardVersion: number
  /** LOD scale used when baking this texture (1 | 2 | 4 | 6). */
  lodScale: number
}

// ─────────────────────────────────────
// Resource: singleton cache
// ─────────────────────────────────────

const _cache = new Map<string, CardTextureInfo>()

// ─────────────────────────────────────
// Hash (invalidation key)
// ─────────────────────────────────────

/** Fast, deterministic hash derived from all visible card fields. */
export function cardHash(card: Card): number {
  let h = 0
  const meta = (card.meta || {}) as Record<string, unknown>
  let metaSnap = ''
  try {
    metaSnap = JSON.stringify(meta).slice(0, 300)
  } catch {
    metaSnap = ''
  }
  const s = `${card.title}|${card.content?.slice(0, 80)}|${card.kind}|${card.rating}|${card.isStreaming ? 1 : 0}|${card.linkedCardIds.length}|${card.autoGenerated ? 1 : 0}|${card.summary || ''}|${metaSnap}`
  for (let i = 0; i < s.length; i++) {
    h = ((h << 5) - h + s.charCodeAt(i)) | 0
  }
  return h
}

// ─────────────────────────────────────
// Cache CRUD
// ─────────────────────────────────────

export function getCachedTexture(id: string): CardTextureInfo | undefined {
  return _cache.get(id)
}

export function setCachedTexture(id: string, info: CardTextureInfo): void {
  _cache.set(id, info)
}

export function removeCachedTexture(id: string): void {
  _cache.delete(id)
}

export function clearAllTextures(): void {
  _cache.clear()
}
