// ═══════════════════════════════════════════════════════════════
// CardService — CRUD + file cards + linking
//
// v8: All operations require projectId (pid)
// ═══════════════════════════════════════════════════════════════

import { randomUUID } from 'node:crypto'
import { createReadStream, existsSync, mkdirSync } from 'node:fs'
import { writeFile } from 'node:fs/promises'
import { extname, join } from 'node:path'
import type { CardRecord } from '@shadowob/flash-types'
import { ensureProjectDirs, projectObjects } from '../config.js'
import { cardDao } from '../dao/index.js'

export const cardService = {
  create(data: Partial<CardRecord> & { projectId?: string }) {
    const pid = data.projectId || 'default'
    const id = data.id || randomUUID()
    const card: CardRecord = {
      id,
      kind: data.kind || 'text',
      title: data.title || '',
      content: data.content || '',
      sourceId: data.sourceId || null,
      linkedCardIds: data.linkedCardIds || [],
      meta: data.meta || {},
      tags: data.tags || [],
      priority: data.priority || 'medium',
      autoGenerated: data.autoGenerated ?? false,
      rating: data.rating ?? 0,
      deckIds: data.deckIds || [],
      createdAt: Date.now(),
      updatedAt: Date.now(),
      projectId: pid,
    }
    cardDao.save(pid, id, card)
    return card
  },

  async createFileCard(
    cardData: Partial<CardRecord>,
    file: { path: string; mimetype: string } | null,
    projectId?: string,
  ) {
    const pid = projectId || 'default'
    const id = cardData.id || randomUUID()
    const kind = cardData.kind || 'image'

    ensureProjectDirs(pid)
    const cardFilesDir = projectObjects(pid, 'card-files')
    mkdirSync(cardFilesDir, { recursive: true })

    let filePath: string
    let fileMime: string

    if (file) {
      filePath = file.path
      fileMime = file.mimetype
    } else {
      const extMap: Record<string, string> = { image: '.png', audio: '.mp3', video: '.mp4' }
      const ext = extMap[kind] || '.bin'
      filePath = join(cardFilesDir, `${id}${ext}`)
      fileMime =
        kind === 'image'
          ? 'image/png'
          : kind === 'audio'
            ? 'audio/mpeg'
            : kind === 'video'
              ? 'video/mp4'
              : 'application/octet-stream'
      await writeFile(filePath, Buffer.alloc(0))
    }

    const card: CardRecord = {
      id,
      kind,
      title: cardData.title || `${kind} card`,
      content: cardData.content || '',
      sourceId: cardData.sourceId || null,
      linkedCardIds: cardData.linkedCardIds || [],
      meta: cardData.meta || {},
      tags: cardData.tags || [],
      priority: cardData.priority || 'medium',
      autoGenerated: cardData.autoGenerated ?? false,
      rating: cardData.rating ?? 0,
      deckIds: cardData.deckIds || [],
      filePath,
      fileMime,
      createdAt: Date.now(),
      updatedAt: Date.now(),
      projectId: pid,
    }
    cardDao.save(pid, id, card)
    return card
  },

  getFileStream(pid: string, id: string) {
    const card = cardDao.getById(pid, id)
    if (!card || !card.filePath || !existsSync(card.filePath)) return null
    return {
      stream: createReadStream(card.filePath),
      mimeType: card.fileMime || 'application/octet-stream',
    }
  },

  update(pid: string, id: string, patch: Partial<CardRecord>) {
    const card = cardDao.getById(pid, id)
    if (!card) return null
    Object.assign(card, patch, { updatedAt: Date.now() })
    cardDao.save(pid, id, card)
    return card
  },

  delete(pid: string, id: string) {
    return cardDao.delete(pid, id)
  },

  link(pid: string, cardId: string, targetId: string) {
    const card = cardDao.getById(pid, cardId)
    const target = cardDao.getById(pid, targetId)
    if (card && !card.linkedCardIds.includes(targetId)) {
      card.linkedCardIds.push(targetId)
      cardDao.save(pid, cardId, card)
    }
    if (target && !target.linkedCardIds.includes(cardId)) {
      target.linkedCardIds.push(cardId)
      cardDao.save(pid, targetId, target)
    }
  },

  getById(pid: string, id: string) {
    return cardDao.getById(pid, id)
  },

  saveBulk(cards: Array<Record<string, unknown>>, projectId: string) {
    for (const c of cards) {
      cardDao.save(projectId, c.id as string, { ...c, projectId } as unknown as CardRecord)
    }
  },
}
