// ══════════════════════════════════════════════════════════════
// ECS Public API — Re-exports from @shadowob/flash-cards
//
// @shadowob/flash-cards is the independent card rendering library.
// This file provides backward-compatible re-exports so existing
// UI code continues to work unchanged.
// ══════════════════════════════════════════════════════════════

// Re-export everything from @shadowob/flash-cards
export {
  // Arena System (ECS)
  type Arena,
  type ArenaKind,
  type ArenaShape,
  advance,
  allSceneEids,
  animationManager,
  arenaEdgeHitTest,
  arenaStore,
  argumentMetaStore,
  bootstrapCards,
  CARD_H,
  CARD_PADDING,
  CARD_RADIUS,
  CARD_SPACING_X,
  CARD_SPACING_Y,
  // Constants
  CARD_W,
  type CanvasSetupResult,
  type CardCommand,
  type CardDecorator,
  type CardPlugin,
  // Renderer Facades
  CardRenderer,
  type CardTextureInfo,
  CCanvas,
  CCardData,
  CFlip,
  CGLState,
  CGPUState,
  CIcon,
  CInteraction,
  CLayout,
  CONTENT_EID,
  type CommandContext,
  type CommandName,
  type CommandParams,
  type CommandResult,
  // Types
  type ContentSystem,
  CRenderOrder,
  CShaderStyle,
  // Components
  CStyle,
  CTransform,
  CVisibility,
  cancelAllAnimations,
  canvasStore,
  cardDataStore,
  // Resources
  cardHash,
  centerViewportOnCards,
  chartMetaStore,
  clearAllTextures,
  clearHighlight,
  clearTextureCache,
  codeMetaStore,
  colorMetaStore,
  commentMetaStore,
  comparisonMetaStore,
  contentWorld,
  countdownMetaStore,
  createFlip,
  createGLContext,
  createGPUContext,
  createInteraction,
  createLayout,
  createPhysicsWorld,
  createSceneEntity,
  createViewport,
  type DecoratorSystem,
  type DeskInputCallbacks,
  DeskInputHandler,
  DeskLoop,
  // Meta stores (registry-backed)
  dataMetaStore,
  definitionMetaStore,
  destroyGLContext,
  destroyGPUContext,
  destroyPhysicsWorld,
  destroySceneEntity,
  // Command System
  dispatchCommand,
  drawArenas,
  // Constraint Rendering
  drawConstraints,
  drawHighlight,
  eventMetaStore,
  exampleMetaStore,
  Flip,
  fileMetaStore,
  // Scene Systems
  flipAnimationSystem,
  frustumCullSystem,
  type GLContext,
  type GLDrawContext,
  type GPUContext,
  type GPURenderConfig,
  getCachedTexture,
  getCardEid,
  getEidCardId,
  getHighlight,
  gifMetaStore,
  glDrawSystem,
  glOrtho,
  glRenderSystem,
  glStateStore,
  // Render Systems
  glTextureSystem,
  gpuRenderSystem,
  gpuStateStore,
  type HighlightState,
  hasActiveAnimations,
  hasSpace,
  hitTestPoint,
  hitTestRectSystem,
  type InputState,
  Interaction,
  iconStore,
  imageMetaStore,
  inputSystem,
  inspirationMetaStore,
  isFlipped,
  isHiddenByCommand,
  isLocked,
  KIND_COLORS,
  KIND_ICON_DRAWERS,
  KIND_INDEX,
  KIND_LABELS,
  KIND_PIPS,
  KIND_RANKS,
  keypointMetaStore,
  layoutStore,
  linkMetaStore,
  live2dMetaStore,
  lottieMetaStore,
  mathMetaStore,
  type PhysicsWorld,
  panViewport,
  parseCommand,
  personMetaStore,
  physicsStep,
  pokerMetaStore,
  positionMetaStore,
  processMetaStore,
  qrcodeMetaStore,
  quoteMetaStore,
  type RenderConfig,
  RenderOrder,
  rawMetaStore,
  referenceMetaStore,
  // Registry (new plugin system)
  registry,
  releaseTextureLayer,
  remainingH,
  removeCachedTexture,
  removeCardTexture,
  renderCardTexture,
  resizeGLContext,
  resizeGPUContext,
  resolveIcon,
  resolveShaderStyle,
  resolveStyle,
  // World
  runPipeline,
  SceneWorld,
  sceneUpdateSystem,
  // Core
  sceneWorld,
  seedBodies,
  setCachedTexture,
  setupCanvas,
  setViewportZoom,
  shaderStyleStore,
  socialMetaStore,
  storyMetaStore,
  styleStore,
  summaryMetaStore,
  syncBodies,
  TAPE_COLORS,
  TILT_STRENGTH,
  Transform,
  tableMetaStore,
  tarotMetaStore,
  terminalMetaStore,
  threeDMetaStore,
  tickCommands,
  timelineMetaStore,
  timestampMetaStore,
  todoMetaStore,
  toggleFlipTarget,
  Visibility,
  viewportScreenToWorld,
  voiceMetaStore,
  webpageMetaStore,
  zoomViewport,
} from '@shadowob/flash-cards'

// Legacy aliases for backward compatibility
// bootstrapECS is defined in ./bootstrap.ts; re-export it from there to avoid
// using bootstrapCards as a plain variable (export-from doesn't create local bindings)
export { bootstrapECS } from './bootstrap'
export const clearSystems = () => registry.reset()
export const registerContentSystem = (sys: ContentSystem) =>
  registry.register({ kind: '__dynamic_' + Date.now(), contentSystem: sys, priority: 500 })
export const registerPreDecorator = (sys: DecoratorSystem) =>
  registry.registerDecorator({ name: 'pre_' + Date.now(), phase: 'pre', system: sys })
export const registerPostDecorator = (sys: DecoratorSystem) =>
  registry.registerDecorator({ name: 'post_' + Date.now(), phase: 'post', system: sys })
