import { useQuery } from '@tanstack/react-query'
import { Link, useParams } from '@tanstack/react-router'
import { ChevronLeft, Image, LayoutDashboard, QrCode, X } from 'lucide-react'
import { QRCodeSVG } from 'qrcode.react'
import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { UserAvatar } from '../components/common/avatar'
import { formatDuration, OnlineRank } from '../components/common/online-rank'
import { PortfolioGrid } from '../components/portfolio'
import { ProfileCommentSection } from '../components/profile/ProfileCommentSection'
import { fetchApi } from '../lib/api'
import { useAuthStore } from '../stores/auth.store'