// ═══════════════════════════════════════════════════════════════
// @shadowob/flash-types — Domain Models
// ═══════════════════════════════════════════════════════════════

import type { CardKind, CardMeta, CardPriority } from './card.js'

/** Knowledge card */
export interface Card {
  id: string
  kind: CardKind
  title: string
  summary?: string
  content?: string
  thumbnail?: string
  sourceId: string | null
  linkedCardIds: string[]
  meta: CardMeta
  tags: string[]
  priority: CardPriority
  autoGenerated: boolean
  isStreaming?: boolean
  rating: number
  filePath?: string
  fileMime?: string
  deckIds: string[]
  createdAt: number
  updatedAt: number
}

/** Uploaded material file */
export interface Material {
  id: string
  name: string
  type: string
  mimeType?: string
  size: number
  status: 'uploading' | 'uploaded' | 'curating' | 'curated' | 'analyzing' | 'error'
  summary?: string
  content?: string
  error?: string
  path?: string
  cardIds: string[]
  uploadedAt: number
}

/** Outline item */
export interface OutlineItem {
  id: string
  slideIndex: number
  title: string
  type: 'cover' | 'toc' | 'section' | 'content' | 'chart' | 'ending' | 'image' | 'quote'
  keyPoints: string[]
  materialRefs: string[]
  cardRefs: string[]
  notes?: string
}

/** Theme preset */
export interface ThemePreset {
  id: string
  name: string
  appearance: 'dark' | 'light'
  colorScheme: {
    dk1: string
    lt1: string
    dk2: string
    lt2: string
    accent1: string
    accent2: string
    accent3: string
    accent4: string
    accent5: string
    accent6: string
  }
  fontScheme: {
    majorFont: string
    minorFont: string
  }
  preview?: string
}

/** Deck — card collection */
export interface Deck {
  id: string
  title: string
  description: string
  outline: OutlineItem[]
  theme: ThemePreset
  autoCreatedReason?: string
  createdAt: number
  updatedAt: number
}

// ── TODO ──

export interface TodoItem {
  id: string
  text: string
  done: boolean
  completionNote?: string
  createdAt: number
}

// ── Task Center ──

export type TaskStatus = 'pending' | 'running' | 'completed' | 'error' | 'cancelled'

export interface TaskArtifact {
  type: 'cards' | 'outline' | 'material_analysis' | 'research'
  label: string
  url?: string
  count?: number
}

export interface TaskRecord {
  id: string
  name: string
  status: TaskStatus
  dependsOn: string[]
  taskType: string
  startedAt: number
  completedAt?: number
  artifacts: TaskArtifact[]
  logs: string[]
  error?: string
  deckId?: string
  progress?: number
  pipelineId?: string
  requestId?: string
}

// ── Research ──

export type ResearchStatus = 'idle' | 'running' | 'completed' | 'error'

export interface ResearchAngle {
  id: string
  name: string
  description: string
  skillId?: string
  status: ResearchStatus
  cardIds: string[]
  logs: string[]
  startedAt?: number
  completedAt?: number
}

export interface ResearchSession {
  id: string
  topic: string
  angles: ResearchAngle[]
  status: ResearchStatus
  totalCards: number
  createdAt: number
  completedAt?: number
}

// ── Skills ──

export type SkillStatus = 'available' | 'installed' | 'installing' | 'error'

export interface SkillDef {
  id: string
  name: string
  emoji: string
  category: 'research' | 'drawing' | 'art' | 'analysis' | 'data' | 'utility'
  description: string
  builtin: boolean
  status: SkillStatus
  skillPath: string
  version?: string
}

export type ResearchGoal =
  | 'academic'
  | 'business'
  | 'competitive'
  | 'trending'
  | 'technical'
  | 'creative'

// ── Project ──

export type ProjectStatus =
  | 'idle'
  | 'analyzing'
  | 'curating'
  | 'outlining'
  | 'researching'
  | 'done'
  | 'error'

export interface Project {
  id: string
  title: string
  materials: Material[]
  cards: Card[]
  decks: Deck[]
  activeDeckId: string | null
  todos: TodoItem[]
  tasks: TaskRecord[]
  skills: SkillDef[]
  researchSessions: ResearchSession[]
  status: ProjectStatus
  sessionKey?: string
  createdAt: number
  updatedAt: number
}
