export const copy = {
  appName: 'Travel',
  tagline: 'Plan beautifully',
  tripName: 'Paris Family Trip',
  tripDates: 'Jul 8 – Jul 10',
  pageTitle: 'Places',
  searchPlaceholder: 'Search Paris places',
  importPlaces: 'Import places',
  importPlacesHelp: 'Import KML, GPX, GeoJSON, or Google Maps exports as candidate places',
  filters: 'Filters',
  placeCategory: 'Place category',
  mapContent: 'Map content',
  allCategories: 'All categories',
  list: 'List',
  map: 'Map',
  savedSection: 'Saved',
  nearbyIdeas: 'Nearby ideas',
  loadMoreIdeas: 'Load more ideas',
  allTripEssentials: 'All your trip essentials in one place.',
  viewTripOverview: 'View trip overview',
  viewAllSaved: 'View all saved',
  scheduleToDay: 'Schedule to day',
  attachFromWorkspace: 'Attach from Workspace',
  openDiscussion: 'Open discussion',
  removeFromTrip: 'Remove from trip',
  showMore: 'Show more',
  showLess: 'Show less',
  notes: 'Notes',
  savedPlaces: 'saved places',
  scheduled: 'scheduled',
  actionDone: 'Action ready',
  previousDay: 'Previous day',
  nextDay: 'Next day',
  mapLayers: 'Map layers',
  landmarks: 'Landmarks',
  transit: 'Transit',
  food: 'Food',
  cafes: 'Cafes',
  museums: 'Museums',
  parks: 'Parks',
  shopping: 'Shopping',
  stay: 'Stay',
  essentials: 'Essentials',
  dropPin: 'Add point',
  dropPinHelp: 'Click the map to add a point',
  markedPoint: 'Map point',
  markHere: 'Mark here',
  removeMarker: 'Remove marker',
  coordinates: 'Coordinates',
  closeMapDetail: 'Close map detail',
  visiblePlaces: 'Visible places',
  dateList: 'Date list',
  weatherDetails: 'Weather details',
  weatherUnavailable: 'Weather unavailable',
  weatherEstimate: 'Climate estimate',
  hourlyForecast: 'Hourly forecast',
  wind: 'Wind',
  airQuality: 'Air quality',
  humidity: 'Humidity',
  precipitation: 'Precipitation',
  sunrise: 'Sunrise',
  sunset: 'Sunset',
  aqi: 'AQI',
  pm25: 'PM2.5',
} as const

export const tripDays = [
  { label: '4月24日 周五', day: '第 1 天', date: '2026-04-24' },
  { label: '4月25日 周六', day: '第 2 天', date: '2026-04-25' },
  { label: '4月26日 周日', day: '第 3 天', date: '2026-04-26' },
] as const

export const navLabels = {
  home: 'Home',
  itinerary: 'Itinerary',
  places: 'Places',
  bookings: 'Bookings',
  wallet: 'Wallet',
  packing: 'Packing',
  tasks: 'Tasks',
  share: 'Share',
  settings: 'Settings',
  more: 'More',
} as const

export const filterLabels = ['All', 'Sights', 'Food', 'Museums', 'Saved'] as const

export type PlaceFilter = (typeof filterLabels)[number]
